### ISSUE TITLE
Logo in Videoplayer für Studienprojekte auf zhdk.ch ändern

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#106]
S. M from the HSK calls me for the Logo who are embade in the Videosequences for the Studiesprojects on zhdk.ch

Embadded are the older logo not the latest one. 

Could you please change the logo in videoplayer

**Comment by nadjaweisskopf** [comment]
Max wird sich mit der Kommunikation treffen und einen Vorschlag zeigen.

**Comment by phoettli** [comment]
Wie brauchst Du die Logos für die verschiedenen Anwendungen?

- [ ] SVG
- [ ] JPG
- [ ] PNG
- [ ] egal
- [ ] richtige Grösse
- [ ] korrekte Farbe

**Comment by eins78** [comment]
> Wie brauchst Du die Logos für die verschiedenen Anwendungen?

SVG, d.h. größe egal und farbe reicht als textangabe (100% weiss bzw. schwarz, oder?)

**Comment by phoettli** [comment]
### Neues Logo für Medienarchiv
hoffentlich tangiert dies nicht die anderen Instanzen.
[2018_zhdk_kompakt-logo_weiss.svg.zip](https://github.com/Madek/madek/files/4128534/2018_zhdk_kompakt-logo_weiss.svg.zip)

## 1. Logo-Platzierung auf der Website
a. Schmale Fensterbreite (Plattformbezeichnung zweizeilig, ZHdK ausgeschrieben)
![logo-website-schmal](https://user-images.githubusercontent.com/42544602/73365867-4c979780-42ad-11ea-8e36-5334566a7bf4.png)

b. breite Fensterbreite (Plattformbezeichnung einzeilig, ZHdK ausgeschrieben)
ACHTUNG: hier sollte der braune Balken wohl ebenfalls 54px hoch sein...(?)
![logo-website-breit](https://user-images.githubusercontent.com/42544602/73365958-70f37400-42ad-11ea-9b7c-35b41e451093.png)


## 2. Logo-Platzierung im Madek-Player
a. externer Player (normale Anwendung)
![madek-player_extern](https://user-images.githubusercontent.com/42544602/73365538-b6637180-42ac-11ea-913d-d9089c814057.png)

das Logo soll neu einen Tooltip mit "Zürcher Hochschule der Künste" erhalten
![madek-player_extern-tooltip](https://user-images.githubusercontent.com/42544602/73366100-aa2be400-42ad-11ea-9d5e-652019c0cc6c.png)

b. interner Player in ZHdK-Website (Logo grau)
![madek-player_zhdk-web-dunkel](https://user-images.githubusercontent.com/42544602/73365635-e3178900-42ac-11ea-8bde-380d526ccdf8.png)

Und als Beispiel bei hellem Hintergrund
![madek-player_zhdk-web-hell](https://user-images.githubusercontent.com/42544602/73365674-f1fe3b80-42ac-11ea-9949-e2038e401ba1.png)

Der interne Player auf der ZHdK-Website ist hier zu finden:
„weisse Seiten“
- https://www.zhdk.ch/studium/musik
- https://www.zhdk.ch/studium/musik/musikundbewegung/ma-elementare-musikpaedagogik-1291
- https://www.zhdk.ch/dmu

Overlays
- https://www.zhdk.ch/weiterbildung/weiterbildung-musik/musikalische-kreation/weiterbildung-csm/inhalt-und-aufbau-7748
- https://www.zhdk.ch/studium/musik/international-musik-3159/zhdk-goes-mahidol-5280

News
- https://www.zhdk.ch/meldung/roadtrips-schildkroeten-und-blockchain-technologie-1518

Studienprojekte
- https://www.zhdk.ch/studienprojekt/f088aa99-9c55-4328-b97d-790f8ef094c7 (Video & Audio)

**Comment by phoettli** [comment]
Minimal-Abstand vom Logo zu angrenzendem Text. In den obigen Beispielen bereits in Pixel umgerechnet.
![image](https://user-images.githubusercontent.com/42544602/73670709-07f36e00-46aa-11ea-8e9a-13b1602e428c.png)

![image](https://user-images.githubusercontent.com/42544602/73670747-180b4d80-46aa-11ea-8581-e1c41aa69d89.png)

**Comment by eins78** [comment]
(work in progress)

---

<img width="1407" alt="Screen Shot 2020-08-25 at 18 02 16" src="https://user-images.githubusercontent.com/134942/91198663-1f08b480-e6fd-11ea-9271-50c771813238.png">

---

<img width="960" alt="Screen Shot 2020-08-25 at 18 04 25" src="https://user-images.githubusercontent.com/134942/91198877-6bec8b00-e6fd-11ea-99e8-1f16e8c28322.png">

https://blog.zhdk.ch/madektest/2020/08/25/musik-studieren/

----

`javascript:Array.from(document.querySelectorAll('iframe')).forEach(n => n.src = n.src.replace('medienarchiv.zhdk.ch', 'test.madek.zhdk.ch'))`

**Comment by phoettli** [comment]
cool !

**Comment by eins78** [comment]
navbar logo done. other instances will need some custom CSS, for the "built-ins" HfG and HSLU its already done as a test how much work it need minimally.
there is no built-in migration, or a toggle between old and new styling – its a custom so not worth the effort.
(that means after deploy we need to edit settings, but that's already the case for "brand name" etc).

---

<img width="1118" alt="Screen Shot 2020-09-08 at 10 14 09" src="https://user-images.githubusercontent.com/134942/92450882-43b06200-f1bc-11ea-9679-dcdf9a3ec095.png">

<img width="1211" alt="Screen Shot 2020-09-08 at 10 14 14" src="https://user-images.githubusercontent.com/134942/92450895-4743e900-f1bc-11ea-965e-143d8d8510d1.png">

---

data-url for settings: 
```
data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2075%2032%22%3E%3Cpath%20d%3D%22M15.3%2031.3h7.1v.7h-7.1zm0-4.9h7.1v.7h-7.1zm0-26.4h7.1v.7h-7.1zm6.5%2017.7L29.6%209V5.2H15.5v4.2h7.3L15%2017.9V22h15v-4.3z%22%20fill%3D%22%23fff%22%2F%3E%3C%2Fsvg%3E
```
❯ https://test.madek.zhdk.ch/admin/app_settings/brand_logo_url/edit

---

pixel counting 

<img width="897" alt="Screen Shot 2020-09-08 at 10 01 19" src="https://user-images.githubusercontent.com/134942/92450969-62aef400-f1bc-11ea-989d-c13d53a610fd.png">

**Comment by phoettli** [comment]
beim Player zeigt es mir auf STAGING noch das alte Logo:
![image](https://user-images.githubusercontent.com/42544602/97466914-ef1b9e80-1943-11eb-9f3a-5fc8b9acfccb.png)

in der Webapp ist das neue Logo ok

**Comment by eins78** [comment]
fehler: deploy-config wurde für `test` angepasst. muss ich für `staging` und `prod` nachziehen.

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/ffea728f06d78618a01e8e2d1c2b4a4178c15a50

**Comment by phoettli** [comment]
ok auf STAGING
