### ISSUE TITLE
Embed the logo in videoplayer changable if user switches the language

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#107]
The ZHdK logo in Madek should be exchanged with the new one. 

******

Msg. from communication: 
"Auf der Website des Medienarchivs ist ein ZHdK-Logo platziert, welches gemäss aktuellem CD nicht mehr in Verwendung sein sollte. Das Logo erscheint auch auf unserer ZHdK-Website, wenn wir z.B. Audio-Dateien via Madek beziehen und in den Studienprojekten präsentieren, siehe z.B. hier: 
 
https://www.zhdk.ch/studienprojekt/f088aa99-9c55-4328-b97d-790f8ef094c7 (In der Galerie unter den Detail auf eine Kachel mit «Audio anhören» klicken)
 
Auch dort sollte lieber das korrekte Logo erscheinen. "

******

In the same way Samuel asked me if it is possible to change the language when user has the language for example English.

After an meeting with max it is possible, but it must be build a structure for this case.

**Comment by nadjaweisskopf** [comment]
@gurmir did you receive the new logo from Samuel? Could you please upload it to the ticket? Thanks.

**Comment by gurmir** [comment]
Link to the Logos
https://intern.zhdk.ch/?corporatedesign

**Comment by nadjaweisskopf** [comment]
Wollen wir uns überhaupt um die Sprache kümmern? Es gibt ein Logo, welches zweisprachig ist. Und falls wir die Sprache prüfen, worauf verweisen wir? Auf die Tastatur, auf den Browser?

**Comment by nadjaweisskopf** [comment]
zweisprachigkeit ist im logo abgebildet.

**Comment by eins78** [comment]
update: ich treffe mich (in anderem projektzusammenhang) sowie mit der HSK wegen des Logos (bzw habe angefragt). Ich warte noch dieses Meeting ab, dann gibt es entweder eine bessere Lösung oder es wird wie hier beschrieben eingebaut.
