### ISSUE TITLE
Tests Batch Editing

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#114]
- I would expect the metatags to be sorted alphabetically 

![bildschirmfoto 2018-08-21 um 07 51 41](https://user-images.githubusercontent.com/3356016/44382899-116d3280-a517-11e8-926b-a9e50c2dfba6.png)
//sorting is according to importance (position in Admin)

- If I press "anwenden", then I do not see any kind of notice on the tile itself. I would like to see a change in colour or the button "anwenden" should vanish.

![bildschirmfoto 2018-08-21 um 07 54 45](https://user-images.githubusercontent.com/3356016/44383044-93f5f200-a517-11e8-9dd8-8d37aaf004dc.png)
//we'll leave it as it is. 

- Can you make the popup bigger, so the Derivates is not on a single line?

![bildschirmfoto 2018-08-21 um 08 03 46](https://user-images.githubusercontent.com/3356016/44383376-d966ef00-a518-11e8-9ff4-7f486e8a1158.png)
//will not do anything at the moment

- It would be nice, if the amount of updated media entries would be added to the green message (Erfolgsmeldung) and if the message would not vanish
//will be done

![bildschirmfoto 2018-08-21 um 08 00 22](https://user-images.githubusercontent.com/3356016/44383231-547bd580-a518-11e8-90be-227af1e856d9.png)

- If the filter is opened, it is hard to differentiate which is the filter and which are the fields to pick.

![bildschirmfoto 2018-08-21 um 08 10 20](https://user-images.githubusercontent.com/3356016/44383651-acffa280-a519-11e8-8c8e-1d8a6ecdceba.png)
//Philipp will have a look at this

- Please write "Medien Einträgen" together "Medieneinträgen"

![bildschirmfoto 2018-08-21 um 08 15 25](https://user-images.githubusercontent.com/3356016/44383837-6b232c00-a51a-11e8-8b4a-937e547752d9.png)
//done

**Comment by phiku** [comment]
@nadjaweisskopf 
Fixed the following:
1. Keywords are separated with a thin grey line (to make multiline entries separated when screen is small).
2. Success message says how many are updated and stays until you change something in the form. At least this now gives also some feedback if you click on apply for a single entry. Not on the entry itself, but at least as success  message.
3. The form is on the right side of the filter, not above anymore.
4. Fixed "Medien Einträge" to "Medieneinträge".

**Comment by nadjaweisskopf** [comment]
@phiku Perfect! I already retested everything. Just waiting for Claudia, and Susanne, then we can merge.

**Comment by cmonstein** [comment]
@phiku Salüt, hier mein Kommentar aus den Tests mit Regula:

MadekCore sagt den Benutzern nichts, evtl. Gruppierung und Benamsung gleich machen wie in Matadaten editieren? (Plichtfelder, ZHdK, Objekt, Personen, Rechte, Archiv ZHdK)
-> hilfreich wäre zudem ein **Infoicon pro Matadatenfeld** mit Beschreibung was es ist.  (Gibts bereits in Metadaten editieren)

Schlagworte findet sie super in der Batchverarbeitung :)

Gewisse Daten sind bei Regula bereits hinterlegt (durch Vorbearbeitung in Lightroom) diese würde sie gerne sehen (falls bei allen gleich) -> anzeigen als grauen Text. Und wenn es unterschiedliche hinterlegte Texte sind und diese überschrieben würden -> orange/gelb hinterlegen. Achtung Vorsicht beim überschreiben.

Thats all :)

LG
Claudia

**Comment by phiku** [comment]
@cmonstein Ich muss schauen, was ich da umsetzen kann. 
@nadjaweisskopf Sind die Anforderungen von @cmonstein nötig für einen Release?

Aus meiner Sicht wäre eine Lösung einfach, 'Madek Core' in 'Basisdaten' umzubenennen. Aber das müsste man mit vielen besprechen.

**Comment by cmonstein** [comment]
@nadjaweisskopf @phiku ich denke nicht das mein Feedback nötig ist für ein Release. 
Geschätzte Prio: 
1) Infoicon 
2) orange/gelb hinterlegen bei unterschiedlichen Metadaten 
3) Text anzeigen wenn Metadaten bereits vorhanden 
4) MadeCore umbenennen

**Comment by phiku** [comment]
@nadjaweisskopf @cmonstein
Ich habe mir noch versucht zu überlegen, ob man das editieren eines einzelnen Eintrages auch gerade unterbringen kann. Das hat allerdings Platzprobleme verursacht und ein Popup wollte ich vermeiden. Ich habe dann versucht eine Version zu machen, bei der das ganze Fenster gefüllt wird. Und am Ende habe ich mir überlegt, ob man beim öffnen der neuen Funktion einfach gerade in eine Total andere Ansicht gelangen soll, welche der Applikation überlager ist. Diese könnte für die Usability viel einschneidender sein:

![bildschirmfoto 2018-08-22 um 19 28 49](https://user-images.githubusercontent.com/16756048/44479746-c8fe6380-a641-11e8-99bd-2987662417fd.png)

Wir sollten das besprechen...

**Comment by nadjaweisskopf** [comment]
@phiku @cmonstein wir haben jetzt noch eine Woche für die Implementierung, d.h. spätestens bis nächsten Dienstag. Ich möchte lieber keine neuen Baustellen öffnen sondern nur noch abschliessen, was wir begonnen haben. Verlinken auf neue Seiten etc. würde ich unterlassen, das können wir immernoch in einer Überarbeitung Anfangs nächsten Jahres einplanen. Susanne testet heute Abend und schreibt ihr Feedback ins Ticket. Ich bin erst wieder am Montag da. Schaut ihr zusammen, wie wir weiterfahren?

**Comment by SusanneSchumacher** [comment]
Liebe alle

Das Feature finde ich sehr gut! Es ist eine echte Verbesserung für die User!

Ich habe auf Usability und Funktionalität geprüft. Ob Daten korrekt übergeben und keine falschen gelöscht werden, habe ich nicht getestet. Da Stapelverarbeitung ein daten-kritisches Feature ist, müsste diese vor dem Release unbedingt geschehen.

Den meisten bereits gemachte Kommentaren im Ticket stimme ich zu. Wo ich anderer Meinung bin:
- Die Reihenfolge der Metakey und der Kontexte wird im Admin-Interface festgelegt. Sie soll überall im Interface des Medienarchivs gleich sein. Daher macht es keinen Sinn hier eine alphabetische Sortierung der Metakeys vorzunehmen.
- Die Titel der Kontexte und der Vokabulare kommen aus dem Admin-Interface und sollen überall im System gleich sein. Madek-Core kann nicht umbenannt werden. 
- Info-Coin-Vorschlag Claudia: Für die Vokabulare gibt es bereits diese Texte (angezeigt unter „Alle Daten“). Diese könnte man sichtbar machen. Für die Kontexte (angezeigt unter Templates) gibt es auch die Möglichkeit, im Admin-Interface Texte zu hinterlegen. Aber das  war bislang noch nicht notwendig.

Anbei mein Feedback, gleich nach Prio sortiert.


**Feedback zu Funktionen (1. Prio):**

Die Keyword haben alle einen Typus und eine Reihe von Eigenschaften, die im Admin-Interface festgelegt werden. Es werden nicht alle Eigenschaften in der neue Stapelverarbeitung übernommen. Die Konsequenz ist, dass die Felder dann in den verschiedenen Editier-Modi (Einzel-Editieren, Alte Stapelverarbeitung und neue Stapelverarbeitung) eine unterschiedliche Dateneingabe erlauben. Dies betrifft:
- Metakeys vom Typ People erlauben es sonst, neue Person und Gruppennamen anzulegen. Das ist in der neuen Stapelverarbeitung nicht möglich.
- Metakeys vom Typ Text kann in der Grösse der Eingabefelder festgelegt werden (line / block). Für manche Felder reicht eine Zeile nicht aus und man muss einen Umbruch einfügen können (z.B. Beschreibung). Diese Einstellung müsste ebenfalls übernommen werden.


Wording (Anpassen vor dem Release):

Begriffe anpassen: (Bitte bei allen Textänderungen diese per Copy/Paste aus dieser Mail entnehmen, damit sich keine Tippfehler reinschleichen.)

Jetzt: "Wähle Metadaten zum zuweisen:“ -> Neu: „Felder auswählen“ "Metadaten editieren"

jetzt: „Templates": -> neu: „Kontexte“

![bildschirmfoto 2018-08-23 um 00 16 28](https://user-images.githubusercontent.com/1416731/44496475-fdd7de00-a674-11e8-85ca-38e99a1e4ee5.jpg)


Wording Infoboxen (anpassen vor Release)
Die beiden Info-Boxen finde ich sehr hilfreich. Ich würde den Text etwas ausführlicher machen, damit man besser verseht, um was es geht.

Überschrift in der Box:
Gefilterte Inhalte

Inhalte bei aktueller Filtereinstellung:
Davon geladen:
Davon durch Sie editierbar:

Es werden alle Inhalte geladen …
Auf alle xx Inhalte anwenden

Ausgewählte Inhalte

Inhalte durch Sie ausgewählt:
Davon durch Sie editierbar:
Auf xx Inhalte anwenden

Usability / Verständlichkeit: Die beiden Buttons in den beiden Feldern sollte nur grün sein, wenn ich auch tatsächlich etwas ausgefüllt habe.


![bildschirmfoto 2018-08-22 um 22 53 10 kopie 2](https://user-images.githubusercontent.com/1416731/44496522-2b248c00-a675-11e8-8602-18bed934b244.jpg)


**Usability (2. Prio):**


**Wichtig**: Wenn der Medieneintrag ausgewählt ist (grün umrandet), dann kann ich ihn nicht mehr öffnen, sondern nur noch deselektieren. Ich denke, man sollte die Aktion zum De/Selektieren für diese neue Stapelverarbeitung nicht ändern. Ent-/Auswählen sollte über die Auswahlbox möglich sein. Sehr wichtig ist, dass man mit dem Klick auf den Medieneintrag/das Set zu diesem in die Detail-Ansicht kommt. Das ist im ganzen System so und sollte hier nicht gebrochen werden. Sonst kann ich die bestehenden Metadaten des Eintrags nicht anschauen.


**Bug**: Wenn man bei einem Keyword einen Eintrag macht und dann von Hinzufügen auf Ersetzen wechselt, ist der Eintrag weg.


**Schliessen**: Beim „Schliessen“ ist ein Pfeil, der auf- und zuklappen suggeriert. Aber die Funktion ist weg, wenn man sie schliesst. Daher würde ich das Symbol ändern. Den Pfeil verwenden wir sonst, wenn wir etwas auf- und zuklappen (z.B. Filterleiste). Wenn wir etwas schliessen, verwenden wir das x-Icon (siehe Styleguide).
Wenn ich es richtig sehe, dann verlässt man über dieses kleine Schliessen-Feld den gesamten Prozess. Das erkennt man nicht einfach. Daher würde ich einen grossen „Schliessen“-Button einfügen, wie wir das sonst auch haben.
![bildschirmfoto 2018-08-22 um 22 41 02](https://user-images.githubusercontent.com/1416731/44496558-54451c80-a675-11e8-9e26-2d4e1f05f9d9.jpg)

**Fehlermeldung**: Was bedeutet diese Fehlermeldung? Ist gemeint, dass man nur Speichern kann, wenn keine Felder leer sind?
Vorschlag: „Bitte füllen Sie alle Felder aus oder schliessen Sie Felder ohne Eingaben. Sonst können Sie ihre Eingaben nicht speichern."
![bildschirmfoto 2018-08-22 um 22 49 41](https://user-images.githubusercontent.com/1416731/44496597-776fcc00-a675-11e8-9601-2850634c6c28.jpg)


Aktionsmeldungen und Fehlermeldungen würde ich an den bisherigen Style anpassen: Balken, der über das gesamte Fenster oben geht. Siehe Styleguide.

Die Texte der Fehler- und Erfolgsmeldung sollen die gleichen sein, wie bei der anderen Stapelverarbeitung. Dort sind sie auch schon in English vorhanden.

**Verständlichkeit**: Das Element „Auswählen / Ersetzen“ sieht aus, als ob es eine Funktion hätte, als ob etwas geschieht, wenn man drauf klickt. Aber es ist wohl ein Auswahl-Feld. Doch man versteht nicht gut, was nun tatsächlich ausgewählt ist: Wenn es gedrückt ist, also grau? Oder wenn es hell ist? Wir haben zwar so einen Umschalter beim Toggle „Set/Medieneinträge“. Aber bei diesem sieht man immer sofort die Änderung (Dort ist die „gedrückte“, die graue Option, die Auswahl). Daher würde ich hier ein Radiobutton (Wie bei der Suche) oder ein Dropdownmenü (wie bei der anderen Stapelverärbeitung für „Werte löschen“).

![bildschirmfoto 2018-08-22 um 22 53 10 kopie](https://user-images.githubusercontent.com/1416731/44496617-89516f00-a675-11e8-87ca-f3cc0da6b153.jpg)
![bildschirmfoto 2018-08-22 um 23 03 16](https://user-images.githubusercontent.com/1416731/44496619-8bb3c900-a675-11e8-9f3d-1186324a09af.jpg)
![bildschirmfoto 2018-08-22 um 23 03 53](https://user-images.githubusercontent.com/1416731/44496623-8eaeb980-a675-11e8-9a46-4ba287502bbf.jpg)

**Comment by SusanneSchumacher** [comment]
@phiku 
Hast Du noch Fragen zu meinen Kommentaren? Ruf mich am besten an, falls das der Fall ist.

Noch einen Hinweis:
Ich würde im Auswahlmenü schreiben:
"Neu: Metadaten Stapelverarbeitung"
Dann beschreibt es, was die Aktion enthält, ist unterschieden zu Set Stapelverarbeitung und ist kein Anglizismus.

<img width="436" alt="bildschirmfoto 2018-08-23 um 11 36 13" src="https://user-images.githubusercontent.com/1416731/44518196-ed9e1e00-a6c9-11e8-9d79-f2816a50cdb3.png">

**Comment by nadjaweisskopf** [comment]
Wir versuchen jetzt noch die folgenden Probleme zu lösen bevor wir live gehen: 
- Bug - Beschreibungsfeld kann zweimal hinzugefügt werden - einmal im Kontext, einmal ohne Kontext
- Personen erfassen
- Eingabe eines neuen Metatags bei Auswahl/Eingabefelder verbessern

**Comment by phiku** [comment]
@nadjaweisskopf 

Ich habe gerade herausgefunden, dass der erste Punkt gar kein Bug ist. Es gibt beide Metakeys separat auf test-blank:
- media_content:description_english
- madek_core:description
Ich habe deshalb noch die Vokabulare unter den Labeln eingeblendet, etwas kleiner und ausgegraut, damit man sieht, dass es nicht dieselben sind.

Den zweiten Punkte habe ich schon mal implementiert, muss ich aber selber auch nochmals etwas testen. Es wurde doch noch etwas komplexer als erwartet.

Den dritten Punkt habe ich noch nicht angeschaut.

**Comment by nadjaweisskopf** [comment]
@phiku ok, was ist denn eigentlich Madek_core und Objekt? Beim einen hatte es doch noch das Info-Zeichen mit dem Info-Text.

**Comment by phiku** [comment]
@nadjaweisskopf 
Madek Core und Objekt sind Vokabulare. Die Idee von Vokabularen ist eine Menge von Begriffen. Nun gibt es noch Kontexte. Die Kontexte sind etwas vage. Einerseits wurden sie gebraucht, weil man z.B. Eingabeformulare definieren wollte (für Diplomarbeiten sind diese Felder nötig), oder auch Ausgaben (z.B. in dieser und dieser Ansicht werden nur diese Felder angezeigt).

Kontexte:
https://test-blank.madek.zhdk.ch/admin/contexts

Sehr verwirrend, zumindest auf test-blank, ist dass im Vokabular 

"Objekt (media_content)" 
https://test-blank.madek.zhdk.ch/admin/vocabularies/media_content

eine Beschreibung

"Beschreibung (media_content:description_english)"
https://test-blank.madek.zhdk.ch/admin/vocabularies/media_content

vorhanden ist. Diese aber im Kontext

"Objekt (media_content)"
https://test-blank.madek.zhdk.ch/admin/contexts/media_content

nicht verwendet wird, sondern 

"Beschreibung (madek_core:description)"


Du musst das hier gar nicht verstehen, besser ein Refinement dazu. Es ist einfach ein Chaos.

**Comment by nadjaweisskopf** [comment]
@phiku ja... das hilft wirklich nicht weiter, ich frage nochmals perönlich nach :-)

**Comment by cmonstein** [comment]
@phiku Konnte nur rudimentär testen, dabei jedoch keine gravierenden Sachen gefunden.

**Comment by nadjaweisskopf** [comment]
@phiku Könntest Du den Bug und die Englische Übersetzung noch beheben? Sonst habe ich nochmals alles durchgetestet und keine Probleme entdeckt. 

- [ ] Bug (denke ich): Bei "neue Gruppe oder Person anlegen" kann die Person nur gespeichert werden, wenn auch ein Pseudonym angegeben wird.

- [ ] Benennst Du noch den Titel der Funktion in "Neu: Metadaten Stapelverarbeitung" um, wie von Susanne gewünscht?

- [ ] "search" ist noch auf Englisch - Bezeichnung in den Feldern

- [ ] "Datum nach" kann vor "Datum von" sein - ist auch bei der jetzigen Umsetzung so - liegt wahrscheinlich dran dass es ein Textfeld ist oder?
<img width="566" alt="bildschirmfoto 2018-08-28 um 19 56 48" src="https://user-images.githubusercontent.com/3356016/44741141-8aaeeb80-aafc-11e8-95a2-4cc211411ec7.png">

- [ ]  Die Begriffe bei "Person oder Gruppe hinzufügen" sind noch in Englisch
<img width="392" alt="bildschirmfoto 2018-08-28 um 20 07 14" src="https://user-images.githubusercontent.com/3356016/44741690-22f9a000-aafe-11e8-9772-5b306044505b.png">

**Comment by phiku** [comment]
@nadjaweisskopf Ich werde alles umsetzen, ausser den Datums Fix. Das ist mir zu heikel im Moment. Und prinzipiell sollten die Leute ja wissen, von wann bis wann die Datierung ist und es somit nicht falsch eingeben. Da es am Ende als Text gespeichert wird, hat es ja sowieso auch keinen Einfluss auf irgendwelche andere Funktionalität wie Sortierung.

**Comment by phiku** [comment]
Hier nochmals der Vorschlag, wie man das Ding richtig cool macht mit einer Stunde Arbeit (kann man auch auf test-blank tun um auszuprobieren):
![bildschirmfoto 2018-08-30 um 13 16 24](https://user-images.githubusercontent.com/16756048/44848508-4edc6900-ac57-11e8-9ac6-423c96f3afde.png)

**Comment by SusanneSchumacher** [comment]
Liebe Nadja, lieber Philipp
@nadjaweisskopf @phiku 

Beim aktuellen Stand der neuen Stapelverarbeitung auf test-blank gibt es folgendes Problem, das zur fehlerhaften Vergabe von Metadaten führt: 	
Die Aufteilung der Metadatenkontexte nach Medieneinträge und Sets suggeriert, dass man Metadatenwerte tatsächlich auch entsprechend vergeben könnte. Dies ist aber nicht der Fall: Wenn man einen Metakey bei Medieneintrag auswählt, werden die Werte auch bei Sets eingetragen – und umgekehrt. So vergibt man ungewollt Metadatenwerte für Inhalte.

Die neue Stapelverarbeitung von Metadaten ermöglicht, dass Metadaten für Sets und Medieneinträge gleichzeitig vergeben werden können. Das gibt es bislang nicht im Medienarchiv. Daher muss man das sehr klar machen. Da es bei einer Aufteilung in zwei Tabs für Sets und Medieneinträgen nun zu ungewollten Fehlvergaben von Daten kommen kann, schlage ich vor, diese beiden Tabs wieder zusammenzunehmen. Dafür sollte man bei jedem Metakey lesen können, ob er für Medieneinträge, für Sets oder für beides gilt. Diese Angaben sind im Admin-Interface bei jedem Metakey festgelegt und daher vorhanden.

Die Angabe, wozu ein Metakey gehört, die jetzt sichtbar ist, ist sehr hilfreich. 
Die kleine graue Information sollte den jeweiligen Kontext angeben, der für "MediaEntry Edit" und für "Set Edit" definiert ist. Dies ist bei den Settings im Admin-Interface definiert. Falls die kleine grau Information das jeweilige Vokabular anzeigt, macht es keinen Sinn, diese Information bei den Tabs Editier-Kontexten anzuzeigen. Das stiftet nur Verwirrung, denn bei den anderen Edit-Ansichten sind auch die Kontexte angezeigt. Eine Bündelung nach Vokabularen findet nur im Tab „Alle Daten“ statt.
Die kleine graue Info müsste ergänzt werden, um die Angabe, ob der Kontext beim Medieneintrag oder beim Set gemeint ist. Jetzt wird z.B. beim Metakey „Material / Format / Sprache“ im Kontext „Objekt“ beim Medieneintrag angeben. Aber es werden auch Werte zum Metakey „Material / Format / Sprache" bei Sets im Kontext Werk gespeichert. 
Wenn ein Metakey in mehreren Kontexten vorhanden ist, dann sollte diese Info entsprechend angezeigt werden.
Seht die verschiedenen Fälle im Screenhot anbei.

![bildschirmfoto 2018-08-30 um 13 29 21](https://user-images.githubusercontent.com/1416731/44850004-2c991a00-ac5c-11e8-9371-5370507ebf97.jpg)
![bildschirmfoto 2018-08-30 um 13 38 36](https://user-images.githubusercontent.com/1416731/44850009-31f66480-ac5c-11e8-8e3f-5c2dbafa36b3.jpg)

**Comment by phiku** [comment]
@SusanneSchumacher Das Problem ist, dass Kontexte eigentlich im Eingabefall "Schablonen", "Formulare" oder "Templates" sind. Im Ausgabefall sind es einfach eine Menge von Daten, welche angezeigt werden sollen.

Ein Beispiel ist, es gibt eine Schablone für die ZHdK-Website. Das sind die empfohlenen Daten, wenn man ein Set auf der Website publizieren möchte. Nun ist es natürlich verwirrend, wenn diese Schablone eigentlich für Sets ist, aber man z.B. Titel wählen kann, welcher auch für Medieneinträge gültig ist. Richtig vermeiden kann man das aber nicht, da es nicht einen madek_core:entry_title und madek_core:set_title gibt. Das beste wäre, gar keine Kontexte anzuzeigen im Batchbereich. Das war zuerst auch so, dann hat Tashi geschrieben, dass die Benutzer verwirrt sind durch "Madek Core". Deshalb habe ich vorgeschlagen, "Madek Core" müsste einfach "Basisdaten" heissen. Das Problem kann man im Moment nicht lösen. Man muss die Kontexte aufräumen und so verwenden, wie sie eigentlich gedacht wären. Erst dann kann man logisch weiterfahren. Ein normaler Benutzer weiss sowieso nicht, was ein Kontext ist. Das muss alles viel einfacher werden.

**Comment by SusanneSchumacher** [comment]
@nadjaweisskopf 
Liebe Nadja, sehr schön, ihr habt noch weitere Verbesserungen eingefügt!

- [ ] Die Zusammenführung der beiden Tabs zum Tab Kontexte ist besser. Es besteht die Situation, dass man beide Entitäten gleichzeitig editieren kann. Das müsste man explizit hinschreiben, da es sonst nirgendwo so ist. Der beste Ort ist in die grauen Info unter dem Feldnamen: Dort stehen jetzt die Vokabulare, aber das ist falsch im Tab Kontexte. Dort sollte stehen: Medineintrag: .... / Set ...... (siehe Screenshot)
![bildschirmfoto 2018-08-30 um 13 29 21 kopie](https://user-images.githubusercontent.com/1416731/44987167-85332480-af86-11e8-8d40-ea45c2f559e6.jpg)


- [ ] Falls diese Info dort nicht angegeben werden kann, dann löscht die jetzt dort abgebildeten Namen der Vokabulare, sie sind dort falsch. Allerdings muss man dann woanders sichtbar machen, welche Felder Felder sich sowohl auf Medieneinträge wie auch auf Sets und welche sich nur auf eine Entität beziehen. 


- [ ] Achtung Die Meldungen sind nicht korrekt: Wenn ich in der Filterbar nach Medieneinträgen filtere, und aus den Feldern eines auswähle, das es eigentlich nur bei Sets gibt, dann müsste nun ein editieren ausgeschlossen sein. Statt dessen steht, dass ich die ausgewählten Medieneinträge editieren könnte. Und es wird mir sogar eine Erfolgsmeldung ausgestellt. Das ist falsch. Siehe die beiden Schritte in den Screenshots.
![stapel 1](https://user-images.githubusercontent.com/1416731/44987423-6f722f00-af87-11e8-8307-b5249667b08b.jpg)

![stapel 2](https://user-images.githubusercontent.com/1416731/44987432-74cf7980-af87-11e8-82f6-631eec82f8b7.jpg)

- [ ] Die Felder würde ich verständlicher beschriften. Ein Vorschlag:
![bildschirmfoto 2018-08-22 um 22 53 10 kopie 2](https://user-images.githubusercontent.com/1416731/44987542-d42d8980-af87-11e8-832e-e6c41df3563f.jpg)

**Comment by phiku** [comment]
@SusanneSchumacher Auf welchem System hast du getestet? Auf Staging ist "Projekttitel auf Entlisch" für beide aktiv, falls ich richtig geschaut habe und das richtig interpretiere:

![bildschirmfoto 2018-09-03 um 15 11 36](https://user-images.githubusercontent.com/16756048/44988688-dbef2d00-af8b-11e8-8787-297e2302cfa3.png)

**Comment by cmonstein** [comment]
Test auf https://test-blank.madek.zhdk.ch

Testfall:
Alle Medieneinträge > Batchverarbeitung > Kontexte: Set > Untertitel gewählt und etwas gesetzt > auf alle anwenden. 

Ergebnis:
Alle Medieneinträge hatten den neu gesetzten Untertitel direkt auf dem Medieneintrag.

Erwartung?:
Ich wäre davon ausgegangen, dass nur die Untertitel der Sets gesetzt würden, in meinem Fall keines, weil ich hatte ja nur Medieneinträge ausgewählt und keine Sets.

oder habe ich da eine falsche Erwartung? Wenn ich das Feedback von Susanne lese, geht es ihr ähnlich. Ausser: es wird nicht nur angezeigt, dass es möglich ist die Werte zu setzen, sondern sie werden auch effektiv gesetzt wenn man mittels "anwenden" ausführt. (in den Medieneinträgen und nicht in den Sets)

**Comment by cmonstein** [comment]
Test auf https://test-blank.madek.zhdk.ch

Testfall:
Personen hinterlegen und neue Personen erfassen
-> erfolgreich getestet bei Autor/in inkl. neuer Person erfassen

👍

**Comment by cmonstein** [comment]
Test auf https://test-blank.madek.zhdk.ch

Testfall:
Medieneinträge und Sets gemeinsam bearbeiten
Sets und Medieneinträge in Stapelverarbeitung gelegt > Batchverarbeitung > Kontext: Set > Untertitel gesetzt und auf alle angewendet.

Ergebnis:
Sets und Medieneinträge haben den neuen Wert im Feld Untertitel

Erwartung:
Sets und Medieneinträge haben den neuen Wert im Feld Untertitel

👍

**Comment by cmonstein** [comment]
Test auf https://test-blank.madek.zhdk.ch

Testfall:
über Favoriten-Medeineinträge die Bachtverarbeitung starten

-> funktioniert wie erwartet

👍

**Comment by phiku** [comment]
@cmonstein Wieso erwartest du, dass bei den anvertrauten Medieneinträgen die Titel nicht gesetzt werden können?

**Comment by cmonstein** [comment]
Antwort an @phiku 
Weil ich nichts setzten möchte, für was ich nicht berechtigt bin.

Erneuter Test mit "mir anvertrauten Sets"
die einen gehen, andere nicht, ich gehe davon die Berechtigungen wurden dementsprechend gesetzt.

**Comment by SusanneSchumacher** [comment]
@nadjaweisskopf @phiku @cmonstein 

Liebe alle
Relevant für das Editieren von Inhalten ist, ob ein Metakey in einem Kontext ist, welcher im Admin-Interface als Bestandteil Edit-Kontexte festgelegt ist. Dort im Admin-Interface wird festgelegt, wie die Editiermasken im Medienarchiv für Sets und für Medieneinträge aussehen!!!! Diese wird nun durch die Neue Stapelverarbeitung übersteuert. Das darf nicht sein, und daher braucht es die Info zu jedem Metakey, in welchem Edit-Kontext er ist.
![](https://user-images.githubusercontent.com/1416731/44850009-31f66480-ac5c-11e8-8e3f-5c2dbafa36b3.jpg)

Der Hinweis von Philipp, dass der "Projekttitel auf Englisch" auch für Medieneinträge möglich ist, ist sehr gut! Vielen Dank! Bislang konnte ein Metakey für Sets und Medieneinträge definiert werden, musste aber nicht zwangsweise in beiden Editier-Kontext enthalten sein. So beim "Projekttitel auf Englisch": dieser ist zwar definiert für Sets und Medieneinträgen, aber er ist nur im einem Editier-Kontext für Sets enthalten. So wird nun also bei der neuen Stapelverarbeitung ein Wert bei diesem Metakey auch für Medieneinträge eingetragen. Man kann ihn nur nicht lesen. Könnte ihn aber lesen, wenn der Key zukünftig in ein entsprechenden Kontext wandert. Tashi oder Philipp Oettli mag da nochmals drüber gehen und alle Metakeys prüfen.

**Comment by nadjaweisskopf** [comment]
@phiku @cmonstein @SusanneSchumacher Könnt ihr euch alle morgen zwischen 14.00 Uhr und 15.00 Uhr Zeit nehmen, damit wir uns treffen und das weitere Vorgehen besprechen können? Ich bin dafür, dass die Kontexte für die aktuelle Einführung nicht verwendet werden sondern wir nur "Alle Daten" anzeigen. Dann zeigen wir zusätzlich bei den geladenen Daten die Anzahl der Sets und die Anzahl der Metadaten an. Philipp ist nicht mehr lange auf dem Projekt. Entweder geht die Funktion live ohne den Menüpunkt anzuzeigen, was für mich worst case wäre, oder wir finden eine einfache Lösung. Aber über Github werden wir keine Lösung finden. Danke

**Comment by cmonstein** [comment]
@nadjaweisskopf passt für mich, bin frei zwischen 14-15 Uhr :)

**Comment by phiku** [comment]
@nadjaweisskopf Ja super Vorschlag! Bin verfügbar.

**Comment by phiku** [comment]
Wir werden das morgen besprechen, aber damit ich das bis morgen nicht vergessen: 
- Bisher war es auch möglich, mit "Alle Daten" den "Projekttitel auf english" zu setzen für Medieneinträge. Wenn also nur editierbar sein darf, was in einem Kontext ist, dann muss man "Alle Daten" entfernen. 
- Die Berechtigungen, was editiert werden darf, liegt auf den Vokabularen, nicht auf den Kontexten. Wenn jemand eine Berechtiung hat, ein Vokabular zu editieren, sollte der das auch können, egal ob alle Meta Keys in einem Kontext vorhanden sind oder nicht. 
- Eine Grundfrage wird sein, ist der Titel eines Medieneintrages dasselbe wie ein Titel eines Sets. Sollen diese gemeinsam editiert werden können. Sie sind jedenfalls derselbe MetaKey. 
- Es ist zwar verwirrend wenn ich aus dem Kontext Pflichtfelder den Titel auswähle, dann aber "Titel - Madek Core" steht. Andererseits ist es genauso verwirrend, wenn derselbe MetaKey in mehreren Kontexten verschieden heissen kann. 
- Eventuell sollte man den Kontext "Set" einfach nicht so benennen und dann schauen, ob man noch dieselben Probleme hat, dass man verwirrt ist, dass Medieneinträge mit editiert werden, wenn man im Kontext Set ist. Die Frage ist auch, kann ein Medieneintrag ein Set sein? Falls nicht, wenn ich via "Alle Daten" alles ausfülle, was im Kontext "Werk" ist, ist der Medieneintrag ein Werk? "Werk" darf nicht als "Klassifizierung" angesehen werden, sondern als Eingabehilfe. Oder aber, wir müssen uns klar auf eine Idee einigen, welche verhebt.

**Comment by SusanneSchumacher** [comment]
Ich versuche zu kommen, weiss aber noch nicht, ob ich es schaffe, da ich vorher extern bin.

Ich habe noch einen Vorschlag, der mit einem Schlag die Probleme lösen könnte:
- Das Problem entsteht, weil wir ermöglichen, Sets und Medieneinträge zusammen zu editieren, aber bislang die ganze Konzeption auf das getrennte Editieren hinaus läuft.
- Eine Lösung wäre, die neue Stapelverarbeitung nur für Sets und nur für Medieneinträge anzubieten. Umschalten kann man oben im Toggle, wie sonst auch. In dem Tab Kontexte und in dem Tab Vokabulare würden die Felder erscheinen, die möglich sind und zwar über die Edit-Kontexte aus dem Admin-Interface. Dort wo die Konfiguration gemacht wird.

**Comment by SusanneSchumacher** [comment]
Aus meiner Sicht kann es in der Besprechung nicht darum gehen, den Sinn und Zweck von Kontexten zu diskutieren oder sie gar abzuschalten. Das ist eine viel zu grundlegende Ebene und würde das System auseinanderreissen.
Es geht darum, die neue Stapelverarbeitung für Metadaten auf der Grundlage der jetztige Architektur zu ermöglichen und an die bestehenden Nutzungsformen anzupassen und zwar bis Ende der Woche.

**Comment by SusanneSchumacher** [comment]
Anbei Screenshot mit meine Beschriftungsvorschlägen.
- [ ] Tab(s) Kontexte umwandeln in "Felder Medieneinträge" und "Felder Sets". Wenn nur ein Tab, dann würde ich den "Metadatenfelder" nennen.
- [ ] Tab "Alle Daten" umbenennen in "Vokabulare". Diesen Begriff verwenden wir auch in der Seitenleiste usw.
Achtung! Dann müssen wir auch das Tab "Alle Daten" an vier weiteren Orten ändern: auf der Medieneintrag-Editseite, der Medieneintrag-Batch-Editseite, der Set-Editseite und der Set-Batch-Edit-Seite ändern.
- [ ] Anzeige der Hints wie auch sonst in den Editiermasken.
- [ ] Anzeige ob Medieneinträge und/oder Sets: "Diese Eingabe wird auf Medieneinträge / auf Sets / auf Medieneinträge und Sets angewendet."
- [ ] In den Boxen die Beschriften deutlicher machen und zwischen Medieneinträgen und Sets zu unterscheiden. 

Generelle Bemerkung: Wir nennen Medieneinträge immer zuerst, dann Sets.

![bildschirmfoto 2018-09-04 um 15 10 08](https://user-images.githubusercontent.com/1416731/45034831-d27fc680-b058-11e8-9500-ac0926e1d20a.jpg)
![bildschirmfoto 2018-09-04 um 15 23 01](https://user-images.githubusercontent.com/1416731/45034832-d27fc680-b058-11e8-8a04-ed144fa8b6e3.jpg)
![bildschirmfoto 2018-09-04 um 15 23 48](https://user-images.githubusercontent.com/1416731/45034833-d3185d00-b058-11e8-8013-5e1415bc9d37.jpg)
![bildschirmfoto 2018-09-04 um 15 31 39](https://user-images.githubusercontent.com/1416731/45034835-d3185d00-b058-11e8-829b-26bb190170b6.jpg)
![bildschirmfoto 2018-09-04 um 15 32 04](https://user-images.githubusercontent.com/1416731/45034836-d3185d00-b058-11e8-9411-f8f81c6e23b0.jpg)
