### ISSUE TITLE
Usability Optimierung

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#116]
Vorschläge für Optimierung:

- Sortierung der Einträge: https://github.com/Madek/madek/issues/125#issuecomment-428561170
- Export einzelner Medieneinträgen mit Metadaten - bessere Beschriftung https://github.com/Madek/madek/issues/115#issuecomment-415335246
- Import-Wizard
- GUI - Filter, Einstiegsseite, Import-Button immer sichtbar (Vorschlag Claudia)
- Neue Stapelverarbeitung für Berechtigungen und Verantwortlichkeiten erweitern
- Klarheit schaffen über Begrifflichkeiten - Madek-Core - Objekte - Kontexte
- Default bei Datierung eines Medieneintrags auf "am", dann "von - bis", dann "freitext" https://github.com/Madek/madek/issues/86
- PDFs als solche erkennen
- Daten finden scheint schwierig zu sein
- Allenfalls Sortierung der Einträge überprüfen - https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=245366

**Comment by phoettli** [comment]
Weitere Optimierung wird in anderen Issues/Projekten umgesetzt.
