### ISSUE TITLE
Madek-Exporter: Export failed

### ISSUE THREAD

**Issue by SusanneSchumacher** [Madek/madek#117]
@nadjaweisskopf 

- [ ] The  Madek-Exporter has a bug. The export does not work. I checked with Thomas whether I made a mistake, but he said it's a bug either of the Madek-Exporter or of the API.

Description:
Actual version of the Madek-Exporter for Mac (darwin X64-3, version 9th march 2018)
Download set: https://medienarchiv.zhdk.ch/sets/36e9c917-8c2b-4fe2-a389-fdd4a0602c43
with 246 media-entries.
The export could not be finished. This is the error-message:

![bildschirmfoto 2018-09-07 um 22 50 51](https://user-images.githubusercontent.com/1416731/45287147-e5c2e400-b4e7-11e8-8011-ebedf5ff00c3.jpg)

Context:
The SNF-Research Projekt "Iconography of Philosophy" of Nils Röller has to deliver a pool of images to prometheus-image archive. The export is needed. 
- [ ] Meanwhile  I want to send some technical docuementation of the Madek-Exporter and the data it delivers to the Prometheus-Bildarchiv. But on our technical documentation I cannot find a section to the Madek-Exportert (https://madek.readthedocs.io) Where is the documentation?

Feedback about the new batch processing: Preparing this export I used the new batch process. I was able to change permissions and to organize via set with all the 246 media entries at once. That was good!

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher Tashi has created the article for the exporter but not yet updated the the madek-help-pages. @ltsotrug please can you inform Susanne when the instruction is online?

I will have a look at the exporter tomorrow in the planning and inform you when the bug is fixed.

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher I just tested the exporter and with my set of four pictures it worked. So at least we don't have a general problem. I'll check with Thomas this specific case.

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher The exporter jumps from 56 entries done
![bildschirmfoto 2018-09-11 um 09 05 18](https://user-images.githubusercontent.com/3356016/45343825-47e01f80-b5a2-11e8-8ad6-fc9ecceb033e.png)


to error when reaching 100 media entries
![bildschirmfoto 2018-09-11 um 09 07 22](https://user-images.githubusercontent.com/3356016/45343818-40b91180-b5a2-11e8-92c4-5d7a7b949c34.png)

**Comment by DrTom** [comment]
Bummer: ich kann den Fehler nicht reproduzieren:

<img width="966" alt="screen shot 2018-09-11 at 10 52 02" src="https://user-images.githubusercontent.com/526053/45349151-d196e980-b5b0-11e8-9f3c-61b2e3473be1.png">

In den logs der Madek-API finde zur Zeit von Nadjas Export einen Fehler die mit den Berechtigungen zu tun hat. Ich müsste jetzt mit eurem login testen. Könnt ihr mir jeweils ein (temporäres) API-Token anlegen?

**Comment by DrTom** [comment]
@SusanneSchumacher wir können den Bug nicht mehr reproduzieren. Auch bei Nadja läuft es jetzt durch. Kannst du den Download bitte noch einmal bei dir starten?

**Comment by phiku** [comment]
@nadjaweisskopf @SusanneSchumacher Die Sprache sollte nur dann in der Url erscheinen, wenn man sie aktiv selektiert hat. In den meisten Fällen entspricht sie dann eben genau nicht mehr der Browsereinstellung, was dann korrekt wäre. Ob man die Sprache in der Url will, muss man definieren (kann auch Vorteile haben). Aber das sollte in ein neues Ticket und hat nichts mit dem hier zu tun.

**Comment by ltsotrug** [comment]
> @SusanneSchumacher Tashi has created the article for the exporter but not yet updated the the madek-help-pages. @ltsotrug please can you inform Susanne when the instruction is online?
> 
> I will have a look at the exporter tomorrow in the planning and inform you when the bug is fixed.

@SusanneSchumacher @nadjaweisskopf the instruction is now online

**Comment by nadjaweisskopf** [comment]
created a new ticket for URL topic: https://github.com/Madek/madek/issues/123
