### ISSUE TITLE
Test-Server von Suchmaschinen-Index ausschliessen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#119]
@nadjaweisskopf Web-Suche gibt z.T. Ergebnisse von Test-Servern zurück
![image](https://user-images.githubusercontent.com/42544602/45363449-d8852280-b5d7-11e8-9e7d-60a295a90576.png)

Test-Server bitte ausschliessen aus Web-Suche:
https://www.google.ch/search?q=inurl%3Astaging.madek
https://www.google.ch/search?q=inurl%3Atest.madek
https://www.google.ch/search?q=inurl%3Atest-blank.madek

**Comment by gurmir** [comment]
Wird mit der Entwicklern nächste Woche besprochen

**Comment by nadjaweisskopf** [comment]
@eins78 Parameter einstellbar - Test ausschliessen

**Comment by eins78** [comment]
- parameter eingebaut, default ist 'erlauben' (auch das default wenn nicht implementiert, also bisher)
- alle nicht-prod server auf 'verboten'
- Bsp: siehe https://test.madek.zhdk.ch/robots.txt
