### ISSUE TITLE
Personenfelder für Metadatenbeschreibung sind öffentlich

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#120]
**Problem:**
Silke Gründer hat sich im Google entdeckt, obwohl sie keine eigenen Werke im Medienarchiv veröffentlicht:
https://medienarchiv.zhdk.ch/people/a842f699-20b6-4b12-9f90-c7c946b986b0
Einzelner Eintrag mit ihrem Namen:
![20180917_descby_ext](https://user-images.githubusercontent.com/42544602/45631544-6743e480-ba9b-11e8-9240-7db90cde2bcc.png)

Die beiden Rechte-Felder «Beschreibung durch» und «Beschreibung durch vor Upload» werden öffentlich ausgegeben:
https://medienarchiv.zhdk.ch/vocabulary/copyright/people
Felder in der Edit-Ansicht:
![20180917_descby_fields](https://user-images.githubusercontent.com/42544602/45631451-34015580-ba9b-11e8-88d9-7441a19cf406.png)

Rolf ist der Ansicht, **diese Felder dürften nicht öffentlich sein**.
Für mich erschliesst sich die Funktion dieser Felder nicht genau. @SusanneSchumacher und @nadjaweisskopf wisst Ihr genaueres, wozu diese Felder gedacht sind und ob die überhaupt noch verwendet werden?

**Lösungsvorschlag:**
Falls die Felder noch gebraucht werden:
Max meinte, die Felder könnten in ein spezielles Vokabular verschoben werden, das nur für eingeloggte User sichtbar wäre: 

> Wir könnten ein Vokabular "nicht-öffentliche Personendaten" machen, den betr. Key dahin verschieben. In den Kontexten kann man es dann aber so aussehen lassen wie vorher.

Bitte baldmöglichst umsetzen, da hier viele Personen öffentlich erscheinen, die nicht sichtbar sein sollten.

**Comment by SusanneSchumacher** [comment]
Dieses Feld bezeichnet die Autorschaft der Metadaten. Es ist öffentlich, weil die Metadaten auch öffentlich sind. Es macht kein Sinn, es zu verbergen. Wenn jemand seinen Namen dort nicht stehen haben möchte, soll er/sie ihn nicht eintragen. Das Feld ist kein Fehler oder "veraltet", sondern Bestandteil des Metadatenschemas.

**Comment by phoettli** [comment]
Sehr gut, jetzt verstehe ich die Funktion des Feldes. Wir werden Silke aus dem Feld löschen. Und mit Rolf schauen, wer dort sonst noch gelöscht werden soll.
@nadjaweisskopf du kannst das Issue schliessen.

Danke für die Hilfe!
