### ISSUE TITLE
Userin möchte ihren Namen gelöscht haben

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#121]
S.G. wünscht nicht im Medienarchiv aufgeführt zu werden.
Tashi hat alle Einträge von ihr im Feld "Beschreibung durch" entfernt.
Im Admin-Bereich ist sie als User [edit]~~nicht mehr~~ **noch immer**[/edit] aufgeführt:
https://medienarchiv.zhdk.ch/admin/users?utf8=✓&search_term=gruender&sort_by=first_name_last_name&commit=Apply
Unter People wird sie noch einmal verwendet:
https://medienarchiv.zhdk.ch/admin/people?utf8=✓&filter%5Bsearch_term%5D=gründer&filter%5Bsubtype%5D=&commit=Apply
![image](https://user-images.githubusercontent.com/42544602/45764801-c9cfe880-bc33-11e8-937f-22486a9f2688.png)
können diese Eintrag bedenkenlos gelöscht werden [edit] oder hat dies Konsequenzen zur Folge? z.B. fehlende User-Einträge in der Bearbeitungs-History [/edit]?

Bitte danach die Person-URL aus dem Google-Index entfernen:
https://medienarchiv.zhdk.ch/people/a842f699-20b6-4b12-9f90-c7c946b986b0

**Comment by nadjaweisskopf** [comment]
@phoettli überschreibt den Namen - Thema wird im Refinement im Detail besprochen.
