### ISSUE TITLE
Language in URL

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#123]
Etwas neues ist mir aufgefallen: Beim "Set teilen", wo man die Adresse für den Madek-Exporter kopiert, steht neu im Feld hinter der UUID noch die Einstellung zur Sprache. Zum einen gehört sie nicht zur UUID und zum anderen ist sie in meinem Fall nicht korrekt gewesen: bei mir was die Sprache auf Deutsch eingestellt und nicht auf Englisch.

![bildschirmfoto 2018-09-25 um 09 14 43](https://user-images.githubusercontent.com/3356016/45999126-22c0d600-c0a5-11e8-9add-3bbf70459ac9.png)

**Comment by nadjaweisskopf** [comment]
Comment from @phiku 

@nadjaweisskopf @SusanneSchumacher Die Sprache sollte nur dann in der Url erscheinen, wenn man sie aktiv selektiert hat. In den meisten Fällen entspricht sie dann eben genau nicht mehr der Browsereinstellung, was dann korrekt wäre. Ob man die Sprache in der Url will, muss man definieren (kann auch Vorteile haben). Aber das sollte in ein neues Ticket und hat nichts mit dem hier zu tun.

**Comment by phoettli** [comment]
ist korrekt wie es sein soll.
