### ISSUE TITLE
Userin wünscht nebst der aufsteigenden Titelsortierung eine absteigende Titelsortierung

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#125]
Weitere Infos: https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=245366

**Comment by nadjaweisskopf** [comment]
@ltsotrug Tashi, können wir bitte nochmals zusammensitzen, Du zeigst mir wo die Sortierung nicht stimmt? Innerhalb vom Set, in einer Übersicht? Meldest Du Dich bei mir?

**Comment by ltsotrug** [comment]
Die Sortierung funktioniert grundsätzlich. Userin möchte aber nebst der aufsteigenden Titelsortierung (betrifft alle Seiten, welche Inhalte anzeigt) **_zusätzlich_** eine absteigende Titelsortierung. Siehe Bildschirmfoto:

![2018-10-10_14-28-37](https://user-images.githubusercontent.com/29139407/46737459-cf04de00-cc9b-11e8-8c74-f4c8e0fbace9.jpg)

Das heisst: Der erste Medieneintrag sollte anhand des Bildschirmfotos der Titel **_Zett 2018, 5_** anschliessend **_Zett 2018, 4_** und so weiter sein.

Siehe auch: 

![bildschirmfoto 2018-10-10 um 14](https://user-images.githubusercontent.com/29139407/46737819-cc56b880-cc9c-11e8-9598-366eca47b418.jpg)


Userin wünscht dieselbe Möglichkeit wie bei der Sortierfunktion nach Importdatum **_aufsteigend absteigend_**

**Comment by eins78** [comment]
@michalpodlecki We want to add a sort option "by title DESC", please contact me when you'll start so i can give you an overview of the related functionality

**Comment by eins78** [comment]
@ltsotrug Es funktioniert auch für den konkreten angefragten Fall wie gewünscht. Siehe https://test.madek.zhdk.ch/sets/29a0ae8f-663b-4536-a434-61810fa2e5f4?list%5Blayout%5D=list&list%5Border%5D=title%20DESC
Besitzer des Sets oder Admin muss dann nach deploy die Darstellung anpassen speichern.

**Comment by phoettli** [comment]
Feature fehlt bei mir auf STAGING:
![image](https://user-images.githubusercontent.com/42544602/53018994-0a869480-3454-11e9-8660-3348b894399a.png)
https://staging.madek.zhdk.ch/sets/29a0ae8f-663b-4536-a434-61810fa2e5f4?list%5Blayout%5D=grid

Auf TEST sehe ich die Sortierfunktion "Nach Titel absteigend" allerdings:
![image](https://user-images.githubusercontent.com/42544602/53019081-3a359c80-3454-11e9-8ea9-f7dc60453f1e.png)
https://test.madek.zhdk.ch/sets/29a0ae8f-663b-4536-a434-61810fa2e5f4?list%5Blayout%5D=grid&list%5Border%5D=created_at%20DESC

**Comment by eins78** [comment]
@phoettli sorry, hatte vergessen den RC für staging zu markieren, also wurde es heute nacht zurückgesetzt (auf test ist es, weil dort immer der allerneueste stand ist). Muss meine checkliste nochmal verbessern dahingehend…
Jetzt deployed es gerade wieder den Stand wie schon angekündigt (und bleibt auch).

**Comment by phoettli** [comment]
ok auf STAGING
