### ISSUE TITLE
Audio-Datei (aiff) lässt sich nicht abspielen

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#127]
![aiff bug](https://user-images.githubusercontent.com/29139407/46465109-2dc3e680-c7c8-11e8-9cb0-2bf9a47fac3c.png)

Weitere Infos:
https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=246696

**Comment by nadjaweisskopf** [comment]
@ltsotrug Könntest Du uns bitte das File zukommen lassen damit wir das testen können? Merci

**Comment by ltsotrug** [comment]
@nadjaweisskopf das Problem hat sich gelöst. Der User hat eine andere Version der Datei erfolgreich importieren können. Das Ticket kann geschlossen werden. Merci.

**Comment by nadjaweisskopf** [comment]
@phoettli Ticket wird geschlossen, siehe Kommentar von Tashi.
