### ISSUE TITLE
Testresults Madek - Roles of Person

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#128]
Here are the Testresults for the First Part for Admin:

**Comment by JudithScheiber** [comment]
Meeting october 17, 2018,14.00 Philippe, Rolf, Michal, Judith

Our feedback: we do not need the metakey. The origin idea was something else. now we decided that a flat list of roles is sufficient.
adding a person or choosing an existing person: this function should be visibly separated from assigning a role. One thing is adding a new person or choosing an existing. and another thing is assigning a role.
Michal will make a proposal (sketch) how he would do that.
A person can get different roles, not only one so it is a 1:n relation (person:role).
More testing make sense when records can be saved.

The existing field "Mitwirkende Personen" should only be visible on tab "Alle Daten". We want to prevent users from using this old field instead or additional to the new one.
Adding a new media record shall show only the new field "mitwirkende Person".

**Comment by phoettli** [comment]
Hi Michal, small bug in rare situations:

1. I have 2 mentions of the same Person with different roles
2. I delete one of the two roles
3. then I delete this mention of the Person without role
4. => both mentions of the Person are gone, not only the selected one

![image](https://user-images.githubusercontent.com/42544602/49144843-a34abf80-f2fe-11e8-8589-60a038c43182.png)

**Comment by michalpodlecki** [comment]
@phoettli Thank you for the detailed description. I've just fixed it.

**Comment by JudithScheiber** [comment]
@Max:
as discussed in yesterday's meeting we suggest the following button labels:
1. Rolle bearbeiten / Edit role
2. Rolle löschen / Delete role
3. weitere Rolle hinzufügen / Add another role
4. either Button with a grey X and tooltip "Zeile löschen" or button "Zeile löschen" / "Delete row"

**Comment by JudithScheiber** [comment]
Ablauf:
1. Max erstellt die Buttons
2. Max ändert den Filter "Persons" noch in deutsch "Personen"
3. Deploy
4. Philipp erstellt die Context-Felder (Metadatenfelder)
5. Philipp beschriftet die neuen Context-Felder
6. Philipp passt die Reihenfolge an.
7. Philipp plant mit HSK die Anpassung im Projektschaufenster
8. Anpassung der Benutzerdokumentation (Tashi/Philipp)

Die Betroffenen wissen die beste Reihenfolge ihrer Aufgaben am besten, falls meine Aufzählung komisch sein sollte....
vielen Dank
Judith

**Comment by phoettli** [comment]
@eins78 [Änderung in Punkt 4](https://github.com/Madek/madek/issues/128#issuecomment-446241148) würde ich weglassen. Grünes X zum Löschen gibt es auch im Filter...

**Comment by eins78** [comment]
Change: Roles will be scoped to MetaKeys, like Keywords. Admin UI will look like Keywords (List with subheading)

**Comment by eins78** [comment]
merged in 
https://github.com/Madek/madek/commit/f8ed4d3580808a09fe2589532b5b1a6118b774a6
