### ISSUE TITLE
Berechtigungs-Fehler für Video bei Zugriff im Admin-Modus

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#129]
1. User hat File hochgeladen, es erscheint der bekannte Fehler während Codierung

2. ich möchte mit Admin-Rechten auf das Medienfile zugreifen, um nachzuschauen, ob Fehler reproduzierbar. Dazu öffne ich die URL
URL: ~ /entries/24ec0045-d698-4693-b8bb-5ae8fdc0c903

3. und wechsle in den Admin-Modus:
![image](https://user-images.githubusercontent.com/42544602/47347777-3d8c6780-d6b0-11e8-9fe5-fbaa4a9b807f.png)

4. Die Metadaten werden angezeigt. Anstelle des Videos wird hingegen folgender Fehler angezeigt:
![image](https://user-images.githubusercontent.com/42544602/47293930-dddc8080-d60b-11e8-941d-a60175cd1fbf.png)

**Comment by eins78** [comment]
Kann ich nicht mehr reproduzieren, scheint also schon nebenbei repariert zu sein während der Umbauten zwecks Vertrauliche Links.
Ich habe auch überprüft, dass es mit Entwürfen funktioniert (die haben ja noch speziellere Permissions, hätte anders schiefgehen können)

![Screen Shot 2019-04-05 at 11 55 16](https://user-images.githubusercontent.com/134942/55619766-b3d1e180-5799-11e9-9d5d-4e56312d7055.png)

**Comment by phoettli** [comment]
sieht gut aus auf `staging`
