### ISSUE TITLE
People mit "unsichtbaren" Medieneinträgen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#130]
Wie finde ich die zugehörigen Medieneinträge von Personen (People), bei denen auf der Personen-Seite auch im Admin-Modus keine Inhalte angezeigt werden:
![image](https://user-images.githubusercontent.com/42544602/47368398-df787800-d6e1-11e8-8d6e-ed7666e78048.png)

![image](https://user-images.githubusercontent.com/42544602/47368505-0c2c8f80-d6e2-11e8-84cb-3751add2ca30.png)

oder
![image](https://user-images.githubusercontent.com/42544602/47368656-54e44880-d6e2-11e8-830c-cc6d5a6de9da.png)

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/c72851c2edc720554385420d64f1e45df890c3eb

**Comment by phoettli** [comment]
@eins78 bei mehreren Einträgen ok. Worauf bezieht sich die "1 Time Usage" ? Diese wird nicht sichtbar.

**Comment by eins78** [comment]
> @eins78 bei mehreren Einträgen ok. Worauf bezieht sich die "1 Time Usage" ? Diese wird nicht sichtbar.

@phoettli du musst erst noch in den admin modus wechseln. der bug, der repariert wurde, war dass bei den Personenseiten dieser bisher ignoriert wurde.

- https://staging.madek.zhdk.ch/admin/people?utf8=✓&filter%5Bsearch_term%5D=heidelberg&filter%5Bsubtype%5D=&commit=Apply
- https://staging.madek.zhdk.ch/people/3143d5f1-4401-4bf1-a4c1-1e9ba271d615

**Comment by phoettli** [comment]
OK bei "Heidelberg"

bei folgenden nicht OK (u.a.):
Abc: https://staging.madek.zhdk.ch/people/12d0aabc-0f01-468d-80e6-98ad5938355c
https://staging.madek.zhdk.ch/people/905dcc96-89d6-4485-835a-8fe17d17bf53
https://staging.madek.zhdk.ch/people/78af328c-5610-467d-b348-f82192a32525

**Comment by phoettli** [comment]
@eins78 hast du meine Punkte im vorhergehenden Kommentar noch gesehen?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/5e080631be250c7882110d715c8ebd24f9b652f9

**Comment by nimaai** [comment]
@phoettli Die Zahl im Admin-Bereich war falsch. Hab's behoben.

**Comment by phoettli** [comment]
es gibt noch wenige Einträge mit weiterer fehlerhafter Zählung:
https://github.com/Madek/madek/issues/157
