### ISSUE TITLE
Fehlender Sprachparameter im Aktionen-Menü

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#132]
Im Aktionenmenü wird der Sprachparameter den Links nicht übergeben. z.B. hier:
https://medienarchiv.zhdk.ch/entries/f1e1bdd1-2bc2-4d18-92f9-7879d90ce3f9?lang=en
![image](https://user-images.githubusercontent.com/42544602/47790329-2b956f00-dd17-11e8-85f5-23b324f1965d.png)

kommt er in allen Links mit, ausser denen im Aktionenmenü. Dies hat ein unerwarteter Sprachwechsel zur folge.

**Comment by eins78** [comment]
@phoettli Ungewöhnliche Situtation: Es ist ein schwierig zu reproduzierendes Problem, denn es tritt nicht immer auf. Bei mir kam es sehr selten, bei michals Versuchen in circa 50% der Fälle.
Wir haben aber den Code angeschaut und allgemein verbessert, d.h. durch leichtes Refaktoring die Komplexität verringert, in der Hoffnung dass das Problem nun nicht mehr auftritt, was auch immer es nun genau war.

**Comment by phoettli** [comment]
ok, sieht aktuell bei mir gut aus auf `staging`
