### ISSUE TITLE
Metadaten-Stapelverarbeitung nur für ausgewählte User sichtbar

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#134]
Die neue Stapelverarbeitung bitte nur für ausgewählte User sichtbar machen, z.B. speziell definierte Usergruppe

![image](https://user-images.githubusercontent.com/42544602/48698031-5f610780-ebe6-11e8-8613-8dc08f51d6fd.png)

**Comment by phiku** [comment]
@phoettli Aus Neugier, gibt es einen Grund dafür (Bugs, Verständlichkeit)?

**Comment by phoettli** [comment]
@phiku Hoi Ebenfallsphilipp - sei herzlich gegrüsst :)

Es gibt einen Namenskonflikt zwischen der bestehenden Stapelverarbeitung und der neuen: heissen beide gleich, funktionieren aber komplett anders, für ungeübte User nicht optimal für die Orientierung.

Da wir davon ausgehen, dass die neue Stapelverarbeitung (ein sehr cooles Tool übrigens!) vorerst vorallem von geübten Usern genutzt wird, können wir sie durch die ausgewählte Usergruppe, nur denen zuweisen. In dieser temporären Phase ("BETA"-Status) bleibt dann Zeit, den Namenskonflikt aufzulösen, Erfahrungen zu sammeln, Problemstellen bereinigen, Dokumentation erstellen.

**Comment by phoettli** [comment]
Vorschlag neue Stapelgruppe: Batch Process Beta Group
Userverwaltung durch @ltsotrug

**Comment by nadjaweisskopf** [comment]
Berechtigung für das Menü anlegen. Gruppe anlegen.

**Comment by nadjaweisskopf** [comment]
nw: 15.1. besprochen und für nächste Iteration einplanen

**Comment by eins78** [comment]
ref: vorherige umsetzung des gleichen konzepts: https://github.com/Madek/madek/commit/83dd5d6fbf5d330025ae8d54a9cb75b412446215

**Comment by phoettli** [comment]
Wie kann ich Funktion einer Gruppe zuweisen?

**Comment by eins78** [comment]
> Wie kann ich Funktion einer Gruppe zuweisen?

Die Gruppe ist fest eingebaut, es müssen nur User hinzugefügt werden. Hier ist sie auf staging (die UUID ist fix/überall die selbe): https://staging.madek.zhdk.ch/admin/groups/8ffe3710-088c-5b31-ad23-573335c9017a

**Comment by phoettli** [comment]
Ok auf STAGING
