### ISSUE TITLE
unvermittelter Sprachwechsel bei ähnlichen Inhalten

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#135]
bei folgendem Medieneintrag
https://medienarchiv.zhdk.ch/entries/d2d42b97-406f-4c0b-8776-480bc00f4fd6
erscheinen bei mir bei ca. jedem 10. Reload die mittleren beiden "ähnlichen Inhalte" Zeilen mit englischem Sprachparameter. 1. und 4. Zeile sind korrekt ohne.
(Fenstergrösse ca 1440 px breit)
![image](https://user-images.githubusercontent.com/42544602/48774868-affe6080-eccb-11e8-896d-3a32d735a931.png)

**Comment by eins78** [comment]
@phoettli Ich glaube, das hat sich auch erledigt – magst du nochmal prüfen und ggf. schliessen?

**Comment by phoettli** [comment]
@eins78 ich hab das Issue ebenfalls in den Milestone aufgenommen. Auf `prod` tritt der Fehler bei mir noch häufig auf, auf `staging` dagegen nicht mehr. Gute Arbeit !

**Comment by phoettli** [comment]
@eins78 sorry, habe mich vertan: ist auch auf `prod` bereits weg...

**Comment by eins78** [comment]
> @eins78 sorry, habe mich vertan: ist auch auf `prod` bereits weg...

Wie erwartet, die Verbesserungen dazu waren schon im letzten Release :)
