### ISSUE TITLE
Medieneintrag mit vielfachem Export im selben Format

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#138]
dieser Medieneintrag hat pro Format 4-5 Downloadversionen
https://staging.madek.zhdk.ch/entries/efe3ab27-11cb-448f-88c7-0a5cf4f0a903/export

![image](https://user-images.githubusercontent.com/42544602/49028347-71244b00-f1a2-11e8-9f59-4c69b9a0bec9.png)

**Comment by phoettli** [comment]
Max meint: Auf 'Reencode' klicken und Ergebnis anschauen.

**Comment by eins78** [comment]
@phoettli Dein Link geht auf `staging`. Hast du das re-encode in `prod` probiert oder dort? Auf `staging` kann es keine Auswirkung haben, weil dort die Dateien nicht schreibbar sind.

Am besten wäre es, wenn du die Original-Dateien auf https://test-blank.madek.zhdk.ch neu importierst. Dort ist der Speicher schreibbar, und die Zencoder-Einstellungen sind identisch. Wenn dort das gleiche Verhalten/Dopplungen auftritt, kann ich genauer Debuggen woran es liegt.

**Comment by phoettli** [comment]
ja klar, reencode auf PROD.
Import auf test-blank geht nicht: Fehler!
![image](https://user-images.githubusercontent.com/42544602/57692743-db915080-7647-11e9-9c1d-f4c02046d1ea.png)

**Comment by eins78** [comment]
@phoettli OK, dann debugge ich mal genauer woran es liegt.

**Comment by phoettli** [comment]
@eins78 hab grad nochmal das neueste Video angeschaut: 
Mediafile e0973cc9-be57-4e2d-a583-d8bea62dfc54 mit **3021 (!) Previews.** (99 Stills x 5 Encodings x 6 Formate)

hier noch ein paar andere Videos
[138_Mehrfachencoding.txt](https://github.com/Madek/madek/files/5553575/138_Mehrfachencoding.txt)
praktisch immer 4 Encodings, manchmal 5

So geht das definitiv nicht! Bitte beheben oder Workaround finden, danke.

**Comment by eins78** [comment]
Erkenntnisse:

1. *bad news:* Ich kann es leider nicht reproduzieren: es scheint ja sehr selten vorzukommen und die wahrscheinlichkeit ist sehr gering es bei manuellem testen zu beobachten. Anhand der beispiel-videos habe ich geschaut, ob es z.B. an deren auflösung liegen könnte (zoom-recordings sind grösser als HD, wäre nicht überraschend wenn dann ein subtiler bug sich bei den wunsch-formaten verrechnet, dem ist aber nicht so). Es könnte noch sein, dass das Problem nur bei sehr langen Videos auftritt, die Vermutung wäre: ein logikfehler beim import der previews, wenn der download nicht "sofort" fertig ist und sich dann vielleicht verschiedene nachrichten von Zencoder kreuzen. Das kann man aber noch schwieriger nachvollziehen, weil der Durchlauf dann 1h dauert, und dann hängt es noch von externen Faktoren ab (wie schnell der Download von Zencoder ist hängt uch vom Netzwerk bzw "Internet Weather" generell ab).

2. *good news*: es werden laut Zencoder-seitigem Log zumindest keine mehrfachen Encoding-Jobs in Auftrag gegeben! D.h. es entstehen keine direkten Mehrkosten, nur marginal mehr Netzwerk-traffic und (aktuell noch) mehr Speicherplatz. Man sieht es auch im Madek-Admin an den Timestamps der Previews, die sind alle nur wenige Sekunden bis Minuten auseinander – ein ganz neuer Job würde ja viel länger dauern.

Minimal-Vorschlag: Den Code, der die Nachrichten von Zencoder interpretiert und die Previews importiert so anpassen, dass immer nur die letzte Version pro Format behalten wird. Dann würde in diesen Problem-Fällen zwar noch mehrfach importiert werden aber nur noch 1 behalten. Ob das mit den Image-Thumbnails überhaupt so geht muss ich noch prüfen.

**Comment by eins78** [comment]
Entscheid mit @phoettli: Zencoder-Integration wird z.Z. nicht angefasst sondern im Rahmen des Fileservice-Projekts. Stattdessen Anzeige anpassen und DB aufräumen.

1. Duplikate im Export-Dialog ausblenden (nach Dateiname, nur die neueste Version nehmen) -> dieses Ticket
2. DB per Script aufräumen. Muss in Ruhe geprüft werden um keine Fehler zu machen (es würde ~100k Files gelöscht werden) -> neues Ticket

**Comment by eins78** [comment]
fix export anzeige: https://github.com/Madek/madek-webapp/commit/919ddd3b8f440084a88d685949416c471437e2f5

![Screen Shot 2020-12-07 at 15 32 22](https://user-images.githubusercontent.com/134942/101363225-6cbabe80-38a1-11eb-871b-33bae4a44a75.png)
