### ISSUE TITLE
Externe User anlegen mit Deaktivierungsdatum

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#140]
Externe User sind vielfach nur für eine bestimmte Zeit auf der Plattform zugelassen. Gegenwärtig muss aber immer manuell überprüft werden, ob diese User noch berechtigt sind, auf der Plattform zu bleiben. Vereinfachen würde
- ein Deaktivierungsdatum,
- das bei der Erstellung des Users festgelegt werden kann (nicht Pflicht-Feld)
- später noch geändert oder gelöscht werden kann

damit die Zugangsberechtigung automatisch deaktiviert wird, sobald dieses Datum überschritten wird.

**Comment by eins78** [comment]
Siehe auch #45 – könnte mit minimaler Änderung an dortiger spec umgesetzt werden (`users.account_disabled_after<Timestamp>` statt `users.account_disabled<Bool>`.)

**Comment by phoettli** [comment]
- [ ] 1. Schritt: Datumsfeld für Verfalldatum einfügen (@DrTom)
- [ ] 2. Backend erweitern für Datumseingabe
- [ ] 3. User deaktivieren nach Verfall

**Comment by phoettli** [comment]
Punkte 2 & 3 in Release 4.3.0 erledigt
