### ISSUE TITLE
Suche: einzelne Sonderzeichen führen zu Fehler

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#143]
einzelne Sonderzeichen wie ' ( | ) im Suchfeld führen zu Fehlern:
![image](https://user-images.githubusercontent.com/42544602/50075347-fa95ce80-01de-11e9-9072-b10c986b4a72.png)

gibt es noch weitere?

**Comment by eins78** [comment]
we had a similar issue before, where input string where not correctly sanitized. 
https://github.com/Madek/madek/issues/80 =>
https://github.com/Madek/madek-datalayer/commit/900aff195e90a2a50f23bbaeeea27cf0d28017df

**Comment by nimaai** [comment]
https://github.com/Madek/madek-webapp/commit/3cc97b4efb329b96c047108e52972179a64c33a6

@eins78 Now it doesn't crash, but some special chars are still removed by PG text search for english language. Search for `english` in datalayer.

**Comment by nadjaweisskopf** [comment]
1. @eins78 check autom. tests
2. @phoettli test with the next release candidate

**Comment by phoettli** [comment]
die Fehler sind bei mir immer noch auf STAGING:
Pipe: 
[20190128_143_pipe.txt](https://github.com/Madek/madek/files/2803046/20190128_143_pipe.txt)
Single Quote:
[20190128_143_singlequote.txt](https://github.com/Madek/madek/files/2803048/20190128_143_singlequote.txt)
Klammer auf:
[20190128_143_klammerauf.txt](https://github.com/Madek/madek/files/2803050/20190128_143_klammerauf.txt)
Klammer zu:
[20190128_143_klammerzu.txt](https://github.com/Madek/madek/files/2803051/20190128_143_klammerzu.txt)

**Comment by eins78** [comment]
Update: der Fix hat andere Teile der Suche kaputt gemacht. Warum ist spontan unklar, kann jedenfalls nicht ausgeliefert werden. Morgen besprechen.

**Comment by eins78** [comment]
@nimaai Die Suche ist nun plötzlich case-sensitiv(!), mehr Fehler habe ich noch nicht gefunden. Siehe tests – die Fehler sind echt ;) https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/c39f1646-256d-4f5b-8dcb-bf6b22d78e16

**Comment by ltsotrug** [comment]
weiter Sonderzeichen, welche Server-Fehler verursachen sind: & : !

**Comment by nimaai** [comment]
@eins78 Let's do it like in leihs/procure. Single string ILIKE (no tokenization and AND logic) with unaccent.

**Comment by eins78** [comment]
@nimaai bitte grobe übersicht aus den tests ziehen, welche "cases" überhaupt getestet/implementiert sind. im einfachsten fall die überschriften anpassen.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/0c427fe5cf3154f8bcd5131de8348f352a475b78

**Comment by nimaai** [comment]
Unser einzige bestehende Test in diesem Hinblick: 
* Suche nach einem von: `['mazda', 'Mazda', 'MaZdA', 'mazda 2', 'mazda '] => 'mazdamazda 2018'`
