### ISSUE TITLE
Statusanzeige beim Importieren (Fortschritt beim Importvorgang soll in Prozentzahlen live angezeigt werden) 

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#144]
User verwenden fast immer das WLAN beim Importieren von Dateien. Beim Import von Videofiles dauert es teils sehr lange und die User wissen nicht, wo der Upload Prozess steht oder gescheitert ist. 

Bsp: (siehe roter Kreis)  

![3 17 2_spyri_2_import_3pfeile_vers 3_ohnewolke](https://user-images.githubusercontent.com/29139407/50761533-f0f60880-126a-11e9-9205-67e7a8dbcd7a.jpg)

(Screenshot stammt aus einem früheren Release aus 2018: 3.17.2 spyri)

**Comment by phoettli** [comment]
oh, diese Anzeige gibt es noch nicht? Bitte prioritär angehen.

**Comment by nadjaweisskopf** [comment]
nw: 15.1. besprochen und für nächste Iteration einplanen
Lösung: Text anzeigen wie oben dargestellt

**Comment by eins78** [comment]
update: habe bei der recherche gefunden das es das feature schon gab, wurde nur durch umbauarbeiten aus versehen versteckt. 
wiederbelebt und auf deutsch übersetzt, ansonsten ist es noch/wieder so wie im screenshot.
