### ISSUE TITLE
Upload-Bereich benötigt Textergänzung bzgl. verwendung eines Netzwerkkabels bei Videofiles

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#145]
User importieren oft via WLAN ihre Files. Bei Videofiles dauert jedoch der Import sehr lange. User sind dann irritiert und brechen den Import ab. 

Bsp:

![bildschirmfoto 2019-01-07 um 09 09 41](https://user-images.githubusercontent.com/29139407/50759108-572b5d00-1264-11e9-8d5d-565e5d744738.png)

**Comment by nadjaweisskopf** [comment]
@phoettli eher was allgemeines schreiben wie "auf gute Verbindung achten" statt "Kabel verwenden". Max bitte den Text senden.

**Comment by phoettli** [comment]
Sprachfile Zeile 296, Label: media_entry_media_import_notes_msg

DE:
Für grosse Dateien auf eine schnelle Internet-Anbindung achten (Netzwerkabel).
Bilder (TIFF, JPEG, PNG) sowie Audio- und Videofiles in den gängigsten Formaten werden direkt verarbeitet und dargestellt. Bilder im CMYK-Farbraum werden nicht korrekt dargestellt. Wandeln Sie diese vor dem Importieren in RGB um.

EN:
Please use a fast internet connection (network cable) for large files. 
Images (TIFF, JPEG, PNG) and audio/video files in the most common formats are processed and displayed directly. Images in the CMYK color model cannot be displayed correctly, please convert to RGB before uploading.


Werden auch Zeilenumbrüche berücksichtigt?

**Comment by eins78** [comment]
done in 
https://github.com/Madek/madek/commit/c80e08e5e101160247c27e87e3857c2d751616b8

**Comment by phoettli** [comment]
ok auf STAGING
