### ISSUE TITLE
Kachel-Ansicht: fehlender Hinweis bei Videos

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#146]
In der Kachel-Ansicht der Vorschau fehlt bei Videos ein Hinweis auf das Format:
![image](https://user-images.githubusercontent.com/42544602/51086102-7a617b00-1742-11e9-8d31-34941584d698.png)

In der Raster-Ansicht durch die Filmstreifen-Symbolik erkennbar:
![image](https://user-images.githubusercontent.com/42544602/51086126-b4cb1800-1742-11e9-9d56-b5f4c5b05710.png)

**Comment by nadjaweisskopf** [comment]
nw: 15.1. besprochen und allenfalls, falls nicht zu viel Aufwand, für nächste Iteration einplanen

**Comment by phoettli** [comment]
ich sehe grad: in der Listenansicht fehlt der Hinweis auf Video-Files ebenfalls:
![image](https://user-images.githubusercontent.com/42544602/51480727-f76ba080-1d91-11e9-8150-93ea97ecc39f.png)

**Comment by phoettli** [comment]
![Video-Play-Button_green](https://user-images.githubusercontent.com/42544602/58797120-63db9380-85ff-11e9-9868-419a32fcdd1b.png)

**Comment by eins78** [comment]
Besprochen: Nach RC.1 (oEmbed) wird versucht Play-Button in das bestehende CSS zu integrieren. Player hat zwischenzeitliches neues Design, wird übernommen (schwarz/weiss).

**Comment by phoettli** [comment]
:-/
aktualisierter Player-Button grau/weiss:
![Video-Play-Button_white](https://user-images.githubusercontent.com/42544602/61629469-446af980-ac85-11e9-874f-d0ae49d6a58b.png)

Und Beispiel-Skizze angewendet:
![Video-Play-Button_skizze](https://user-images.githubusercontent.com/42544602/61629496-58166000-ac85-11e9-9ea4-a817b45d3d85.png)

Bitte die Anpassung der (bestehenden) Icons in der Listenansicht nicht vergessen!
https://github.com/Madek/madek/issues/146#issuecomment-456094211

**Comment by eins78** [comment]
* lösung in CSS, mit leichten anpassungen kopiert vom player selbst
* bonus-fix: bei der listenansicht war der filmstreifen kaputt, obwohl es eigentlich das gleiche thumbnail sein sollte wie im 'grid' modus

---

![Screen Shot 2019-10-10 at 10 31 49](https://user-images.githubusercontent.com/134942/66552373-82234400-eb49-11e9-9c34-0c786fdabad2.png)

---

![Screen Shot 2019-10-10 at 10 31 09](https://user-images.githubusercontent.com/134942/66552422-9404e700-eb49-11e9-8c86-e129993374b6.png)

**Comment by eins78** [comment]
@phoettli bei den "featured" thumbs fehlt es auch. könnte man genauso lösen. was meinst du?

![Screen Shot 2019-10-10 at 12 06 56](https://user-images.githubusercontent.com/134942/66559920-8f92fb00-eb56-11e9-8b26-484b2e34428c.png)

**Comment by phoettli** [comment]
> bei den "featured" thumbs fehlt es auch. könnte man genauso lösen. was meinst du?

ja gerne :)

**Comment by phoettli** [comment]
ok auf STAGING
