### ISSUE TITLE
Studienprojekt-Seite benötigt - scheinbar - weniger Zugriffsberechtigungen seitens Medienarchiv

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#147]
Studienprojekte, sowohl das Set und der dazugehörende Inhalt benötigen weniger Zugriffsberechtigungen (als im Wiki angegeben) um auf der Studienprojekt-Seite dargestellt werden zu können. Davon betroffen ist der Download-Zugriff. 

Ich prüfe dies noch in Absprache mit der HSK (Webredaktion; Yvonne Mattern& co.) bei weiteren Inhalten (versch. Dateitypen).
![bildschirmfoto 2019-01-16 um 17 30 36](https://user-images.githubusercontent.com/29139407/51263932-8b65f280-19b5-11e9-9ea2-06b1a63dc19d.png)

**Comment by ltsotrug** [comment]
PDF Beispiele auf der ZHdK Website (Studienprojekte):

![bildschirmfoto 2019-01-23 um 14 18 24](https://user-images.githubusercontent.com/29139407/51617657-f91d9b80-1f2c-11e9-9752-e4dabeba5dc0.png)

![bildschirmfoto 2019-01-23 um 16 20 13](https://user-images.githubusercontent.com/29139407/51617667-fe7ae600-1f2c-11e9-95a4-c736d7cea8df.png)

Medienarchiv Zugriffsberechtigungen: 

![bildschirmfoto 2019-01-23 um 14 51 41](https://user-images.githubusercontent.com/29139407/51617753-2ff3b180-1f2d-11e9-92e4-de53757a73ad.png)

![bildschirmfoto 2019-01-23 um 16 18 24](https://user-images.githubusercontent.com/29139407/51617758-33873880-1f2d-11e9-954d-da684ec6520b.png)

**Comment by ltsotrug** [comment]
Ich setze mich mit Yvonne (HSK) in Verbindung.

**Comment by ltsotrug** [comment]
Bildschirmfoto von unserem Austausch via Slack bzgl. dem Set: A very crowded room 
https://medienarchiv.zhdk.ch/sets/4396521c-0aac-4a97-ad45-df22b62eb7c6?lang=en

<img width="611" alt="bildschirmfoto 2019-01-31 um 16 34 10" src="https://user-images.githubusercontent.com/29139407/52066040-0c0d1d00-2578-11e9-8c30-9547c611ebb0.png">


- [ ] Yvonne (&Snowflake) und Philipp setzten sich in Verbindung und klären den aktuellen Zustand der Schnittstelle und dessen erforderlichen Freigaberechte

**Comment by ltsotrug** [comment]
Hier noch Beispiele welche ohne API Freischaltung (seitens Medienarchiv) auf der ZHdK Studienprojekte Website dargestellt werden:

Audio
https://medienarchiv.zhdk.ch/entries/1501a141-d43b-4887-af4e-450a1ef788f3/permissions
https://www.zhdk.ch/studienprojekt/0f1677b3-126a-4649-ac60-f4f9524d5b5a

Video
https://medienarchiv.zhdk.ch/entries/e061213d-ffde-41ab-972e-1672c8a956bd/permissions
https://www.zhdk.ch/studienprojekt/66fffc6b-61e9-4960-b3d4-5ad90ce95834

PDF
https://medienarchiv.zhdk.ch/entries/f3ba4ab9-ea71-425b-9f8a-17ab35b6ef79/permissions
https://www.zhdk.ch/studienprojekt/12c86665-e332-4f29-9d01-ec98938168bd

**Comment by phoettli** [comment]
Website-Entwickler schreiben:

> Grundsätzlich benötigen wir für das beziehen der Daten _**ausschliesslich Zugriffe über die API**_. Wir verwenden jedoch _**regelmässig während der Entwicklung den Zugriff über das Internet**_, um sicher zu stellen, dass unser Applikationscode auch tatsächlich die korrketen Daten bezieht. Es ist also nicht zwingend Notwendig, dass die Dateien alle per Internet verfügbar sind, wenn wir das jedoch nicht haben kann es uns die Zukünftige Weiterentwicklung potentiell punktuell erschweren.
Über die API beziehen wir sowohl die Verarbeiteten Versionen als auch zum Teil die Originale. Hier haben wir gewisse Logiken, wann was genau geladen werden sollen. So z.B. haben wir File-Extensions, wo wir meines Wissens gar keine verarbeiteten Version versucht wird (z.B. PDFs) sondern direkt das Original verwendet wird.
Falls ihr hier auf Dateityp-Ebene Berechtigungen setzen möchtet, können wir euch gerne diese genaue Logik noch nachliefern.
Da ich gerade nicht genau weiss, was für Auswirkungen Berechtiungsumstellungen bei euch wirklich haben können, wäre natürlich mein Vorschlag, dass ihr diese dann erst auf dem Staging-System durchführt. Unser Staging System indexiert aus staging.madek.zhdk.ch, wir können also nach den Anpassungen dort eine Indexierung durchführen um zu testen, ob alles noch sauber durchläuft.
Falls du mehr Details brauchst, kannst du dich natürlich gerne wieder bei uns melden.
