### ISSUE TITLE
test search with "naughty strings"

### ISSUE THREAD

**Issue by eins78** [Madek/madek#150]
followup of #143 

Like the existing spec that uses the list of string as MetaDatum::String input,
make a spec that searches for each string and makes sure there is no server error.

**Comment by eins78** [comment]
done in https://github.com/Madek/madek-webapp/compare/84ac0a61aa0d2e14803a098fa43f61fc51d97eb5...8226ea656758c0ff89bc491b40f3640ff9685361

**Comment by phoettli** [comment]
Keine Ahnung, worum es hier geht. Ich gehe davon aus: OK auf STAGING.

**Comment by eins78** [comment]
@phoettli Ja, es wurden nur die automatischen tests erweitert. Zum Verständnis, es gibt diese Liste von "komischen Zeichenketten", wir testen jetzt das man all diese als Suchbegriff verwenden kann ohne das es kracht ;) 
https://github.com/minimaxir/big-list-of-naughty-strings
