### ISSUE TITLE
sql assistant: polish 'similar keywords' query

### ISSUE THREAD

**Issue by eins78** [Madek/madek#151]
followup #141 

- [ ] add `offset` variable
- [ ] mark variables with 'edit here' comments

check here: [Link](https://test.madek.zhdk.ch/admin/assistant/sql_reports?utf8=✓&query=--+For+each+keyword+find+a+list+similar+keywords+using+the+levenshtein+distance+function.%0D%0A--+Levenshtein+distance+between+two+words+is+the+minimum+number+of+single-character+edits%0D%0A--+%28insertions%2C+deletions+or+substitutions%29+required+to+change+one+word+into+the+other.+%0D%0A%0D%0A--+Example%3A+finding+out+keywords+with+exact+difference+of+1+letter+and+only+substitution.%0D%0A--++SELECT+1+AS+min_difference%2C%0D%0A--+++++++++1+AS+max_difference%2C%0D%0A--+++++++++2+AS+insertion_cost%2C%0D%0A--+++++++++2+AS+deletion_cost%2C%0D%0A--+++++++++1+AS+substitution_cost%2C%0D%0A%0D%0A--+Find+keywords+which+are+either+exactly+the+same+or+have+distance+of+1%0D%0A--+insertion+or+deletion+or+substitution.%0D%0AWITH+vars+AS+%28%0D%0A%0D%0A++SELECT+%0D%0A++--+START+EDIT+VARIABLES+HERE%0D%0A++++++++--+base+settings%0D%0A++++++++%27madek_core%3Akeywords%27%3A%3Atext+AS+meta_key_id%2C%0D%0A++++++++50+AS+keywords_limit%2C+++++--+how+big+is+the+list%0D%0A+++++++++0+AS+keywords_offset%2C++++--+skip+how+many+from+start+of+list%0D%0A+++++++++0+AS+min_difference%2C%0D%0A+++++++++1+AS+max_difference%2C%0D%0A+++++++++--+advanced+settings%0D%0A+++++++++1+AS+insertion_cost%2C++++++--+must+be+at+least+1%0D%0A+++++++++1+AS+deletion_cost%2C+++++++--+must+be+at+least+1%0D%0A+++++++++1+AS+substitution_cost++++--+must+be+at+least+1%0D%0A+++--+END+EDIT+VARIABLES+HERE%0D%0A++%29%0D%0A++SELECT+k1.id+as+id%2C%0D%0A+++++++++k1.meta_key_id%2C%0D%0A+++++++++k1.term+as+term%2C%0D%0A+++++++++array_agg%28k2.term%29+as+similar_terms%2C%0D%0A+++++++++%27%2Fadmin%2Fkeywords%3Fsearch_term%3D%27+%7C%7C+k1.id+AS+term_link%2C%0D%0A+++++++++json_agg%28k2.*%29+as+similar_terms_data%0D%0AFROM+%28%0D%0A++SELECT+*%0D%0A++FROM+keywords%0D%0A++WHERE+meta_key_id+%3D+%28+SELECT+meta_key_id+FROM+vars+%29%0D%0A++--++AND+term+%7E*+%27Abschluss.*%27%0D%0A++ORDER+BY+term+ASC%0D%0A++LIMIT+%28+SELECT+keywords_limit+FROM+vars+%29%0D%0A++OFFSET+%28+SELECT+keywords_offset+FROM+vars+%29%0D%0A++%29+AS+k1%0D%0A++INNER+JOIN+%28%0D%0A++++SELECT+id%2C+term%2C+meta_key_id%0D%0A++++FROM+keywords%0D%0A++++WHERE+meta_key_id+%3D+%28+SELECT+meta_key_id+FROM+vars+%29%0D%0A++%29+AS+k2%0D%0A++ON+%28+SELECT+min_difference+FROM+vars+%29+%3C%3D+levenshtein%28%0D%0A++++k1.term%2C%0D%0A++++k2.term%2C%0D%0A++++%28+SELECT+insertion_cost+FROM+vars+%29%2C%0D%0A++++%28+SELECT+deletion_cost+FROM+vars+%29%2C%0D%0A++++%28+SELECT+substitution_cost+FROM+vars+%29%0D%0A++++%29%0D%0A++AND+levenshtein%28%0D%0A++++k1.term%2C%0D%0A++++k2.term%2C%0D%0A++++%28+SELECT+insertion_cost+FROM+vars+%29%2C%0D%0A++++%28+SELECT+deletion_cost+FROM+vars+%29%2C%0D%0A++++%28+SELECT+substitution_cost+FROM+vars+%29%0D%0A++++%29+%3C%3D+%28+SELECT+max_difference+FROM+vars+%29%0D%0A++AND+k1.id+%3C%3E+k2.id%0D%0A++GROUP+BY+k1.id%2C+k1.term%2C+k1.meta_key_id%0D%0A++ORDER+BY+k1.term+ASC%3B&run=Run+Query)

```sql
-- For each keyword find a list similar keywords using the levenshtein distance function.
-- Levenshtein distance between two words is the minimum number of single-character edits
-- (insertions, deletions or substitutions) required to change one word into the other. 

-- Example: finding out keywords with exact difference of 1 letter and only substitution.
--  SELECT 1 AS min_difference,
--         1 AS max_difference,
--         2 AS insertion_cost,
--         2 AS deletion_cost,
--         1 AS substitution_cost,

-- Find keywords which are either exactly the same or have distance of 1
-- insertion or deletion or substitution.
WITH vars AS (

  SELECT 
  -- START EDIT VARIABLES HERE
        -- base settings
        'madek_core:keywords'::text AS meta_key_id,
        50 AS keywords_limit,     -- how big is the list
         0 AS keywords_offset,    -- skip how many from start of list
         0 AS min_difference,
         1 AS max_difference,
         -- advanced settings
         1 AS insertion_cost,      -- must be at least 1
         1 AS deletion_cost,       -- must be at least 1
         1 AS substitution_cost    -- must be at least 1
   -- END EDIT VARIABLES HERE
  )
  SELECT k1.id as id,
         k1.meta_key_id,
         k1.term as term,
         array_agg(k2.term) as similar_terms,
         '/admin/keywords?search_term=' || k1.id AS term_link,
         json_agg(k2.*) as similar_terms_data
FROM (
  SELECT *
  FROM keywords
  WHERE meta_key_id = ( SELECT meta_key_id FROM vars )
  --  AND term ~* 'Abschluss.*'
  ORDER BY term ASC
  LIMIT ( SELECT keywords_limit FROM vars )
  OFFSET ( SELECT keywords_offset FROM vars )
  ) AS k1
  INNER JOIN (
    SELECT id, term, meta_key_id
    FROM keywords
    WHERE meta_key_id = ( SELECT meta_key_id FROM vars )
  ) AS k2
  ON ( SELECT min_difference FROM vars ) <= levenshtein(
    k1.term,
    k2.term,
    ( SELECT insertion_cost FROM vars ),
    ( SELECT deletion_cost FROM vars ),
    ( SELECT substitution_cost FROM vars )
    )
  AND levenshtein(
    k1.term,
    k2.term,
    ( SELECT insertion_cost FROM vars ),
    ( SELECT deletion_cost FROM vars ),
    ( SELECT substitution_cost FROM vars )
    ) <= ( SELECT max_difference FROM vars )
  AND k1.id <> k2.id
  GROUP BY k1.id, k1.term, k1.meta_key_id
  ORDER BY k1.term ASC;
```

**Comment by eins78** [comment]
@ltsotrug @phoettli hier können wir die query weiter verbessern bis wir zufrieden sind. die neue version wird dann fix eingebaut, in der zwischenzeit kann dem link oben gefolgt oder der code copy/pasted werden. 
die 2 feedbacks sind eingebaut, es gibt es offset und mit den kommentaren ist markiert wo man die variablen bearbeiten kann.

**Comment by phoettli** [comment]
klappt gut, grosser Nutzen, vielen Dank !
