### ISSUE TITLE
Alleinstehendes Schlagwort auf mind. 2 ME kann in der Bubble-Darstellung nicht entfernt werden  (Stapelverarbeitung)

### ISSUE THREAD

**Issue by ltsotrug** [Madek/Madek#154]
Ein alleinstehendes (d.h. ein einziges) Schlagwort auf mindestens 2 Medieneinträgen,
lässt sich in der Stapelverarbeitung und der Set-Ansicht über das Aktionsmenü nicht entfernen,
wenn der User im Schlagwort Metadatum Feld also im Bubble des Schlagwortes das Kreuz zum löschen bedient (und die Speichern Schaltfläche betätigt).

Gelöscht kann das alleinstehende Schlagwort nur über das ausklappbare Feld: Werte für alle Inhalte löschen

Siehe:

Bildschirmfoto: Schlagwort Bubble mit Lösch Kreuz:

![bildschirmfoto 2019-02-06 um 16 12 17](https://user-images.githubusercontent.com/29139407/52355151-158ffc80-2a32-11e9-8e61-817082151ab0.png)

Bildschirmfoto: Ausklappbare Feld: Werte für alle Inhalte löschen

![bildschirmfoto 2019-02-06 um 16 19 34](https://user-images.githubusercontent.com/29139407/52355159-1b85dd80-2a32-11e9-8e6d-d01c9c6e083d.png)

**Comment by phoettli** [comment]
@ltsotrug kannst du überprüfen, ob der Bug so noch immer aktuell ist?
Falls ja, dann bitte Max zuweisen.

**Comment by urs-van-binsbergen** [comment]
@phoettli @ltsotrug Ich konnte das nicht reproduzieren (Firefox und Chrome auf Mac). Vielleicht wurde das Problem seit November 2020 durch einen anderen Fix behoben, oder es wurde damals ein veralteter Browser verwendet. 

Könnt Ihr nochmals testen? Falls noch bestehend: welcher Browser (inkl. Version), Mac oder Windows? Beispieldaten (welches Set, welches Schlagwort)...

Thx rs

**Comment by ltsotrug** [comment]
@urs-van-binsbergen 

Problem besteht weiterhin.

getestet mit Mac:
Chrome, Version 104.0.5112.79 (Offizieller Build) (arm64) 
Firefox, 91.12.0esr (64-Bit)
Safari, Version 15.4 (17613.1.17.1.6)

siehe Video:

https://user-images.githubusercontent.com/29139407/187888500-27250d91-f97d-4461-9ec2-1cb69201f73c.mp4

**Comment by urs-van-binsbergen** [comment]
Dieses Verhalten besteht für alle Felder (egal welchen Typs, also auch Textfelder etc.). Wenn vorher ein Wert vorhanden war, und man diesen im Formular löscht, wird die Änderung beim Speichern nicht übernommen. Gedacht ist, dass man dafür statt dessen die Funktion "Wert für alle Inhalte löschen" verwendet. 

Dies ist sicher nicht sehr benutzerfreundlich. Wenn man das anpassen will, muss eine neue Lösung gefunden werden, um zu verhindern, dass Felder mit unterschiedlichen Werten nicht überschrieben werden. 

Hier eine Entwurf, wie das ungefähr aussehen könnte:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/25439444/188477214-60407bb9-de9e-44f2-b130-d0fc120c69c9.png">

**Comment by phoettli** [comment]
OK, kein Bug!
Verbesserung in separatem Ticket https://github.com/Madek/Madek/issues/392

**Comment by urs-van-binsbergen** [comment]
Hier noch der Commit, mit welchem obige Mock-Screenshot erzeugt wurde, als Einstiegshilfe für die Umsetzung von #392

```patch
From 0a96c9cd8b3cb1ec0ea28846603a6407de452f27 Mon Sep 17 00:00:00 2001
From: uvb <urs.vanbinsbergen@zhdk.ch>
Date: Mon, 5 Sep 2022 17:09:52 +0200
Subject: [PATCH] WIP: quick draft of a new ui

---
 .../decorators/metadataedit/MetadataEditRenderer.cjsx  | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

diff --git a/app/assets/javascripts/react/decorators/metadataedit/MetadataEditRenderer.cjsx b/app/assets/javascripts/react/decorators/metadataedit/MetadataEditRenderer.cjsx
index 70a78ec10..72dcb29aa 100644
--- a/app/assets/javascripts/react/decorators/metadataedit/MetadataEditRenderer.cjsx
+++ b/app/assets/javascripts/react/decorators/metadataedit/MetadataEditRenderer.cjsx
@@ -111,10 +111,10 @@ module.exports = {
 
 
     <div style={style}>
-      <select name={name} value={model.batchAction} onChange={_onChange}>
-        <option value='none'>...</option>
-        <option value='remove'>{t('meta_data_batch_action_remove_meta_data')}</option>
-      </select>
+      Feld zur Bearbeitung gesperrt (unterschiedliche Feldwerte)<br/>
+      <label>
+        <input type="checkbox" /> Feld entsperren
+      </label>
     </div>
 
 
@@ -139,7 +139,7 @@ module.exports = {
         </div>
       }
       {@_renderLabelByContext(meta_meta_data, context_key_id)}
-      {@_renderBatchDropdown(meta_meta_data, meta_key_id, name, model, _onChangeForm.onChangeBatchAction) if batch}
+      {@_renderBatchDropdown(meta_meta_data, meta_key_id, name, model, _onChangeForm.onChangeBatchAction) if batchConflict}
       {@_renderValueByContext(((values) -> _onChangeForm.onValue(meta_key_id, values)), name, subForms, metaKey, batch, model, workflow)}
     </fieldset>
 
-- 
2.34.1
```
