### ISSUE TITLE
Matroska Video Codec

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#156]
mit welchen Parametern muss Matroska/ffv1 konvertiert sein, damit die Video-Files akzeptiert werden?

Testupload wird nicht encodiert:
https://medienarchiv.zhdk.ch/entries/65c964d4-e78d-4e8c-a5e4-1a4cb1e3f936
![image](https://user-images.githubusercontent.com/42544602/52965488-3bf45700-33a5-11e9-9bd7-b45a6bd66cf6.png)

im Medienarchiv encodierte MKVs:
https://medienarchiv.zhdk.ch/entries/18453ac9-d61f-4df0-a352-2528e43d6d67
https://medienarchiv.zhdk.ch/entries/e1e528d9-00da-453b-9816-984e4f272090/usage_data

**Comment by eins78** [comment]
Erklärung: Die MKV-Files haben keinen zuverlässigen MIME-Type. Manchmal ist es `video/x-matroska` (dann wird es als Video behandelt), manchmal, wie im Falle deines Test-Videos als `application/octet-stream`. Dann wird es als "generisches Files" behandelt, wie ein ZIP-Archiv o.ä..

Thema Filehandling, denn es muss system-weit überarbeitet werden wie die Medientyp-Erkennung funktioniert. Konkret: Selbst wenn wir im Admin-Interface einen "Erzwinge Video-Encodierung"-Button hätten, dann würde das restliche System diese Previews gar nicht verwenden.

Referenz: https://www.pivotaltracker.com/story/show/137262269

**Comment by phoettli** [comment]
danke für den Tipp. Weisst Du einen Weg, wie ich den MIME-Type ändern könnte?
Ich hab ein neues Video encodiert mit `video/x-matroska`, geht aber noch immer nicht. Ev. habe ich auch etwas falsch gemacht.

`$ ffmpeg -i test.mp4 -acodec flac  -vcodec ffv1 -level 1 -coder 1 -context 1 -g 1 -metadata mime-type="video/x-matroska" test-mkv-ffv1.mkv`

https://medienarchiv.zhdk.ch/entries/394136fb-66b0-4fb5-bdc9-2aee65c1543b

**Comment by eins78** [comment]
Der MIME-Type wird leider Server-intern mit irgendwelchen Heuristiken "erkannt" und nicht aus so einem eingeschriebenen Metadatum wie in deinem Beispiel. Was genau der Unterschied zwischen diesen Files, so dass etwas verschiedenes herauskommt, ist müsste man genauer analysieren.

**Comment by phoettli** [comment]
Wie weiter?
- Zencoder anfragen
- Recherche
- ...

lass uns das am Montag anschauen.

**Comment by eins78** [comment]
Besseres Erkennen von MIME-Type, sowie Mapping dessen auf Medientypen ist im scope des 'filehandling' Projekts. Ich würde erstmal warten, was die Entscheidung dazu ist.
Falls das Projekt nicht umgesetzt wird, kann man schauen wie man es separat lösen kann; dazu bräuchte es dann noch Recherche (um den Gesamt-Aufwand zu schätzen, kommt darauf an wieviele Teile des Systems angepasst werden müssen).

Was man bis dahin tun kann: Beispiel-Files sammeln, schauen was das [EXIFtool](https://github.com/exiftool/exiftool) erkennt. Langfristig werden wir sicher das nehmen (was besseres, freies kam mir noch nicht unter).

**Comment by phoettli** [comment]
Guter Hinweis mit unterschiedlichen Systemen!
Erkenntnis:
- Upload mit Firefox aus Citrix (Windows) geht
- Upload mit Firefox oder Safari aus Mac **geht nicht** 
![image](https://user-images.githubusercontent.com/42544602/53405925-30aeb600-39b9-11e9-9d5b-de51b70b7a15.png)
https://medienarchiv.zhdk.ch/sets/6358d050-e519-49c4-88c2-b2faf3b8dcc4

**Comment by eins78** [comment]
plan: bei upload den mime-type aus dem exiftool holen, statt wie bisher rails/rack.
- [ ] verifizieren, dass das funktioniert (video wird nach zencoder gesendet etc)
- [ ] test files sammeln

**Comment by eins78** [comment]
@phoettli btw, das wäre vielleicht ein gutes Ausgangsvideo. Hat freie Lizenz, und ist schön anzuschauen (bzw ein realistisches Beispiel) http://bbb3d.renderfarming.net/explore.html

**Comment by eins78** [comment]
@phoettli bin an der analyse, wie exiftool die mimetypes der files in prod erkennt. gutes zwischenergebnisse:

- von 78'000 files gibt es nur 362, bei dem sich Madek und Exiftool bezüglich des haupt-types uneinig sind (z.b. `audio/…` statt `video/…`). Exiftool scheint es jeweils besser zu machen.

- deine test-MKVs habe ich (korrekt!) in dieser liste gefunden, prinzipiell würde der plan also funktionieren



file_name | file_upload_date | db_content_type | exiftool_mime_type | type_mismatch | type_major_mismatch | media_file | media_entry | file_store_path
-- | -- | -- | -- | -- | -- | -- | -- | --
test-mkv-ffv1-mime.mkv | 2019-02-19T10:18:02.547Z | application/octet-stream | video/x-matroska | true | true | https://medienarchiv.zhdk.ch/admin/media_files/448b16c4-15bf-42b9-b50a-3ae0784f6458 | https://medienarchiv.zhdk.ch/entries/394136fb-66b0-4fb5-bdc9-2aee65c1543b | 9/95ba9757c2024751b8629a27ce9c97f4
test-mkv-ffv1-avpres.mkv | 2019-02-26T09:59:44.153Z | application/octet-stream | video/x-matroska | true | true | https://medienarchiv.zhdk.ch/admin/media_files/c505412e-7158-4f79-bdcb-37b3a50056a9 | https://medienarchiv.zhdk.ch/entries/a221b015-11fa-4495-bb5a-63c91ae865e2 | 3/3071fe946fd24969a0baf7e0c82c0fe7
test-mkv-ffv1-lvl3.mkv | 2019-02-26T10:11:10.249Z | application/octet-stream | video/x-matroska | true | true | https://medienarchiv.zhdk.ch/admin/media_files/59c2a7d3-a726-4bfc-af31-507a00c27e66 | https://medienarchiv.zhdk.ch/entries/d39c6565-46d8-4c4a-a140-67062f21667d | b/bd48467e272b43598a457670cad0e736
test-mkv-ffv1-mime.mkv | 2019-02-26T10:11:10.459Z | application/octet-stream | video/x-matroska | true | true | https://medienarchiv.zhdk.ch/admin/media_files/7786ba3e-9db5-41f3-b9a9-abeccc34ef2c | https://medienarchiv.zhdk.ch/entries/760a05d5-14ea-4820-b137-f729a72ca6e4 | 5/5ad035caa8554923b6964d8607676166
test-mkv-ffv1-avpres.mkv | 2019-02-26T10:11:10.765Z | application/octet-stream | video/x-matroska | true | true | https://medienarchiv.zhdk.ch/admin/media_files/ad0a3c71-c04c-4a5f-82cd-cffbd0417958 | https://medienarchiv.zhdk.ch/entries/64316435-2e5d-4af5-a9a5-9896f7e59e2d | c/c499783ce2a541dfbf3943d6f4d2d196

**Comment by eins78** [comment]
Wird zum nächsten (nicht diesen) Release umgesetzt wie besprochen, nur noch die Mediatype-Erkennung von exiftool wird benutzt. MKVs werden wie gewünscht erkannt, webm auch.


vorher: https://medienarchiv.zhdk.ch/sets/4d63018c-8163-4411-902a-74f2afd678a1?lang=en
![Screen Shot 2019-03-18 at 14 44 57](https://user-images.githubusercontent.com/134942/54534401-8957ea00-498c-11e9-975c-b74bcf6d0a43.png)

---

nachher: 
https://test-blank.madek.zhdk.ch/sets/65588387-e756-47e0-87f4-101f9051366e
![Screen Shot 2019-03-18 at 14 44 44](https://user-images.githubusercontent.com/134942/54534432-9c6aba00-498c-11e9-88b1-0443a66ca89e.png)
