### ISSUE TITLE
Weitere People-Einträge mit sonderbarer Zählung der Inhalte

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#157]
Es gibt noch weitere Einträge, bei denen die Anzahl der abhängigen Einträge nicht stimmen.
(siehe https://github.com/Madek/madek/issues/130)

(1) https://staging.madek.zhdk.ch/people/d8b3fea1-fbca-4b84-afe8-569a04a5f057?type=entries
(2) https://staging.madek.zhdk.ch/people/bd545fc6-6bdb-43f7-a71e-fc190ccca8bb?type=entries
(19) https://staging.madek.zhdk.ch/people/ea527429-f77f-420f-81e6-7598ecfea1f4?type=entries
(2) https://staging.madek.zhdk.ch/people/4b9e1df1-5ae8-49a1-b0bc-6fc812dbbcd0?type=entries

**Comment by nimaai** [comment]
1. https://staging.madek.zhdk.ch/people/d8b3fea1-fbca-4b84-afe8-569a04a5f057?type=entries
Admin zählt hier auch unveröffentlichte Einträge (`is_published = false`), das ist der Unterschied. Soll es Admin nicht tun oder soll der Admin-Modus das tun (@eins78)?
2. https://staging.madek.zhdk.ch/people/bd545fc6-6bdb-43f7-a71e-fc190ccca8bb?type=entries
Eine Person kann mehrfach verwendet werden bei einem Eintrag. Das ist hier der Fall. Der Begriff `Usage` ist evtl. nicht spezifisch genug. Es bezieht sich auf Anzahl Metadaten nicht Medieneinträge. Änderungswunsch der Benennung? (@phoettli / @eins78)
3. https://staging.madek.zhdk.ch/people/ea527429-f77f-420f-81e6-7598ecfea1f4?type=entries
Das gleiche wie 2.
4. https://staging.madek.zhdk.ch/people/4b9e1df1-5ae8-49a1-b0bc-6fc812dbbcd0?type=entries
Das gleiche wie 2.
5. https://medienarchiv.zhdk.ch/admin/users/cb222977-fa06-42c1-9342-37d9a6ce9c01
Kann nicht reproduziert werden. (@phoettli)

**Comment by eins78** [comment]
> * https://staging.madek.zhdk.ch/people/d8b3fea1-fbca-4b84-afe8-569a04a5f057?type=entries
>   Admin zählt hier auch unveröffentlichte Einträge (`is_published = false`), das ist der Unterschied. Soll es Admin nicht tun oder soll der Admin-Modus das tun (@eins78)?

Es sollen überall nur `is_published = true` gezählt werden, der Rest wird getrennt gezählt und "Entwürfe" genannt.

> * https://staging.madek.zhdk.ch/people/bd545fc6-6bdb-43f7-a71e-fc190ccca8bb?type=entries
>   Eine Person kann mehrfach verwendet werden bei einem Eintrag. Das ist hier der Fall. Der Begriff `Usage` ist evtl. nicht spezifisch genug. Es bezieht sich auf Anzahl Metadaten nicht Medieneinträge. Änderungswunsch der Benennung? (@phoettli / @eins78)

In der Webapp geht es nur um Anzahl Einträge, da ist es klar (bleibt wie es ist).
Im Admin-UI wäre ideal, beides anzuzeigen ("3x verwendet in 2 Einträgen"). Anderfalls bin ich unentschieden: Anzahl Metadaten: kann verwirren wie in diesem Ticket; Anzahl Medieneinträge: ist weniger sinnvoll für den Use Case "Wie viel muss noch aufgeräumt werden".

> * https://medienarchiv.zhdk.ch/admin/users/cb222977-fa06-42c1-9342-37d9a6ce9c01
>   Das sind 2 verschiedene Paar Schuhe. Die Anzahl Resources bezieht sich auf Einträge wo der User (nicht die Person!) der Verantwortliche ist.

ok

**Comment by nimaai** [comment]
Vorschlag von @eins78 bez. 1 und 2 entsprechend umgesetzt.

95f1e75

**Comment by phoettli** [comment]
danke für die Erklärung von 5)
ok auf `staging`
und vielen Dank für die jetzige Lösung!
