### ISSUE TITLE
Translation for Vocabulary and Context

### ISSUE THREAD

**Issue by eins78** [Madek/madek#163]
- like the previous work regarding MetaKeys (https://github.com/Madek/madek/commit/bef86c7fe30dac507d19303eaacecb81ecee21a9)

- [x] extend DB (tables `vocabularies`, `contexts`; fields `label`, `description`)
- [x] Admin UI
- [x] Webapp
  - To be defined further, but "everywhere"
- [x] API

General Question, since those are the last tables on the translation roadmap:
How do we want to handle the old, non translated fields (e.g. `label`). 
Right now it contains the translation into the default lang, which can change.
Maybe there is a plan that I am not aware of – then we should document it. 
We could update the fields with triggers in case the default lang changes, but I am leaning towards removing the fields and adapting all the Apps to not use them anymore (the usage is obsolete in almost all cases anyhow, the only important place is the API where the field should still be supported (but it obv. does not need to a DB field to do that).

**Comment by michalpodlecki** [comment]
The old fields were not removed because they are validated by some `CHECK constraints` in the db. From my perspective the fields can be removed as they are not used by rails directly because of custom methods for default translation. The constraints could be also rewritten then.
