### ISSUE TITLE
Bildausgabe mit Madek-Player (einbetten in Webseite)

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#164]
Der Madek-Player funktioniert gut für Video und Audio.
Für Bilder ist die Ausgabe schwierig:
- Abweichung von Bildgrösse zu URL unklar
- ausgegebenes iFrame ist erheblich breiter als eigentlicher Player, es erscheint ein horizontaler Scrollbalken
- Bild wird in riesiger Grösse angezogen unabhängig von Ausgabe (Datenmenge!)
- Bildunterschrift kann nicht entfernt werden.
http://people.zhdk.ch/philipp.oettli/oembed.html

Optimierungsmöglichkeiten
1. Parameter für ohne Bildunterschrift
2. ohne horizontaler Scrollbalken
3. optimierte Datenmenge (Bildgrösse?, iframe-Code?...)

Alternativ: persistente Bildurl mit Parameter für Grösse und ohne iframe (für img-Tag)

**Comment by eins78** [comment]
Kommentar in 2 Teilen: erst akut, dann zum länger nachdenken.

---

Vorschlag: Weil a) anscheinend niemand image-embeds benutzt und b) es gerade extrem kaputt ist schlage ich vor, das Feature zu deaktivieren bis geklärt ist was wir wollen.

---

Zum Weiterdenken:

- zu breiter Inhalt im iframe/Scrollbalken: habe nachgeschaut und ist definitiv ein (neuer) Bug. Kann schnell passieren, weil es sich die Styles mit der restl. App teil und wir keine (visuellen) Test dafür haben.

- riesige Grösse: könnte teilweise verbessert werden, für "klein", bis "mittel", darüber haben wir nur "riesig" und mehr Grössen gibt es nicht (Stichwort Filehandling)

- Bildunterschrift: Das ist so umgesetzt wie gewünscht. Hintergrund ist die zwangsweise Angabe von Quelle und Rechteinhaber. Hier muss entschieden werden, was wir unterstützen wollen und dürfen. Zu beachten ist, dass wir bei externen Nutzung nicht mehr zwischen Eigen- und Fremdnutzung unterscheiden können. Wenn wir es für den Fall "eigene Bilder im eigenen Portfolio" sehr bequem machen, dann ginge das auch für alle andere Fälle wo es weniger erwünscht ist.
Für Videos haben wir schon einen undokumentierten Parameter ([`?internalEmbed`](https://medienarchiv.zhdk.ch/entries/9b5fa1d7-3c61-46bf-986b-213ca52031d3/embedded?internalEmbed)) um den Titel auszuschalten – aber nur wenn die einbettende Seite bekannt ist (bis jetzt enthält diese Liste nur die eigene URL, so funktioniert das einbetten im Madek selber)

- Hinweis: Die Alternativ-Idee könnte auch per oEmbed umgesetzt werden, die spec erlaubt was wir gerade machen (html ausliefern), aber geht eher davon aus, dass wir eine Bild-URL liefern. Korrekte Quellenangabe ist dann wieder Sache des CMS

- 2. Hinweis: oEmbed geht auch für statisches HTML bzw ohne CMS, also per Javascript.

---

**Comment by phoettli** [comment]
danke für Info!
Dann schlage ich vor:
a) Bugfix
b) oder f) - je nachdem, was leichter geht. b) nur, wenn für den Bugfix in b der Player eh angefasst werden muss.
Erlaubte URLs in Liste finde ich super.

Weitere Features hängen dann n.m.V. von Filehandling ab.

**Comment by eins78** [comment]
entscheid: zu grosser rand wird gefixed.

**Comment by eins78** [comment]
Reproduziert: Der zu grosser-rand-bug kam bei diesem Feature mit: https://github.com/Madek/madek-webapp/commit/84d719f8869fb16e6c2a6dbb817b0f6092f904e1#diff-6ee854f8ecfe5f17707c57be5d56bfbf

**Comment by eins78** [comment]
@phoettli fix ist auf `test`. habe dein beispiel angepasst (nur domain für test server), siehe https://phoe-embed.eins78.now.sh

**Comment by eins78** [comment]
merged: https://github.com/Madek/madek/commit/b401b6027c5b5f974a2a5b84e99c397148b69a48

**Comment by phoettli** [comment]
super jetzt :)
ok auf STAGING
