### ISSUE TITLE
Feature: "About Pages"

### ISSUE THREAD

**Issue by eins78** [Madek/madek#165]
- page `madek.example.com/about`
- set content as Markdown in Admin UI 
- for general info, Privacy Policy, etc; and upcoming info about "Fair Principles"

- [x] DB: `app_settings.about_page`
- [x] Admin: Edit UI
- [x] Webapp: serve `/about` *if* content configured
- [x] tests!

**Comment by phoettli** [comment]
Bitte

- Hinweis reinschreiben, welche MD-Formatierung verwendet wird
![image](https://user-images.githubusercontent.com/42544602/57783890-3e114c00-772f-11e9-8053-71158f50fd10.png)

- ev. mit Link zu Beispielformatierung

- In welchem Ticket folgt die Mehrsprachigkeit ? #70 ?

**Comment by eins78** [comment]
Werde Hinweis einfügen, das "normales, nicht-GitHub-flavored" Markdown verwendet wird. Es gibt zum Glück inzwischen eine gute, moderne Spec, auf deren Übersicht würde ich verlinken: https://commonmark.org/help/

**Comment by eins78** [comment]
… und der Hinweis, das HTML innerhalb von Markdown erlaubt ist – ist manchmal einfacher bzw erlaubt fremden HTML code zu kopieren (wie unsere Re3Data badge)

**Comment by eins78** [comment]
Ticket für fehlende translations: https://github.com/Madek/madek/issues/180 (+ in Liste von #70)

**Comment by eins78** [comment]
![Screen Shot 2019-05-17 at 16 01 28](https://user-images.githubusercontent.com/134942/57933262-16e88500-78bd-11e9-9380-5260ee62a607.png)

**Comment by phoettli** [comment]
das ist super!
ich hatte etwas gehadert mit benötigen Zwischenleerzeilen.
OK auf Staging.
