### ISSUE TITLE
Test results Vertrauliche Links

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#166]
1. Sollten die Links nicht auch auf Set-Ebene funktionieren? Mir ist, das wurde in der Demo im Herbst so angekündigt.

2. PDF wird nicht ausgegeben:
a) Vertraulichen Link auf PDF erstellt: 
https://staging.madek.zhdk.ch/entries/d73676fd-e6dd-4192-9231-8e1df3723391/access/SM391WPMWDMSPFC1J5WM3Z6H7GFEYFXR
b) Datensatz kann aufgerufen werden:
![image](https://user-images.githubusercontent.com/42544602/54765964-b9a4c000-4bfa-11e9-9790-1515e6d71fc8.png)
c) Klick auf PDF öffnet Login Box
![image](https://user-images.githubusercontent.com/42544602/54766003-cd502680-4bfa-11e9-9bf8-ddda6bbc0962.png)

3. Temp-URL im eingeloggten Zustand öffnen => Reiter fehlen
![image](https://user-images.githubusercontent.com/42544602/54766573-ca096a80-4bfb-11e9-8fe7-54c6dd53c261.png)

4. Berechtigungs-Icon wird mit Temp-URL zu Weltkugel, obwohl keine Internet-Freigabe besteht (verwirrend):
![image](https://user-images.githubusercontent.com/42544602/54766879-5fa4fa00-4bfc-11e9-84d8-7edf17bafb37.png)
Optionen:
a) Bei Berechtigungen Hinweis auf Temp-Url anbringen (Übersteuerung erläutern)
b) eigenes (spezielles) Icon verwenden
c) ... ?

5. Sinnvoll wäre Zusammenfassung aller erstellter Vertraulichen Links in der Navigation links. Man verliert schnell den Überblick über die offenen URLs. (ev. neues Ticket für Zwischendurch):
![image](https://user-images.githubusercontent.com/42544602/54767689-ff16bc80-4bfd-11e9-9931-b3f74057511f.png)

6. Könnte man Gültigkeit der URLs auch verlängern? (neues Ticket)

7. Im Zusammenhang mit den Links für PAUL ist die Default-Einstellung für unbeschränkte Laufzeit reingerutscht. Nach ausführlicher Besprechung im Support haben wir grosse Bedenken, dass eine beschränkte Laufzeit von den meisten Usern übersehen würde.
Wie aufwendig ist es, die Default-Einstellung zu ändern?
(Allenfalls mit anderer Bezeichnung der Checkbox)

**Comment by eins78** [comment]
> 1. Set-Ebene

Es würden nur die Metadaten, aber nicht die Inhalte im Set angezeigt werden.

> 2. PDF wird nicht ausgegeben:

Das sind 2 verschiedene Probleme:
- in b) ist das Vorschaubild nicht sichtbar – sollte es aber. Bug.
- bei c) würde das *Original File* heruntergeladen werden (weil PDFs im Madek so funktionieren).
Aktuell sind die Vertraulichen Links so umgesetzt, dass mit diesen die Berechtigungen entsprechend der Stufe "Betrachten" vergeben werden.
Hier bräuchte es aber "Original Exportieren & in PDFs blättern". Wir haben dieses Thema schon kurz im Entwicklungsteam diskutiert – das "Research Video" Projekt bräuchte (planmässig) auch diese Stufe (Original File).
Wir könnten das (jetzt) so anpassen (aber dann für Alle), oder später als Auswahl hinzufügen (würde bei den Einstellungen des V. Links gesetzt werden können).


> 3. Temp-URL im eingeloggten Zustand öffnen => Reiter fehlen

Das hatte mich auch gewundert, aber dachte es sei so gewünscht. Es geht nur um "ich bin auch gleichzeitig eingeloggt", ja?
Dann ist es eher ein Edge-Case, die V. Links sind ja gerade für nicht-eingeloggte User.

> 4. Berechtigungs-Icon wird mit Temp-URL zu Weltkugel

Ich bin allgemein dafür, auf der Berechtigungs-Seite a) allgemein im Text auf das Feature hinzuweisen (falls ein Nutzer es dort sucht) b) gut sichtbar auszuzeichnen, wenn (noch gültige) V. Links vorhanden sind.

Aber: Das Icon würde ich aber so lassen wie es vorher war – das Feature V. Links wird ja eben als *Alternative* zu den anderen Permissions angeboten, sollte also keinen Einfluss auf das Icon haben.

> 5. Zusammenfassung aller erstellter Vertraulichen Links

Das ist eine gute Idee, hat die Frage 4 für mich einfacher gemacht (wenn es eine globale Liste gibt sind die Icons weniger wichtig).

> 6. Könnte man Gültigkeit der URLs auch verlängern? (neues Ticket)

Technisch spricht nichts dagegen. Es fiel auch neulich auf, dass für die API-Tokens noch ähnlich Features fehlen; und funktional und visuell ist das ja nah aneinander.
Vorschlag: Gemeinsames Enhancement-Ticket für Punkte 5, 6 und API-Tokens.

> 7. Default-Einstellung für unbeschränkte Laufzeit 
Wie aufwendig ist es, die Default-Einstellung zu ändern?
(Allenfalls mit anderer Bezeichnung der Checkbox)
 
Wird geändert.

--

Zusammenfassung:

- wird im aktuellen RC geändert:
  - [ ] Icon (4.)
  - [ ] Default-Einstellung Laufzeit 1 Jahr(?) (7.)

- Fixes in Nachfolge-Tickets
  - [ ] Reiter wenn eingeloggt (3.)

- Verbesserungen in Nachfolge-Tickets:
  - [ ] V. Links im Dashboard (5.)
  - [ ] V. Links bearbeiten (6.)

- Noch zu klären/diskutieren:
  - [ ] PDFs/Original Files (2.)

**Comment by eins78** [comment]
@phoettli Zur Laufzeit: da gibt es auch eine Beschränkung, dass es maximal 1 Jahr sein darf. Im Endergebnis erlauben wir also "zwischen 1 Tag und 1 Jahr" oder "Unendlich". D.h. wenn man 2 Jahre bräuchte, dann kann man aktuell nur "kein Ablaufdatum" auswählen. Ich würde vorschlagen, die Beschränkung zu entfernen oder auf 10 Jahre zu erhöhen.

**Comment by phoettli** [comment]
1. Ok, Nur Metadaten nützt niemandem.

2. zu zweitem Problem: ich habe den Eindruck, mit der Preview haben wir an verschiedenen Stellen Probleme (dann auch in FAIR): Es sollte für PDF eine Preview möglich sein, ohne dass bei Film & Bild Zugang zum Original-File gewährt wird. Möglicherweise ist die Preview beim Film aber eh falsch und sollte nur Vorschaubild sein, dann wäre sie analog zum PDF. Braucht es da einen zusätzlichen Berechtigungslayer dazwischen?

3. Ja. Ich merke als User nicht, weshalb mir die Reiter nicht mehr angezeigt werden, wenn ich eingeloggt bin...

4. Für das Icon bin ich anderer Meinung:
Mengenbegründung:
- Die Berechtigung durch eine Temp-URL kann ich nur als Besitzer des ME verändern (_einer_). Für den Besitzer hat das Global-Icon einen Mehrwert: "aha, Ressource ist öffentlich".
- Für sämtliche andere User scheint es als Bug (_viele_): Zwar als global angezeigt, aber nur lokal zugänglich, Rechte sind nicht auf global gesetzt. Leichtfertig kann die Ressource auch weitergegeben werden (Download, Copy etc.), da Global-Icon.
- Das Feature Vertrauliche Links und seine Auswirkungen werden nur die wenigsten User kennen (_wenige_).
Lieber dann Privat-Icon trotz Vertraulichem Link => weniger Verwirrung.

5. Was meinst Du mit "globale Liste"? Eine Liste gilt ja nur für einen User mit seinen Links (analog Token).

6. Sehr gut!

7. 10 Jahre scheint mir grad sehr viel. Kompromiss? 2 Jahre ? Längere Denkperspektive scheint mir nicht realistisch.

**Comment by eins78** [comment]
> 2. zu zweitem Problem: ich habe den Eindruck, mit der Preview haben wir an verschiedenen Stellen Probleme (dann auch in FAIR): Es sollte für PDF eine Preview möglich sein, ohne dass bei Film & Bild Zugang zum Original-File gewährt wird. Möglicherweise ist die Preview beim Film aber eh falsch und sollte nur Vorschaubild sein, dann wäre sie analog zum PDF. Braucht es da einen zusätzlichen Berechtigungslayer dazwischen?

Das ist schon bei FAIR data bzw ein Diskussionspunkt, sollten wir auslagern. Wäre so oder so eine relativ aufwändige Erweiterung die Berechtigungen anzufassen.
In Punkto PDFs ginge es evtl. in Richtung "Filehandling" (wenn es darum ginge ein Vorschau-Bild pro Seite zu haben, statt nur der ersten).

> 3. Ja. Ich merke als User nicht, weshalb mir die Reiter nicht mehr angezeigt werden, wenn ich eingeloggt bin...

Ich versuche es eh zu lösen, ist aber ganz hinten in der Prio. Dein Argument erinnert mich aber an eine andere Überlegung: vielleicht sollten wir allgemein und immer einen Hinweis anzeigen. An der Stelle, wo auch auf den Entwurfsstatus hingewiesen wird, eine Box die sagt "Sie sehen diesen Inhalt durch einen Vertraulichen Link, …". Ich würde aber erstmal das Nutzerfeedback abwarten.

> 4. Für das Icon bin ich anderer Meinung:
> …  Lieber dann Privat-Icon trotz Vertraulichem Link => weniger Verwirrung.

Dann sind wir doch einer Meinung, hatte mich nur unklar ausgedrückt ;)

> 5. Was meinst Du mit "globale Liste"? Eine Liste gilt ja nur für einen User mit seinen Links (analog Token).

Ich meinte nur "alle deine Links, egal wo", nicht alle von jedem. 
Wobei, jetzt wo du sagst: das wäre eigentlich im Admin-UI angebracht… Fürs erste könnte es in den SQL-Assistant, das man überhaupt was sieht, und wenn es mal sehr viele gibt kann man über ein Admin-UI nachdenken.

> 7. 10 Jahre scheint mir grad sehr viel. Kompromiss? 2 Jahre ? Längere Denkperspektive scheint mir nicht realistisch.

Können wir nachher besprechen…

**Comment by eins78** [comment]
@phoettli Wg. Anzeige der Tabs: habe kurz probiert, müsste separat geklärt werden. Tabs anzeigen wäre kein Problem, aber gibt nicht automatisch Berechtigungen für diese. D.h. es muss angepasst werden, dazu muss zuerst geklärt werden welche Tabs denn sichtbar/benutzbar sein sollen.

Aber: damit es klarer ist, habe ich mal die Idee mit dem Hinweis ausprobiert. Der käme dann immer, wenn gerade ein Vertraulicher Link verwendet wird:

![Screen Shot 2019-03-26 at 10 54 45](https://user-images.githubusercontent.com/134942/54988195-34ccf400-4fb6-11e9-97b6-19ec6c8774c5.png)

**Comment by phoettli** [comment]
Cool!
Kommt der Hinweis nur für eingeloggte (wünschenswert) oder für alle User (ev. verwirrend)?

**Comment by eins78** [comment]
> Kommt der Hinweis nur für eingeloggte (wünschenswert) oder für alle User (ev. verwirrend)?

Ich finde es gut, wenn der auch angezeigt wird wenn man nicht eingeloggt ist – z.B. als Hinweis, dass man den Link nicht einfach weiterschicken soll. Wenn es mal Doku dazu gibt, dann kann man auch dorthin verlinken für noch mehr Erläuterungen. 
Evtl. fehlt mir grad nur die Eingebung, warum es verwirrend sein könnte – wie meinst du das?

**Comment by phoettli** [comment]
ok, den Hinweis habe ich im Scratch Pad entsprechend ergänzt.

**Comment by eins78** [comment]
Offene Punkte aus Feedback in neuem Ticket: https://github.com/Madek/madek/issues/174
