### ISSUE TITLE
Bug: API: GET /vocabulary/:id returns incorrect vocabulary when logged in

### ISSUE THREAD

**Issue by eins78** [Madek/madek#168]
it seems we get the first vocabulary from the 'accessible' list instead of where the id matches

https://github.com/Madek/madek-api/blob/9d1dad893d147ba12cf800c7548b1d57a0e0bd86/src/madek/api/resources/vocabularies/vocabulary.clj#L21-L25

https://medienarchiv.zhdk.ch/api/browser/?#url=%2Fapi%2Fvocabularies%2Fzhdk_bereich&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/18bc88de804fcbd0b7a6a0976a44a4fa30afdb68
