### ISSUE TITLE
API: enforce "read only scope" when authenticating via cookie

### ISSUE THREAD

**Issue by eins78** [Madek/madek#169]
result: write operations will only be possible when auth via token (and token has write scope)

implementation hint from tom: in a (new) middleware, check for "cookie auth", if it is used in combination with "unsafe HTTP method", fail with error message.

**Comment by nimaai** [comment]
@DrTom ok? https://github.com/Madek/madek-api/commit/33c691e0a7fa5210a4c9f001c750abd481080c8d

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/a2396c015e344b346abd3e20a059dcc85e45fcc3
