### ISSUE TITLE
languages cleanup

### ISSUE THREAD

**Issue by eins78** [Madek/madek#170]
- [ ] cleanup DB fields
  - [x] remove all old/untranslated fields from DB
  - [ ] adapt webapp, should only use the translated version @eins78 
  - [x] adapt admin-webapp, should only use the translated version
  - [x] only API should still offer the old field (but dynamic/according the settings.default_lang)
- [x] remove params from API
- [x] check handling of default values in DB/seeds/…
- [x] integration test 
   - [x] default settings (default lang is active as long as a user has not selected one)
   - [x] changing the language shows different labels/etc
   - [x] changes to translations in the admin UI are reflected in all other apps (api/webapp)
     - api: vocabularies, metakeys
     - webapp: vocabularies + metakeys (public pages), contextkeys: in edit form (look in existing webapp tests)

- [x] @eins78 decide where settings and defaults should live

workflow: 
- open a draft PR, give update every 1-2 days
- as always, ask here if a task is unclear

**Comment by eins78** [comment]
@michalpodlecki I will look after the webapp/presenters as soon as you have adapted the DB

**Comment by eins78** [comment]
@michalpodlecki can you open a draft PR/send update about the progress please? (tomorrow/friday)

**Comment by michalpodlecki** [comment]
@eins78 of course, I will create a draft PR with API part today, as it is almost done.

**Comment by phoettli** [comment]
ok, da kann ich nichts testen...
