### ISSUE TITLE
Upload macht eine automatische Umbenennung, innerhalb des Upload-Fensters, der importierten Dateien bei einer Userin

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#172]
Im Upload-Fenster werden die Dateinamen umgewandelt. Diese Beobachtung wurde bei Betty Fleck festgestellt.

Beispiele:

![Bildschirmfoto 2019-04-05 um 16 03 05 Kopie](https://user-images.githubusercontent.com/29139407/55642855-f7e0d880-57d1-11e9-97fa-38a16c37dde8.png)

![Bildschirmfoto 2019-04-05 um 16 50 57 Kopie](https://user-images.githubusercontent.com/29139407/55642875-fa433280-57d1-11e9-8de9-03516b80351f.png)

**Comment by eins78** [comment]
@ltsotrug Dies ist ein Feature! Nach Upload wird der Titel gemäss den Metadaten in der Datei gesetzt. Dies ist in den IO-Mappings definiert. 

In dem Beispiel-Fall:
* die rot markierten Einträge haben noch *keinen* Titel, es wird der Dateiname angezeigt
* die blau markierten haben schon den Titel aus der Datei gesetzt bekommen

Beispiel-Datei:
* Metadaten zu sehen hier: https://medienarchiv.zhdk.ch/entries/2fcb8f17-0f50-435b-8376-57206df9b3ce/usage_data
* Relevant ist `"XMP-dc:Title": "Jahresbericht 2018"`
* dieses IO-Mapping bestimmt dass daraus der Titel wird: https://medienarchiv.zhdk.ch/admin/io_mappings/611a2b53-d996-4f1d-8bb7-47c742de2c05

**Comment by ltsotrug** [comment]
@eins78 danke für den Hinweis. Nach Absprache mit @phoettli schliesse ich das issue
