### ISSUE TITLE
Transcodierung soll nach Reihenfolge der Dateinamen (nach Titel) erfolgen

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#173]
Beim Upload werden die Dateien nicht nach Reihenfolge der Dateinamen transcodiert. Dies hat einen nachhaltigen Einfluss auf die Sortierung nach Importdatum. Problem wurde von Betty Fleck (HSK, Fotografin) gemeldet.

<img width="1230" alt="Bildschirmfoto 2019-04-05 um 17 16 06 Kopie" src="https://user-images.githubusercontent.com/29139407/55643652-003a1300-57d4-11e9-8f68-4644da64edde.png">

**Comment by eins78** [comment]
Generell: Nach Reihenfolge der Dateinamen zu sortieren ist nicht möglich, nur die Reihenfolge wie die Dateien in den Uploader hinzugefügt werden. Ist aber in diesem Fall das gleiche Resultat.

Das die Reihenfolge derzeit "verloren" gehen kann, und dies Einfluss auf das Importdatum hat, ist korrekt beobachtet. Es liegt daran, dass der Uploader immer 4 Uploads gleichzeitig sendet, z.B. um die Leitung optimal zu nutzen und zu verhindern das ein grosses Video viele kleine Fotos "blockiert".

Lösungsansätze:
* Uploader sendet generell nur 1 File auf einmal (theoretische Verschlechterung für andere Nutzer). Dev-Aufwand sehr gering.
* User kann am Uploader einstellen wieviele Uploads parallel laufen sollen, default würde 4 bleiben, aber kann auf 1 gestellt werden um das oben gewünschte Verhalten zu haben. Dev-Aufwand mittelgross (nur Frontend)
* Warten auf https://github.com/Madek/madek/issues/172 – Workflow enthält schon Lightroom und händische Datei-Umbennungen. Evtl. ist es eine Option die Titel im Lightroom zu setzen und dieser Wunsch ist erledigt.
* Warten auf "Projekt Filehandling" – ist enthalten im Paket "Importzeiten verbessern" ("… asynchroner Massenupload…"

**Comment by ltsotrug** [comment]
@eins78 danke für die Erläuterungen und Lösungsansätze. Nach Absprache mit @phoettli schliesse ich das issue
