### ISSUE TITLE
add authority control providers

### ISSUE THREAD

**Issue by eins78** [Madek/madek#176]
- https://orcid.org `https://orcid.org/0000-0002-1825-0097`
- https://en.wikipedia.org/wiki/ResearcherID `https://www.researcherid.com/rid/K-8011-2013`
- https://www.wikidata.org `https://www.wikidata.org/wiki/Q42`

**Comment by eins78** [comment]
+ https://www.wikidata.org/wiki/Q5879

**Comment by eins78** [comment]
Bonus: IMDb `https://www.imdb.com/name/nm0251868` - eher relevant für die Film- und Fernsehwelt

**Comment by eins78** [comment]
@phoettli @wlfnsbrgr ORCID ist cool, am besten technisch und organisatorisch ausgebaut von der Liste der Anbieter, die wir jetzt unterstützen. Ich glaube, das hat am ehesten Zukunft :) 

Die komplette Liste findet sich in den Tests (Zeilen mit `input:`): https://github.com/Madek/madek-datalayer/blob/master/spec/lib/uri_authority_control_spec.rb#L11

**Comment by phoettli** [comment]
unvollständige URL ("oett.li") generiert Fehler. Kann man den abfangen?
https://staging.madek.zhdk.ch/people/071f61be-644f-45a6-9c5c-3120451718fb

```
Benötigen Sie diesbezüglich Hilfe, dann kontaktieren Sie bitte den Support (support.medienarchiv@zhdk.ch) mit einer Beschreibung Ihrer letzten Arbeitsschritte sowie einem Screenshot dieser Seite.


ActionView::Template::Error: undefined method `sub' for nil:NilClass
datalayer/lib/uri_authority_control.rb:47:in `block in UriAuthorityControl' 
datalayer/lib/uri_authority_control.rb:112:in `block in detect' 
uri:classloader:/jruby/kernel/enumerator.rb:72:in `block in map' 
```

**Comment by eins78** [comment]
Ups. Ja, kann und muss! Habe wohl auch noch einen Testfall vergessen. RC.2

**Comment by phoettli** [comment]
naja, ich bin nicht ein Fan von automatischer Löschung, unverlinkte Ausgabe wäre mir da lieber (Text stehen lassen, wie eingegeben). So bliebe für den eintragenden Benutzer, wenigstens der Text erhalten. Ausserdem hätte man die Möglichkeit, einen Link zusätzlich zu beschreiben über mehrere Zeilen.
```
Persönliche Website:
www.meineurl.tld
```
Und das Verhalten wäre das gleiche, wie im URL-Feld im Frontend.

**Comment by eins78** [comment]
Da bin ich generell ganz deiner Meinung, allerdings bei Textfeldern. Dieses Datenbankfeld ist aber kein Freitext, sondern "Liste von URLs", und wir wollen dort saubere Daten haben und z.B. API-Clients so geben können. 
Das was du meinst, kann man im "description" Feld machen. Noch ist es eh nicht bearbeitbar, aber wenn das kommt können wir auch das autolinking dafür einschalten (so funktioniert es bei den Metadaten, dort gibt es nur Freitexte und Links darin werden automatisch erkannt).
