### ISSUE TITLE
LDAP / ZHdK Bereich aktualisieren: Style & Design (alt) > Trends & Identity (neu)

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#179]
Die 2 ZHdK Bereiche:
_Bachelor Design - Style & Design 
Vertiefung Style&Design_ 

heissen neu:
_Bachelor Design - Trends & Identity
Vertiefung - Trends & Identity_

![Bildschirmfoto 2019-05-15 um 16 18 52](https://user-images.githubusercontent.com/29139407/57783526-909e3880-772e-11e9-8a25-f9ffc47eb766.png)

**Comment by eins78** [comment]
@DrTom bitte einmal den Sync laufen lassen.

**Comment by phoettli** [comment]
vierteljährlicher Abgleich wäre sinnvoll, mit Start z.B. ca. eine Woche nach Semesterbeginn. Automatisch möglich?

**Comment by eins78** [comment]
@DrTom siehe oben
- Sync soll jetzt einmal laufen für die aktuellen Umbenennungen 
- Sync soll 2x im Semester laufen; 1 Woche nach Start und dann zur Halbzeit. Ob du dir einen Kalender-Reminder oder einen Cronjob einrichtest überlassen wir dir ;)

**Comment by phoettli** [comment]
Nach Sync checken ob E-Learning ebenfalls vorhanden:
https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=284904

**Comment by eins78** [comment]
Für Automation extra ticket, täglicher sync wäre besser

**Comment by phoettli** [comment]
@ltsotrug : bitte testen, ob die Gruppenbezeichnung stimmt und dann Ticket schliessen.
