### ISSUE TITLE
📦 Workflow-Feature V1

### ISSUE THREAD

**Issue by eins78** [Madek/madek#181]
- ohne kollaborative Funktionen
- mit "Freeze" für Berechtigungen + Metadaten

start: mai
end: mid-aug (ready to test)

ressources: Max, Michal (Juni-Aug full time)

**Comment by eins78** [comment]
tasks from first feedback (may be more after demo)

- [ ] collection should have title like workflow

- [ ] "part of workflow" should only be shown when its active

- [ ] permissions tab while part of active workflow
  - permissions tab should be almost empty, only showing a message about the workflow
  - disallow update of permissions  (pundit policies)

- DB contraint change: Entries can be part of collections even if they are still drafts, but only if they are part of an active workflow.
  - in turns this means that "finalize" also converts drafts to entries! so the upcoming "validation before finalization" must take into account that at least the "mandatory fields" needs to be filled (otherwise DB contraint would trigger error)


Some Notes:
- removing something from a workflow is not possible (except by deleting of course). let's wait for feedback.
- Mandatory fields are defined in the database: For each Key in `app_settings.contexts_for_entry_validation` there needs to exist a MetaDatum

**Comment by eins78** [comment]
[WIP]

next steps:
- [ ] editing metadata of content in active workflow - completely blocked (like permissions) or just the "common" keys?

max ui:
- [ ] deco "part of" banner

**Comment by phoettli** [comment]
I can't save any metadata (Author, Keywords, Inst. aff., Date...).
And "Finishing Workflow" doesn't work either => Error: "ActiveRecord::RecordNotFound: Couldn't find Keyword"

**Comment by phoettli** [comment]
Questions:

1.  What is the difference between Workflow and Batch processing?
2. Is it possible to change ownership of the media entries?
3. Is it possible to select fields (metadata/permissions) which have to be filled with any content / with specific content and the selection will be verified before finishing workflow?
4. Is it possible to include subsets in the workflow?

**Comment by michalpodlecki** [comment]
> * I can't save any metadata (Author, Keywords, Inst. aff., Date...).
There is a bug indeed, I'm working on fixing it.
> * And "Finishing Workflow" doesn't work either => Error: "ActiveRecord::RecordNotFound: Couldn't find Keyword"
The reason is the same bug as above.
> * "_These data and settings apply to all contents and are permanently applied at the end of the process._" => after finishing workflow, I'am still able to change media entries which are part of the workflow set also as a different user with write permissions
Hmm yes, this message needs some clarification. I'll talk to Max after he comes back from holiday.

**Comment by michalpodlecki** [comment]
Answers:
2. You can change ownership by specyfing the `responsible person` in common permissions section.
4. You can add subsets in the same way as you would already do by clicking a button on set's page and selecting on of the workflow's sets.

**Comment by phoettli** [comment]
@eins78 **Feedback nach/vor Usertest**

1. Workflow-Settings:
    - Es fehlt eine Beschreibung, wofür die Metadaten auf der Konfig-Seite sind. Nicht selbsterklärend! -> Was tun die bereits ausgewählten Felder, weshalb kann man zusätzliche auswählen, welche können im nächsten Schritt bearbeitet werden, welche erst zum Schluss… Bitte Textfeld einfügen, das wir über das Languagefile befüllen können.
    - Reihenfolge der Felder anpassbar? (haben wir glaub auf 2. Version verschoben). Wie ist die Reihenfolge aber definiert? resp. sie ist sonderbar! (z.B. wenn versehentlich gelöscht und wieder eingefügt). In der Zuweisungsliste hatten wir eine Reihenfolge definiert.
2. Befüllen von Feldern geht nur für Titel, nicht für weitere Felder.
3. Abschliessen von Workflow geht nicht.
4. Navigationsschritte: nach „Prüfen“ kann man „Daten speichern“ oder „Abschliessen“. Nach „Daten speichern“ fehlt aber die Option erneut „prüfen“ um danach „abschliessen“ zu können.
5. Seite „Prüfen“/„Daten eingeben“ (Nice to have)
    - Schalter „alles aufklappen/zuklappen“ - alle Untersets und Medieneinträge werden auf- bzw. zugeklappt.
    - Klapptitel „Collection / MediaEntry“ haben Titel der Medieneinträge und Untersets, Hilfreich für die Identifikation der ME/Sets.
    - Medieneintrag-/Set-Thumb führt zu Medieneintrag oder Set (anstatt zu Preview).
6. Wir werden noch Texte anpassen im Language-File (Buttons etc.) zur besseren Verständlichkeit.

**Comment by eins78** [comment]
latest feedback: https://github.com/Madek/madek/issues/246
