### ISSUE TITLE
📦 Eigene Personenseite bearbeiten

### ISSUE THREAD

**Issue by eins78** [Madek/madek#183]
every user has a person -> can be edited.
link to "my person" from menu/dashboard?
show edit button on person page.

special feature:
live preview of the "external link decorations" would be nice (example: https://medienarchiv.zhdk.ch/people/416f8b18-197b-4208-92e3-869967dacf92)

**Comment by phoettli** [comment]
thank you!

some minor issues:
- Edit Button should not be shown to other people, only to me for my own Person (logged in as a normal user) and to admins:
![image](https://user-images.githubusercontent.com/42544602/84061698-af691000-a9be-11ea-9504-abbc3bc996a5.png)

- I like to customize some labels, where do I find labels like edit button, link add button, description, links, authority... etc. (prefix ?)

**Comment by michalpodlecki** [comment]
@phoettli the corresponding translation keys have prefix `person_show_` and `person_edit_` accordingly. Thank you for pointing out the bug with button, thankfully it does not work for users without permission to edit a person :)

**Comment by phoettli** [comment]
@eins78 ein wichtiger Punkt habe ich vergessen: Aus meiner Sicht sollte **Name und Vorname nicht veränderbar sein für User**. Das wäre das erste Metadatum, das durch User geändert werden könnte. Dabei ist mir im Hinblick auf destruktive Interventionen nicht ganz wohl dabei.

**Comment by eins78** [comment]
@phoettli Ich habe die Felder deaktiviert aber sie bleiben angezeigt, inklusive einem Hinweistext.
<img width="1904" alt="Screen Shot 2020-06-11 at 11 34 57" src="https://user-images.githubusercontent.com/134942/84369746-98e9d100-abd7-11ea-8268-b37f09c43d5b.png">

**Comment by phoettli** [comment]
perfekt! dankeschön

**Comment by phoettli** [comment]
> @phoettli the corresponding translation keys have prefix `person_show_` and `person_edit_` accordingly. Thank you for pointing out the bug with button, thankfully it does not work for users without permission to edit a person :)

thanks @michalpodlecki . Where do I find the language file, that is currently used on `TEST`?

**Comment by eins78** [comment]
> Where do I find the language file, that is currently used on `TEST`?

auf `TEST` ist immer der `master` branch, also: https://github.com/Madek/madek-webapp/blob/master/config/locale/translations.csv

**Comment by phoettli** [comment]
Label Anpassung:
```
458 person_edit_add_uri_btn,URL hinzufügen,Add URL,
...
465 person_show_description,Kurzbiographie,Short biography,
466 person_show_edit_btn,Seite bearbeiten,Edit Page,
...
468 person_show_external_uris_autority_control,Verzeichnis(se),Register,
```
