### ISSUE TITLE
Translation missing: Pager, Chooser, Login, Logout

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#189]
- Die Paginierung wird bei mir nicht übersetzt (vorhanden im Language File Zeile 404/405)
- "Seite auswählen" wird ebenfalls nicht übersetzt (in Language File nicht enthalten)

https://staging.madek.zhdk.ch/sets/gedankenspruenge?lang=en (logged in)
![image](https://user-images.githubusercontent.com/42544602/58468008-06e26800-813d-11e9-8156-55b5f1b570aa.png)

und:
- Login/Logout schmeisst die Sprache raus.

**Comment by phoettli** [comment]
wenns reicht gerne auch in aktuellen _In progress_ nehmen, damit wir die Mehrsprachigkeit abschliessen können (notfalls ohne Login/Logout).

**Comment by eins78** [comment]
https://github.com/Madek/madek-webapp/blob/7586635bca587ea212737854117878876fd5aa78/app/controllers/sessions_controller.rb#L10

@phoettli Ich habe die Übergabe des Sprachparameters bei ZHdK-Login verbessert, aber wie es scheint hat es vorher auch schon funktioniert (es wird immer an die "vorherige" Seite weitergeleitet, und da ist ja der Sprachparameter ja eigentlich immer drin). Zumindest auf staging geht es.
Aber(!): Ich habe noch unübersetzte Meldungen gefunden, konkret die "Sie haben sich angemeldet.". Evtl. hat dich das verwirrt? So oder so kommt es noch auf die Liste.

https://github.com/Madek/madek-webapp/blob/7586635bca587ea212737854117878876fd5aa78/app/controllers/sessions_controller.rb#L10

**Comment by phoettli** [comment]
stimmt, erst der Logout wechselt die Sprache:

![image](https://user-images.githubusercontent.com/42544602/58889327-04f24900-86e9-11e9-81ac-74af3a3c4087.png)

![image](https://user-images.githubusercontent.com/42544602/58889689-9feb2300-86e9-11e9-875c-7154b747f92d.png)

**Comment by eins78** [comment]
> Logout

😅 oh, das hätte ich übersehen! Habe dabei generelle Verbesserungen eingebaut, jetzt sollte es keine Aktionen mehr geben in denen die Sprache verloren geht (theoretisch nur noch möglich wenn verbotenerweise URLs händisch erzeugt werden)

**Comment by eins78** [comment]
@phoettli Zu beachten: für den ZHdK-Login ist die Nachricht nach dem Login im zhdk-agw-plugin definiert, deswegen nicht übersetzbar. Wenn das stört, würde ich vorschlagen einfach auf die spezielle Nachricht zu verzichten und bei Login egal woher die gleiche Nachricht zu zeigen.

---

![Screen Shot 2019-06-05 at 15 21 04](https://user-images.githubusercontent.com/134942/58959584-b1920080-87a5-11e9-962a-158a18d1e4f5.png)

---

![Screen Shot 2019-06-05 at 15 21 40](https://user-images.githubusercontent.com/134942/58959605-bbb3ff00-87a5-11e9-918a-22b4456a267d.png)

**Comment by phoettli** [comment]
ok auf STAGING
