### ISSUE TITLE
SQL-Abfrage fehlende Preview ergänzen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#190]
Bitte die SQL-Abfrage der fehlenden Preview ergänzen damit:
Abfrage bei fehlenden HD-Videos diese nur moniert, wenn original in HD ist.

![image](https://user-images.githubusercontent.com/42544602/58800379-00a22f00-8608-11e9-9a1e-d151c8faba52.png)

**Comment by eins78** [comment]
In der DB stehen leider keine Grössen, Query kann also nicht schlauer sein. Aber: Die Zeilen, die sich auf 'HD' beziehen kann man rauslöschen, dann kommen zumindest alle SD-Videos mit fehlenden Versionen.
