### ISSUE TITLE
Random Proxy-Error when accessing a preview data-stream via the API

### ISSUE THREAD

**Issue by eins78** [Madek/madek#191]
When using the Exporter with API Token auth,
Exporting this set: https://portfoliodb.hslu.ch/sets/c6f8dc9c-936a-461b-ad83-90798827ca47
This download error is raised:

> **Proxy Error** The proxy server received an invalid response from an upstream server. The proxy server could not handle the request GET&nbsp;/api/previews/107c875f-e2fc-4ec7-822e-835dcb9c4794.Reason: <strong>Error reading from remote server</strong>.

```
clojure.lang.ExceptionInfo: clj-http: status 502 {:status 502, :headers {"Date" "Thu, 13 Jun 2019 09:43:13 GMT", "Server" "Apache/2.4.10 (Debian)", "Content-Length" "565", "Connection" "close", "Content-Type" "text/html; charset=iso-8859-1"}, :body "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/api/previews/107c875f-e2fc-4ec7-822e-835dcb9c4794\">GET&nbsp;/api/previews/107c875f-e2fc-4ec7-822e-835dcb9c4794</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache/2.4.10 (Debian) Server at i-portfoliodb.hslu.ch Port 443</address>\n</body></html>\n", :request-time 6, :trace-redirects ["https://i-portfoliodb.hslu.ch/api/previews/107c875f-e2fc-4ec7-822e-835dcb9c4794"], :orig-content-encoding nil}
```

* This seems to be a problem with the HTTP-Gateway, and only with `/api/previews/…` routes(!?), the error always comes with the first preview that it tries to download, metadata and mediafiles before were ok. 
* Same error happens with the staging instance.
* The URLs do work in the browser (when logged in)!
  * https://portfoliodb.hslu.ch/api/previews/080cc3b0-6dee-4ad6-9424-c93ad06082e3
  * https://portfoliodb.hslu.ch/api/previews/080cc3b0-6dee-4ad6-9424-c93ad06082e3/data-stream

Some logs below, note that **there is nothing about the failing request in the Apache logs of the api server** (the one behind the gateway)!

Apache Access Logs from Gateway:

```
10.130.36.103 - - [13/Jun/2019:09:34:46 +0000] "GET /api/media-files/98d7ea7d-58eb-4526-8b40-2809bc186048/data-stream HTTP/1.1" "portfoliodb.hslu.ch" 200 3416263 "-" "Apache-HttpClient/4.5 (Java/1.8.0_131)"
10.130.36.103 - - [13/Jun/2019:09:34:47 +0000] "GET /api/previews/080cc3b0-6dee-4ad6-9424-c93ad06082e3 HTTP/1.1" "portfoliodb.hslu.ch" 502 940 "-" "Apache-HttpClient/4.5 (Java/1.8.0_131)"
```

Apache Error Logs from Gateway:

```
[Thu Jun 13 09:34:47.096250 2019] [proxy_http:error] [pid 66615:tid 139960694859520] (22)Invalid argument: [client 10.130.36.103:58228] AH01102: error reading status line from remote server prod-hslu.madek.zhdk.ch:443
[Thu Jun 13 09:34:47.096318 2019] [proxy:error] [pid 66615:tid 139960694859520] [client 10.130.36.103:58228] AH00898: Error reading from remote server returned by /api/previews/080cc3b0-6dee-4ad6-9424-c93ad06082e3
[Thu Jun 13 09:38:47.198094 2019] [proxy_http:error] [pid 66615:tid 139960510285568] (22)Invalid argument: [client 10.130.36.103:58310] AH01102: error reading status line from remote server prod-hslu.madek.zhdk.ch:443
[Thu Jun 13 09:38:47.198190 2019] [proxy:error] [pid 66615:tid 139960510285568] [client 10.130.36.103:58310] AH00898: Error reading from remote server returned by /api/previews/080cc3b0-6dee-4ad6-9424-c93ad06082e3
```

**Comment by DrTom** [comment]
No, this seems not to be a particular problem with the Exporter. 

I can very "unreliably" reproduce it  via `curl` or a Browser, too! 

There is a lot of fluctuation. Sometimes 10 consecutive curls will all work, sometimes none of  10 consecutive curls will not work and I can see the above mentioned 502.  I can also confirm, that I can see nothing in the apache logs on the Madek server itself when it fails. 

It feels like the fail rate within the Browser is lower. That might just be a side effect that it is hard to produce a high request frequency with the Browser; or it might be just random.

I would have restarted the proxy but it seems nowhere near exhausting resources (RAM, CPU, Disk, etc).

**Comment by DrTom** [comment]
Update: it seems very likely to be a problem with this particular reverse proxy. If I use the Gateway as an ssh proxy and connect some local port to the Madek machine I can download the set with the exporter (It has to be done this way because direct HTTP(S) connections to the machine are firewalled). 

@phoettli is it known if the Exporter did ever work for the HSLU or did it not. I ask this because I would like to know if this is something new or maybe it did never work and there is a problem with the configuration or a software module here. The HSLU proxy is special because of switchAAI / shibboleth.

**Comment by eins78** [comment]
@DrTom maybe this could be reason enough to try the newer Debian + Switch AAI packages? We would set up a second server; maybe installing everything from clean slate just works. If not we could make it a gateway on a separate hostname, so it can be used with the exporter (with uses Token Auth and does not need the AAI).
What do you think?

**Comment by phoettli** [comment]
> @phoettli is it known if the Exporter did ever work for the HSLU or did it not. I ask this because I would like to know if this is something new or maybe it did never work and there is a problem with the configuration or a software module here. The HSLU proxy is special because of switchAAI / shibboleth.

no, it is not known. AFAIK they used the exporter a few times for single files only. Ask Michi...

**Comment by DrTom** [comment]
Resolved
