### ISSUE TITLE
Rollen/Personen: im UI Labels ändern

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#193]
im UI die Texte bei den Feldern Rollen/Personen von "Rollen" zu "Funktionen" ändern. Rollen erinnert zu stark an Theater-Rollen. Dies stimmt nicht überein mit der Anwendung, wie wir sie für das Rollen/Personen-Feld vorgesehen haben.

Im beiliegenden translation.csv die Labels angepasst.

folgendes File habe ich verwendet:
https://github.com/Madek/madek-webapp/blob/a362f9044abfdd651c81fe1db0151dbae2523e17/config/locale/translations.csv

aus diesem Commit: e5f631b
https://github.com/Madek/madek-webapp/commit/e5f631b467185a752fdb59586db6467aebc9c856

Zeilen 388 bis 394 geändert.

[translations.csv.txt](https://github.com/Madek/madek/files/3297316/translations.csv.txt)

**Comment by eins78** [comment]
@phoettli Damit kann man das Feature jetzt nicht mehr als Beta bezeichnen, oder? Auf solcherlei Umbennungen wollten wir noch warten, die technischen Dinge haben sich auch erledigt.
(Weiss aber gerade auch nicht, ob ausserhalb der Relasenotes überhaupt irgendwo "Beta" steht)

**Comment by phoettli** [comment]
@eins78 Was meinst Du mit "Beta" und "wir"? Die Funktion haben wir bereits implementiert auf Live (z.T. sehnlichst erwartet). Anpassen werden wir aber trotzdem noch müssen: Userfeedback war teilweise bestechend !

**Comment by phoettli** [comment]
einen haben wir vergessen, sorry:

row | key | de | en
-----|----------------------------|------------|----------
197 | dynamic_filters_role_header | Funktionen | Functions

**Comment by phoettli** [comment]
danke !
OK auf STAGING
