### ISSUE TITLE
Datenauszug für Forschungsprojekt HandsOn

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#195]
Fürs Forschungsprojekt HandsOn wird eine Liste ihrer Files benötigt:

Filename Originalfile | UUID File | UUID Medieneintrag
---------------------|-----------|--------------------
GD_5_Zürich_02_Musik_history_A0_V9 4.pdf | c771483d-8605-4a44-91bb-02b2acdad743 | 7b0feea7-830d-4348-af0a-0f4e126349ee

a) Wie kann eine solche Liste am einfachsten erstellt werden?
- Liste mit vollständigen Filenamen verfügbar ?
- Medienfiles beginnen mit einheitlichem Prefix z.b. _mate_HO__... ?
- Alle Files sind in einem Set vereint (Angabe von Set) ?
- ... ?

b) Kann man direkt auf die Originalfiles zugreifen via Web?
c) gibt es Performance-Einschränkungen, wenn man direkt auf Files zugreifen will ?

**Comment by phoettli** [comment]
Antworten von Max
a) Set erstellen mit allen Medieneinträgen darin
b)
-  nur wenn sie öffentlich sind !
-  prinzipiell zugreifbar: Sourcefile ist statisch

c) eigentlich keine Einschränkungen: empfohlen auszutesten oder zu Cachen.

**Comment by phoettli** [comment]
@eins78 das Set heisst "Hands-on_IFCAR"
Bitte Liste erstellen.

**Comment by phoettli** [comment]
@eins78 hättest Du Zeit nochmal eine Liste zu erstellen? sie haben nochmal etwas geändert.
Vielen Dank!

**Comment by eins78** [comment]
für protokoll, das script:


```ruby
# $ RBENV_VERSION=2.3.3 be rails runner ../ifcar-query.rb  > handson.json
    
  puts \
    Collection.find('3ec95285-9efe-434f-82fe-2a5d60bc489a')
    .child_media_resources.select { |entry| entry.is_a? MediaEntry }
    .map do |entry|
      mf = entry.media_file
      {
        entry_id: entry.id,
        file_id: mf.id,
        file_original_name: mf.filename,
        media_type: mf.media_type,
        entry_url: "https://medienarchiv.zhdk.ch/entries/#{entry.id}",
        file_url: "https://medienarchiv.zhdk.ch/files/#{mf.id}",
        previews: mf.previews.map do |p|
          {
            preview_id: p.id,
            media_type: p.media_type,
            content_type: p.content_type,
            size_class: p.thumbnail,
            preview_url: "https://medienarchiv.zhdk.ch/media/#{p.id}",
          }
        end
      }
    end
    .to_json
```

**Comment by phoettli** [comment]
hi @eins78, wenn du mal eine freie Minute hast: Hands On fragt nach neuem Export…
