### ISSUE TITLE
LDAP Sync Automatisieren

### ISSUE THREAD

**Issue by eins78** [Madek/madek#198]
aus: https://github.com/Madek/madek/issues/179

- Wunsch war: 2x im Semester laufen; 1 Woche nach Start und dann zur Halbzeit
- Gegenvorschlag: am liebsten jede Nacht, ist einfacher und konsistent mit anderen Sync-Jobs im Haus

**Comment by DrTom** [comment]
Eledigt. Täglicher Sync, ohne Monitoring.
