### ISSUE TITLE
Vertrauliche Links: oembed-tauglich

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#199]
vertrauliche Links sollen ebenfalls oembed-tauglich sein.
Insbesondere für PAUL oder geschlossene Blogs (Unterricht) wichtig.

Weitere Optimierungen "vertrauliche Links"
#174

**Comment by eins78** [comment]
zwischenstand:
* vertrauliche links können nun direkt und per oEmbed eingebunden werden
* ein iframe wird nun immer etwas anzeigen (keine leerer kasten mehr), es gibt dann evtl. eine mehr oder wenige spezifische fehlermeldung (wie bei youtube ;))
* TODO: tests, kleines code review

---

![Screen Shot 2019-09-26 at 15 04 37](https://user-images.githubusercontent.com/134942/65690288-04523980-e06f-11e9-9766-d2a38f6862d9.png)

**Comment by eins78** [comment]
done in https://github.com/Madek/madek/commit/15a0871b0c7b08edcce82451bbb4d3fae201164b

**Comment by phoettli** [comment]
das sieht soweit gut aus auf deiner Testseite.
Im Paul klappt die Einbindung bei mir noch nicht, das kann aber an der Staging-URL liegen. Ich teste das dann nochmal, wenns auf Prog ist.

**Comment by phoettli** [comment]
Dankeschön !
