### ISSUE TITLE
Doppelter Login-Schritt

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#200]
Häufig führt mich das Login über zwei AGW-Schritte. Lässt sich dies vermeiden?

![image](https://user-images.githubusercontent.com/42544602/60907676-6d00f580-a27a-11e9-8f3f-12db4ca7cd8b.png)

![image](https://user-images.githubusercontent.com/42544602/60907693-7ab67b00-a27a-11e9-94a5-8dee59b55c1f.png)

![image](https://user-images.githubusercontent.com/42544602/60907716-84d87980-a27a-11e9-8606-0ec911a60ab4.png)

**Comment by eins78** [comment]
Ja, das ginge. Wir haben es bisher nicht gemacht, weil es nur einen Bruchteil der Nutzer betrifft (solche, die sich mehr als 60 Minuten zuvor im Intranet eingeloggt haben) und es einen Nachteil gibt:
wenn wir das AGW so verwenden, dass die "Erneutes Einloggen"-Seite nicht mehr kommt, dann werden alle Nutzer, die sich darüber anmelden aus dem Intranet ausgeloggt.
D.h. es käme die gleiche "Erneutes Einloggen"-Seite, aber dann dort…

**Comment by phoettli** [comment]
...wenn man von hier kommt:
![2019-07-10_14-00-43](https://user-images.githubusercontent.com/42544602/60967521-2a432a00-a31b-11e9-89d6-843ce0aa9644.png)

sinds vier Schritte bis eingeloggt - eindeutig zu viele :(

Schauen wir in nächster Sitzung.

**Comment by phoettli** [comment]
gemäss @eins78  ist der Prozess "AGW ohne erneutes Einloggen im Intranet" bei leihs bereits so umgesetzt. Für Madek bitte nachziehen.
