### ISSUE TITLE
Medieneintrag fehlt Vorschau-Video und Vorschaubilder

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#201]
diesem Medieneintrag
https://medienarchiv.zhdk.ch/entries/c7ff3867-bea6-4364-bc3f-6548a4e78d83
fehlt das Vorschauvideo:

![2019-07-10_13-53-43](https://user-images.githubusercontent.com/42544602/60967244-7f327080-a31a-11e9-827b-5d90d0f912c7.png)

Das Video existiert aber:
https://medienarchiv.zhdk.ch/entries/c7ff3867-bea6-4364-bc3f-6548a4e78d83

Was ist die Lösung?
- Neu encodieren mit Zencoder?
- Previews neu erstellen?

**Comment by eins78** [comment]
@phoettli Der 2. Link ("existiert aber") ist der gleiche wie der 1., was war da gemeint?
So oder so: Es wurde kein Zencoder-Job erzeugt! 
Gute Nachricht: "Reencode"-Button drücken und alles ist gut ("Recreate Thumbnails" ist nur relevant für Bilder und PDFs).
Schlechte Nachricht: *warum* kein Zencoder-Job erstellt wurde, ist unklar. Ich kann in den Logs schauen, evtl. finde ich was; ansonsten keine Idee und auch kein Mechanismus es besser zu machen (Stichwort: Filehandling).
Zumindest ist die Anzeige in der Liste korrekt, es steht dort "4 Missing Formats!" (mehr als 2 sind nie normal, bei bei HD sollte kein missing sein) https://medienarchiv.zhdk.ch/admin/media_files?commit=Apply&filter%5Bmedia_type%5D=video&page=7&sort_by=created_at_desc&utf8=✓

**Comment by phoettli** [comment]
sorry mein Copy/Paste klemmt:
https://medienarchiv.zhdk.ch/files/54a541e0-0b76-4ee8-a1d4-dbd9e3b8cc4f

**Comment by phoettli** [comment]
prima, danke.
Dann reencodiere ich mal...

**Comment by eins78** [comment]
Aha, das ist das "Original File" (url mit `/files/`, die konvertierten Medien sind unter `/media/`).

**Comment by phoettli** [comment]
Max (resp. ffmpeg) sagt File korrupt:

```
$ ffprobe '/Users/ma/Downloads/Timeline Kamera A ph02d06 01.mov'
[...]
Unsupported codec with id 0 for input stream 2
```

**Comment by eins78** [comment]
Im Backend von Zencoder steht ähnliches: "There was a problem with this file.
The input file appears to be corrupt in the audio track and could not be correctly decoded. Get more information in the documentation." -> https://support.brightcove.com/zencoder-error-unreadablefileerror

Intern wird da auch `ffmpeg` genommen, solange also `ffprobe` Probleme mit der Datei hat muss (soll) man es gar nicht neu probieren.

**Comment by eins78** [comment]
Evtl. gibt es einen milden Bug im Admin-UI, wegen dem [der Zencoder-Job vom 28.06](https://medienarchiv.zhdk.ch/admin/zencoder_jobs/8e852ca0-501f-47c4-9a24-0e27394b4abf) vorhin nicht angezeigt wurde. Jetzt wo ein 2. Job gestartet wurde werden beide angezeigt.

**Comment by eins78** [comment]
> Evtl. gibt es einen milden Bug im Admin-UI, wegen dem [der Zencoder-Job vom 28.06](https://medienarchiv.zhdk.ch/admin/zencoder_jobs/8e852ca0-501f-47c4-9a24-0e27394b4abf) vorhin nicht angezeigt wurde. Jetzt wo ein 2. Job gestartet wurde werden beide angezeigt.

Lokal mit Datenbestand von vorgestern betrachtet kann ich das Problem nicht reproduzieren. Ich schliesse das Issue.

![Screen Shot 2019-07-10 at 16 11 21](https://user-images.githubusercontent.com/134942/60980027-017b5e80-a334-11e9-8838-dd06a3fccb0e.png)
