### ISSUE TITLE
Medieneinträge manuell sortierbar pro Set

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#204]
### Ausgangslage
Medieneinträge können in Sets sortiert werden nach
- Alphabet aufsteigend
- Alphabet absteigend
- Erstellungsdatum aufsteigend (nicht kontrollierbar bei Massenupload)
- Erstellungsdatum absteigend (nicht kontrollierbar bei Massenupload)
- letzter Änderung

### Problem
**Medieneinträge können nicht manuell sortiert werden**,
z.B. für eine gezielte Reihenfolge/Auswahl von Bildern oder für verschiedene Reihenfolgen der selben Auswahl etc.
Behelfsmässig kann man die Titel von MEs mit Nummern versehen. Eine solche Sortierung widerspricht aber dem Konzept der Sets: freie Auswahl gewünschter, auch sich überschneidender Elementen.

### Lösung
Manuelle Sortierung der MEs pro Set.
- [x] DB-Erweiterung
- [x] Ausgabe über API
- [ ] UI: manuelle Sortierfunktion & Ergänzung Sortiermenüpunkt

**Comment by DrTom** [comment]
DB ist vorbereitet. API code soweit wie sinnig umgesetzt. Dabei fehlt insbesondere das Verwenden der vorgegebenen Sortierung. Die vorgegebene sortierung wird gegenwärtig in einem pseudo SQL Format abgespeichert. Dies soll generalisiert werden. Siehe JSON Struktur in in der API als Beispiel:

https://github.com/Madek/madek-api/blob/master/spec/resources/media_entries/index-order-by_spec.rb

insbesondere: 

https://github.com/Madek/madek-api/blob/master/spec/resources/media_entries/index-order-by_spec.rb#L57-L59

https://github.com/Madek/madek-api/blob/master/spec/resources/media_entries/index-order-by_spec.rb#L155

**Comment by eins78** [comment]
tasks neu sortiert: 

- [x] DB-Erweiterung
- [x] Ausgabe über API
- [ ] webapp: Anpassung für DB-Änderung, 
- [ ] API: Ergänzung: "Verwendung der vorg. Sortierung" -> https://github.com/Madek/madek/issues/205
- [ ] UI: manuelle Sortierfunktion 
  - affordance for sorting
  - add 'manual' to saveable view-options for Set
- [ ] spec: Integration Test


open Q: is DB implemented for *resources* in set, or just entries???

**Comment by phoettli** [comment]
@michalpodlecki 
the position of the arrows is cool in the list view
![image](https://user-images.githubusercontent.com/42544602/91834630-97fd9400-ec48-11ea-8317-0bd90548a103.png)

but we like to have the go to first / last position arrows also in the grid view.
![image](https://user-images.githubusercontent.com/42544602/91834928-fa569480-ec48-11ea-95d6-6b84fb96c12e.png)

**Comment by phoettli** [comment]
thanks @michalpodlecki 

two points:
1. I like to have clear difference between the next/last icon. I will discuss this issue with Max, how to/(I can) enhance the madek-icon-set
2. the sorting shows some strange behavier for me: In the video the last order should be 1/2/3/4/5 but is not!
![sorting-test_20200921-1220](https://user-images.githubusercontent.com/42544602/93758028-feeae900-fc07-11ea-92d9-aadac54defa0.gif)

**Comment by michalpodlecki** [comment]
@phoettli Thank you for the feedback and the video showing the issue. There is a bug indeed. I've just localized my small mistake in the code. I'll deploy the fix in a few minutes.

**Comment by phoettli** [comment]
@michalpodlecki 
sorting looks fine now.

another question: in a set > 30 entries it would be very hard to sort entries at the end of the list. ( => /sets/758042c8-a4bd-4dea-9f2b-85008d2351f3). Would it be possible to get also to different sort orders also for **manual sorting ASC and DESC**?
On that way a user could move the end of the list to the beginning and sort this part without waiting for loading the entire page after each change of the sorting order.

**Comment by michalpodlecki** [comment]
@phoettli of course, it is possible to add a descendant order. It really would improve the case you described.

**Comment by phoettli** [comment]
on Staging: sorting of a bunch of Entries results in Pages less then 10 Items
![2020-10-28_16-44-37](https://user-images.githubusercontent.com/42544602/97480394-9f44d380-1953-11eb-96fa-1c101be6b59c.jpg)

**Comment by michalpodlecki** [comment]
This in an interesting issue 😠 Investigating...

**Comment by phoettli** [comment]
OK auf STAGE.
