### ISSUE TITLE
Sortierung von Medieneinträgen in API ausgeben

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#205]
### Ausgangslage
Medieneinträge in einem Set können über die API sortiert oder unsortiert abgefragt werden. Als mögliche Sortierung steht Importdatum aufsteigend oder absteigend zur Verfügung.

### Problem
Sind Medieneinträge in einem Set z.B. nach Titel sortiert oder manuell (zu entwickeln #204), kann diese Sortierung über die API nicht abgefragt werden. Z.B. für das Projektschaufenster auf der ZHdK-Website wäre eine kontrollierte Sortierung wünschenswert.

### Lösung
API erweitern um Art der Sortierung.
Option Abfrage der im Set gespeicherten Sortierung.
Rückwärtskompatibilität gewährleisten für bestehende API-Anwendungen.

**Comment by eins78** [comment]
Zu klären: geht es nur um Medieneinträge oder alle Inhalte eines Sets (Einträge/Sets gemischt). Für ersteres gibt es die Funktionalität bereits: https://medienarchiv.zhdk.ch/api/docs/resources/media-entries.html#order

**Comment by phoettli** [comment]
habe die Lösung um Option _der im Set gespeicherten Sortierung_ ergänzt.

@eins78 deine erwähnte Funktionalität bezieht sich nur auf die in der Beschreibung bereits erwähnten Sortierung nach Importdatum auf-/absteigend. Andere Möglichkeiten der Sortierung inkl. der, die im Set gespeichert ist, gibt es noch nicht.

**Comment by DrTom** [comment]
Umgesetzt bis auf verwendung der vorgegebenen Sortierung. Dafür sind noch anpassungen in der Webapp notwendig. Siehe https://github.com/Madek/madek/issues/204#issuecomment-534078416

**Comment by phoettli** [comment]
Die Doc-Ergänzung sehe ich noch nicht auf STAGE:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/42544602/97698780-5a32b580-1aa9-11eb-8668-214c7ff190ab.png">
https://staging.madek.zhdk.ch/api/docs/resources/collections.html#collections
schaue ich am falschen Ort?

**Comment by michalpodlecki** [comment]
@phoettli you should rather take a look at https://staging.madek.zhdk.ch/api/docs/resources/media-entries.html#order

**Comment by phoettli** [comment]
cool ! @michalpodlecki thank you

OK auf STAGING
