### ISSUE TITLE
Delegations for Responsibility | Besitzer eines Elements (Set, ME) auch als Gruppe möglich

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#206]
### Ausgangslage
Jeder Medieneintrag, jedes Set hat einen Verantwortlichen User:
![image](https://user-images.githubusercontent.com/42544602/61697760-3aee9980-ad38-11e9-8fc2-e77ab737564e.png)

### Problem
1. Oft werden Daten von Personen importiert in einer bestimmten Funktion (Rolle) und nicht als Autor z.B. als Assi einer Vertiefung. Wenn die Aufgaben einer solchen Person übertragen werden, häufig nach Unterbruch, sollten die entsprechenden Inhalte ebenfalls übertragen werden. Leider muss dies manuell und einzeln je Eintrag geschehen, dh. häufig verwaist die Verantwortlichkeit solcher Einträge.

2. Verschiedene Gruppen von Medieneinträgen sollten nicht mehr editiert werden (freeze), sie sollten also nicht einem User zugewiesen sein, der sie dann "versehentlich" editieren könnte. Beispiele solcher Gruppen sind Forschungsdaten, Archiv etc. Ideal wäre, wenn diese Medieneinträge einer "anonyem" oder speziellen Gruppe zugewiesen werden könnte ohne User.

### Lösung
Medieneinträge und Sets können als Verantwortlichkeit auch einer Gruppe zugewiesen werden.

**Comment by phoettli** [comment]
@DrTom @eins78 bitte Lösungsvorschläge absprechen

**Comment by eins78** [comment]
## MVP Spec:

* add entity/table "Delegations", (with `delegations`, `delegations_users`, `delegations_groups`)
* changes for `media_entries and `collections` tables:
  * `responsible_user: users.id` + new `responsible_delegation: delegations.id`, 1 of them needs to be set (or 1 col for both…)
* permissions and policy changes for webapp and API:
  All the permissions that apply to the `responsible_user`, now also apply to a `responsible_delegation`, meaning all the Users in the Delegation and all Users in all Groups in the Delegation.

### tasks:
- [ ] DB changes
- [ ] Admin UI 
- [ ] permissions/policies in Webapp and API
  - [ ] existing automated test: extend where needed (but also have a critical look if they are good enough or need to be improved in general)

NOT tasks yet:
- display of Delegations in Webapp
- webapp actions (permissions edit, transfer responsibility, …)
- API for Delegations CRUD


### mockups

admin home (slight reorder of ressources in menu)

<img width="80%" alt="Resources" src="https://user-images.githubusercontent.com/134942/95075383-5ad96580-0710-11eb-8472-59577c0c4a85.png">

---

admin delegations index

<img width="80%" alt="Delegations (1)" src="https://user-images.githubusercontent.com/134942/95075394-6036b000-0710-11eb-8d33-fca1b6c1b6b1.png">

---

admin delegations show/edit

<img width="80%" alt="Archiv ZHdK" src="https://user-images.githubusercontent.com/134942/95075411-66c52780-0710-11eb-910d-a0093d10c98c.png">

---


(not a task yet) Permissions Table in webapp

<img width="80%" alt="Verantwortlichkeit" src="https://user-images.githubusercontent.com/134942/95075361-52812a80-0710-11eb-9952-2724fbce7919.png">

---

**Comment by phoettli** [comment]
looks pretty cool !

two preferred additions:
- separate section for Delegations in the Group page (my groups) like in the mockup above
- separate section for delegated entries and sets in "my archive", maybe with two additional pages in the navigation for these entries and sets

**Comment by phoettli** [comment]
@michalpodlecki Labels
[206_Labels-for-Delegations.pdf](https://github.com/Madek/madek/files/5673177/206_Labels-for-Delegations.pdf)

**Comment by michalpodlecki** [comment]
@phoettli requested additions and updated labels are already deployed to https://test-blank.madek.zhdk.ch/

**Comment by eins78** [comment]
@phoettli Heissen die Delegations auf Deutsch nun "Verantwortungs-Gruppen"? Wenn ja, müsste es konsequent überall so heissen, im Dropdown beim Übertragen steht noch "Name (Delegation)". 
Da müssen eh noch Tipfehler und Bindestriche korrigiert werden, ich dann nochmal rüber.

**Comment by eins78** [comment]
@phoettli Vorschlag: die 2 neuen"in gemeinsamer Verantwortung" Sektionen auf dem Dashboard nur dann anzeigen, wenn der Nutzer auch Mitglied mind. 1 Delegation ist (auch wenn noch keine Inhalte drin sind). So sehen es nur Nutzer, die das betrifft,

**Comment by phoettli** [comment]
@eins78 ja gern

**Comment by phoettli** [comment]
Testing on `staging`:

a) some labels missing or misspelled
[206_Labels-for-Delegations_bis.pdf](https://github.com/Madek/madek/files/5913661/206_Labels-for-Delegations_bis.pdf)

b) Is ist possible to show the new sections for joint responsibility (collection and entry) only if there are some items inside? (both in navigation and in my archive overview)
