### ISSUE TITLE
Stapelverarbeitung : Aktion : Alle ** zur Stapelverarbeitung hinzufügen funktioniert nicht korrekt

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#208]
Dieser Bug existiert auf der produktiven Instanz 3.27.1 Stölzl 

Problem: 

Ich suche nach einem Begriff bspw. Laufnummer und finde 37 Treffer, klicke anschl. im Aktionsmenü den Befehl: Alle 37 zur Stapelverarbeitung hinzufügen. In der Stapelverarbeitung sind jedoch nicht die 37 Treffer aus der Suche vorhanden. Siehe Bildschirmfotos. Die manuelle Auswahl funktioniert hingegen.

![batch 2019-07-24_11-10-00](https://user-images.githubusercontent.com/29139407/61799841-22f84200-ae2c-11e9-9008-b38303e17a22.jpg)

![batch 2019-07-24_11-10-51](https://user-images.githubusercontent.com/29139407/61799849-268bc900-ae2c-11e9-9da2-721b9a46ede5.jpg)

**Comment by eins78** [comment]
Analyse-Log:

* Was passiert? Es werden nicht die Suchergebnisse hinzugefügt, sondern die neusten Inhalte (so als wäre gar keine Suche bzw Filter aktiv). Das ist so seltsam, da kann nicht direkt im Code nach einer Ursache gesucht werden, sondern zuerst in der Projekt-Historie, um zu finden welche Änderung im Code die Ursache ist.

* Binär-Suche nach dem Commit ab dem es kaputt ging:
  * ✅ https://github.com/Madek/madek-webapp/commit/84d719f8869fb16e6c2a6dbb817b0f6092f904e1 (letzter Commit vor Arbeit an neuem batch feat)
  * ❌ https://github.com/Madek/madek-webapp/commit/c02e6cacd9a0a758474b8aecf4a819cd19f1e001 (nach batch feat)
 * ✅ https://github.com/Madek/madek-webapp/commit/5bf59c2baec409832ab6effe13b91765009e1398 
* ❓ https://github.com/Madek/madek-webapp/commit/7a15db83b35e699792486cb591cbda418730a31b
