### ISSUE TITLE
Dimensionen fehlen bei Bildern in der DB

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#210]
Bei Bildern fehlen seit September 2016 die Dimensionen (Height, Width) in der DB, einerseits bei den Files und dann auch bei den Previews vom Format "maximum".

File vom August 2016 mit **vorhandenen Dimensionen**:
https://test.madek.zhdk.ch/admin/media_files/c4166974-e082-4257-af64-a238439fb828
und "Maximum"-Preview ebenfalls mit vorhandenen Dimensionen:
https://test.madek.zhdk.ch/admin/previews/121943ec-9faa-4e4e-ba00-702aead5b9e1

File vom September 2016 mit **fehlenden Dimensionen**:
https://test.madek.zhdk.ch/admin/media_files/3e5f02e0-1cbd-4b49-94e5-6ee65434ab33
ebenfalls fehlende Dimensionen in der "Maximum"-Preview:
https://test.madek.zhdk.ch/admin/previews/1ebacc2a-3f17-4560-8d70-3bfb404a9e64

**Comment by eins78** [comment]
Erklärung schriftlich weil vermt. kompakter als mündlich:

**Diese Datenbank-Felder sind ungenutzt!** Sie wurden irgendwann mal (v2) eingeführt, aber nicht sehr stabil und auch ohne es für alte Uploads nachzuführen. D.h. man kann die Felder nicht in der Applikation benutzen, weil man sich nicht darauf verlassen kann dass (überhaupt bzw korrekte) Daten drin sind.
Ab v3 befüllen wir die Felder also auch nicht mehr.

_Warum wurden die Felder nicht entfernt?_ -> Wir haben bei der v3 Migration prinizipiell keine Daten "wegschmeissen" wollen. Kostet effektif nix (ausser dieser Dialog gerade ;))

_Was ist der Plan für die Zukunft bzgl. dieser Felder, bzw warum haben wir es in v3 nicht gleich "richtig" gemacht?_ -> Ist Teil von Filehandling, bzw. einer der dann möglichen "async jobs" ist es, alle bestehenden Medien nochmal neu auszumessen.
