### ISSUE TITLE
admin: "switch to user" fails when user has no password

### ISSUE THREAD

**Issue by eins78** [Madek/madek#211]
repro: create a new user, don't set a password (`password_digest` is empty), then try to switch to that user (both in admin ui). bug can then be seen in the stacktrace, it fails when trying to set the new session cookie where the `password_digest` is used; the underlying crypt lib complains about getting `nil` instead of a string.

workaround: set a (long and random) password before switching to the user.

curios detail: all users in zhdk-medienarchiv *do* have a `password_digest` set, so we never experienced this bug. in hslu-portfolio DB all normal users don't have a password set. so this might either point to some other problem or it is expected behaviour (difference between our login and AAI maybe).

**Comment by eins78** [comment]
niedrige prio.

**Comment by DrTom** [comment]
I can confirm this behavior. Cookies used to be bound to the password. This way it is/was possible to invalidate them by resetting the password. 
Note to why do (almost) all ZHdK users have a password: there was a Bug older versions of Bcrypt for rails which required this.

**Comment by eins78** [comment]
@DrTom Thanks. So, what do we do?
- workaround: set long random password for all users (migration + db default)
- change session/cookie-handling code to not require password or not crash on empty password (i dont know nearly enough about this code to estimate how much changes are needed)

**Comment by phoettli** [comment]
wird vorerst nicht umgesetzt
