### ISSUE TITLE
Alte Versionen (Bsp. 58.0.3029.110) des Chrome Browser unterstützen die Abspielbarkeit von Videos nicht

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#214]
Alte Versionen (Bsp. 58.0.3029.110) des Chrome Browser unterstützen die Abspielbarkeit von Videos nicht. Statt dem Video taucht untenstehende Fehlermeldung auf:

![2019-10-02_15-04-48](https://user-images.githubusercontent.com/29139407/66052488-f568fc80-e530-11e9-9859-d2e0c06beff3.jpg)

**Comment by eins78** [comment]
@ltsotrug interessant, jedenfalls mindestens aus technischem Interesse. 
Eigentlich hat sich an dieser stelle nix geändert, und eigentlich ist ein 2 Jahre alter Chrome-Browser nicht relevant. Es kann aber ein Hinweis auf einen (subtilen) Bug sein. 
Es ist aber erstmal eine Challenge, so einen alten Chrome zu finden und dann nicht zu auto-updaten ;)

@phoettli Können wir das ignorieren, falls ich es nicht reproduziert oder gelöst bekomme?

**Comment by eins78** [comment]
Überprüft: kein neues problem, es sieht jetzt nur schöner(?) aus. 
Im alten Chrome auf Prod geht es auch nicht, warum ist nun auch egal weil es auf aktuellem Chrome ja funktioniert.

![Screen Shot 2019-10-03 at 11 06 33](https://user-images.githubusercontent.com/134942/66113850-e3896700-e5cd-11e9-9e3c-7045b9d33ba8.png)


![Screen Shot 2019-10-03 at 11 04 04](https://user-images.githubusercontent.com/134942/66113734-af15ab00-e5cd-11e9-9c4a-f3aa5a67bed6.png)

**Comment by phoettli** [comment]
@eins78 

> Können wir das ignorieren, falls ich es nicht reproduziert oder gelöst bekomme?

yep, können wir ignorieren.
Steht hier zu Dokumentationszwecken im Zusammenhang mit https://github.com/Madek/madek/issues/199
