### ISSUE TITLE
feat Workflows 0.1 test results

### ISSUE THREAD

**Issue by eins78** [Madek/madek#216]
bugs

- [x] ui: render error when `AuthenticationGroup` is added to permissions 
    ```
    Error: Decorator: Unknown Resource! Type: AuthenticationGroup
    ```

- [x] ui: `onSubmit={e => {e.preventDefault()}}` for all forms (no submit on enter etc)

- [ ] ui: DateInput component should have all options as normal edit

- [x] trying to upload into *finished* Workflow-set should show an error (and not allow upload), ideally a link to "normal" upload in case use is confused

- [x] resource are only allowed to be part of **1** *actice* Workflow at a time

- [x] Have a "Fill Data" step, similar to "Check" but without the summary and no "finish" button (shuld use same view-partial for editing Metadata as in "Check" step

**Comment by phoettli** [comment]
**Test-Schritte**
- bestehende Medien einem Workflow zuweisen: OK
- Set in einen Workflow integrieren: OK

**Testlauf**
- Set erstellen geht, aber wird nicht angezeigt. Wie integrieren in Workflow-Set. 
_OK geht => Set zuweisen zu Workflowset._
- Im Workflow-Set unter „alle“ keine Anzeige der Medieneinträge (und Sets)
- Metadaten-Edit: Enter im falschen Moment schliesst gleich Bearbeitungsmodus (Datierung: Jahr eintragen und Enter drücken)
- Datierung: Eingegeben 2018-2019 - im Bearbeitungsmodus zeigt es nur noch „Freie Eingabe 2018“, beim nächsten Abspeichern nur noch „2018“
- Urheberrechtshinweis: „Zürcher Hochschule der Künste“ Workflow-Hinweis aber sinnvoll in anderem Feld (welches ??)
- Beim „Prüfen“ werden bereits Metadaten eingetragen (die nicht über Workflow gesteuert sind)  !
- Prüfen überschreibt bereits eingefüllte Daten - verwirrend ! (im Prüf-Modus Pflichfelder befüllt, Workflow-Felder aber nicht….?)
- Welche Metdaten werden in Medieneinträge und welche in Sets eingefügt? Optional wählbar für Untersets und Medieneinträge
- PID gilt nur für ein Objekt, zB. Workflow-Set. Wo eintragen?
- Unter-PIDs für Medieneinträge, wie eintragen (=> wird nicht gehen !) ==> manuell eintragen
- Medieneintrag zu abgeschlossenem Workflow hinzufügen ==> Error ! (Set sollte nicht auswählbar sein)
- Wann werden Verwandtschaftsbeziehungen eingetragen?
- Medieneinträge in einem Workflow werden abgeschlossen und Felder blockiert. In einen weiteren Workflow können sie eingefügt und überschrieben werden.
- https://madek-spiel.kiste.li/entries/bd619790-8a87-4b47-89d2-c4945bc9fa21/meta_data/edit/by_context in Edit-Modus Verweis auf falschen Workflow.
- „Pflichtfelder“-Festlegung und Prüfart (nichtleer/vorgegebener Wert) fehlt noch.

**Fehlt noch (Feature)**
- Beim Abschliessen anderen Prozessbesitzer eintragen als Option (Delegierung von Verantwortung (mehrere möglich), unabhängig vom Woorkflow-Prozess solange er offen ist)
- Fehlerkorrektur für Prozess-Verantwortlichen emöglichen
- Prozess-Verantwortlichen im Admin-Panel veränderbar?
- Mögliche Freigabe der Workshops über Usergruppe, wie Batchverarbeitung)

**Comment by eins78** [comment]
@phoettli @michalpodlecki I added tasks on top, relating to feedback where its obvious what to do. the following points are addressed, rest i will talk over with @phoettli first.

> * Metadaten-Edit: Enter im falschen Moment schliesst gleich Bearbeitungsmodus (Datierung: Jahr eintragen und Enter drücken)
> * Datierung: Eingegeben 2018-2019 - im Bearbeitungsmodus zeigt es nur noch „Freie Eingabe 2018“, beim nächsten Abspeichern nur noch „2018“
> * Medieneintrag zu abgeschlossenem Workflow hinzufügen ==> Error ! (Set sollte nicht auswählbar sein)
> * Medieneinträge in einem Workflow werden abgeschlossen und Felder blockiert. In einen weiteren Workflow können sie eingefügt und überschrieben werden.

**Comment by michalpodlecki** [comment]
@eins78 thanks, I'm on it ⌨️
