### ISSUE TITLE
API: clean up URL generation / parameter handling

### ISSUE THREAD

**Issue by eins78** [Madek/madek#218]
Problems described in this issue #217, for now only a very simple workaround for a specific use case was added.

@DrTom I tried out a few things with @nimaai  that seemed clever, but broke other things; we concluded that we dont understand everything about the intentions of the code and you should have a look and/or explain it to us.

code: https://github.com/Madek/madek-api/commit/f2eb287f75e981ac45755e3203b1023f01fefd51

- [x] handle query params vs templated params
- [x] handle duplicated params when generating 
- [x] handle invalid parameters from requests 
- [x] test collection pagination over > 2 pages

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/e365e73f419c766da6aeb3ca3f14eb5990e5af47

**Comment by phoettli** [comment]
tangiert dieses Ticket die API? Muss man Snowflake informieren, bevor das ausgerollt wird auf `PROD`?

**Comment by eins78** [comment]
@phoettli Nein. Im vorgängigen Ticket wurde haben wir einen Bug behoben ("hotfix"), der deren Client betraf; in diesem wurde nur aufgeräumt und das generelle Problem behoben.
