### ISSUE TITLE
Video-Player-Icon für alle Thumbnails

### ISSUE THREAD

**Issue by eins78** [Madek/madek#219]
followup #146

**Comment by eins78** [comment]
explore:
![Screen Shot 2019-10-28 at 11 05 25](https://user-images.githubusercontent.com/134942/67669832-fa27a180-f972-11e9-9911-8a678f31a273.png)

featured:
![Screen Shot 2019-10-28 at 11 02 13](https://user-images.githubusercontent.com/134942/67669833-fa27a180-f972-11e9-9c98-8c4b07ac015d.png)

**Comment by phoettli** [comment]
ok auf STAGING
