### ISSUE TITLE
Madek-Exporter: Download Error bei Test-Export

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#220]
Beim Download von diesem Set
https://medienarchiv.zhdk.ch/sets/8f77e194-18d0-46e1-9ef0-faa78f62f948
 mit dem Madek-Exporter gibt es bei mir diese Fehlermeldung:

> clojure.lang.ExceptionInfo: clj-http: status 422 {:status 422, :headers {"Date" "Wed, 30 Oct 2019 16:06:54 GMT", "Server" "Aleph/0.4.4", "X-Content-Type-Options" "nosniff", "Referrer-Policy" "no-referrer,strict-origin-when-cross-origin", "Strict-Transport-Security" "max-age=31536000", "Content-Security-Policy" "upgrade-insecure-requests", "Content-Type" "application/json; charset=utf-8", "content-length" "66", "Connection" "close"}, :body "{\"message\":\"Value of me_get_full_size must be true when present.\"}", :request-time 71, :trace-redirects ["https://medienarchiv.zhdk.ch/api/media-entries/?me_get_full_size=true&collection_id=a803c8e5-208e-4fd9-aa20-ab0b96908fdf&page=1&me_get_full_size=error-case&collection_id=a803c8e5-208e-4fd9-aa20-ab0b96908fdf"], :orig-content-encoding nil}

Was mache ich falsch?

**Comment by eins78** [comment]
@drtom this is also a case of a `next` link that is generated with "broken" params.
apart from the duplicated params (known issue, #218 ) what sticks out to me is `&me_get_full_size=error-case`.

repro in API browser:
1. https://medienarchiv.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2F%3Fme_get_full_size%3Dtrue%26collection_id%3Da803c8e5-208e-4fd9-aa20-ab0b96908fdf&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A
2. click next link

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/e365e73f419c766da6aeb3ca3f14eb5990e5af47

**Comment by phoettli** [comment]
Ein (anderer?) Fehler im Exporter ist auf `STAGING` noch immer vorhanden (**3.29.0**):

> `clojure.lang.ExceptionInfo: clj-http: status 403 {:status 403, :headers {"Date" "Tue, 03 Dec 2019 11:59:19 GMT", "Server" "Aleph/0.4.4", "X-Content-Type-Options" "nosniff", "Referrer-Policy" "no-referrer,strict-origin-when-cross-origin", "Strict-Transport-Security" "max-age=31536000", "Content-Security-Policy" "upgrade-insecure-requests", "content-length" "0", "Connection" "close"}, :body "", :request-time 16, :trace-redirects ["https://staging.madek.zhdk.ch/api/collections/e7396a94-9604-402b-a84e-d22c25f04bd1"], :orig-content-encoding nil}`

Allerdings kann ich jetzt nicht sagen, ob der in **3.28.2** oder **3.28.3** behoben war. Aktuell tritt er auch auf `PROD` (**3.28.4**) auf.
Die Files kommen an.

**Comment by eins78** [comment]
Das ist, wenn überhaupt, ein anderer Bug. In dem genannten Beispiel stimmen die Berechtigungen nicht: https://staging.madek.zhdk.ch/sets/e7396a94-9604-402b-a84e-d22c25f04bd1/permissions

**Comment by phoettli** [comment]
@eins78 schrieb:
> good news and bad news: API-Bug gefixed, Bug im Exporter gefunden.
> Aber: ist für dieses Set um das es ging (bzw allgemein im Zusammenhang mit Archivierung) glaube ich nicht relevant: die Berechtigungen sind nicht überall gleich gesetzt + für sets-in-sets fragt der Exporter das nicht korrekt ab = Fehler.
> Wenn man aber dieses Set anpasst, dann geht es durch (gleiche Rechte wie alles andere, mindestens muss es der exportierende User sehen): https://medienarchiv.zhdk.ch/sets/e7396a94-9604-402b-a84e-d22c25f04bd1/permissions

Was heisst "Stimmen die Berechtigungen nicht"? Es kann sehr wohl sein, dass nicht alle Berechtigungen Leserechte für den exportierenden User beinhalten. Dies sollte m.E. nicht in einem kryptischen Fehler enden, allerhöchstens in einer für den User verständlichen Warnung ;)

@eins78 erstellst Du dazu ein neues Ticket?

**Comment by eins78** [comment]
Neues Ticket damit es klarer ist: https://github.com/Madek/madek/issues/224
