### ISSUE TITLE
API-Doku: Media-File ergänzen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#222]
Die API-Doku ist auf der Seite “Media-File” unvollständig: https://medienarchiv.zhdk.ch/api/docs/resources/media-file.html

**Comment by DrTom** [comment]
@phoettli mir ist mittlerweile wieder eingefallen, dass dieses Stück Dokumentation absichtlich nicht eingetragen wurde. Das Filehandling wird da wahrscheinlich etwas ändern. Damals war aber auch nicht abzusehen, das dieses Filehandling ein 5 Jahresprojekt wird. Ich kann die Dokumentation trotzdem ergänzen und eine Warnung dazuschreiben?

**Comment by phoettli** [comment]
gerne :)
genau diesen Teil benötigt Hands On für die API-Abfrage. Probieren ginge schon, Doku ist etwas komfortabler (und macht besseren Eindruck).

Danke Dir !

**Comment by DrTom** [comment]
Das ist  auf master gemerged.

**Comment by eins78** [comment]
@phoettli Wie schnell soll das auf `prod` sichtbar sein? Dazu müsste es theoretisch ein release geben. Auf `test` ist es ab morgen, falls das reicht.

**Comment by phoettli** [comment]
`test` ist gut, das reicht vorerst. Vielen Dank Euch beiden !

**Comment by phoettli** [comment]
ok auf STAGING
