### ISSUE TITLE
API: Ausgabe des File Types für Medieneinträge

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#223]
gemäss @DrTom sollte der Content Type der Medienfiles über die API verfügbar sein.

bei den Hands On Files wird er allerdings nicht ausgegeben:
https://medienarchiv.zhdk.ch/entries/261ebf67-53c3-4db2-8c66-1359844e3bf7
weder bei Eintrag
https://medienarchiv.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2F261ebf67-53c3-4db2-8c66-1359844e3bf7&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A
noch bei Medienfile
https://medienarchiv.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2F5ee97b72-44a6-46d4-9d53-b1b99cc1a5ab&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

nur die Previews enthalten einen Content Type.

@DrTom 

- Hast Du mir ein Beispiel, wo der Content Type ausgegeben wird?
- Weshalb wird er bei einigen ausgegeben und bei anderen nicht?

**Comment by DrTom** [comment]
Doch wird er: 

```
curl -I HEAD 'https://medienarchiv.zhdk.ch/api/media-files/5ee97b72-44a6-46d4-9d53-b1b99cc1a5ab/data-stream'
...
HTTP/1.1 200 OK
...
Content-Type: video/quicktime
```

Ich habe den Verdacht, dass mit über die API ausgegeben ein Feld in den JSON-Daten gemeint ist. DER "Content-Type" ist ein HTTP Header, z.B. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type.  Der korrekte "Content-Type" kommt dann auch nur über die url des echten videos; also `.../data-stream` bei uns. 

Jetzt gibt es auch ein Feld in der DB auf dem media file `content_type` (ist massgeblich für eben den Conten-Type HEADER). Dies wird mit dem Media-File nicht herausgegeben. Wir können dieses Feld zusätzlich ausgeben braucht halt eine kleine Änderung in der API. 

Die notwendige Information gibt es aber auch heute schon, siehe oben.

**Comment by phoettli** [comment]
aha.
im Stream sieht man halt erst bei der Datenübertragung, was der Content Type ist. Ich fände gut, wenn dies schon vorher abgefragt werden könnte, also: welcher Stream will ich überhaupt. Analog den Previews:

```
{
  "media_type": "image",
...
  "content_type": "image/jpeg",
...
}```

Kannst Du das einbauen, sofern sinnvoll?

**Comment by DrTom** [comment]
Done https://github.com/Madek/madek/commit/79901bc7bd66224e0ede0adb26b6ec90de720ecb

**Comment by phoettli** [comment]
Dankeschön !
ok auf STAGING
