### ISSUE TITLE
Exporter: missing permissions-parameter when recursing sets

### ISSUE THREAD

**Issue by eins78** [Madek/madek#224]
```gherkin
Given I have permissions for a Set "A"
  And this Set contains another Set "B", that I don't have permissions for
When I export the Set with the Exporter
Then it tries to download to download Set "B"
  And throws an Error "403 - Forbiden
```

Solution: when requesting "sets in sets", add the `me_get_metadata_and_previews` to `true`.

**Comment by eins78** [comment]
@phoettli Workaround for Users: Make the permissions in (recursively) contained Set match the top-level Set. This is by definition only possible to do for admins, normal users dont even see the problematic sub-sets  :/
Yes, this is not a nice workaround, but it should be doable for most of our usecases (archiving) where the permissions should match anyhow.

We could also make the messages less cryptic, but those kinds of errors (shown in this way) are never something the user can do anything about (like in this case, where the exporter does the wrong thing).

**Comment by DrTom** [comment]
Done https://github.com/Madek/madek-exporter/releases/tag/0.9.7

**Comment by DrTom** [comment]
FYI @phoettli

**Comment by phoettli** [comment]
ganz grosse Eisenbahn ;) funktioniert wunderbar und fehlerfrei !
Dankeschön
