### ISSUE TITLE
Bildformat HEIF und HEIC unterstützen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#228]
Apple nutzt seit iPhone7 das Fotoformat HEIF. Es soll deutlich besser komprimieren als JPEG.
![image](https://user-images.githubusercontent.com/42544602/73159573-127c9900-40e7-11ea-9c53-16d36ede2525.png)

Können wir das in Madek unterstützen?
- Original als HEIF belassen
- Preview als JPEG ausgeben

Soweit ich verstanden müsste HEIC über Zencoder gehen (HVEC-Codierung)...?

**Comment by phoettli** [comment]
http://nokiatech.github.io/heif/technical.html

**Comment by eins78** [comment]
@phoettli Das mit dem Containerformat scheint hier der tricky Teil zu sein. Wenn wirklich nur ein Foto drin ist, könnte es mit der bestehenden, simplen Dateien-Pipeline funktionieren (der mime-type ist `image/heif`, also sollte es als Bild behandelt werden).
In deinem Screenshot sieht es aber aus, als wäre es als Video erkannt/behandelt, dann geht es natürlich nicht einfach so.
Für konkretere Aussagen müsste ich mal mit diversen Test-Files probieren, aber ob sicher Aufwand lohnt ist fraglich – kompletter/korrekter Support ist mit derzeitigem Filehandling sicherlich nicht umsetzbar. Nur der einfache Fall, 1 (Haupt-)Foto extrahieren könnte mit simplem Workaround machbar sein; evtl. braucht es nur eine neuere Version des EXIFtool.

**Comment by eins78** [comment]
> evtl. braucht es nur eine neuere Version des EXIFtool.

🔔 ja das reicht schon :) also geringen aufwand, muss nur verifizieren dass es keine unerwarteten änderungen bei EXIFtool gab (ist in der Vergangenheit oft der Fall gewesen, deswegen wird es auch nicht mehr automatisch aktualisiert).

---

![Screen Shot 2020-01-27 at 11 33 10](https://user-images.githubusercontent.com/134942/73167937-1d402980-40f9-11ea-86b5-fdc61f0050f5.png)

---

![Screen Shot 2020-01-27 at 11 33 01](https://user-images.githubusercontent.com/134942/73167934-1addcf80-40f9-11ea-9fd8-5582f7f385b0.png)

**Comment by eins78** [comment]
@phoettli mist, leider doch nicht so simpel. die library, welche die thumbnails erzeugt muss auch HEIF verstehen. das ist `imagemagick`. auf meinem lokalen system habe ich die neueste version (deswegen ging es lokal), auf den servern ist aber wegen Debian eine sehr alte version. 
kann man versuchen einzeln upgrade zu machen, oder gleich die neue Debian version aufsetzten, so oder so mehr aufwand.

**Comment by phoettli** [comment]
Wann habt ihr das Debian-Upgrade eingeplant? Kann man das verbinden?
Extra-Aufwand nur für HEIF finde ich etwas übertrieben. Wenn es aber "noch Jahre dauert", sollte man das vorziehen...

**Comment by eins78** [comment]
> Wann habt ihr das Debian-Upgrade eingeplant? Kann man das verbinden?
> Extra-Aufwand nur für HEIF finde ich etwas übertrieben. Wenn es aber "noch Jahre dauert", sollte man das vorziehen...

Upgrade müsste innerhalb der nächsten 1-2 Jahre eh gemacht werden, wir warten immer ein bisschen ab und suchen dann nach einem Grund. "Nur für HEIF" stimmt also nur so halb, wir nehmen es mal als Gelegenheit es zu checken. 
Falls doch mehr zu tun ist als gedacht können wir nochmal planen.

**Comment by eins78** [comment]
@phoettli Gab keine Komplikationen, upgrade kann gemacht werden. Muss bei nächsten deploy manuell gemacht werden.

**Comment by phoettli** [comment]
ok auf `test-blank` :)
