### ISSUE TITLE
Fix nightly run of ZHdK Group Sync

### ISSUE THREAD

**Issue by DrTom** [Madek/madek#229]
The ZHdK Group Sync (supposedly) runs nightly. It failed to do so because of missing permissions to some files and folders. It seems (most likely) that the normal Madek deployment is resetting these permissions. I can see two ways to fix that:
* make the deployment not do that 
* run some sync pre task via Systemd which sets the required permissions for the sync user

**Comment by phoettli** [comment]
bitte dies doch gelegentlich fixen.
Es gab einen Rüffel, weil Forschungsbezeichnung falsch ist. `Geschäftsstelle Forschung` fehle.
Ich glaube, die Bezeichnung fehlt allerdings schon im LDAP. Wenn der Sync aber zuverlässig tut, ist diese Angriffsfläche weg.

Bis wann könnte der Sync zuverlässig laufen?

Danke !

**Comment by DrTom** [comment]
Fixed: https://github.com/Madek/madek-zhdk-ldap-sync/commit/4970573703ad7bdde519963399dfb291e5fa367f

None of the two options mention above was used. We deploy to a different directory outside `/madek`. So the madek deploy should not mess with it.
