### ISSUE TITLE
DB: ensure defaults for {people,keywords}.external_uris

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#234]
bug in migration, did not set the default for NULL fields.
https://github.com/Madek/madek-datalayer/compare/Madek:589f529...Madek:e644119#diff-bbcdc17e37663d99e857358c3441dd36

needs new migration to clean up existing values. code below can "hotfix" a prod instance.

```sql
update people set external_uris = '{}' where external_uris IS NULL;
update keywords set external_uris = '{}' where external_uris IS NULL;

```

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/1b00d670de5689918aab18b395468fbfaf8806f0
