### ISSUE TITLE
Eingebettete Videos laden nicht zuverlässig in PAUL

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#236]
Das eLearning-Forum in PAUL listet verschiedene Videos aus dem Medienarchiv auf. Insbesondere über VPN (am Nachmittag z.T. auch ohne) dauert es ewig, bis eine Video-Datei gestartet werden kann oder es tritt ein Fehler auf und das Video ist nicht verfügbar.
https://paul.zhdk.ch/mod/forum/view.php?id=13160

Beobachtung

- Das iFrame lädt i.d.R. korrekt, d.h. meist besteht eine Verbindung zum Medienarchiv, um den Player zu laden.
- Das Video starten geht bei mir dann oft nicht (drehender Warten-Ring), z.T. lädt nach langer Wartezeit mal noch das Video, häufig folgt aber der Fehlerhinweis (Safari bricht früher ab).
- Nicht reproduzierbar auf bestimmte Videos, tritt unterschiedlich bei allen langen auf. Das kurze "SmartSetting" lädt praktisch immer.
- Wie VPN viel häufiger keine Videos.
- Wenn ein Video mal gestartet ist, kann es auch später wieder weitergespielt werden. Nur der erste Start dauert so lange/scheitert.

Wie kann man sich der Fehlerursache annähern? (Verbindung, gleichzeitige Aufrufe, Flaschenhals Toni...)

Ev. off topic:

- 72 Verbindungen zum Medienarchiv für 8 Videos: Verbindungsengpass?
- Weshalb so viele unverschlüsselte Verbindungen?

[20200402_2335_Ladefehler-iframe.pdf](https://github.com/Madek/madek/files/4424005/20200402_2335_Ladefehler-iframe.pdf)

**Comment by DrTom** [comment]
Beobachtungen:

@phoettli hat mich MI den 1.4 Spätnachmittags auf die Probleme hingewiesen. Ich konnte sie zu dem Zeitpunkt nicht reproduzieren. Ein leichtes hakeln bei der Wiedergabe meinte ich bestätigen zu können, d.h. beim starten oder springen im Video kam es manchmal zu Verzögerungen zwischen 1 und 2 Sekunden. Einen kompletten Abbruch konnte ich nie bestätigen. Einen Unterschied mit und ohne VPN konnte ich nicht feststellen. Alle tests wurden von mir mit dem Chrome Browser durchgeführt. 

Heute FR 3.4 ca 8:30 konnte ich bei dem erwähnten Video mit dem Chrome Browser stärkeres hakeln nachvollziehen. Safari und FF produzierten für eine weile tatsächlich die erwähnten Ausfälle. Einige wenige Datenbankprozesse waren dabei in `top` auffällig lange oben (idle!).  
Eine gegenprobe um ca 8:45 auf `staging.madek` zeigte keine Probleme. Etwa 8:50 zurück auf `medienarchiv` waren dann wiederum überhaupt keine Probleme mit keinem Browser zu sehen. Um 9:00 gab es leichte eher normale verzögerungen mit dem Safari.

**Comment by DrTom** [comment]
Ich möchte in dem Zusammenhang auf Netzwerke Probleme hinweisen, die ich/wir vor etwa 1 bis 2 Jahren speziell im Toni erlebt hatten. Damals waren speziell um die Zeit nach dem Mittagessen, also dann wenn viele Leute dazu tendieren im Web zu surfen, grössere HTTP(s) downloads problematisch. Es war in etwa so, dass die ersten "paar" Bytes relativ schnell durch kamen; darauf brach die Übertragungsrate mehr oder weniger komplett ein. Ich kenn die Ursache nicht aber es ist vorstellbar, dass an irgend einer Stelle versucht wurde so irgendwelcher Bandbreitenprobleme herr zu werden. Ich erwähne das hier weil in der Beschreibung speziell "grosse Videos" erwähnt werden.

**Comment by DrTom** [comment]
Was können wir tun:

1. Langfristig einen Objekt-Store einsetzen um die Medien zu speichern.  Mit sehr hoher Warscheinlichkeit hätten wir diese Probleme nicht wenn die "File-Service" Geschichte nicht verschleppt worden wäre. 

2. Kurzfristig kann ich die "DB defragmentieren" (nicht wirklich aber um das mal kompakt und vereinfacht darzustellen). Ich spreche dabei die Datenbank Peaks an, die ich meine gesehen zu haben. Generell könnte das über alles ein bisschen etwas bringen. Es ist unwahrscheinlich, dass es dieses spezielle Problem (komplett) löst. Nachteil: 
* Ich muss das medienarchiv für einige Zeit herunternehmen. Das kann zwischen Minuten sein oder bis zu Stunden dauern (nach aller Wahrscheinlichkeit eher Minuten). 
* Es ist operativ eine etwas heikle Sache. Ein kleiner Bedienfehler oder ein Problem (volle Disk) kann dazu führen, dass wir das Medieanrchiv aus einem Snapshot zurückholen müssen.

**Comment by phoettli** [comment]
@eins78 hilft das?

[Chrome-Profile-20200403T104925.json.zip](https://github.com/Madek/madek/files/4426022/Chrome-Profile-20200403T104925.json.zip)

Jetzt liefs grad rund bei mir. Aber dann würde ich heute Nachmittag nochmal schauen

**Comment by phoettli** [comment]
Chrome scheint ein recht cooler Browser zu sein. Damit habe ich praktisch keine Probleme. Aber Safari und Firefox laden bei mir schon wieder nicht.
Wie bekommen wir diese lahmen Browsers auch in den Griff?

**Comment by phoettli** [comment]
Chrome scheint grundlegend anders mit grösseren Dateien umzugehen.
Absolute Laienfrage: könnte HTTP/2 da etwas verbessern in den Verbindungen, bei denen Verzögerungen auftreten bis zum Schliessen der Verbindung?

**Comment by DrTom** [comment]
DB ist "defragmentiert". Leider treten die Probleme immer noch sporadisch auf. Auf dem Server sehe ich während dessen überhaupt nichts. Die CPUs zucken nocht nicht mal ein wenig. Ich bin jetzt ratlos. Bestätigen kann ich, dass wenn es in Chrome etwas hakt dann haben die anderen beiden richtige Probleme.

**Comment by phoettli** [comment]
Firefox:
![image](https://user-images.githubusercontent.com/42544602/78549958-87fd9780-7803-11ea-9d3a-b10bded9b594.png)

und
![image](https://user-images.githubusercontent.com/42544602/78549868-5f759d80-7803-11ea-9b34-320c60b7eb09.png)

**Comment by phoettli** [comment]
Via Citrix sieht es aus:

- Firefox hat ähnliche Probleme: die ersten beiden und das kurze Videos laden gut, spätere laden praktisch nicht mehr.
- IE funktioniert gut über alle Videos auf der ganzen Seite.

**Comment by eins78** [comment]
Solution: "preloading" of media is now disabled (`<video preload="none">`) which reduced traffic on the test page by 90% (saving almost 700MB). All the embedded players now load reliably.

fixed in https://github.com/Madek/madek/commit/add17eb9b5efc40a209be473ca7e2512d32fee50
