### ISSUE TITLE
Use HTTP/2 in Apache config

### ISSUE THREAD

**Issue by eins78** [Madek/madek#238]
Hopefully this will lead to better preloading of many video-players on 1 page (less blocking of requests).

- [ ] evaluate if this can be done easy/unintrusively (only in Apache Config, HTTP/1.x still works)
- [ ] implement if easy

**Comment by eins78** [comment]
@DrTom `test-blank` is already upgraded to Debian buster, and the master branch is ready; so if you want to quickly try out some config this would an easy option.

**Comment by phoettli** [comment]
wird vorerst nicht weiter verfolgt
