### ISSUE TITLE
Resolution Toggle zeigt HD an, Darstellung ist jedoch SD

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#239]
Tritt beim Aufrufen von Medieneinträgen mit Videos auf

Konkret: 
Resolution Toggle zeigt HD an, Darstellung ist jedoch SD

Erst durch das Anklicken auf den Resolution Toggle HD wechselt
die Anzeige von SD auf HD.

![2020-04-14_10-32-43](https://user-images.githubusercontent.com/29139407/79204301-9cade100-7e3c-11ea-96ec-6a30903f1883.jpg)

**Comment by phoettli** [comment]
/entries/f3773d3d-cb43-4f17-a988-c4bbefcb8d3a

**Comment by phoettli** [comment]
grad zufällig drübergestolpert:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/42544602/92590523-ab3dde80-f29c-11ea-8972-c19c3cb36081.png">

**Comment by ltsotrug** [comment]
der Bug-Fix von v3.0.0-10.2 Miedinger scheint aktuell inaktiv zu sein. Aktuell in 3.30.0 Burkhard ist es wie folgt: Wenn ein HD Video aufgerufen wird, wird die SD-Auflösung als erstes dargestellt und der Toggle wird mit HD angezeigt. Erst durch den Klick auf den Toggle HD wechselt die Anzeige von SD zu HD.

Beispiel: Standbild bei TC 01:20 (oberes Bild SD Auflösung mit Toggle Anzeige HD, unteres Bild HD Auflösung nach Klick auf Toggle Anzeige HD)
https://medienarchiv.zhdk.ch/entries/1694b193-a1ec-4e22-9f09-0e1d2dc1f596

![2020-09-15_09-55-53 resolution 01](https://user-images.githubusercontent.com/29139407/93182924-99e05080-f73a-11ea-8ee2-e9e06330e297.jpg)
![2020-09-15_09-56-47 resolution 02](https://user-images.githubusercontent.com/29139407/93182935-a1075e80-f73a-11ea-9a08-0da431f67cf7.jpg)

**Comment by eins78** [comment]
@ltsotrug Miedinger ist doch eine sehr sehr alte Version, da ging es um einen ganz anderen fix. Ich bin aber dran.

**Comment by eins78** [comment]
Problem gefunden und gelöst. 
Technische Erklärung: Das verwendete Plugin nutzt zur Konfiguration die Attribute `label` und `res` auf dem video-source HTML-Element (`<source src="/media/1234" type="video/mp4" label="HD" res="1080">`). Das ist allerdings ungültiges HTML (`res` ist kein Attribut für `source`).
Lösung: `data`-Attribute nutzen (`<source src="/media/1234" type="video/mp4" label="HD" data-resolution="1080">`).
Dazu musste ich das verwendete Plugin anpassen, es ist jetzt in unserem Repo integriert statt das Paket zu nutzen (weil das Plugin nicht mehr gepflegt wird habe ich die Verbesserung nicht upstream eingereicht).

**Comment by eins78** [comment]
Fix: https://github.com/Madek/madek-webapp/commit/b12bca1cba693341a9d5025b8b4d6b01b017c528

**Comment by eins78** [comment]
@ltsotrug https://test.madek.zhdk.ch/entries/1694b193-a1ec-4e22-9f09-0e1d2dc1f596

**Comment by ltsotrug** [comment]
@eins78 cool, merci

**Comment by phoettli** [comment]
in Safari: Umschalten auf HD bleibt beim Posterbild hängen. (auf PROD funktioniert Restart korrekt):

![HD-switch-20201028](https://user-images.githubusercontent.com/42544602/97479222-4d4f7e00-1952-11eb-80c6-99ccb646910b.gif)

**Comment by eins78** [comment]
bestätigt.

* nur im Safari
* nur wenn auch `preload=none` gesetzt wurde (auch eine neue Änderung, wegen Performance/Effizienz)

@phoettli ich versuche heute Vormittag einen simplen Workaround zu finden, wie erwähnt schwierig weil die Libraries im Player inzwischen schon sehr alt sind. Wenn wir wie besprochen evtl. doch mit diesem Bug ausrollen, dann würde ich als nachhaltige reparatur versuchen die libraries zu updaten ([video.js](https://videojs.com))

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/225c0bcf3443327e6c23980b6789c48d67e8e133

**Comment by phoettli** [comment]
ok auf STAGING
