### ISSUE TITLE
Meta-Key Typen fehlen auf Staging

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#242]
aktuell fehlen auf Staging die Meta-Key-Typen:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/42544602/81206532-87a41800-8fcc-11ea-931f-2754fd45b2ae.png">

Ich kann kein Meta-Key erstellen => error 500

**Comment by phoettli** [comment]
auf PROD ebenfalls !!!

**Comment by michalpodlecki** [comment]
@phoettli the fix for this issue is already on master, next deploy will resolve the problem.

**Comment by michalpodlecki** [comment]
fixed on staging 🔨

**Comment by eins78** [comment]
@phoettli I want do a release next week, including the other small fixes (like HEIF support). Please tell me if this issue is more urgent, I could do a smaller patch-release just for that as well.

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/147c646fa2a2c1e44fa1dfb0bf5568c4a225a200

**Comment by phoettli** [comment]
@eins78 next week is fine.

**Comment by phoettli** [comment]
@michalpodlecki fix on Staging, shure?
![image](https://user-images.githubusercontent.com/42544602/81284350-49573900-905e-11ea-89f3-11359c28d1ac.png)
;)

**Comment by michalpodlecki** [comment]
@phoettli it was at time I wrote the comment, nightly deploy apparently has overrided it :(

**Comment by eins78** [comment]
@phoettli that was a misunderstanding; just to be clear: its fixed on `test` (because its merged to master/the ticket is closed), on `staging` would mean there is also a release candidate (so next week)

**Comment by phoettli** [comment]
@eins78 
does not work for me on `stage`!
works fine on `test`

**Comment by phoettli** [comment]
ok on `staging` now
