### ISSUE TITLE
Login geht wieder über zwei Schritte

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#243]
Login geht wieder über zwei Schritte.
Hast du das nicht mal auf einen reduziert?
https://github.com/Madek/madek/issues/200

**Comment by eins78** [comment]
Es gab Änderungen am AGW im Zusammenhang mit der neuen "remember-me"-Funktion. Wenn diese genutzt wird gibt es weiterhin nur einen Schritt, wenn nicht dann leider teilweise wieder 2 Schritte.
Wir können von unserer Seite nix machen, bzw. habe ich den Änderungswunsch (AGW) schon vermeldet (aktuell ungeplant).
