### ISSUE TITLE
"Beta Groups" – User looses membership when logging out.

### ISSUE THREAD

**Issue by eins78** [Madek/madek#245]
Could either be that the user is removed from the group on logout (some hook?), or the whole group is deleted (and then recreated via the groups controller hook).

**Comment by eins78** [comment]
problem: when loggin in from ZHdK, group is removed! solution: exclude the beta groups.

**Comment by eins78** [comment]
fixed in https://github.com/Madek/madek/commit/e43bb7bf1f5f233c0f614f88cb0ff80c35acdeba

**Comment by phoettli** [comment]
testbar erst nach dem nächsten Deployment.
