### ISSUE TITLE
Workflow-Test ergibt Fehler beim Speichern 

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#246]
Server: `madek-spiel`

folgender Workflow
85179568-3a7d-41b9-8f08-d8e13f0b1577

ergibt folgenden Fehler beim Speichern
- -> Daten eingeben
- Titel ausfüllen bei ME "Bild 7"
- Speichern
`ActiveRecord::RecordNotFound: Couldn't find MediaResource with 'id'=29b4c62a-17ec-45ce-94a8-bda74f939cf0 [WHERE (vw_media_resources.id IN (SELECT "media_entries"."id" FROM "media_entries" INNER JOIN "collection_media_entry_arcs" ON "media_entries"."id" = "collection_media_entry_arcs"."media_entry_id" WHERE "collection_media_entry_arcs"."collection_id" = 'b3831525-01f2-4a72-b9fb-d61fef0d4360' AND "media_entries"."is_published" IN (TRUE, FALSE) ORDER BY "media_entries"."created_at" ASC, "media_entries"."id" ASC) OR vw_media_resources.id IN (SELECT "collections"."id" FROM "collections" INNER JOIN "collection_collection_arcs" ON "collections"."id" = "collection_collection_arcs"."child_id" WHERE "collections"."clipboard_user_id" IS NULL AND "collection_collection_arcs"."parent_id" = 'b3831525-01f2-4a72-b9fb-d61fef0d4360' ORDER BY "collections"."created_at" ASC, "collections"."id" ASC) OR vw_media_resources.id IN (SELECT "filter_sets"."id" FROM "filter_sets" INNER JOIN "collection_filter_set_arcs" ON "filter_sets"."id" = "collection_filter_set_arcs"."filter_set_id" WHERE "collection_filter_set_arcs"."collection_id" = 'b3831525-01f2-4a72-b9fb-d61fef0d4360'))]`

Was habe ich vorher gemacht? (hat allenfalls Einfluss auf Fehlverhalten)
- ~~ME zugefügt, der schon einen Untertitel hatte (sollte mit Workflow überschrieben werden)–– (sollte keinen Einfluss haben, separat getestet ohne Fehlermeldung)
- ~~Autor zu Pflichtfeld gewechselt, obwohl z.t. schon Einträge in MEs bestehend waren.~~ (sollte keinen Einfluss haben, wird einfach überschrieben – separat getestet)

PS: ich lasse diesen Workflow mal unverändert, bis ich von Dir Feeback erhalte.

**Comment by eins78** [comment]
@phoettli Die Fehlermeldung bezieht sich auf einen anderen Eintrag. Es scheint mir daher nichts mit Bild 7 zu tun zu haben, sondern bild_02. Dies ist auch in einem Unterset verschachtelt, kann mir vorstellen dass der Fehler daher rührt.

**Comment by eins78** [comment]
@michalpodlecki Minimal reproduction for this bug: Add a published Entry to a new Set, then add the Set to a main workflow set. Saving "prefill" Data then raises the error above (Entry can't be found, it looks like the query only looks in top-level set)
