### ISSUE TITLE
fix apache log for non-gateway setups

### ISSUE THREAD

**Issue by eins78** [Madek/madek#249]
this change introduced a custom log format that only works for hosts behind a gateway. needs to be made optional.
https://github.com/Madek/madek-deploy/commit/735496e165f32bf50d2eb4ccac2e0477f2646b90

- [x] deploy config: add variable `is_behind_gateway`, default false
- [x] apache: use custom log format `is_behind_gateway`
- [x] inventory: set `is_behind_gateway` for affected instances

**Comment by eins78** [comment]
@phoettli War kleine Anpassung, wird im nächsten Release sein, habe es aber vor allem manuell auf den prod-server angewendet. Ist also aktiv ab jetzt, sollte morgen in den neuen stats sichtbar sein.

**Comment by phoettli** [comment]
sehr cool, dankeschön !
