### ISSUE TITLE
TimeStamp im Tab Nutzung benötigt die zusätzliche Angabe UTC +2

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#251]
Auf den ersten Blick erscheint die Veränderungszeit um 2 Stunden falsch zu liegen. Für User ist die 2 Stunden Zeitverschiebung irritierend. Hier müsste zumindest die Angabe UTC + 2 
vorhanden sein, damit nachvollziehbar ist, dass sich die Datenbank an der Weltzeituhr orientiert.

![TimeStamp](https://user-images.githubusercontent.com/29139407/84416024-ebe17980-ac13-11ea-9c7f-7908cb7ea5df.jpg)

**Comment by phoettli** [comment]
@eins78 Bitte local Time

**Comment by eins78** [comment]
- [ ] app_setting.server_time (default `Europe/Zurich`)
- [ ] immer als server time anzeigen

**Comment by phoettli** [comment]
ok auf `staging`
