### ISSUE TITLE
CORS Header Access-Control-Allow-Credentials ist missing on production

### ISSUE THREAD

**Issue by DrTom** [Madek/madek#253]
The Header

    Access-Control-Allow-Credentials: true

should be present but is missing on production. It is present on `test.madek`. The change which adds this is

https://github.com/Madek/madek-api/commit/a7438b3fd94dddc5248e9e8b35e8df6a47f018e4

Could it be that this one is somehow not deployed on production. 

Note the other CORS  headers seem to be present and the CORS headers are also enabled in settings.

**Comment by eins78** [comment]
Yes, it is not deployed because we only had some small "patch" releases since this change. I'll include it in the next release.

**Comment by eins78** [comment]
will be part of v3.30.0

**Comment by DrTom** [comment]
@eins78 I am reopening this since the solution is not yet deployed and process studio which is monitoring this ticket is still waiting for it.

**Comment by eins78** [comment]
```
❯ curl -v https://medienarchiv.zhdk.ch/api | grep -i 'Access-Control-Allow-Credentials'
> GET /api HTTP/1.1
> Host: medienarchiv.zhdk.ch
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 27 Aug 2020 06:30:33 GMT
< Server: Aleph/0.4.4
< X-Content-Type-Options: nosniff
< Referrer-Policy: no-referrer,strict-origin-when-cross-origin
< Strict-Transport-Security: max-age=31536000
< Content-Security-Policy: upgrade-insecure-requests
< Access-Control-Allow-Credentials: true
< Content-Type: application/json-roa+json; charset=UTF8
…
```
