### ISSUE TITLE
Upgrade PostgresSQL Before 2021-02

### ISSUE THREAD

**Issue by DrTom** [Madek/madek#254]
Madek Postgresql runs on 9.5 which ends 2021-02. 

Discuss how and when we do the upgrade.

Leihs runs on 10 but maybe we want to keep both on the same version.

**Comment by DrTom** [comment]
Some further investigation: PG10 seems to work both with older stuff and some hacks required to import older dumps in PG>=11. Since leihs is on PG10 we should  consider to just upgrade Madek to PG10.

**Comment by eins78** [comment]
@DrTom just to be sure, when we upgrade from v9 to v10 the backups previously made with v9 will still possible to import? If so, this seems like a rather simple upgrade (just with a full manual system test to be sure, like we always do with larger dependency upgrade)

**Comment by DrTom** [comment]
Yes, backups from 9.x will restore into 10.  They will also restore into 11 and 12 but you need to do some hacks (delete the public schema before you restore) and you need to avoid some options of `pg_restore` which unfortunately we use. Plus the other way round, dumps from 11x and 12x can not be used with pg_restore of older versions (9.x sure not 10 maybe). I started to update deploy to upgrade PG.

**Comment by DrTom** [comment]
https://github.com/Madek/madek/issues/256
