### ISSUE TITLE
admin ui: make timezone configurable

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#255]
`app_settings.time_zone` [was introduced](https://github.com/Madek/madek-datalayer/commit/7916a1d7593947c3899a0c361b5d55e35eb7b3a1) and defaults to `Europe/Zurich`, but it can only be edited in the DB.
Should also be edited in admin UI. Needs validation against `tzdata` to check for valid zone name.
(NOTE: server and DB are on UTC, this setting is only used for displaying dates in the UI)

**Comment by phoettli** [comment]
wird nicht umgesetzt
