### ISSUE TITLE
optional select in core field „Copyright notice“

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#258]
The core field "Copyright notice" should have possibility to optionally select predefined value(s).

Default value:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/42544602/87339489-fb235200-c546-11ea-8369-d62acb9d7178.png">

Reselect default value:
![image](https://user-images.githubusercontent.com/42544602/87339527-08d8d780-c547-11ea-984d-bb1699488d14.png)

note:
no impact on other instances (HSLU, hfg)

**Comment by eins78** [comment]
- In the Admin Panel > Settings, under "Copyright/License Defaults", add a new setting "list of copyright notice templates" (array of strings).

- In the UI, make a new Input for MetaDatumText that this list of inputs and presents it like an autocomplete. Visually it should look like above (not like keywords). Internally it should work like the Input for a fixed keyword with only a few choices, meaning all the choices are already included in the "meta datum edit presenter", and there is no Ajax to fetch them.

**Comment by phoettli** [comment]
@michalpodlecki 
- Selection of values is perfect! (Copyright Notice Templates)

- I'am missing the possibility of setting the default value:
![](https://user-images.githubusercontent.com/42544602/87339489-fb235200-c546-11ea-8369-d62acb9d7178.png)
Where can I set it?

**Comment by phoettli** [comment]
ok on STAGING
