### ISSUE TITLE
User aus Frontend entfernen & korrekte Trennung User/Person

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#260]
1. User darf in öffentlichem Frontend nicht ausgegeben werden. 
2. "Person" ist Metadatum und kann keine Handlungen vornehmen. Handlungen werden durch User vollzogen.

a) ~in Listenansicht "Verantwortlicher Nutzer" (sic!) entfernen~ _erledigt_
![image](https://user-images.githubusercontent.com/42544602/87569901-208b9980-c6c8-11ea-9d79-a0c4cc4a30bf.png)
=> Bereich z.B. über Kontext frei bestückbar machen... 

b) Im Tab "Nutzung" die falsch als Person dargestellte Bubble entfernen und User ausgeben ohne Bubble (öffentlich nicht sichtbar)
![image](https://user-images.githubusercontent.com/42544602/87571076-c8ee2d80-c6c9-11ea-87b1-a006b427ff96.png)
_==> bisher nur Bubble entfernt_

Anmerkung:
Im Tab "Berechtigungen" ist die Anzeige korrekt (User ohne Bubble)

**Comment by eins78** [comment]
Umgesetzt (fast) wie beschrieben. Hinweise dazu:

> 1. User darf in öffentlichem Frontend nicht ausgegeben werden.
> 2. "Person" ist Metadatum und kann keine Handlungen vornehmen. Handlungen werden durch User vollzogen.

Es wird in der Oberfläche **nie** der Name eines Nutzers angezeigt – immer nur die _zugeordnete Person_ (die einen anderen Namen haben könnte).

Zu den Bubbles:

Der Unterschied in der Darstellung mit oder ohne "Bubble" ist lediglich der Link auf die Personenseite. Bei den Berechtigungen wäre es eher störend, daher ist es dort nur Text; an anderer Stelle ist es gut den Link zu haben denn dort ist auch die Personen-ID enthalten. Personen mit gleichen Namen können dann nicht mehr unterschieden werden.

> b) Im Tab "Nutzung" die falsch als Person dargestellte Bubble entfernen und User ausgeben ohne Bubble (öffentlich nicht sichtbar)

Sie oben – Nutzer werden bisher immer durch ihre Person repräsentiert. Unabhängig von der Bubble wäre es eine grundlegende Änderung hier nun den Nutzer-Namen zu zeigen, denn dieser ist bisher auch für eingeloggte Nutzer nirgends sichtbar (ausser Admins).

> a) in Listenansicht "Verantwortlicher Nutzer" (sic!) entfernen

Damit wird eine vorhandene, früher einmal spezifische Funktion entfernt. Die Namen verschwinden damit noch nicht aus der Oberfläche, sie können noch im Berechtigungs-Filter gesucht/ausgewählt werden.

**Comment by phoettli** [comment]
ok, kleines Missverständnis mit Teilumsetzung.
Die Umsetzung bis hierhin ist aber gut und hilfreich, kann also bleiben:
- Entfernter Eintrag in der Listenansicht. (Datenschutzkollision behoben.)
- Bubbles entfernt im Tab Nutzung (sichtbare Unterscheidung Person als Metadatum und "User" mit Aktionsverhalten)

Wenn ich dich richtig verstanden habe, ist weiterhin unter Verantwortliche Person und im Tab Nutzung die Person aufgeführt (einfach nicht als Bubble). Nun sollte also an beiden Stellen der User mit seinem Namen aufgeführt werden, damit da nicht versehentlich ein anderer Name "reinrutscht", wenn der Personennamen mal verändert wird(ToDo).
Dann ist die Trennung Person/User aus meiner Sicht perfekt.

Issue eilt nicht, Teil vom geplanten Projekt Userbereinigung o.ä.

**Comment by phoettli** [comment]
@urs-van-binsbergen Orte, die Usernamen enthalten, die mir grad einfallen (ohne Anspruch auf Vollständigkeit):
Webapp
- angezeigter Login-Name (wenn eingeloggt)
- Seite Berechtigungen (ME & set)
 - Verantwortlichkeit
 - Single User Berechtigungen
- Tab Nutzung
 - Verantwortlichkeit
 - Letzte Änderungen
- (Arbeits-)Gruppenansicht: enthaltene User (https://staging.madek.zhdk.ch/my/groups/ffe19fb1-943a-4ed6-af8b-b29f52bc5e55)
- Arbeitsgruppe bearbeiten: Userauswahl (.../edit )

Admin App
- Delegations (enthaltene Einzeluser)
- API-Clients (Responsible User)
- Media Files-Listenansicht (Uploader)
- Media Entries Listenansicht (Responsible Person)
- Media Entries Detailansicht resp. User & Creator (Kombi aus User und Person)
- Sets Listenansicht (Resp. User)
- Drafts (wohl gefilterte Liste von MEs siehe dort)


**Wichtig: im Frontend darf ohne Login kein Usernamen zu sehen sein !**

**Comment by phoettli** [comment]
Beobachtung für @urs-van-binsbergen aus der User-Kollision #512

> alte Person löschen geht nicht `ForeignKeyViolation`. Beim User die Person-UUID entfernen ebenfalls nicht `NotNullViolation`.
> Hab jetzt den alten User inkl. Person gelöscht.

**Comment by urs-van-binsbergen** [comment]
@phoettli Ich habe habe den Stand gemerget, der ist dementsprechend auf TEST deployed. Das umfasst natürlich auch #510 (bzw. #260 und #510 bilden eigentlich eine Einheit). 

Um die ganze Sache zu testen, änderst du am besten den Namen deines Users oder deiner Person leicht ab, so dass sie unterscheidbar sind. Im Admin kann man die neuen Felder User First- und Lastname sehen und bearbeiten. Ansonsten gibt es wohl keine sichtbaren Änderungen.

**Comment by phoettli** [comment]
wenn ich einen User anlege in der Admin-App (Vorname & Nachname eintrage) bleibt der Benutzername im Usermenü leer. 
<img width="250" alt="image" src="https://github.com/Madek/Madek/assets/42544602/094c2bed-d7df-4e34-a452-0e52bcb714a5">

Möglicherweise wird vom Erstellungsformular der Name nicht übernommen.
Name bei der Person ist korrekt....
<img width="1075" alt="image" src="https://github.com/Madek/Madek/assets/42544602/b28eabde-3188-45b5-b262-023eb096a5a1">

**Comment by urs-van-binsbergen** [comment]
f7909deb32fb54656977b4427dc967fd8d212306
