### ISSUE TITLE
Einsatzzweck Meta-Key-Typ Media-Entry

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#265]
Wozu genau ist der Metadaten-Typ _Media-Entry_ gedacht?

<img width="813" alt="image" src="https://user-images.githubusercontent.com/42544602/96022241-db0a7400-0e50-11eb-87ae-379bdf65c9fb.png">

- Für Versionierung kann nur ein Verweis eingetragen werden, ev. gibt es alte, neue UND andere Version
<img width="143" alt="image" src="https://user-images.githubusercontent.com/42544602/96022983-06419300-0e52-11eb-8373-fe9e354c80b9.png">

- Der Verweis-Typ kann ich nicht auswählen (z.B. Keywords), sodass immer die selben Bezeichnungen verwendet würden
- Für Verwandtschaft macht keinen Sinn, da nur ein Link verfügbar

**Comment by eins78** [comment]
> Für Versionierung kann nur ein Verweis eingetragen werden, ev. gibt es alte, neue UND andere Version
> Der Verweis-Typ kann ich nicht auswählen (z.B. Keywords), sodass immer die selben Bezeichnungen verwendet würden

Es soll einen Meta-Key pro "Verweis-Typ" geben, mit eigenen Labels etc.

Im Core-Vokabular ist schon ein Key drin (noch nicht Teil von einem Release, kann noch angepasst werden), der in der Weboberfläche entsprechend markiert wird: https://test.madek.zhdk.ch/vocabulary/madek_core#is_new_version_of
Das kam aus der FAIR-Data Anforderung, dass man in den Metadaten von neuen Versionen markieren kann, dass hiermit eine (möglicherweise inzwischen eingefrorene) ältere Version ersetzt wird. Es wird dann auf der Seite der alten Version ein Hinweis/Link auf die neue Version.

> Für Verwandtschaft macht keinen Sinn, da nur ein Link verfügbar
Wenn Verwandschaftsbeziehungen unterstützen werden sollen, die mehrere Links erlauben sollen (z.B. "inspiriert von"), dann müsste der Metadaten-Typ entsprechend erweitert werden (entweder immer eine beliebig lange Liste, oder konfigurierbar ähnlich wie bei Keywords).
