### ISSUE TITLE
Email-Adressen Spam schützen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#266]
**Ausgangslage**
Email-Adressen in Feldern werden automatisch als Mailto-Links gerendert.
<img width="138" alt="image" src="https://user-images.githubusercontent.com/42544602/96581026-7b411c80-12d9-11eb-875d-0a0be18de13a.png">

**Problem**
Die Email-Adressen sind nicht vor Bots geschützt

**Lösung**
Adressen vor Bots schützen (scramblen ?).

**Comment by phoettli** [comment]
Max klärt mit Hendrik

**Comment by eins78** [comment]
Nach Rücksprache mit dem IT-Sicherheitsbeauftragten als nicht nötig erachtet.
