### ISSUE TITLE
Medieneintrag ersetzen (replace ME with same metadata and permissions)

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#269]
Title EN: New Feature – replace ME with same metadata and permissions

**Ausgangslage**
Hin und wieder kommt es vor, dass eine neue oder korrigierte Version von einem File hochgeladen werden muss.

**Problem**
Es müssen bei einer neuen Erfassung sämtliche Metadaten erneut eingegeben werden. Bei umfangreich erfassten Medieneinträgen ist das eine mühsame und zeitraubende Arbeit.

**Lösungsvorschlag**
Automatismus implementieren, bei dem z.B. während der Vervollständigung eines neuen Medieneintrages eine ID eingegeben werden kann und dann werden sämtlich Metadaten und Zugriffsrechte vom vorherigen Medieneintrag übernommen.
(oder ähnliche Lösung)

**Comment by michalpodlecki** [comment]
My idea would be to place the „update file” button in the upper right corner of the media entry edit page.

After user uploads a new file, the following steps will be performed:
- create a copy of a media entry with the same meta data and permissions, this copy will be remembered later as a previous version of the original media entry; advantage: collecting the history of a resource versions
- original media entry will receive the updated file and remembered ID of the previous version ~> ID of created copy

By creating a copy of a media entry we won’t need to struggle with changing IDs in the database.
The all queries will have to be updated to filter out previous versions of updated media entries with a file. It also applies to the API.

We could use the enhanced version of the feature https://github.com/Madek/madek/issues/187 that would enable us to remember the whole history of media entry versions.

**Comment by eins78** [comment]
> We could use the enhanced version of the feature #187 that would enable us to remember the whole history of media entry versions.

For this feature we could also add a MetaDatum, with the key `Madek_core:is_new_version_of`. Then its editable by the user (has pros and cons).

**Comment by michalpodlecki** [comment]
My estimation: in my opinion it should take no more than 5 days of work (40 hrs) to realize this feature. The crucial part would be to check/update the all corresponding sql queries if they return only the updated media entry.

**Comment by michalpodlecki** [comment]
Good to hear that @phoettli !
1. 👍🏻 
2. yes, it would be possible but what should happen when you upload more than one new file? Which of the new media entry should receive the custom URL?
3. It's in purpose (you've probably haven't seen the note on the bottom of the configuration section ;)), checking/unchecking checkboxes need some additional implementation.

I will provide the language keys and let you know.

**Comment by phoettli** [comment]
Translation File: https://github.com/Madek/madek-webapp/blob/mp/issue-269/config/locale/translations.csv#L306-L316

**Comment by michalpodlecki** [comment]
@phoettli translation key for action menu entry is available in line 539 here https://github.com/Madek/madek-webapp/blob/mp/issue-269/config/locale/translations.csv#L539

**Comment by phoettli** [comment]
Translations
[20210623_Translation-269.pdf](https://github.com/Madek/madek/files/6731911/20210623_Translation-269.pdf)

**Comment by phoettli** [comment]
one small suggestion:
![image](https://user-images.githubusercontent.com/42544602/126354759-bb8844d2-a6b8-4dca-993e-a5d67099f439.png)

DE: Weiter zu Meine Medieneinträge
EN: Continue to My media entries


everything else: OK auf `staging`
