### ISSUE TITLE
Default-Tab in Sets festlegen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#271]
### Ausgangslage
In Sets werden Contexte als Tabs angezeigt.

### Problem
Wenn spezielles Tab ausgewählt wird, z.B. Projekt, Werk oder Projektschaufenster werden Metadaten z.B. in diesem Tab eingefüllt. Nachfolgende User sehen aber nicht, dass in diesem Tab spezielle Angaben erfasst wurden, weil alle gleichberechtigt angezeigt werden, resp. die Priorisierung der Tabs ist über deren Reihenfolge definiert. "Set" enthält aber am wenigsten Metadaten.

### Lösungsvorschlag
Tabs können priorisiert oder deaktiviert werden. z.B.
- gewünschte(r) Tab(s) kann gewählt werden. Nichtgewählte werden ausgeblendet.
- Set-Vorschaubild und nachfolgender Inhalt wird ebenfalls im ausgewählten Tab angezeigt.

**Comment by eins78** [comment]
* pro set ein Tab als Default speichern, ähnl. "Darstellung speichern"
* überlegen ob ihnhalt in jedem kontext tab anzeigen (nicht nur 1.)
* nicht crash wenn es den kontext nicht mehr gibt / fkey

**Comment by phoettli** [comment]
Kann das allenfalls Michal machen?

**Comment by phoettli** [comment]
Question to @michalpodlecki 
I have a Set, choose "Project" as default tab and save my display settings.
Then I open the set url: https://staging.madek.zhdk.ch/sets/24b934e4-0ccf-4c55-b8f2-942901a447e8
all my settings are gone and the set opens with the first tab "set" selected.
How can I store the settings that other users will see my preferred tab?

**Comment by michalpodlecki** [comment]
@phoettli I investigated the issue and it turns out that the collection with ID=`set_summary` is hardcoded somewhere in the code and I missed it, because it is not included in test data I'm using on my local machine during development. I already have an idea how to fix that, will prepare solution tomorrow,.

**Comment by michalpodlecki** [comment]
@phoettli temporarily I set option in admin panel https://staging.madek.zhdk.ch/admin/app_settings/context_for_collection_summary/edit to empty value (it was set to `set_summary` Context ID), please check it now.

**Comment by michalpodlecki** [comment]
`Set` is a constant name for main tab/Context regardless of which Context is set in the setting section in admin panel mentioned above.

**Comment by michalpodlecki** [comment]
So the final reason for the issue wasn't hardcoded `set_summary` in the code, however it has lead me to the bug & solution :)

**Comment by phoettli** [comment]
Test war ok auf `test-blank`

**Comment by phoettli** [comment]
ok auf `staging`
