### ISSUE TITLE
zhdk: remove eternal superadmins

### ISSUE THREAD

**Issue by eins78** [Madek/madek#273]

**Comment by phoettli** [comment]
`zhdk_admin_ids: [`
  ~~10301, # susanneschumacher~~
  ~~162294, # birkweiberg~~
  182749, # tschank
  ~~186272, # cweckema~~
  189987, # mkmit
  ~~195509, # pkuederl~~
  196200, # malbrech
  158882, # lsotrug
\+ phoe
`]`

Michal und Rolf nehme ich manuell rein

**Comment by phoettli** [comment]
oh, und bitte den nicht mehr gebrauchten phiku-key entfernen in dem File.

**Comment by phoettli** [comment]
(testen erst auf `live` möglich)

**Comment by phoettli** [comment]
mich hast du vergessen :-D

> `+ phoe`

**Comment by eins78** [comment]
ah, das hatte ich gar nicht gesehen in diesem textblock… wird ergänzt.
