### ISSUE TITLE
Setting default language to english is broken

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#274]
Setting is now in the DB, but not all config files were cleaned up, so the DB setting is overwritten from those, resulting in default language German now matter what setting.

A quick fix reveals that some tests and/or code needs to be adapted as well

https://github.com/Madek/madek/commit/692e48350e805f77ca4f6047c8a2be0bac7e60e8

**Comment by phoettli** [comment]
Bug, der momentan nicht gefixt wird
