### ISSUE TITLE
Duplicate Previews: Find and Delete

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#275]
* roughly 25% of our media files have some kind of duplicated preview file. 
* can be found because `previews.filename` attribute is the same (but timestamps differ)
* to save manual work we could only cleanup images (only a third of the entries but most of the filesize)
* first export a list of all duplicates, so it can be spot-checked manually
* maybe: do automatic checks (are all duplicated previews byte-identical? if yes we can really just delete them without further research)

```ruby
# find entries with duplicated previews:
MediaEntry.joins(:media_file).where('media_files.media_type': 'video').map {|me| [me.id, me.media_file.previews.group_by(&:filename).map {|k,v| v.count}.max] }.select {|k,v| v.to_i > 1}
```

**Comment by phoettli** [comment]
wird mit MediaService behoben
