### ISSUE TITLE
Icon für Description verschwunden

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#276]
das (i)-Icon für die Feldbeschreibung im Edit-Modus ist verschwunden. Es wurde ersetzt durch ein Fragezeichen.
Bitte wieder zurück zum Icon.

![image](https://user-images.githubusercontent.com/42544602/101386801-f8dadf00-38bd-11eb-80d2-63d377119572.png)

Seit Release 3.30.1 ?

**Comment by eins78** [comment]
Das ist beim letzten Update der Icon-Font kaputtgegangen. Wie das passiert ist, kann ich nicht nachvollziehen, aber `.icon-question` heisst nun `icon-question2` – so subtil, dass es mir nicht aufgefallen ist im diff https://github.com/Madek/madek-webapp/commit/f626b67fd92a2ef3056fa48b727da31b215b50a8#diff-e7c4d8b875e18561404f967b621aab7040e31e07338cbb09bb4909fb484d330eR205

Wie es aussieht, sollte das aber einfach zu reparieren sein: einfach im source wieder zurück-benennen, dazu muss nicht die ganze Font neu exportiert werden. Für das nächste Mal, dass sie erweitert müsste man aber drauf achten bzw. im icomoo tool reparieren.

**Comment by phoettli** [comment]
OK auf `staging`
