### ISSUE TITLE
Formatierung About Page

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#277]
gibt es die Möglichkeit in der About Page
- Leerzeilen einzufügen
- 2. Hierarchie für Bullet-Liste einzusetzen

Die lange Liste ist extrem unübersichtlich, wenn alle Inhalte so gedrängt sind.
https://medienarchiv.zhdk.ch/about

**Comment by eins78** [comment]
Das CSS vom Madek ist sehr weit von den Styles für die übliche Darstellung von Markkdown-Inhalten (bzw. jeder Fliesstext…). Ich muss daher sehr viel überschreiben und habe es absichtlich minimalistisch gehalten weil das ein potentiell grosses Zeitgrab ist. Ich würde hier einen kurzen Text mit allen Beispielen sammeln die wir unterstützen wollen, dann kann ich das in einem Ruck einbauen.

@phoettli fallen dir noch mehr Beispiele ein oder reicht das unten?

---

# Überschrift erster Ordnung

## Überschrift zweiter Ordnung

### Überschrift dritter Ordnung

Ein Absatz.

Noch ein Absatz, es sollte genug Abstand unter und über diesem geben.

* eine bullet liste
    * mit 2. level
        * und 3. level

Noch ein Absatz, es sollte genug Abstand unter und über diesem geben.

1. eine nummerierte liste
    1. mit zweitem level
        1. und drittem level

Noch ein Absatz, es sollte genug Abstand unter und über diesem geben.

---

Ein Trennstrich ist über diesem Absatz

**Comment by phoettli** [comment]
## Ergänzungen:

(keine Linie unter H1 und H2)

[Ein Link](url)

<img width="112" alt="image" src="https://user-images.githubusercontent.com/42544602/103794814-7c1a5c80-5045-11eb-96e4-8d65ac51cf92.png">

Schrift normal, _kursiv_ und **fett**

**Comment by eins78** [comment]
Habe noch Blockquote und eine Lange Überschrift ergänzt, damit haben wir alles an üblichem Inhalt.

* Beispiel Markdown: https://raw.githubusercontent.com/Madek/madek-webapp/e1689a107b68791510f48ba9112236aab6e5255b/spec/_support/about-pages-example-content.markdown

* Beispiel von GitHub gerendert: https://github.com/Madek/madek-webapp/blob/e1689a107b68791510f48ba9112236aab6e5255b/spec/_support/about-pages-example-content.markdown

* Screenshot:
![Screen Shot 2021-04-20 at 13 10 56](https://user-images.githubusercontent.com/134942/115386616-e8c2fc80-a1d9-11eb-9a77-5dd69586ee95.png)

**Comment by eins78** [comment]
@phoettli Hab mal die `<br>`s rausgenommen (auf `test`), dann siehts so aus:

![Screenshot_2021-04-20 Medienarchiv](https://user-images.githubusercontent.com/134942/115401375-9b02c000-a1ea-11eb-835d-6b1268392bd8.png)

**Comment by phoettli** [comment]
@eins78
Von mir aus bitte gerne die Linien nach den H* entfernen, wie in Kommentar https://github.com/Madek/madek/issues/277#issuecomment-755413954
Wirkt für mich mehr trennend, als verbindend zum nachfolgenden Absatz, insb. wenn nur kurzer Text folgt, wie z.B. im Abschnitt Kontakt

Sonst aber cool, danke !

**Comment by eins78** [comment]
@phoettli ok, ohne Linien. kommt gleich mit der anderen Änderung zusammen.

**Comment by eins78** [comment]
![Screenshot_2021-04-20 Medienarchiv(1)](https://user-images.githubusercontent.com/134942/115416746-54b45d80-a1f8-11eb-8f71-435ea1885bce.png)

**Comment by phoettli** [comment]
perfekt! Dankeschön
