### ISSUE TITLE
Link zu Online-Hilfe in Description (Edit modus)

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#284]
### Ausganglage
wir haben im Wiki eine umfassende Online-Hile mit vielen Beispielen erstellt.

### Problem
Der Aufwand, die treffenden Beispiele in den Hilfe zu finden ist hoch.

### Lösung
In den Beschreibungsboxen (über den (i)-Button erreichbar) eine Linkmöglichkeit einfügen. Der Link sollte in neuem Tab öffnen.
![image](https://user-images.githubusercontent.com/42544602/101840305-23d66480-3b44-11eb-9b9d-2dcb7c9c7d2e.png)

**Comment by eins78** [comment]
solution:
- [ ] new field for meta_keys and context_keys: "documentation_url"
- [ ] field overiddes like hint/description/etc
- [ ] link target for the `i` icon is this URL
- [ ] hover bubble functionality stays as is, but last line is added "click link for details

**Comment by phoettli** [comment]
Test war ok auf `test-blank`

**Comment by phoettli** [comment]
aktueller Stand unklar:
- ev. fertig
- Stand archäologisch ausgraben (Urs)
- checken ob für beide Sprachen korrekt implementiert (Urs)
- schätzen

**Comment by urs-van-binsbergen** [comment]
- Ausgangslage ist folgender Branch: https://github.com/Madek/Madek/tree/mfa/mp/issue-284 (den hat Max aufgrund Michals' Branch erstellt, mit Rebase auf den damals aktuellen `master`-Branch und einer kleinen Korrektur an einem Migrations-Skript)
- Ich Habe diesen auf den Stand von `master` von heute aktualisiert (`uvb/issue-284`)
- Alles im GUI getestet. Alles gut. Funktioniert in beiden Sprachen korrekt. 
- [ ] 2 Specs sind rot: https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/a3d85541-55b4-44cc-afd7-d9cc53d0057e (diese waren in Michals Original-Branch grün)
