### ISSUE TITLE
Statische Seite für Datenschutz und Nutzungsbedingungen

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#285]
### Ausgangslage
Die Nutzungsbedingungen sind beim ersten Login sichtbar.

### Problem
Die Nutzungsbedingungen sind nur auf einer externen Site einsehbar (Wiki), aber nicht direkt aus dem Medienarchiv.
Die Datenschutzerklärung fehlt ganz.

### Lösung
zusätzliche statische Seiten erstellen analog About-Page für:
- Nutzungsbedingungen (wie in DB schon vorhanden, letzte Version)
- Datenschutzbestimmungen (frei MD-editierbar wie About-Seite)

**Comment by eins78** [comment]
tech notes: allow list of pages under `/about/$page_name`. multi-language. in the DB it can just be a PG hash or array of stuff, we dont need complicated tables because the number of pages will be small and change infrequently.

```ruby
about_pages = [
  { page_name: 'privacy', content: { de: "# Datenschutz\n\Nehmen wir sehr wichtig", en:"# Privacy\n\Is very important to us" } },
  { page_name: 'test', content: { en: "just english" } }
]

**Comment by phoettli** [comment]
it looks pretty nice !
But language selector doesn't work for me (on `test`. I get german text also on the english page... /about/cookies
@eins78 or is the parameter `?lang=en` needed in the link?

**Comment by michalpodlecki** [comment]
@phoettli After you choose the english language from the selector, `?lang=en` should be present in the URL. Please check it one more time 🤔 
German: https://test.madek.zhdk.ch/about/cookies
English: https://test.madek.zhdk.ch/about/cookies?lang=en

**Comment by phoettli** [comment]
ok on `staging`
