### ISSUE TITLE
Delegations auch als Workflow-Besitzer wählbar

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#286]
Als Workflow-Besitzer müssen auch Delegations (#206 ) ausgewählt werden können

**Comment by phoettli** [comment]
https://github.com/Madek/madek/issues/206

**Comment by eins78** [comment]
(was closed by accident)

**Comment by eins78** [comment]
@phoettli can you please describe the use case, scenario and/or reason for this feature? There are some tricky details to be resolved before this can be merged. Maybe it should be part of the next release.

**Comment by phoettli** [comment]
Use Case: 10 Personen arbeiten in Forschungsprojekt, eine lädt Medien hoch, eine verschlagwortet, eine kontrolliert, verschiedene Arbeiten mit den Medien. Es kommt eine neue Person dazu etc. diese Personen und Mutationen müssen alle während dem Lauf des Forschungsprojektes auch im Workflow angepasst werden. Mit Delegations einfacher zu lösen.
Zugriffsrechte-Einstellungen werden ja erst mit Abschluss appliziert...

Ev. bräuchte es aber auch im Workflow eine Ergänzung, damit auf neu hochgeladene Daten ein Grundset an Zugriffsrechten und Daten hinzugefügt werden, zusätzlich zu den Abschlusseinstellungen.

**Comment by eins78** [comment]
@phoettli Funktioniert so (minimal) wie besprochen. Weil ich selber kurz drüber gestolpert bin: Beim testen darauf achten, dass alle User die per Delegation (oder direkt) Besitzer sind, alle aber *auch* in der Beta-Gruppe sein müssen (es kommt dann eine "nicht berechtigt" Fehlermeldung, die man auch für nen Bug halten kann…)

**Comment by phoettli** [comment]
für die Delegations in den Permissions habe ich separates Issues erstellt: https://github.com/Madek/madek/issues/302

**Comment by phoettli** [comment]
OK on `staging`
