### ISSUE TITLE
Workflow default fields: missing Roles

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#296]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/42544602/105062476-ecc86c80-5a7a-11eb-8dcc-9c9fd42ccbf4.png">

**Comment by phoettli** [comment]
does still not work on `staging`

![image](https://user-images.githubusercontent.com/42544602/106648094-1a8bd600-6590-11eb-9013-e9068380fd0a.png)

**Comment by eins78** [comment]
@phoettli it only applies to newly created workflows, the settings of existing ones stay the same.

<img width="617" alt="Screen Shot 2021-02-02 at 20 07 29" src="https://user-images.githubusercontent.com/134942/106649814-62abf800-6592-11eb-8a05-a2740ce5fcb0.png">

**Comment by phoettli** [comment]
aha! Interessante Info :-D

na dann: ok auf `staging` :)
