### ISSUE TITLE
Metadata-Search also for Meta Key

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#297]
### Ausgangslage

Die Suche in den Metadaten ist nur nach ID, ME-ID, Set-ID, String und Meta-Typ möglich.

### Problem
Eine Suche nach Meta Key ist nicht möglich.  Hin und wieder ist eine Suche nach allen vorhandenen Inhalten in einem bestimmten Meta-Daten-Feld gefragt.

### Lösungsvorschlag

Suche auch nach Meta Key ermöglichen
![image](https://user-images.githubusercontent.com/42544602/105996731-05eca100-60ab-11eb-8ac1-9734ce2075e2.png)

**Comment by eins78** [comment]
I am amazed at this omission, but its simple to do.
Existing spec to be extended: https://github.com/Madek/madek_admin-webapp/blob/298f3f791eb7d69ee665af734fcf7f954e0f3e02/spec/features/meta_datums_spec.rb#L22-L32

**Comment by phoettli** [comment]
OK auf `staging`
