### ISSUE TITLE
Workflow: Abschliessen geht nicht, Urheberrechtshinweis nicht vorhanden in Unter-Sets

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#303]
Wenn ein Workflow Unter-Sets enthält, wird beim Abschliessen auf den fehlenden Eintrag im Feld _Urheberrechtshinweis_ hingewiesen. Dieses Feld gibt es aber nicht für Sets!

![image](https://user-images.githubusercontent.com/42544602/108730276-a9ef2e00-752b-11eb-8dc2-c16806b164fa.png)

**Comment by eins78** [comment]
Konnte es teilweise reproduzieren, der Bug ist subtil anders. Kaputt ist die Anzeige und Validierung der Workflow-Pflichtfelder als solche, d.h. bei den "Prüfen"- und "Ausfüllen"-Schritten wird es nicht rot markiert oder nicht als Fehler gewertet. Deswegen kommt die "harte" Fehlermeldung beim Abschluss, denn dieser sollte eigentlich noch nicht stattfinden dürfen.

Es liegt also nicht daran, dass "Urheberrechtshinweis" nicht auf Sets angewendet werden könnte (denn das geht, vielleicht verwechselt mit dem Medienarchiv-Metakey [`copyright:copyright_usage`](https://test.madek.zhdk.ch/vocabulary/copyright#copyright_usage)).
Stattdessen wird moniert, dass die entsprechenden Felder nicht ausgefüllt sind (wie gesagt, dass das nicht vorher geschieht ist der eigentliche Bug).
Durch die Workflow-Default-Konfiguration ist wiederum garantiert, dass dieser Bug auftritt, denn dort hat `madek_core:copyright_notice` die Einstellungen "Pflichtfeld" aber nicht "Fixer Wert", d.h. es _muss_ individuell ausgefüllt sein.

Workaround 1: Wenn alle Inhalte den gleichen Hinweis bekommen sollen, kann die Einstellung auf "Fixer Wert" gesetzt, und direkt dort ausgefüllt werden.
<img width="506" alt="Screen Shot 2021-02-22 at 17 21 16" src="https://user-images.githubusercontent.com/134942/108736944-61873e80-7532-11eb-9d3f-f0bf795defff.png">

Workaround 2: Beim "Ausfüllen"-Schritt manuell prüfen und alles ausfüllen

**Comment by phoettli** [comment]
Naja, dann sollten wir wirklich nochmal überlegen, ob die Felder nicht trennbar zwischen Set und ME sein sollten. Urheberrechtshinweis, aber auch Lizenz (Rechtsschutz) und Nutzungsbedingungen machen wirklich keinen Sinn auf Set-Ebene, sollten aber zwingend ausgefüllt werden auf ME-Ebene. Wenn man dies dann manuell überprüfen muss, ist das nicht sehr hilfreich.

**Comment by phoettli** [comment]
Ich habs nochmal überprüft mit Urheberrechtshinweis ausgefüllt für das Set. Jetzt hats geklappt.

**Comment by eins78** [comment]
* Jetzt: Bug wird gefixed.
* Mittelfristig: Wir wollen die "shared" Workflow-Settings trennen zwischen Feldern für Einträge und Sets (evtl. visuell gemeinsam dargestellt). Es gibt also intern 2 Listen von Feldern.

**Comment by phoettli** [comment]
Für Settings auftrennen habe ich neues Issue erstellt: https://github.com/Madek/madek/issues/308

**Comment by phoettli** [comment]
@eins78  still not able to terminate workflow with subset, now `copyright:license` and `copyright:copyright_usage` are missing. Both fields are not available in sets.

![image](https://user-images.githubusercontent.com/42544602/115446771-f8f9cc80-a217-11eb-85f1-3449b299ef6b.png)


![20210420_303_WF-terminate](https://user-images.githubusercontent.com/42544602/115446731-ebdcdd80-a217-11eb-99c8-4e9b3b911b57.png)

**Comment by eins78** [comment]
@phoettli Ich bekomme das irgendwie nicht so richtig reproduziert. Ich habs schon auf `test-blank` versucht mit den `prod`-Daten und frischen Uploads, aber wenn ich es auf ein Minimalbeispiel eindampfen will, dann kommt der Fehler nicht mehr.
Kannst du das nochmal versuchen, und genau Schritte aufschreiben? Im einfachsten Fall würde vielleicht ein  Screenrecording reichen.

**Comment by michalpodlecki** [comment]
@eins78 I've already reproduced the error and I'm aware of the source of the problem.

**Comment by phoettli** [comment]
it looks cool @michalpodlecki. Thank you !

**Comment by phoettli** [comment]
OK auf `staging`
