### ISSUE TITLE
DB: some keywords have `external_uris = NULL`

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#307]
As reported by HSLU: some keyword-pages crash, because `external_uris` is `NULL` (instead of an empty list). 
Medienarchiv also has 9 such keywords (out of 11150).

Examples:
* https://medienarchiv.zhdk.ch/vocabulary/keyword/47b66191-fc61-40a0-a728-a8cc0aede305
* https://portfoliodb.hslu.ch/vocabulary/keyword/9cc74f66-cd76-4cfb-ab54-7d0e95dabc24
* https://portfoliodb.hslu.ch/vocabulary/keyword/c81c3228-38a2-4c18-b0c1-4030cb9fdcb7

---

Workaround in DB: 

```sql
UPDATE "keywords" SET "external_uris"='{}' WHERE "external_uris" IS NULL;
```

--- 

TODO:
* [ ] add migration to fix this, and add a non-null-constraint so it cant happen again

**Comment by eins78** [comment]
als zwischenlösung nochmal den workaround auf Medienarchiv/prod ausgeführt `UPDATE "keywords" SET "external_uris"='{}' WHERE "external_uris" IS NULL;`

**Comment by eins78** [comment]
see also https://github.com/Madek/Madek/issues/234

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/1b00d670de5689918aab18b395468fbfaf8806f0
