### ISSUE TITLE
Person#show page shows "last name" for Groups

### ISSUE THREAD

**Issue by eins78** [Madek/madek#319]
https://madek.slack.com/files/U0HLAH57D/F01SJT2T4KG/20210329-falscherkey-willkommensseite.mp4

**Comment by eins78** [comment]
problem shown in the video:

![Screen Shot 2021-04-20 at 15 32 22](https://user-images.githubusercontent.com/134942/115404873-01d5a880-a1ee-11eb-9397-5f22ed60759d.png)

this is tricky to do "correctly", so i suggest to keep it simple
* People and Groups are the same entity so they use the same "template"
* This entire has "first name", "last name" and "pseudonym" fields 
* another bug: the pseudonym is never shown
* groups also have a pseudonym (in the example `DDK.alle`) but it would look weird

suggestion: just use a single "Name" field, with the same content that is used everywhere else to display the name (so the same as in  titles, "bubbles" etc)

group:

![Screen Shot 2021-04-20 at 15 29 29](https://user-images.githubusercontent.com/134942/115405089-38132800-a1ee-11eb-9d49-c72ba57a1390.png)

person:

![Screen Shot 2021-04-20 at 15 29 37](https://user-images.githubusercontent.com/134942/115405113-3f3a3600-a1ee-11eb-9126-7e00af7cd39c.png)

**Comment by eins78** [comment]
@phoettli was meinst du? es wäre schon umgesetzt: https://github.com/Madek/madek-webapp/commit/0a38fe55f086eb6699fe5180a56c34a12c0cbaa2

**Comment by phoettli** [comment]
@eins78 von mir aus ok
