### ISSUE TITLE
Vorschaubilder für Videos in API: welches entspricht Vorschau in Webapp?

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#323]
#### Ausgangslage

Snowflake soll für das Projektschaufenster der ZHdK-Webiste Videos auch als Projekt-Headerbild und Vorschaubilder zu den Videos ausgeben

#### Problem

Es gibt Videos, die in der API eine Vielzahl von Previewbildern ausgeben. Welches der Previewbilder entspricht der Ausgabe in der Webapp?

z.B.
- Medieneintrag: https://medienarchiv.zhdk.ch/entries/f1b37b21-c9b7-498c-a4dd-f3d6d7f2d2e5
- Preview-Liste in API: https://medienarchiv.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2F52fd01a4-d49c-40c8-bf6e-43cbd21f7395&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A
=> das passende zur Webapp ist erst in der dritten Serie (https://medienarchiv.zhdk.ch/media/5e18b762-ded0-4a81-8f83-c2c683e71162)

#### Lösung

- Kennzeichnung in API ?
- ungewollte entfernen ?
- ... ?

**Comment by DrTom** [comment]
@eins78 weiss es glaube ich auswendig wie das funktioniert; wir hatten das vor kurzem thematisiert. Wegen mir alle anderen gerne löschen. So wie es jetzt ist, passt das nicht mit den Zielen vom neuen Media-Service nicht zusammen.

**Comment by DrTom** [comment]
I believe this answers the Question: 

https://github.com/Madek/madek-webapp/blob/919ddd3b8f440084a88d685949416c471437e2f5/app/presenters/presenters/media_files/media_file.rb#L101-L116

**Comment by eins78** [comment]
* löschen geht erst mit dem neuen Media-Service
* @DrTom hat korrekt den code identifiziert. es ist ein simpler algorithmus, der aber bisher nur in der webapp umgesetzt wurde. d.h. es muss die gleiche logik nochmal implementiert werden, zu entscheiden ist wie und wo.
  * client-seitig, also bei snowflake (dann würden wir den algorithmus kurz in 1 satz beschreiben)
  * in der API (ticket für tom oder michal). habe noch nicht nachgedacht *wo* das stehen könnte, aber wird schon irgendwo hinpassen

**Comment by phoettli** [comment]
Aus meiner Sicht sehr sinnvoll, wenn das Previewbild auch in der API erkennbar ist.

- im ersten Schritt: per Auswahl-Algorithmus definiert
- im zweiten Schritt, sobald Previewbild durch Benutzer festgelegt werden kann: das Default-Bild resp. das vom Benutzer festgelegte falls vorhanden.

**Comment by phoettli** [comment]
> * löschen geht erst mit dem neuen Media-Service

@eins78 : bitte überlege mal, wie man die fehlerhaften Previews schon früher entfernen könnte. Wir verschleissen da zunehmend Speicherplatz und Nerven.

**Comment by phoettli** [comment]
@DrTom bitte die Vorgaben festlegen und Issue an Michal übergeben. Danke !

**Comment by DrTom** [comment]
Together with @phoettli we decided to put a Hack in the API: add a boolean value to each preview which marks the preview if this is used by the Madek UI/frontend. This is apparently not a good API design but it is quick solution and imho we need to change everything again with new `media_serivce` later anyways. Current suggestion for the boolean `used_as_ui_preview`, if there is a better name: I don't care much.

**Comment by eins78** [comment]
sound good! is suggest the name `is_poster_image`.

writing down some details to make sure I understood correctly.

the new value would be on the media-file resource, under the preview key?
https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2Fa4e36ef4-e4f0-462f-a84b-e37e04e0fa8d&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

example:

```json
{
  "media_type": "video",
  "previews": [
    {
      "id": "faa0b399-22e9-4388-b701-9efb6b9c8778",
      "thumbnail": "large",
      "is_poster_image": true
    },
    {
      "id": "82af3e79-c6e9-41f5-b7f0-7025b94a113f",
      "thumbnail": "large"
    }
  ]
}
```

I also think the API would be enhanced in this regard, once the `media-service` is taking shape. The structure should then be more like `collection-media-entry-arcs`, so it can be filtered and so on, but that would be too much change right now (https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fcollection-media-entry-arcs%2F%3Fcollection_id%3D8fe28871-c49e-47fb-bb7b-39a53f2ea8a9&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A).

**Comment by DrTom** [comment]
@eins78 something like `poster_image` was in the discussion. @phoettli argued later on a more generic name would be better since it could be used for other 'media'. Personally, I don't give a rolling donut.

**Comment by michalpodlecki** [comment]
@phoettli the working solution is already deployed to https://test.madek.zhdk.ch/. Please check it out and let me know about your impressions :) I've used `used_as_ui_preview` for the key name returned by API.

**Comment by phoettli** [comment]
hi @DrTom reicht es, wenn nur die verwendeten Bilder markiert sind? Oder sollten die nicht verwendeten mit `used_as_ui_preview: false` gekennzeichnet werden?
https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2F52fd01a4-d49c-40c8-bf6e-43cbd21f7395&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

**Comment by phoettli** [comment]
> the working solution is already deployed to https://test.madek.zhdk.ch/. Please check it out and let me know about your impressions :) I've used `used_as_ui_preview` for the key name returned by API.

thanks @michalpodlecki , looks cool. Would it be possible to mark all used preview images of all different sizes? (small, large, x-large...)

**Comment by eins78** [comment]
> > the working solution is already deployed to https://test.madek.zhdk.ch/. Please check it out and let me know about your impressions :) I've used `used_as_ui_preview` for the key name returned by API.
> 
> thanks @michalpodlecki , looks cool. Would it be possible to mark all used preview images of all different sizes? (small, large, x-large...)

@phoettli This question, and the naming of the key, make me think there is some general misunderstanding going on here. This ticket is only about the "Poster Image" used in the Player. This has nothing to do with the different sizes of previews, we only use the largest size to pick a poster image. It also has nothing to do with any other previews/thumbnails shown in the UI.

So, fro my perspective this problem is a "done" as it gets. We might need to check some edge cases (does it work/not crash for short videos that have only 0 or 1 frames to pick from?). And as i said, the key could be better named, but I dont really care about that.

How to quickly check/compare the results:
* GET https://test.madek.zhdk.ch/entries/f1b37b21-c9b7-498c-a4dd-f3d6d7f2d2e5.json?___sparse={%22media_file%22:{%22previews%22:{}}}
* returns a list of previews, there should be only 1 image
    ```json
    {"media_file":{"previews":{"images":{"large":{"content_type":"image/jpeg","size_class":"large","height":348,"media_type":"image","extension":"jpg",
    "url":"/media/bfbefdb0-026b-487a-bed9-0f484751b638"
    ```
* check API: https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2F52fd01a4-d49c-40c8-bf6e-43cbd21f7395&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A
* API marks the image with the same id as `used_as_ui_preview` (`bfbefdb0-026b-487a-bed9-0f484751b638`) -> correct! ✅

**Comment by phoettli** [comment]
@eins78 . Das ist tatsächlich ein Missverständnis. In der Webapp verwendet ihr mehrere Bildgrössen oder? Und die grösste Preview ist m.E. "x_large".
Wenn man schon Previews in der API identifiziert, wäre es dann nicht sinnvoll, alle grössen entsprechend zu markieren?

**Comment by eins78** [comment]
> Wenn man schon Previews in der API identifiziert, wäre es dann nicht sinnvoll, alle grössen entsprechend zu markieren?

Ist vielleicht einfacher nachher mündlich zu besprechen, aber wenn du mit "entsprechend markieren" meinst "als poster image für den video player markieren": Nein, das macht keinen Sinn, denn nur für die grösste Grösse trifft das überhaupt zu.

**Comment by eins78** [comment]
@michalpodlecki Please merge this as soon as possible, and also add a minimal documentation for the `Preview` resource (there is just a "TODO" right now). Just mention the newly added key as "experimental".

**Comment by michalpodlecki** [comment]
@eins78 will do that today in the evening

**Comment by phoettli** [comment]
@eins78 nochmal eine Verständnisfrage zur Grösse: das grösste ausgegebene Previewbild ist `x_large` (1024x...). Wird das hochgerechnet aus dem Posterbild 620x... ?
Weil ein HD-Video hat ja 1280x..., aber die Posterbilder haben dann nur 620x...?
- large (markiert): https://medienarchiv.zhdk.ch/media/bfbefdb0-026b-487a-bed9-0f484751b638
- maximum: https://medienarchiv.zhdk.ch/media/8b5f6265-6d90-4637-9ff3-80db9734b03b
- x_large: https://medienarchiv.zhdk.ch/media/f9819099-b3df-41bd-8e44-c13d51756fb3

https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-files%2F52fd01a4-d49c-40c8-bf6e-43cbd21f7395&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

(Auf der ZHdK-Website werden Videos mit ca 1000x563px ausgegeben...)

**Comment by eins78** [comment]
> @eins78 nochmal eine Verständnisfrage zur Grösse:

Wie ich gestern schon meinte, warum da "large" markiert ist und nicht, wie man erwarten würde, "original" kann ich nicht (mehr) nachvollziehen. Deine Frage ist im Grunde die gleiche. Um sie zu beantworten müsste ich nochmal einiges an code lesen und den Zencoder-Prozess beobachten/debuggen…

**Comment by phoettli** [comment]
>... and also add a minimal documentation for the `Preview` resource (there is just a "TODO" right now). Just mention the newly added key as "experimental".

@michalpodlecki where do I find the documentation for the new key?

**Comment by michalpodlecki** [comment]
@phoettli right here https://staging.madek.zhdk.ch/api/docs/resources/previews.html

**Comment by eins78** [comment]
@phoettli @michalpodlecki we just realized that the docs are not linked from the browser. It can be found via the above link, but to be correct we'd need to extend the JSON-ROA "relations".

**Comment by phoettli** [comment]
für mich ok auf ´staging´
