### ISSUE TITLE
Redirect to canonical URL loses lang param / Language switches back to german when media entry edit form is aborted

### ISSUE THREAD

**Issue by buergimi** [Madek/Madek#326]
Hi Max

steps to reproduce:
- open medienarchiv.zhdk.ch
- log in
- switch to english
- go to "my archive"
- open edit form of a media entry
- click on "Cancel"
- now I'm back to german

Besides: the tabs in the edit form are not translated to english.

Regards
Michi

**Comment by eins78** [comment]
I can not reproduce this. If I follow those steps, the link behind the "Cancel" button has a `lang=en` parameter, as it should. 

<img width="966" alt="Screen Shot 2021-05-28 at 11 31 33" src="https://user-images.githubusercontent.com/134942/119964830-e5294f00-bfa9-11eb-841e-6447f3543aab.png">


There is no other mechanism to persist the selected language except this parameter, so this kind of bug would be plausible, but no in this case. Same result when coming from the Dashboard, or using the edit button on the detail view.

The "untranslated" Tabs _are_ a problem, but the labels are not part of the app and should be translated in the admin UI: https://github.com/Madek/madek/issues/334

**Comment by buergimi** [comment]
Hi Max
Thanks for checking this out. I had another look at it, and I learned that the problem occurs with media entries with alias, only. Maybe there is redirection from GUID to alias which removes the query param `lang`?
Liebe Grüsse
Michi

**Comment by eins78** [comment]
> Maybe there is redirection from GUID to alias which removes the query param `lang`?

💡 thats it! the bug is not in the edit form, but in the redirect (so it affects all places where we use the UUID-based url instead of the canonical one).

```sh
❯ curl -i https://medienarchiv.zhdk.ch/entries/9b5fa1d7-3c61-46bf-986b-213ca52031d3?lang=en | grep Location
Location: https://medienarchiv.zhdk.ch/entries/nasa-iss
```
