### ISSUE TITLE
Certbot is taking the reverse proxy down

### ISSUE THREAD

**Issue by DrTom** [Madek/Madek#330]
Madek was just gone because of apache. The logs show that certbot stopped it. We might have to upgrade certbot or something. At least make certbot not do that in the middle of the day.

**Comment by DrTom** [comment]
We wait until @eins78 is back from vacation. I think I remember something.

**Comment by DrTom** [comment]
Some context I remember: certbot used to use apache to check and update certs. Then there was a bug in some version of certbot and the fix was certbot stops apache; opens on port 80; does its thing; restarts apache. Seems now that is broken. There might also be some nasty interaction with monit or something.

**Comment by eins78** [comment]
@DrTom I finally found the underlying problem a few weeks back (on some other servers) but did not remember it still affects Medienarchiv. Maybe there are also some old versions of certbot, the service and the timer installed…

* [ ] clean up the config, remove the "hooks" from 
* [ ] reinstall certbot with current packages and systemd unit/timer

**Comment by eins78** [comment]
@DrTom I purged `certbot` package and deleted `/etc/letsencrypt` and started from scratch with the simple settings that work on all other servers without issue.
I then ran `certbot renew --force-renewal` to verify that `apache2` does not hang anymore when the cert is replaced.
