### ISSUE TITLE
Fullscreen Player auch bei eingeschränkten Zusgriffsrechten

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#332]
### Ausgangslage

Videos können in Fullscreen abgerufen werden im Umweg über die embedded-Funktion:
https://medienarchiv.zhdk.ch/entries/e7dee8aa-7eaf-436a-ab2d-97f0c47b0443/embedded/

### Problem
Videos mit eingeschränkten Zugangsrechten können leider nicht in Fullscreen angezeigt werden. Es erscheint eine Fehlermeldung, auch wenn man berechtigt ist, das Video im Medienarchiv anschauen zu dürfen:
https://medienarchiv.zhdk.ch/entries/6d478e8f-4c27-4fb0-9b1b-c6b96cc5d112/embedded/

### Lösungsvorschlag

Videos auch mit beschränkten Zugangsrechten in Fullscreen zugänglich machen.
@eins78 schlägt vor:

- zusätzliches URL-Segment für diesen Use Case
- Hinweis bei fehlenden Zugangsrechten inkl. Link zu Medienarchiv-Login

**Comment by eins78** [comment]
einfachstmögliche version zeigt den ganz normalen login-screen (inkl. dem button oben rechts, mit dem man _nicht_ wieder zurück kommt).
wenn man den grossen grünen button in der mitte nutzt, kommt man nach dem AGW wieder auf die richtige seite.

3 varianten wie weiter:
1. gut so, wird mit angefasst wenn login allgemein verbessert wird
2. schneller hack um den button oben rechts auszublenden
3. noch etwas weiter umbauen und für die fullscreen-view auch "custom error pages" machen (beim embed player sind das die mit dem schwarzen-rauschen-hintergrund), dort ein loginform einzeln anzeigen

![Screen Shot 2021-05-31 at 16 08 25](https://user-images.githubusercontent.com/134942/120206032-f765f000-c22a-11eb-9b77-1a2dbf750a58.png)

---

ansonsten nur minimale anpassungen am style: es wird im gegensatz zu `/embedded` seitenfüllend. vielleicht bekomme ich noch auf die schnelle die schrift im titel ein bisschen besser skaliert, das wars dann aber auch schon.

![Screen Shot 2021-05-31 at 16 14 18](https://user-images.githubusercontent.com/134942/120206406-74916500-c22b-11eb-9f16-f0bd39a61382.png)

**Comment by phoettli** [comment]
> 3 varianten wie weiter:
> 
> 1. gut so, wird mit angefasst wenn login allgemein verbessert wird
> 2. schneller hack um den button oben rechts auszublenden
> 3. noch etwas weiter umbauen und für die fullscreen-view auch "custom error pages" machen (beim embed player sind das die mit dem schwarzen-rauschen-hintergrund), dort ein loginform einzeln anzeigen

ich bin für 1. sofort (hat da #278 keine positiven Auswirkungen?)
resp. 3. mittelfristig => neues Issue machen. 


> ansonsten nur minimale anpassungen am style: es wird im gegensatz zu `/embedded` seitenfüllend. vielleicht bekomme ich noch auf die schnelle die schrift im titel ein bisschen besser skaliert, das wars dann aber auch schon.

das ist OK so!

**Comment by eins78** [comment]
> ich bin für 1. sofort (hat da #278 keine positiven Auswirkungen?)

genau so meinte ich das. wird erstmal ausgeliefert wie im screenshot, und ich schreib in #278 noch dazu dass man diese view nicht vergisst (aber sollte eigentlich schon von alleine gut sein).

**Comment by eins78** [comment]
@phoettli https://test.madek.zhdk.ch/entries/9337a71f-93c7-480b-8e6c-8a37f8cd9143/fullscreen

**Comment by phoettli** [comment]
@eins78 lässt sich das Wort "Madek" rechts noch durch das korrekte Logo ersetzen?

**Comment by eins78** [comment]
oh, stimmt. die Medienarchiv-config muss noch angepasst werden 

https://github.com/Madek/madek-deploy/blob/122c82b5ff175f214e69b424434c6b636ba3e5fb/inventories/zhdk/group_vars/zhdk.yml#L40

**Comment by eins78** [comment]
logo config done in https://github.com/Madek/madek/commit/72ce25c54c6a90311069c01455a7ce5b55d95fc1

![Screen Shot 2021-07-19 at 19 14 21](https://user-images.githubusercontent.com/134942/126206496-4abd866c-4160-495c-87da-2943d3064f8c.png)
![Screen Shot 2021-07-19 at 19 14 08](https://user-images.githubusercontent.com/134942/126206508-cd43a467-5bf6-4370-ab31-5805df58cd76.png)

**Comment by phoettli** [comment]
OK auf `staging`
(super !!!!!)
