### ISSUE TITLE
Medienarchiv: Kontext-Namen übersetzen

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#334]
Die Namen Kontexte sind nicht übersetzt, diese tauchen u.a. im Edit-Formular als Tabs auf.

jetzt:

<img width="771" alt="Screen Shot 2021-05-28 at 11 37 24" src="https://user-images.githubusercontent.com/134942/119964376-70561500-bfa9-11eb-9036-8fa6ebb45646.png">

---

übersetzt:

<img width="793" alt="Screen Shot 2021-05-28 at 11 37 35" src="https://user-images.githubusercontent.com/134942/119964397-764bf600-bfa9-11eb-8d62-3b6158f4fc58.png">

---

<img width="1102" alt="Screen Shot 2021-05-28 at 11 37 14" src="https://user-images.githubusercontent.com/134942/119964428-7ea43100-bfa9-11eb-8733-ef86e923b5e7.png">

---

**Comment by phoettli** [comment]
@eins78 aso, wenn ich so schaue, ist keiner der Reiter übersetzt :)
Wo liegt denn die Übersetzung für "Alle Daten" ?

**Comment by eins78** [comment]
> wenn ich so schaue, ist keiner der Reiter übersetzt

ja, "Personen" war nur ein Beispiel

> Wo liegt denn die Übersetzung für "Alle Daten" ?


```csv
meta_data_form_all_data,Alle Daten,Alle daten,
```

https://github.com/Madek/madek-webapp/blob/74b52acb9b6ba0625319a3a08019c02407d37573/config/locale/translations.csv#L369

**Comment by eins78** [comment]
@phoettli Ich mache da einfach "All Data" draus, ja?

**Comment by phoettli** [comment]
im Browsen-Modus steht da "All metadata"

![image](https://user-images.githubusercontent.com/42544602/120307914-ce4d6a00-c2d3-11eb-8564-32190a6b21cb.png)

**Comment by eins78** [comment]
> im Browsen-Modus steht da "All metadata"

gut, dann so.

**Comment by phoettli** [comment]
erledigt
