### ISSUE TITLE
Hinweis auf weitere Filter in Sets

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#336]
### Ausgangslage

Die Suche bietet diverse Filtermöglichkeiten, um ein Suchergebnis einzuschränken, eine mächtige Funktion für zielführende Suchergebnisse.

### Problem

Die Filter sind an mehreren Stellen ebenfalls verfügbar, so z.B. in Sets. Leider ist nicht ersichtlich, dass man z.B. in einem Set erst in der Auswahl "Medieneinträge" oder "Sets" wählen muss, damit die ausführlichen Filter sichtbar werden.

### Lösungsvorschlag

Pragmatischer Vorschlag.
Unterhalb des Suchfeldes im Filter einen Hinweistext anbringen:

![image](https://user-images.githubusercontent.com/42544602/121023029-2e944e00-c7a3-11eb-95b4-b908577a18b3.png)

DE: Wählen Sie in der Aktionsleiste [Medieneinträge](nix) oder [Sets](nix) aus, um weitere Filterkriterien anwenden zu können.
EN: Please select [Media entries](nix) or [Sets](nix) in the Action bar to see more filter options.

**Comment by eins78** [comment]
@michalpodlecki "Medieneinträge" und "Sets" should have a link that sets the correct filter (same result like clicking on the buttons in the top bar). Look for `setParamsInUrl` helper (or similar).

**Comment by phoettli** [comment]
ok auf `prod`
