### ISSUE TITLE
Aktionen Menü in einem Set, Menüpunkt: Set erstellen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#339]
_EN: Set view: new Menue entry "create set" in Action manue._

Wenn man in einem Set ist, gibt es keine Funktion ein Unterset zu erstellen. Das Set lässt sich nur im Zusammenhang mit Medieneintragzuordnung erstellen. Das Set muss danach in einem weiteren Schritt dem übergeordneten Set zugewiesen werden.

Einfacher wäre, im Set direkt ein Unterset zu erstellen. Und danach Medieneinträge dem erstellen Set zuzuweisen.

![image](https://user-images.githubusercontent.com/42544602/122248706-8c721580-cec8-11eb-987a-0e5301eebc13.png)

**Comment by eins78** [comment]
@phoettli UI sieht nun so aus, finde die abtrennung gut weil es eine andere art aktion. 
wording und übersetzungen muss man ja noch generell anschauen (heisst es unterset bzw "child", ist das konsistent, soll der menupunkt dann auch so?)

![Screen Shot 2021-12-06 at 15 49 35](https://user-images.githubusercontent.com/134942/144867620-915a506d-ef63-49da-bda3-759b100a3dbf.png)

**Comment by phoettli** [comment]
cool !
Reicht nicht "Set erstellen"? Haben wir denn "Unterset" schon mal an einem anderen Ort eingesetzt?
Für mich wäre die Funktion logisch genug.
Sonst müsste man wohl schreiben: "Neues Set in diesem Set erstellen." – scheint mir sehr umständlich!

**Comment by phoettli** [comment]
very nice !

the only point here, the feature should show up only in sets. The function makes now sense in the my archive views:

![image](https://user-images.githubusercontent.com/42544602/146190201-f5049458-458b-4528-b654-d062a7f51a0e.png)

- incomplete media entries
- media entries
- sets
- MEs joint responsibility
- sets joint resp.
- Last imports
- Favorite MEs
- Favorite Sets
- My entrusted MEs
- My entrusted Sets

**Comment by phoettli** [comment]
Test war ok auf `test-blank`

**Comment by phoettli** [comment]
ok auf `staging`
