### ISSUE TITLE
Auszeichnung bestimmter Sets als "offizieller Inhalt"

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#341]
## Ausgangslage

Die Sets im Medienarchiv sind alle gleichwertig. Sie können beliebig verschachtelt und verbunden werden.

## Problem

Man sieht den Sets nicht direkt, ob sie "offiziell" eingerichtet sind, quasi einer bestimmten Sturuktur folgen oder einfach beliebig entstanden sind. Nun sollen Abschlussarbeiten im Medienarchiv "offiziell" abgelegt werden. Dafür wird vom Archiv eine Struktur vorgegeben, die der ZHdK-Struktur entspricht. Ein User kann aber nicht erkennen, wann er sich in der offiziellen Struktur befindet und wann er sie verlässt.

## Lösung

Kennzeichnung von offiziellen Sets, erkennbar für User. Funktion nur für Admins verfügbar.

## Klärungsbedarf

- betrifft dies nur Sets? – Ja, Medieneinträge sind nicht gekennzeichnet, da von Usern verwaltet
- Wer kann die Sets entsprechend kennzeichnen? – Nur Admin
- Verschachtelung hat keine Relevanz? – keine Vererbung, muss separat markiert werden.
- Wie sollte es aussehen? Label, Icon, Farbe? – keine Vorzüge, gut erkennbar sollte es sein.
- Müssen mehrere Auszeichnungen möglich sein? – im ersten Schritt nur eines nötig, ev. sinnvoll erweiterbar anzustreben.
- Auswirkungen auf Zusammenhänge? – muss nicht sein, wenn Auszeichnung erkennbar.
(nicht vergessen! Thumbnail Status Badge)

**Comment by phoettli** [comment]
Geschütztes Vokabular erstellen mit entsprechenden Keywords

**Comment by phoettli** [comment]
Den Meta-Key habe ich erstellt: https://medienarchiv.zhdk.ch/sets/8f3f6dfe-7804-4b0a-b6d0-8a8582126d09/more_data
Seltsamerweise wirft das Aufrufen der Key-Page einen Fehler:

![image](https://user-images.githubusercontent.com/42544602/173355453-73223d16-9b36-4bf8-9304-c6c64fc7edba.png)

@eins78 kannst du dagegen etwas tun?

**Comment by eins78** [comment]
@phoettli ist behoben. war schon wieder der https://github.com/Madek/Madek/issues/234

**Comment by phoettli** [comment]
Dankeschön !
