### ISSUE TITLE
Safari in Big Sur macht Probleme mit Videos

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#356]
Manuel von Paul berichtet:

~Wenn~ im Safari von Big Sur (11.5.2 mit Safari 14.1.2) ~die Experten Tools eingeschaltet werden,~ werden automatisch Experimentelle Webm-Funktionen aktiviert, die Probleme mit gewissen Medienarchiv-Videos machen.

Funktionen:
- Experimentelle Funktionen > WebM MSE parser
- Experimentelle Funktionen > WebM format reader
(Default)

Beispiel das scheitert: https://medienarchiv.zhdk.ch/entries/4a9ed80f-ea4a-45d9-849f-76594903c955/embedded?height=360&width=640

Was ist zu tun?

**Comment by phoettli** [comment]
<img width="1152" alt="image001" src="https://user-images.githubusercontent.com/42544602/132357629-191dd291-011d-45d4-aba9-feb4ce3b3ba8.png">

**Comment by phoettli** [comment]
manuel schreibt weiter

> Wenn ich die beiden experimentellen webm-Funktionen deaktiviere, funktioniert es, ja.

> Was aber nicht heisst dass das Problem nur Leute mit Entwickler-Tools & Big Sur betrifft. Weil Entwickler-Tools im Safari kann man nicht installieren, nur anzeigen / ausblenden in den erweiterten Einstellungen. Leute ohne Entwickler-Tools haben somit die beiden experimentellen webm-Funktionen standardmässig aktiv.

> Ich habe nun übrigens schon 3 Leute innert einer Woche mit dem Problem, da wir oft auf Paul-Hilfeseiten mit eingebetteten Medienarchiv-Videotutorials referenzieren. Ich hoffe ihr seid da dran?

**Comment by eins78** [comment]
Bin dran, erstes Debuggen wirft nur noch mehr Fragen auf. 
* es geht wenn das HTML von `localhost` kommt (unklar warum, es gibt keine Netzwerk/policy-spezifischen Fehlermeldungen die das erklären können)
* es geht in iOS 15 Beta (unklar warum, ist auch Safari 14.x)
* es geht auch nicht in macOS Monterey Beta (also wie Bug Sur, aber nicht wie die Geschwister-iOS version…)

Einzige (vielleicht) gute nachricht ist, dass ich keine Fehlerberichte im Netz finde bzgl. video.js + Safari 14.1 bzw webm. 
Ich werde also mal probieren, ob es geht wenn wir die neueste Video-JS version nehmen (wie aufwändig das upgrade dann wird kann ich noch nicht sagen).

**Comment by eins78** [comment]
Mehr schlechte Nachrichten und Weirdness:
* Es liegt nicht am Videoplayer, Safari wirft generell einen Fehler wenn ein `webm` vom Medienarchiv-Server geladen und abgespielt wird (ex. https://test.madek.zhdk.ch/media/4670c653-4883-449c-9a77-6a4240d4dda5)
* Von einem anderen Server aus geht das aber(!)
* In Firefox und anderen Browsers gibt es aber keinen Fehler, `webm` funktioniert seit vielen Jahren und nichts hat sich dort geändert
* lt. macOS Console wirft Safari selbst einen Fehler, das bedeutet es ist ein Bug im Browser in den wir da reinlaufen

Neuer Plan: Mit dem Testserver probieren, ob wir am Webserver etwas anders konfigurieren können (eher Workaround als Lösung, aber Safari können wir nicht reparieren). Je nachdem was da rauskommt mache ich ein Ticket bei Apple.

**Comment by eins78** [comment]
🎉 Problem identifiziert und Lösungsidee abgeleitet!

Es gibt einen **Bug in Safari**: `webm` kann nur abgespielt werden, wenn die URL mit `.webm` endet.
Das kann

**Comment by eins78** [comment]
fixed in https://github.com/Madek/Madek/commit/26ad5ad3f8c1a6d3437fc086d605838f5b464345

**Comment by eins78** [comment]
released in https://github.com/Madek/Madek/releases/tag/v3.32.1
deploy to Medienarchiv https://medienarchiv.zhdk.ch/release#3.32.1

**Comment by phoettli** [comment]
User bestätigt: Videos laufen wieder!
👍
