### ISSUE TITLE
Projektüberarbeitung SoundColourSpace

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#362]
Das Forschungsprojekt _SoundColourSpace_ wird überarbeitet und gewisse Fehler werden behoben.
Für dieses  Projekt ist ein umfangreicher Datenbestand im Medienarchiv erfasst worden.
https://medienarchiv.zhdk.ch/sets/sound-colour-space
Ein Teil dieser Daten wird über die API in das Verarbeitungstool auf deren Website ausgespielt.
http://sound-colour-space.zhdk.ch

Nun werden die Daten in der externen Datenbank auf deren Website bereinigt und korrigiert.

Wäre es möglich, den Meta-Datenbestand einmalig ins Medienarchiv zurückzuspielen, damit die Meta-Daten im Medienarchiv auf den neusten Stand gebracht werden könnten?

Falls ja,
- mit welchem Aufwand wäre da zu rechnen? (Anpassen JSON, Testlauf, Durchlauf, Abnahme...)
- wie müssten die Daten angeliefert werden?

**Comment by phoettli** [comment]
Gemäß @DrTom sollte das möglich sein.
Mit welchem Aufwand müssten die rechnen? (Forschungsprojekt, extern finanziert).

**Comment by eins78** [comment]
@phoettli wenn es wirklich nur um die Meta-Daten geht und sonst keine Mutationen oder Strukturänderungen stattfinden, würde ich grob einen Arbeitstag schätzen. Wenn nur Texte angepasst werden (`MetaDatum::Text und MetaDatum::TextDate`) dann 1/3 weniger – im Falle Schlagworte gibt es mehr Logik zu besprechen und zu implementieren.
Bei noch komplexeren Änderungen haben wir in der Vergangenheit 3 AT und mehr aufgewendet.

Wenn die Daten direkt aus dem externen System exportiert werden, bietet sich JSON an. Muss nicht der Struktur der API entsprechen, im Gegenteil soll es möglich exakt die gewünschten Änderungen ausdrücken.
Am besten bekommen wir mal einen JSON-Vorschlag, dann klären sich vielleicht auch Inhaltliche Fragen schneller.
Skizze wenn nur Text-MD: 

```json
{
  "updates": [
    {
      "resource": "[UUID von Entry oder Set]",
      "metakey": "madek_core:title",
      "value": "Neuer Titel"
    }
  ]
}
```

**Comment by phoettli** [comment]
@SebastienPellet kannst du aus Max' Schätzung einen "Betrag" machen und abklären, wie solche Aufträge für Forschungsprojekte abzuwickeln/abzurechnen sind?

**Comment by SebastienPellet** [comment]
ja, werde ich machen.

**Comment by phoettli** [comment]
@SebastienPellet hast du da schon Erkenntnisse gewinnen können?

**Comment by SebastienPellet** [comment]
Konnte mittlerweile mit Lars darüber sprechen.
Bei einem solchen Vorhaben muss ein Antrag geschreiben werden, analog Vorgang beim Editierinterface.

Bzgl. Kosten rechnen wir bei interner Entwicklung mit 65 CHF / Stunde (ATP B).
Da es sich aber so wie ich das verstehe um externe Finanzierung, verstehe ich die Frage nicht ganz.
Wo muss ich das Forschungsprojekt SoundColourSpace innerhalb des Madek-Spektrums einordnen?

**Comment by phoettli** [comment]
Kein Auftrag erfolgt duch Projekt.
