### ISSUE TITLE
Error 500 in der Website-Api beim Bezug der Daten

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#364]
Die Entwickler der ZHdK-Website erhalten seit dem 16.10 beim nächtlichen Job beim Zugreifen auf  `https://medienarchiv.zhdk.ch/api/meta-data/ecad9c83-8359-4824-9b7b-631ba8a25b23`
einen Serverfehler bekommt: 500 Internal Server Error response: {“message”:“No matching clause: MetaDatum::MediaEntry”} 

Wie kommt es zu diesem Fehler und könnte der vermieden werden?

**Comment by DrTom** [comment]
Mit migration 400 wurde das MetaDatum `MediaEntry` eingeführt. Ich vermute, dass das in der API nicht implementiert oder zumindest an einer Stelle vergessen wurde. Dann wurde wohl um die Zeit dieses neuerer MetaDatum verwendet und Boom.

**Comment by DrTom** [comment]
Die logs sind gerade nicht brauchbar (ich kann den genauen Fehler oben nicht zuordnen). Aber `No matching clause` bekommt man in der Regel mit einem `case` Statement. Es gibt da nicht so viele Stellen, die in Frage kommen.

**Comment by eins78** [comment]
Ich kann das bestätigen. Wie Tom vermutet, ist der Metadaten-Typ `Metadatum::MediaEntry` nicht in der API implementiert.


 Hier ist das Metadatum in der API, aus Sicht des Client 1 Schritt vor dem Fehler:
https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2Fa7b2dc19-417e-40b0-8f43-5539b6d45f67%2Fmeta-data%2F&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

Der Client kann den Fehler vermeiden, indem aus Metadata-Collection die Einträge mit `"type": "MetaDatum::MediaEntry"` ignoriert/übersprungen werden. Alternativ könnte auch ein Filter gesetzt sein, um nur die erwarteten/verwendeten MetaKeys abzurufen:
https://test.madek.zhdk.ch/api/browser/?#url=%2Fapi%2Fmedia-entries%2Fa7b2dc19-417e-40b0-8f43-5539b6d45f67%2Fmeta-data%2F%3Fmeta_keys%3D%255B%2522madek_core%253Atitle%2522%255D&headers=Accept%3A%20application%2Fjson-roa%2Bjson%0A

Mögliche Lösungen in der API:

A) für diesen MD-Typ den korrekten Statuscode `501 Not Implemented` ausgeben; oder
B) den MD-Typ implementieren.

**Comment by phoettli** [comment]
Wie aufwendig ist B) ? Wäre doch wohl sinnvoll, korrekt zu implementieren.
Falls aufwendig, kann man bis dahin superkurzfristig den korrekten Code 501 ausgeben?

**Comment by eins78** [comment]
> Wie aufwendig ist B) ? Wäre doch wohl sinnvoll, korrekt zu implementieren.

wir werden es im Developer-Meeting thematisieren und eine grobe Schätzung erstellen.

> Falls aufwendig, kann man bis dahin superkurzfristig den korrekten Code 501 ausgeben?

Nicht super-kurzfristig, es braucht so oder so eine mittelgrosse Anpassung am Code. Zu beachten ist auch, dass sich bei dieser Lösung keine wirkliche Verbesserung für den Client ergeben würde, es würde ja immer noch ein Fehler zurückgegeben werden der entsprechend behandelt werden muss.

Alternative/Bessere Idee für einen Quickfix: Diesen Metadaten-Typ ganz aus der API ausschliessen. Dann gäbe es schon im Schritt zuvor keinen Link auf das Metadatum wo der Fehler auftaucht.
Wir werden auch das besprechen und eine Schätzung abgeben.

**Comment by eins78** [comment]
@phoettli wir haben den "Quickfix" beprochen, Aufwand ca. 1/2 Tag. Es wird also also an keiner Stelle mehr das Metadatum diesen Typs referenziert werden und die API ist damit "in sich konsisitent" bzw technisch korrekt.
@DrTom wird das im Laufe der Woche angehen

tasks:
- [ ] exclude `MetaDatum::MediaEntry` from `meta-data` ROA-collection on `media-entry`
- [ ] exclude `MetaDatum::MediaEntry` from `meta-data` ROA-collection on `collection`
- [ ] specs?

**Comment by phoettli** [comment]
super !
Danke

**Comment by phoettli** [comment]
ok auf `staging`
