### ISSUE TITLE
Keywords lassen sich nicht aufrufen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#373]
Die Keywords "Digital Destination" und "Destination Digital" lassen sich nicht aufrufen.
https://medienarchiv.zhdk.ch/vocabulary/keyword/8403582a-fa25-4d0a-a66e-aed16b965088

<img width="803" alt="image" src="https://user-images.githubusercontent.com/42544602/147226676-2d3d2fd8-b9cb-4825-af4b-99b6162fabee.png">

https://medienarchiv.zhdk.ch/vocabulary/keyword/726e1ce7-34d0-4bbc-b55e-be04a4b54c0f

Tippfehler? Falsches Zeichen? ...?

PS: und ich kann neue Issues nicht mehr der Madek-Inbox zuweisen :(

**Comment by eins78** [comment]
vermutlich dieser bug. wird behoben https://github.com/Madek/Madek/issues/307

**Comment by eins78** [comment]
confirmed: both keywords mentioned in this issue have `external_uris = NULL`, so its very likely bug #307

**Comment by phoettli** [comment]
ok, fehlerhafte Aufrufe oben sind manuell behoben worden. Vielen Dank !
Bleibt der generelle Fix in #307 
@eins78 von mir aus kannst du dieses Ticket hier schliessen, wenn du im anderen weiterarbeiten möchtest.
