### ISSUE TITLE
dropdown Felder der Stapelverarbeitung sind verschoben (Firefox 91.5.0esr auf Prod.- und Staging-Instanz

### ISSUE THREAD

**Issue by ltsotrug** [Madek/Madek#377]
Dropdown-Felder der Stapelverarbeitung in Firefox (edit-mode) sind in allen Kontexten verschoben.
Betrifft Firefox 91.5.0esr (Version von 11.Jan.22). auf Prod.- und Staging-Instanz 
Siehe Screenshots Vergleich
![20220124 - dropdown felder in firefox 91 5 0esr verschoben - Vgl mit Chrome](https://user-images.githubusercontent.com/29139407/150867073-8b489349-5246-42aa-9737-d709d4e1d72c.jpg)
![20220124 - dropdown felder in firefox 91 5 0esr verschoben - Vgl mit Safari](https://user-images.githubusercontent.com/29139407/150867297-f1f6b238-d2d4-4b79-9bb1-e470f802917c.jpg)

**Comment by eins78** [comment]
@ltsotrug bei mir (gleicher Firefox, macOS) sieht es korrekt aus. Hast du irgendwelche Extensions (Adblocker o.ä.) installiert? 
Du könntest mal im "Troubleshoot Mode" (früher "Abgesicherter Modus") schauen, ob es dann auch auftritt.

<img width="1269" alt="Screen Shot 2022-01-25 at 09 18 36" src="https://user-images.githubusercontent.com/134942/150938643-1187d77f-7e20-4ece-b95a-b3b0686a309f.png">

**Comment by eins78** [comment]
ah, wichtiges wort "Stapelverarbeitung" im titel übersehen. dort sehe ich es auch, im neuesten firefox genauso.

<img width="1347" alt="Screen Shot 2022-01-25 at 09 38 24" src="https://user-images.githubusercontent.com/134942/150941661-4f5030ed-ec93-4802-accc-8fca432e86bd.png">

<img width="1216" alt="Screen Shot 2022-01-25 at 09 38 37" src="https://user-images.githubusercontent.com/134942/150941681-f5be01ac-f220-43dc-9657-cf8ef4552aed.png">
