### ISSUE TITLE
fehlende max. Preview von Medieneintrag

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#382]
bei folgendem Medien-File 
`be629ecc-974f-430f-b347-e7c506d100d3`

fehlt die Maximale Preview:
![image](https://user-images.githubusercontent.com/42544602/172663629-aa80c0a5-7a4d-4141-80f4-be2899d1236d.png)

(alle anderen Previews sind vorhanden.)
Die maximale Grösse wird aus dem Medieneintrag verlinkt, weil fehlend wird dann das Bild nicht geladen.

Bitte die Thumbs neu generieren. Ich kann das nicht, weil Button wirkungslos.

PS: ich bringe dieses Issue wiederum nicht ins Projektboard "Madek" :(

**Comment by eins78** [comment]
Weil das Original-File eine sehr hohe Auflösung hat, taucht anscheinend ein Fehler auf wenn das grösste Preview erzeugt wird. Es ist dann eine Referenz auf ein leeres/defektes File in der Datenbank, was dann zur Anzeige "herausgesucht" wird, aber nicht angezeigt werden kann.

Das habe ich erst gemerkt, nachdem ich es 2x manuell neu erstellt hatte. Die eigentlich Lösung war, bei "maximum" Preview auf "Delete" zu klicken. Nun wird dieses gar nicht mehr angeboten und stattdessen das jetzt grösste (`x_large`). Dort nun der Link hin, wenn man auf der Medieneintragsseite vergrössern klickt.

**Comment by phoettli** [comment]
😎👍
Vielen Dank !

**Comment by eins78** [comment]
@DrTom @nimaai ich habe das "execute script" playbook aus leihs rübergezogen, damit manuelle eingriff auf dem server wenigstens nicht ganz so ad hoc sind ;)
Logs von meinen Preview-Versuchen im Anhang als Beispiel.

[madek-script.20220613T122054.log.txt](https://github.com/Madek/Madek/files/8891248/madek-script.20220613T122054.log.txt)
[madek-script.20220613T122718.log.txt](https://github.com/Madek/Madek/files/8891249/madek-script.20220613T122718.log.txt)
