### ISSUE TITLE
Rollen von Personen erweitern – unbeschränkte Keywords für Rollen zulassen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#397]
## Ausgangslage
In Madek können Personen mit zusätzlich beschreibenden Rollen versehen werden (#12 ).
Für gewisse Anwendungen ist dies sinnvoll, wenn z.B. nur aus einer vordefinierten Menge von Rollen ausgewählt werden darf (Filmcredits etc).

## Problem
Die Rollen müssen fix vordefiniert werden. Dies führt sehr oft zu Problemen, wenn noch nicht vorhandene Rollen gewünscht sind. Auch sind mehrere Rollen der selben Person nur sehr umständlich zu erfassen und auszugeben.

## Lösungsvorschlag
Die Rollen können optional auch durch freie Keywords definiert werden (freie Definition mit Vorauswahl bestehender Einträge). Es wird dadurch auch möglich, mehrere Rollen einer Person zuzuweisen.
Die bestehende Option der vordefinierten Liste bleibt bestehen.

für Personen gibt es demnach drei Optionen:

- [ ] Person steht alleine
- [ ] Person mit Rolle(n) aus vordefinierter Liste (bestehend, ev. Edit Mode überarbeiten)
- [ ] Person mit Rolle(n) aus freier Keywordliste

**Comment by phoettli** [comment]
### Darstellung der Personen und ihre Rollen
![image](https://user-images.githubusercontent.com/42544602/208429020-9593f53e-9dfd-4142-9051-abeb3eb499c2.png)

a) Personen ohne Rollen hinterneinander (Medienersteller:in im Screenshot)
b) Personen mit Rollen durch Doppelpunkt voneinander getrennt, Rollen fortlaufend, neue Personen auf neuer Zeile (Autoren)

**Comment by nimaai** [comment]
@phoettli Es handelt sich hier um 2 verschiedene Themen, obwohl sie das gleiche Formular betreffen. Bitte, erstelle hierfür 2 Tickets:
1. Frei wählbare Liste an Rollen ermöglichen
2. Bestehende Darstellung von Personen:Rollen optimieren

Ich und Urs haben weitere Fragen zu beiden. Vielen Dank.

**Comment by phoettli** [comment]
@nimaai schrieb:

> Bitte, erstelle hierfür 2 Tickets:
> 1. Frei wählbare Begriffe (und/oder Liste) an Rollen ermöglichen

=> bleibt in diesem Issue

> 2. Bestehende Darstellung von Personen:Rollen optimieren

=> in neuem Issue #421

**Comment by nimaai** [comment]
@phoettli Fragen:

- Soll eine Ad-Hoc-erstellte Rolle nachher auch für andere Medieneinträge in der Liste der vordefinierten Rollen zur Auswahl stehen? Sprich, der User erweitert die vordefinierte Liste selber?
- Der User legt an oder erweitern eine separate Liste der frei wählbaren Rollen mit seinem neuen Eintrag?
- Der User legt nur für den einzelnen Medieneintrag eine Rolle an, welche man bei den anderen MEs nicht sieht?

**Comment by phoettli** [comment]
Schön wäre
1. wahlweise sowohl geschlossene als auch durch User erweiterbare Liste wie bei den Keywords, sortierbar nach Alphabet oder wie im Admin-Panel festgelegt.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/42544602/220318678-ac796fbd-ce7c-48ec-a8c5-59d7de82f491.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/42544602/220318126-d9714123-5432-40a0-b9a5-6af153f34e97.png">

2. Bearbeitung in Admin-Panel wie bei den Keywords  `~/admin/meta_keys/media_content:type` bzw. wie die jetzigen Rollen: `~/admin/meta_keys/media_object:creative_participants_roles` (inkl. Option und Festlegung manueller Reihenfolge)
3. FE-Erfassung der Rollen in der Reihenfolge ebenfalls wie bei den Keywords (Reihenfolge kann User selber wählen)
<img width="245" alt="image" src="https://user-images.githubusercontent.com/42544602/220318261-f45f9d97-66fc-43df-9e4e-15c58226812d.png">

4. optional wäre toll, wenn eine Rollen-Liste (= Rollen-„Vokabular“) für mehrere Personenfelder ausgewählt werden könnte. Also z.B. `Autorschaft` und `Mitwirkung` haben selbes Rollen-„Vokabular“, (fiktive) `Projektleitung` hat eigenes/separates Rollen-„Vokabular“
5. optional: Sprachentrennung resp. Mehrsprachigkeit (müssen wir ggf. gesondert diskutieren), bei den jetzigen Rollen möglich, weil geschlossenes Vokabuar, ev. nicht mehr möglich, wenn die Liste erweiterbar ist ???)

**Comment by nimaai** [comment]
> 5. optional: Sprachentrennung resp. Mehrsprachigkeit (müssen wir ggf. gesondert diskutieren), bei den jetzigen Rollen möglich, weil geschlossenes Vokabuar, ev. nicht mehr möglich, wenn die Liste erweiterbar ist ???)

Ja, plus andere Probleme weil man die Wertemenge nicht (vollständig) unter Kontrolle hat, wie z.B. Typo-Fehler...

**Comment by phoettli** [comment]
Ja genau, das werden wir analog der Keywords handhaben müssen, auch die periodische Doubletten-Bereinigung (müssen wir bei den Keywords und Personen auch schon machen).

**Comment by nimaai** [comment]
backend vorerst mal abgeschlossen

**Comment by urs-van-binsbergen** [comment]
> Ein Feld kann ich definieren und Personen auswählen. Aber wo lege ich die Rollen zu der Person an resp. wähle sie aus wenn die Auswahl erweiterbar ist?
Gleich wie bei erweiterbaren Keywords: Eingeben + Enter

> und wo lege ich die Rollen an, wenn es eine geschlossene Rollenliste gibt? 
Gleich wie vorher, im Admin

**Comment by phoettli** [comment]
ah, blöd, danke für den Hinweis! Jetzt hab ich's gefunden. Und funktioniert !
Die Eingabe ist einfach furchtbar umständlich und kompliziert. Aber jetzt sehe ich das Problem, insb. für die Personen.

Blöd ist vor allem, dass es einen komplett anderen Eingabemodus ist, als bei den Keywords.

Vielleicht wäre zumindest ein Hinweis hilfreich:
- (geschlossene Liste): "Wählen Sie eine Funktion aus der Liste"
- (erweiterbare Liste): "Wählen Sie eine Funktion aus der Liste oder ergänzen Sie die Liste mit der gewünschten Funktion. Mit Enter die Eingabe abschliessen."

o.ä.

**Comment by phoettli** [comment]
und: komfortabel gelöst, dass die FE-Eingabe grad beide Sprach-Label belegt ! 💯

**Comment by phoettli** [comment]
> > Ein Feld kann ich definieren und Personen auswählen. Aber wo lege ich die Rollen zu der Person an resp. wähle sie aus wenn die Auswahl erweiterbar ist?
> 
> Gleich wie bei erweiterbaren Keywords: Eingeben + Enter

Jetzt habe ich es reproduzierbar: Wenn noch keine Rolle definiert wurde, kann im Frontend keine Rolle angelegt werden (bei erweiterbarer Liste)

![](https://user-images.githubusercontent.com/42544602/231237306-9e42fbe5-4f59-4d37-ae43-1e9408c54faa.png)

Erst nachdem die erste Rolle im Admin Panel erstellt wurde, erscheint im Frontend der "Rollenmodus" und können weitere Rollen hinzugefügt werden.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/42544602/231392940-9f4f8665-2c12-4776-b190-2fd4faab6e0c.png">


Das ist jetzt nicht der Killer, aber ev. etwas verwirrend für die Administration.

**Comment by urs-van-binsbergen** [comment]
Als Notiz für allfällige spätere Entwicklung: Migration zur Einführung eines Konfigurationsfeldes für die alphabetische Sortierung von Rollen -> im Rahmen dieses Tasks nicht durchgeführt, da vorerst nicht benötigt

```rb
def up
  add_column(:meta_keys, :roles_alphabetical_order, :boolean, null: false, default: true)
  execute <<~SQL
    ALTER TABLE meta_keys
    ADD CONSTRAINT check_roles_alphabetical_order_is_boolean_for_meta_datum_key
    CHECK (
      (roles_alphabetical_order = true OR roles_alphabetical_order = false)
        AND meta_datum_object_type = 'MetaDatum::Roles'::text
      OR meta_datum_object_type <> 'MetaDatum::Roles'::text
    )
  SQL
end

def down
  remove_column(:meta_keys, :roles_alphabetical_order)
  execute <<~SQL
    ALTER TABLE meta_keys
    DROP CONSTRAINT IF EXISTS check_roles_alphabetical_order_is_boolean_for_meta_datum_key
  SQL
end
```
