### ISSUE TITLE
Visuelle Auszeichnung für "offizielle Inhalte"

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#398]
Es fehlt noch die visuelle Erkennbarkeit der "offiziellen inhalte" 
#341 

Momentan sind folgende "Sections" definiert: Archiv, Forschung, Kooperation.
Weitere denkbare könnten allenfalls sein: HSK

**Comment by phoettli** [comment]
@urs-van-binsbergen kannst du mal einschätzen:
- was geht einfach
- was geht
- was geht gar nicht
[Auszeichnung-ZHdK-Bereiche_20221116.pdf](https://github.com/Madek/Madek/files/10057157/Auszeichnung-ZHdK-Bereiche_20221116.pdf)

**Comment by urs-van-binsbergen** [comment]
@phoettli 
- Meine Favoriten Seiten: 13/14, 15, 18
- 13/14 sind am einfachsten umsetzbar
- Was geht eher nicht: alles was mit Hauptnavigation und Bedienelementen konkurriert, alles was alleine auf Farbe basiert. 

Überlegungen zur Umsetzung: Wie verdrahten wir das neue UI-Element mit dem Meta Key "Medienarchiv-Sektion"? Am ehesten analog der bisherigen Lösung für das Platzieren von Inhalten: App Settings und Context / Context Key. Das nur mal als erster Ansatz.

**Comment by phoettli** [comment]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/42544602/210656474-7012aff6-6b7d-41b8-b6d2-53ac4cd42e5a.png">

**Comment by phoettli** [comment]
Screens:

- Einzelnes Label
![20230123_Section-Label](https://user-images.githubusercontent.com/42544602/214111747-ac7d023d-a8b8-49b7-8d93-ea726ec4be59.jpg)

- mehrere Label
![20230123_Section-Labels](https://user-images.githubusercontent.com/42544602/214111792-64f8f02c-8600-4468-990e-81a9a96f13b4.jpg)

- Rollover über Label
![20230123_Section-Label_Rollover](https://user-images.githubusercontent.com/42544602/214111835-0f0cb4b6-efdb-43f6-a70f-f2847dfeb341.jpg)
