### ISSUE TITLE
Löschen von MEs auf STAGING löscht Dateien auf PROD

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#399]
Wenn ich Medieneinträge auf STAGING lösche, werden die betreffenden Dateien auf PROD gelöscht (Original und Previews) !

**Comment by phoettli** [comment]
Medieneintrag auf PROD
![image](https://user-images.githubusercontent.com/42544602/192587485-24d624d0-fba1-4446-8ef1-afc14bd143b9.png)
![image](https://user-images.githubusercontent.com/42544602/192587746-f3ed1588-8a2f-4c72-a54f-60faede0ed63.png)


Original-File auf PROD
![image](https://user-images.githubusercontent.com/42544602/192587582-347b10b4-140d-4e5e-aac2-e3984a78d2de.png)

Medieneintrag auf STAGING
![image](https://user-images.githubusercontent.com/42544602/192587682-d30f961b-8e63-4de9-9d2e-8985d18db0a2.png)

Löschen auf STAGING
![image](https://user-images.githubusercontent.com/42544602/192587822-8ef65238-adba-4c35-97a6-ead4a5bf6f6c.png)

Nach dem Löschen auf STAGING => Medieneintrag auf PROD
![image](https://user-images.githubusercontent.com/42544602/192587931-c96492ab-2415-4ead-bca6-efa58cd6a357.png)

Original-File auf PROD
![image](https://user-images.githubusercontent.com/42544602/192588823-8bab1640-ac74-417f-827e-9e2f577f5e4f.png)

Der Eintrag vom Original-File bleibt zwar vorhanden (2c07101b-ba3d-4949-bd49-fddf5f9b4177), die Previews sind aber alle weg:
![image](https://user-images.githubusercontent.com/42544602/192589239-8f366931-8c4b-4635-97b2-a10553e8a608.png)

**Comment by DrTom** [comment]
> Tom hat geflickt.
😄 

> Kann man dies über automatische Tests beobachten?

Nein 😞 Was wir als "tests" haben funktioniert so nicht. Mit nennenswertem Aufwand könnte man den deploy aufbohren, so dass nach jedem deploy ein solcher Test stattfindet.  

> Mir scheint, Löschen wäre schön öfter möglich gewesen...

Ja 😞 Die default Konfiguration beim Betrieb war inkorrekt, seit 2016 wie sich nach analyse herausgestellt hat.
