### ISSUE TITLE
Ausgabe von Madek-Player für Bild passt sich nicht Seitenverhältnis an

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#408]
Der Madek-Player für Bild skaliert sich selber nicht entsprechend dem Bildformat resp. das Bild wird nicht in korrektem Seitenverhältnis ausgegeben

Siehe auch https://github.com/Madek/Madek/issues/164

![image](https://user-images.githubusercontent.com/42544602/196718833-9d986273-c917-4c29-b0ef-6180dd91e89b.png)

z.B. /entries/fd14f6d9-5981-48cf-876c-df64e2fd171a/embedded

**Comment by urs-van-binsbergen** [comment]
Der Grund für dieses Problem ist (wie besprochen), dass die Bilddimensionen nicht (mehr) in die Datenbank geschrieben werden. Siehe dazu https://github.com/Madek/Madek/issues/210

**Comment by urs-van-binsbergen** [comment]
https://github.com/Madek/madek-webapp/commit/ace9cc89507074d2fba76842572f0325256945a4

Alte Lösung (Madek V2) zur Ermittlung der Dimensionen übernommen. Getestet und optimiert (alte Lösung hatte Probleme mit Photoshop Layers und Animated Gifs, sowie mit Bildern, die per EXIF Orientation 90 bzw. 270 Grad gedreht sind). 

Noch offen: 
- Nicht nur Originalgrösse, sondern auch effektive Grösse für jedes Preview-Bild ermitteln und speichern (war in V2 der Fall)
- Der Player (/embedded) ignoriert anscheinend die gespeicherte Grösse (auch bei Bildern vor 2016)
- Export-Dialog zeigt die Dimensionen nicht an (dies funktioniert allerdings für Bilder vor 2016)

**Comment by urs-van-binsbergen** [comment]
Angepasster Bildplayer (/embedded):
- Hintergrund immer transparent
- Ohne Parameter fluid, d.h. füllt die Breite die vom IFrame zur Verfügung gestellt wird, es sei denn die Breite des Bildes ist kleiner (dann horizontal zentriert mit seitlichen "Randstreifen")
- URL-Parameter `width`: Setzt eine fixe Breite
- URL-Paramter `height`: Setzt eine fixe Höhe, Bildbeschriftung eingerechnet
- Falls nur die Höhe fixiert ist, bleibt die Breite der Box fluid, wobei ggf. seitliche "Randstreifen" entstehen

**Comment by urs-van-binsbergen** [comment]
Separater Task erstellt betr. oEmbed: #416
