### ISSUE TITLE
Message from HSLU regarding the API

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#41]
"Ich sass gestern noch mit unserer Evento-Spezialistin zusammen, damit ich die Felder, die von Evento in die Portfolio DB gelangen müssen, genauer definieren kann und die Regeln klar sind. Dabei kamen wir auf verschiedene Lösungen. Einerseits könnte man die E-Mail-Adresse weitergeben oder die Departements-Zugehörigkeit.
Damit man sich mehr vorstellen kann, habe ich dir die Tabelle mal reinkopiert. Unser Entwickler hat dies noch nicht gesehen. Von den Ressourcen her können sie das erst im Q1/2018 realisieren (Aussage vom 31.10.). Kann aber gut sein, dass sie irgendwann eine Lücke haben (vor allem wenn sie sehen, dass eure Seite bereits bereit ist). Der Entwickler wird der ersten Kontakt mit euch nicht ohne mich aufnehmen.

![bildschirmfoto 2017-11-21 um 13 17 04](https://user-images.githubusercontent.com/3356016/33072078-53b71b68-cebe-11e7-8e96-cc7d81217d64.png)

Bei den Dozierenden haben wir zusätzliche Einschränkungen, damit nur jene ausgewählt werden, die auch Betreuer/in einer BA- oder MA-Arbeit sein könnten.“

**Comment by eins78** [comment]
obsolet
