### ISSUE TITLE
Thumbnail (medium) ist nicht verfügbar

### ISSUE THREAD

**Issue by ltsotrug** [Madek/Madek#411]
Thumbnail medium wurde nicht erstellt:
https://medienarchiv.zhdk.ch/admin/previews/96999826-d089-4ae0-b237-d11a47ca1648

betrifft media entry ID: 57a92ee4-fab7-4c67-8300-4c6dd4c1559f

Im Frontend werden keine Thumbnails angezeigt:

Es fehlen die Previews `small` (Bild inkl. DB-Eintrag) und `medium` (nur Bild)

<img width="831" alt="preview 1 Ansicht im Set" src="https://user-images.githubusercontent.com/29139407/201655882-9ab4a6bd-1972-4422-985d-c1107c194403.png">
<img width="828" alt="preview 2 Ansicht im Medieneintrag" src="https://user-images.githubusercontent.com/29139407/201655898-bd0a0c8b-8788-40ce-934a-c7bb622890d0.png">

**Comment by phoettli** [comment]
phoe: suche nach vorigen Vorkommen

**Comment by urs-van-binsbergen** [comment]
Zufällig über Source Code gefunden: https://github.com/Madek/Madek/issues/382

**Comment by phoettli** [comment]
🏆🎖

**Comment by phoettli** [comment]
@urs-van-binsbergen kannst du das so ausführen oder braucht es dazu ein Deployment?

**Comment by urs-van-binsbergen** [comment]
Weitere Aspekte
- Wie kam es dazu? Ich konnte es nicht reproduzieren auf `test-blank` und lokal. Es handelt sich um ein 120MB TIFF, von daher könnte man ein Out of Memory oder Timeout vermuten.
- ...

**Comment by urs-van-binsbergen** [comment]
> @urs-van-binsbergen kannst du das so ausführen oder braucht es dazu ein Deployment?

So wie es aussieht braucht es kein Deploy. Aber erstmal muss ich mich @DrTom absprechen, ob das Ganze safe ist.

**Comment by phoettli** [comment]
> Weitere Aspekte
> 
> * Wie kam es dazu? Ich konnte es nicht reproduzieren auf `test-blank` und lokal. Es handelt sich um ein 120MB TIFF, von daher könnte man ein Out of Memory oder Timeout vermuten.
> * ...

der User hat zur gleichen Zeit noch viele weitere Bilder in ähnlicher Grösse hochgeladen:
`/sets/a0aa9bc0-7a1a-4580-90dd-d5cd859b620f`
U.a. auch z.B. dieses: `/entries/b68da629-12b1-4253-b881-fc1e2e011e2b/usage_data`
bei all denen hatte die Preview-Erstellung offenbar problemlos funktioniert. Nur bei diesem einen schlug es fehl.

**Comment by phoettli** [comment]
@urs-van-binsbergen hmm, `small` und `small125` sind nun tatsächlich da, dafür sind bei mir jetzt all die anderen Previews weg und fehlen von `medium` bis `maximum` :(

Auf `test-blank` habe ich den Import vom Origianlbild getestet, der funktioniert dort problemlos inkl. aller Previews.
Hattest du die bestehenden Previews erst entfernt, bevor du die neuen generiert hattest?

**Comment by urs-van-binsbergen** [comment]
@phoettli Ups Sorry... Ich habe zuerst generiert und dann die doppelten gelöscht. Offenbar werden dabei kreuzmässig Files gelöscht 🤔 Nun also nochmals: zuerst alle löschen, dann Skript laufen lassen. Sieht OK aus, bitte um Gegencheck.

**Comment by phoettli** [comment]
sehr cool, jetzt ist's perfekt. vielen Dank!
