### ISSUE TITLE
Set-Tab: Hervorgehobene Inhalte fehlen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#418]
über die Set-Einstellungen können andere Tabs als der "Set"-Tab gespeichert werden. Es fehlen jedoch die hervorgehobenen Inhalte. Bitte die vorgehobenen Inhalte auch bei den anderen Tabs einfügen.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/42544602/215470223-d912ec3e-3f73-44df-9401-fef4999c7e8c.png">

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/42544602/215470424-cba54257-6eb3-46d6-b14c-2827ba8a69b5.png">

siehe https://github.com/Madek/Madek/issues/271 (Erweiterung für Tab-Speicherung)

**Comment by nimaai** [comment]
@phoettli can one highlight resources per context? in "Set" highlighted resources doesn't seem to be highlighted in "Werk" for certain sets.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/aebccad6414a678962c6bcab778341dddfc8ef5f
