### ISSUE TITLE
FE-Optimierung Personen und ihre Rollen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#421]
### Darstellung der Personen und ihre Rollen
![image](https://user-images.githubusercontent.com/42544602/208429020-9593f53e-9dfd-4142-9051-abeb3eb499c2.png)

a) Personen ohne Rollen hinterneinander (Medienersteller:in im Screenshot)
b) Personen mit Rollen durch Doppelpunkt voneinander getrennt, Rollen fortlaufend, neue Personen auf neuer Zeile (Autoren)

Technische Beschreibung hier: #397

_Originally posted by @phoettli in https://github.com/Madek/Madek/issues/397#issuecomment-1357614353_

**Comment by nimaai** [comment]
@phoettli Im Hinblick auf die vorgeschlagene Lösung sind folgende Fragen zu klären bzw. Gegebenheiten zu berücksichtigen:
- Die aktuelle Darstellung der Personen:Rollen entspricht 1:1 der Abbildung der Daten in der DB (eine Person:Rolle = eine Row in der `meta_data_roles` Tabelle) sowie der Darstellung in der Editieransicht. Sie ist einfach und auf allen Ebenen konsistent und unmissverständlich. Dies wäre idealerweise zu behalten.
- Wenn man mehrere Rollen pro Person gruppiert verliert man die Flexibilität der Positionierung der einzelnen Einträge bzw. muss diese ggfs. eingeschränkt werden. Konkrete Frage: evtl. will man, dass eine Person mit verschiedenen Rollen folgendermassen positioniert wird (weil aus irgendeinem Grund Hans Regie wichtiger ist als Rolfs Animation): 
  1. Rolf:Tanz
  2. Hans:Regie
  3. Rolf:Animation
- Auch wenn dies kein Use-Case ist, dann will man unter Umständen wenigstens pro Person die Reihenfolge der Rollen festlegen können? Z.B. "Rolf : Tanz, Animation" vs. "Rolf: Animation, Tanz". Falls ja, müsste man höchst wahrscheinlich die aktuelle Implementation von der Positionierung erweitern / anpassen (evtl. bis hin zur DB samt Migration bestehender Daten). 
- Und nicht zuletzt reicht der visuelle Vorschlag nicht ganz zur klaren Kommunikation der Datenstruktur, meiner Ansicht nach. Die Bubbles haben die gleiche Farbe für Person und Rolle. Ferner müsste man Umbrüche deutlicher definieren wie sie geschehen sollen, um Verwirrungspotenzial zwischen Person und Rolle zu minimieren.

Wir können es gerne näher besprechen, am Besten zusammen mit Urs. Ich stelle jedoch grundsätzlich in Frage, ob sich der Aufwand und die zusätzliche Komplexität lohnt.

**Comment by phoettli** [comment]
@nimaai sehr gute Punkte!

1. die Auflistung Person-Rolle macht in vielen Fällen sinn, wie z.B. einem Orchester. Meist werden bei uns aber Projekte umgesetzt, bei denen einzelne Personen verschiedenste Rollen bekleiden. Da wird dann entweder die Rollen-Liste unendlich lang oder weil zu mühsam, werden viele Rollen nicht angegeben. Wenn man Person-Rolle-Rolle-Rolle angeben kann, kann man die Ausgabe deutlich vereinfachen.
2. Im Medienarchiv haben wir drei verschiedene Felder für Autorschaft: `Autor`, `Mitwirkende Personen`, `weitere beteiligte`, man kann also eine Person mehrmals nennen mit unterschiedlichen Rollen, wenn das denn unbedingt sein muss. Einfacher ist aber natürlich die einfache Nennung mit den zusammengefassten Rollen.
3. Reihenfolge der Rollen sollte möglich sein. z.B. wie bei den Keywords
<img width="245" alt="image" src="https://user-images.githubusercontent.com/42544602/220324719-f6676053-4d1a-4376-80c8-d0d563676450.png">
4. Die Bubble für die Rolle ev. etwas dunkler machen? z.B. wie die Hover-Farbe und dann für Hover noch etwas dunkler?

**Comment by urs-van-binsbergen** [comment]
@phoettli Variantenentscheid:
[Neue Darstellung Personen-Rollen.pdf](https://github.com/Madek/Madek/files/11341661/Neue.Darstellung.Personen-Rollen.pdf)

**Comment by phoettli** [comment]
Wow, vielen Dank für die Aufstellung @urs-van-binsbergen !
Die Variante "Neu (Variante mit Buttons)" ist die korrekte. Das Link-Ziel der Buttons ist aber ein verknüpftes Ergebnis der Person mit dieser Rolle. Deshalb ist der Button abgedunkelt.
also:

- Button `[UvB]` => alle Einträge mit `[UvB]`
- Button `[UvB]:[Animation]`  => alle Einträge mit Erwähnung `Animation von UvB`, aber nicht die Einträge, wo `Ch. Reuter die Animation` gemacht hat.

Die Suche/Filter-Ausgabe müssen wir später mal noch besprechen.

**Comment by urs-van-binsbergen** [comment]
@phoettli Danke für das Feedback. Wohin soll der Link "Alle Einträge mit Erwähnung Animation von UvB" gehen? Bereits gegeben wäre die Ansicht "people/xyz" mit aktiviertem Filter auf die Rolle, das ergibt dann diesen hübschen URL:

https://medienarchiv.zhdk.ch/people/2d5c0fad-bf9d-4f86-b6d0-d1d1648dee54?list%5Bshow_filter%5D=true&list%5Bfilter%5D=%7B%22meta_data%22%3A%5B%7B%22key%22%3A%22media_object%3Acreative_participants_roles%22%2C%22value%22%3A%221e17f3a9-961b-4738-8a48-25bd6d289381%22%7D%5D%7D&list%5Baccordion%5D=%7B%22sections%22%3A%7B%22meta_data-media_content%22%3A%7B%22isOpen%22%3Afalse%2C%22subSections%22%3A%7B%7D%7D%2C%22meta_data-media_object%22%3A%7B%22isOpen%22%3Atrue%2C%22subSections%22%3A%7B%22madek_core%3Aauthors%22%3A%7B%22isOpen%22%3Afalse%7D%2C%22media_object%3Acreative_participants_roles%22%3A%7B%22isOpen%22%3Atrue%7D%7D%7D%2C%22meta_data-zhdk_bereich%22%3A%7B%22isOpen%22%3Afalse%2C%22subSections%22%3A%7B%7D%7D%2C%22meta_data-copyright%22%3A%7B%22isOpen%22%3Afalse%2C%22subSections%22%3A%7B%7D%7D%2C%22media_files-file%22%3A%7B%22isOpen%22%3Afalse%2C%22subSections%22%3A%7B%7D%7D%2C%22permissions-permissions%22%3A%7B%22isOpen%22%3Afalse%2C%22subSections%22%3A%7B%7D%7D%7D%7D&list%5Bpage%5D=1

**Comment by phoettli** [comment]
eine sehr gute Frage!

Das Ziel wäre eigentlich eine Seite `people: rolle` , aber wenn du so fragst befürchte ich, dass das gar nicht geht; und wir von unterschiedlichen Konzepten ausgegangen sind.

Die People-Seite mit aktiviertem Filter wäre als Notlösung ok, aber ich befürchte, das geht auch hier nicht.

Angenommen, im Autorschaft-Feld ist die Person ebenfalls aufgeführt bzw. in einem anderen ME dort aufgeführt mit der gleichen Rolle wie oben, müssten diese beiden MEs auf der Seite `people: rolle` erscheinen.
Oder dito beim Filtern. (resp. ebenfalls dito bei weiteren Personen-Feldern mit Rollen)

So wie Lösung jetzt aber angelegt ist, ist das Rollen-Vokabular aber immer an ein Metakey gebunden, richtig? Das hiesse im Ergebnis: gleiche Rolle in unterschiedlichen Metakeys.

Was schlägst du vor?
