### ISSUE TITLE
media shortcut urls

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#425]
HTTP-Weiterleitungen um die (dynamischen) Media-URLs für einen Medieneintrag zu bekommen (ohne API o.ä.).

Medienfiles lassen sich nicht generisch nach Typ aufrufen, z.B. explizit das mp4 in HD vom Medieneintrag xy.

* formate möglich: video, audio, bild, RDF, text?
* am besten als kleine Demo für neuen Media-Service (dieser sollte durch besseres Datenmodell bzgl. der Fomate bessere/stabilere URL-Parameter ermöglichen)

* Bsp:

  `https://medienarchiv.zhdk.ch/entries/nasa-iss/video.mp4?resolution=HD` bzw.
  `https://medienarchiv.zhdk.ch/entries/9b5fa1d7-3c61-46bf-986b-213ca52031d3/video.mp4?resolution=HD`
  liefert folgendes File aus:
  `https://medienarchiv.zhdk.ch/media/4670c653-4883-449c-9a77-6a4240d4dda5` (mp4 in HD vom nasa-iss-Medieneintrag)

* maybe even "REST-ish"
  * `https://medienarchiv.zhdk.ch/entries/nasa-iss.mp4? resolution =HD`
  * ~~`https://medienarchiv.zhdk.ch/entries/nasa-iss.jpg?height=500&width=500`~~

Parameter könnten sein:
 * **Video**:
   * video.mp4
   * video.webm
   * ?resolution=
     *  SD
     * HD
     * später FULLHD und
     * 4K
 * **Audio**:
   * audio.mp3
   * audio.ogg
 * **Bild**:
   * image.jpg
   * ?resolution=
     * large
     * xlarge
     * ...
 * **PDF**
   * document.pdf  

Falls eine bestimmte Preview nicht vorhanden sein sollte (z.B. nur SD-Video, falscher Suffix (z.B. Bild statt Video, etc.), wird eine Fehler-Statusmeldung ausgegeben.
==> UvB definiert den Statuscode.

**Comment by urs-van-binsbergen** [comment]
@phoettli 

Beispiel: https://test.madek.zhdk.ch/entries/nasa-iss/image.jpg?resolution=x_large

Spez:

image.jpg
- Verfügbar für Bild-, Video- und PDF-Einträge
- Parameter `resolution`: erlaubte Werte `maximum`, `x_large`, `large`, `medium`

video.mp4, video.webm
- Verfügbar für Video-Einträge
- Parameter `resolution`: erlaubte Werte `SD`, `HD`

audio.mp3, audio.ogg
- Verfügbar für Audio-Einträge

document.pdf
- Verfügbar für PDF-Einträge

Weiteres
- Parameter `download=yes` bewirkt Download-Dialog statt Direktanzeige im Browser (content disposition = attachment)
- Alle oben nicht definierten Pfade geben 404 zurück (z.B. "image.png"). Ebenso nicht definierte Auflösungen (z.B. "image.jpg?resolution=foo")
- Berechtigung: PDF-Dokument erfordert Berechtigung für Original, sonst nur allgemeine Anzeige-Berechtigung.

**Comment by urs-van-binsbergen** [comment]
> die zwei kleinsten Previewgrössen sind nicht unterstützt (small und small_125)
und zwar absichtlich. Es sollte statt dessen `medium` verwendet werden, das auch schon ziemlich klein ist.
