### ISSUE TITLE
Serverangaben fehlen nach Ruby-Upgrade ?

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#428]
im Admin Panel fehlen auf `STAGING` die Serverangaben:

Staging:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/42544602/221923830-65c90c3f-210a-4e97-a330-556c378705c7.png">

Prod:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/42544602/221923790-109bea7b-f6b7-4c2b-8014-a6c823361982.png">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/0c6fbe0ccdf88d9483dc7a760e4159bf252fa000
