### ISSUE TITLE
Abklären: Audio-Ausgabe für Website ("Podcast")

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#436]
## Ausgangslage
Die HSK möchte auf der [News-Seite](https://www.zhdk.ch/suche?recordType=news&noTypeSwitch=1) neu Podcasts ausgeben.

## Problem
Der Madek-Player ist nicht für Audio optimiert. Es wird der Video-Player ausgegeben mit viel schwarzem Platz für ein Audio-Symbol.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/42544602/234052571-debc3d17-6992-4430-83af-fb9c889795e5.png">

Wenn der Player in der Höhe angepasst wird, verschwindet die Steuerleiste unten:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/42544602/234052996-0b116f19-344b-4433-86af-b5ada2e2fda7.png">

## Lösungsvorschlag
vier Optimierungsmöglichkeiten stehen zur Diskussion

1. Medienarchiv-URL um Medien-Parameter ergänzen (siehe #425 ). Es könnte der Audioplayer der Website verwendet werden (falls vorhanden)
2. Audio-Player kann in der Höhe angepasst werden, damit nur noch Hinweise auf Titel/Autorschaft und Steuerleiste sichtbar bleiben
3. Ein Posterbild kann definiert werden (Neues Metadatenfeld im Medieneintrag mit Posterbild UUID. Der entsprechende Medieneintrag wird für Posterbild verwendet).
4. Audio-Player implementieren für Audio-Files (ACHTUNG: Vorschu-Player im Medieneintrag muss ggf. angepasst werden.)

## weiteres Vorgehen

- [x] erste Einschätzung uvb
- [x] phoe schaut mit Webadmins, welches Vorgehen in der Website implementierbar wäre
- [x] verbleibende Optionen prüfen
- [x] einfachste Option umsetzen

**Comment by urs-van-binsbergen** [comment]
Erste Gedanken zu den Varianten: 
1. https://github.com/Madek/Madek/issues/425
  Attraktiv, weil wohldefinierte und bereits spezifizierte Lösung
2. Audio-Player Layout anpassen/konfigurierbar machen
  Audio/Video-Player (video.js) anfassen... wird eher tricky. Könnte eine gröbere Überarbeitung erfordern. Eigentlich wäre auch video.js von aktuell v5 auf v8 upzudaten. Eher im Rahmen eines grösseren Player-Updates angehen? 
3. Posterbild
   Interessantes Feature mit Potential, muss aber gut konzipiert werden. Aufwand nicht gering. 
   Ich würde es nicht mit Metadaten lösen, sondern "richtig" modellieren. Es handelt sich nicht um generische Daten, sondern um ein Feature (das trifft übrigens aus meiner Sicht auch auf das einzige bestehende Metadaten-Feld dieses Typs - `madek_core:is_new_version_of` - zu). Auch sind herumfliegende Medieneinträge mit dem einzigen Zweck, einen anderen ME zu ergänzen, unerwünscht, siehe Diskussion bei Set-Vorschaubildern. 
   Das Vorschaubild sollte direkt an den ME angehängt sein, analog Previews. 
   Lösung auch für Set-Vorschaubild, sowie Vorschaubild für Video und PDF und sonstige Dokumente. 
   Ich vermute, dass es ggf. auch zwei verschiedene Bilder braucht: Vorschaubild und Posterbild, aber das könnte man in einem Aufwisch lösen. 
5. Separater Audio-Player
   Problematik ist diesselbe wie bei Variante 2 (bzw. Variante 4 kann wieder gestrichen werden, weil mehr ein Implementierungsentscheid als ein selbständiger Ansatz, sorry meinerseits)

**Comment by phoettli** [comment]
Variante 1 umgesetzt in Release 4.2.0
