### ISSUE TITLE
Deaktivierte User überprüfen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#438]
Die Funktion "deaktiviert" der User überprüfen.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/42544602/235723919-bb766c97-db04-407f-80e0-081583079be3.png">

**Comment by DrTom** [comment]
@phoettli By which way of authentication:
1. madek internal password, or
2. ZHdK AGW,
or maybe even both? In the case of 2. this might even make sense.

**Comment by phoettli** [comment]
@DrTom Externer User (manuelles Passwort). Interne kann ich nur schwer überprüfen, sonst sperre ich mich aus ;)

**Comment by DrTom** [comment]
Fixed for password authentication
