### ISSUE TITLE
Review disabled webapp tests  after using seeds and disabling transactional_fixtures

### ISSUE THREAD

**Issue by DrTom** [Madek/Madek#442]
https://github.com/Madek/madek-webapp/commit/90e97e2265ad910dccb2e845d6a454428785660f

Uses seed data also for basic tests (that was a TODO for a while) and disables `transactional_fixtures`. 

Some tests have been disabled because they only worked because the use of `transactional_fixtures` circumvented some checks in the database carried out by deferred triggers.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/5cf9ecc86d0b60404147f75455bcc61944f22fd0
