### ISSUE TITLE
Neuer Login-Prozess im UI

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#443]
Die Überarbeitung der Authentisierung (#433 ) zieht eine Überarbeitung des UI für das Login mit sich.

Beschreibung und Screens folgen hier...

**Comment by phoettli** [comment]
@urs-van-binsbergen kannst du mal die Skizzen an- und durchschauen?
## Login ab Home:
[2023_NewLogin-Home_001.pdf](https://github.com/Madek/Madek/files/12099159/2023_NewLogin-Home_001.pdf)
[2023_NewLogin-Home-ext_001.pdf](https://github.com/Madek/Madek/files/12099163/2023_NewLogin-Home-ext_001.pdf)

## Login ab Inhalt (Medieneintrag oder Set):
[2023_NewLogin-publ-ressource_001.pdf](https://github.com/Madek/Madek/files/12099164/2023_NewLogin-publ-ressource_001.pdf)
[2023_NewLogin-private-ressource_001.pdf](https://github.com/Madek/Madek/files/12099165/2023_NewLogin-private-ressource_001.pdf)

## Login für Fullscreen-Video (ggf. weitere Medientypen)
Die folgende müssen wir noch besprechen, die gibt es so noch nicht, resp. müssen wir noch anschauen, wie das gehen könnte.
[2023_NewLogin-fullscreen-video_001.pdf](https://github.com/Madek/Madek/files/12099170/2023_NewLogin-fullscreen-video_001.pdf)

**Comment by urs-van-binsbergen** [comment]
(work in progress)
- Nach dem Login gelangt man zu "Mein Archiv", nicht zu "Erkunden", das soll ws. so bleiben? (weil anders gezeichnet)
- Login Home extern, falsches Passwort: 
  - Verhalten aktuell: zurück zu Home, Tab "Externes Login" ist nicht ausgewählt. Benutzername ist nicht eingefüllt
  - Verhalten gezeichnet: zurück zu Home: Tab "Externes Login" ist ausgewählt. Benutzername ist nicht eingefüllt
  - Vorschlag: zum Login Screen, Benutzername wird übernommen

**Comment by phoettli** [comment]
danke @urs-van-binsbergen,  korrigierte Versionen:

[2023_NewLogin-Home_002.pdf](https://github.com/Madek/Madek/files/12147089/2023_NewLogin-Home_002.pdf)
[2023_NewLogin-Home-ext_003.pdf](https://github.com/Madek/Madek/files/12147092/2023_NewLogin-Home-ext_003.pdf)

**Comment by phoettli** [comment]
> ### Login Home AGW (u.dgl.)
>   
>   * keine Anpassungen

=> Sollte sich dynamisch anpassen (gemäss Config) und nicht mehr hardgecoded sein.
=> Buttons müssten ggf. selbstredend für Methode sein (siehe "Private Ressource")

> ### Login Home extern
>   
>   * Unterschied zu heute: Nach Abschicken mit falschem Passwort bleibt das Tab "Externes Login" ausgewählt
>     
>     * ❓ Möglichkeit/Vorschlag: Nach Abschicken mit falschem Passwort erscheint der Login-Screen. Benutzername wird übernommen und muss nicht nochmals eingegeben werden.
>   * ❓ Link "Passwort vergessen" und entsprechender Dialog würden wir vorläufig nicht umsetzen, ja?

ja genau:
- Benutzername bleibt bei fail (wo spielt für mich keine Rolle), 
- Passwort vergessen gibt es nicht.

> ### "Fullscreen":
>   
>   * Unterschied zu heute: kompaktere Darstellung des Login-Screen, keine Navigationsreiter

Das verstehe ich nicht. Was meinst du mit "kompaktere Darstellung"?
Ich hätte gedacht: immer die selbe Login-Box, 
- auf Startseite kompakt eingepackt
- auf Login Page mit etwas mehr Platz und ggf. Zusatztext vor und danach

> ### Private Ressource:
>   
>   * Unterschied zu heute:
>     
>     * Kein "Anmelden"-Button oben rechts
>     * Text "Anmelden" statt "Alle Funktionen nutzen und auf mehr Inhalte zugreifen."
>     * Button-Text "Login für ZHdK-Angehörige" statt "Anmelden"

Was findest du besser:
- für jede Login-Methode einen eigenen Reiter oder 
- unterscheiden ZHdK/extern und dann bei ZHdK ggf. mehrere Buttons (mit entsprechender Bezeichnung der Login-Methode) ?

> ### Öffentliche Ressource (bzw. einfach Klick auf "Anmelden" oben rechts❓):
>   
>   * Unterschied zu heute: Geht auf Login-Screen statt auf Startseite
>     
>     * ❓ Der Titel "Um Zugang zu diesem Inhalt zu bekommen, melden Sie sich bitte an." passt bei private Ressource, hier aber nicht unbedingt.

Argh :(
kann man den Text je nach Anwendung unterscheiden? Oder ist home besser geeignet? (Zusätzliche Umleitung scheint mir überflüssig und mühsam.)


Jetzt hab ich noch herausgefunden, dass `Home` und `/explore` nicht die gleichen Seiten sind.
- `/explore` ist `Home` ohne Login-Box.
- eingeloggt ist `Home` == `/my`


Grundsätzlich: nur so viel Änderungen wie nötig und wo's Verbesserungen bringt, sonst so wenig wie möglich.

**Comment by urs-van-binsbergen** [comment]
> Wäre allenfalls ein einfaches Overlay möglich mit der Login Box, statt dem Link zur Login Page ? (je nach Security mit oder ohne Methoden-Filter)?

Möglich ja, aber nicht einfacher.

> (Fullscreen) ... Das verstehe ich nicht. Was meinst du mit "kompaktere Darstellung"?

heute:
<img width="991" alt="image" src="https://github.com/Madek/Madek/assets/25439444/4dd806cd-1d0d-4091-9fc7-6d3f2c9eb9eb">
entspricht dem Wireframe:
<img width="663" alt="image" src="https://github.com/Madek/Madek/assets/25439444/934b046e-b13e-4ae7-93d8-7050bc767c22">
bei Fullscreen dieser Wireframe (meine ich mit "kompaktere Darstellung"):
<img width="727" alt="image" src="https://github.com/Madek/Madek/assets/25439444/3d868c1c-ab3f-4deb-b758-78b63461bfde">

> Was findest du besser:
> - für jede Login-Methode einen eigenen Reiter oder
> - unterscheiden ZHdK/extern und dann bei ZHdK ggf. mehrere Buttons (mit entsprechender Bezeichnung der Login-Methode) ?

In der ZHdK-Situation 2 Tabs + mehrere Buttons, solange es ein hierarchischer Entscheidungsbaum ist: Entweder ich bin ZHdK oder extern. In ersterem Fall habe ich verschiedene Authentisierungsmöglichkeiten (z.B. AGW, MS365, Switch AAI). 
Aber das lässt sich nicht ungefähr verallgemeinern auf andere Konstellationen. 

> argh... kann man den Text je nach Anwendung unterscheiden?

Kein Problem. Das war nur Nitpick zu deinem Wireframe ;)

**Comment by phoettli** [comment]
überarbeitete Screens:
- [2023_NewLogin-Home_004.pdf](https://github.com/Madek/Madek/files/12420574/2023_NewLogin-Home_004.pdf)
- [2023_NewLogin-publ-ressource_002.pdf](https://github.com/Madek/Madek/files/12420580/2023_NewLogin-publ-ressource_002.pdf)
- [2023_NewLogin-private-ressource_002.pdf](https://github.com/Madek/Madek/files/12420584/2023_NewLogin-private-ressource_002.pdf)

Fullscreen-Login vorerst noch nicht möglich

**Comment by urs-van-binsbergen** [comment]
Hinweis: Der Schritt mit der Auswahl des Auth-Systems (derzeit "AGW vs. Externe User") wird automatisch übersprungen, wenn nur eines zur Verfügung steht. Aktuell erscheint aber die Auswahl noch bei allen internen Usern -> Lösung siehe https://github.com/Madek/Madek/issues/470
