### ISSUE TITLE
Startseite: Ladezeit Teaser-Bilder

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#446]
Die Ladezeit der Teaserbilder ist etwas hoch.
Als Vorbereitung zu #441 Ladezeit verbessert

**Comment by nimaai** [comment]
https://github.com/Madek/Madek/commit/b1d5e30dd10d28531d16a90f949249ae8a14fbb9
https://github.com/Madek/Madek/commit/d19e0eb48005efe10b40f49849b89ef313f07d0f
