### ISSUE TITLE
Aussagekräftige Fehlermeldung nach Login mit deaktivierten Benutzerdaten

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#449]
### Problem
Das Login mit einem deaktivierten User endet in einem Error 500

<img width="1450" alt="image" src="https://github.com/Madek/Madek/assets/42544602/d4f10103-0de0-4efd-999a-67b3385cd722">

### Lösungsvorschlag
Eine für den User verständliche Rückmeldung anzeigen.
Braucht es dazu eine separate Meldung oder kann man die für falsche Login-Angaben verwenden?
<img width="724" alt="image" src="https://github.com/Madek/Madek/assets/42544602/59a4930f-2ad8-4890-ab92-4b6c57800309">

=> `Deaktiviertes Benutzerkonto. Bitte wenden Sie sich an den Support.`

**Comment by urs-van-binsbergen** [comment]
Ich warte damit mal zu, da ggf. durch #443 obsolet.
