### ISSUE TITLE
Section: Erstellen mit + anstatt x

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#450]
### Problem
Bei der [Section](https://github.com/Madek/Madek/issues/398)erstellung enthält der Button für die Erstellung ein Entfernen-X – leicht verwirrend, weil mit dem Button ein Section-Label  _erstellt_ wird.

<img width="1014" alt="image" src="https://github.com/Madek/Madek/assets/42544602/9b1858d8-badd-4b17-bc85-9f288c641bfd">

### Lösungsvorschlag
a) Das X durch ein + ersetzen
<img width="35" alt="image" src="https://github.com/Madek/Madek/assets/42544602/7b6ee936-90eb-456b-a920-e5e2a26e7d19">
b) Button ev. grün wie bei Gruppen (hinzufügen von Usern) ?

PS: das X bei "Remove" ist stimmig.

**Comment by urs-van-binsbergen** [comment]
https://github.com/Madek/madek/commit/08f384da9e02eecf93d15eeab8e18d3da0c0d3a7
