### ISSUE TITLE
Sender Medienarchiv bekommt Fehler 500 bei Abfrage

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#453]
im Log vom Sender steht:

`received invalid response code:500 url:https://medienarchiv.zhdk.ch/api/media-entries/?public_get_metadata_and_previews=true... response:Internal Server Error`

**Comment by DrTom** [comment]
So this is a configuration issue. 

I just applied a hot fix on staging and production which fixes this error temporarily. 

A proper fix is pending. An new deployment would reactivate the broken state.

**Comment by phoettli** [comment]
Der Sender läuft wieder 👍
