### ISSUE TITLE
automatisches Logout nach relativ kurzer Zeit

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#458]
neuerdings wird man automatisch ausgeloggt aus WebApp und AdminApp.
nach ca. 120min.

soll das so sein?

**Comment by DrTom** [comment]
Jein, es gibt ein Default:
```
session_max_lifetime_minutes | 1080
```
und wenn ich das so sehe vermute ich, dass er anstatt Minuten (`_minutes`) den wert als Sekunden interpretiert. Ist demnach ein Bug.

**Comment by DrTom** [comment]
@phoettli  der Wert ist im übrigen per `auth_system` und kann besser gesetzt werden: 
```
madek=# select id, session_max_lifetime_minutes from auth_systems;
    id    | session_max_lifetime_minutes
----------+------------------------------
 password |                         1080
 zhdk_agw |                         1080
 ```

**Comment by phoettli** [comment]
sieht gut aus jetzt, vielen Dank !

**Comment by phoettli** [comment]
@DrTom aktuell auf `staging` < 16h. Gibt es einen triftigen Grund für so kurz?
