### ISSUE TITLE
Webapp: React-Warnungen beheben

### ISSUE THREAD

**Issue by urs-van-binsbergen** [Madek/Madek#459]
Zahlreiche Warnungen nerven bei der Frontend-Entwicklung.

**Comment by urs-van-binsbergen** [comment]
<img width="728" alt="image" src="https://github.com/Madek/Madek/assets/25439444/e88cfabd-3311-43a0-9ba5-bbbe0da39476">

**Comment by urs-van-binsbergen** [comment]
- Einige autofocus behoben (bemerkbar im UI, Rest ist nur technisch)
- Div. issues mit `key`
- 2 PropTypes Issues
- Problemfall: "isMounted is deprecated". 3 behoben, 12 nicht. Aufwand ist zu gross, Komponenten müssten stark überarbeitet werden.

**Comment by phoettli** [comment]
Testergebnis kann ich nicht beurteilen auf `staging`.

**Comment by urs-van-binsbergen** [comment]
Richtig, diese Warnungen sah man nur im Entwicklungsmodus. Kannst du durchwinken, ich bürge dafür ;)
