### ISSUE TITLE
HfG-Instance: Improvement in Configuration

### ISSUE THREAD

**Issue by SusanneSchumacher** [Madek/madek#46]
The Instance works well and all data are there! Great!

Following aspects are missing:
- [x] please install there Zencoder account. Contact them directly for their keys/tokens.

- [x] The field ISO-Ländercode can not be user. Please add the Keywordlist (same as ours, Max knows what to do) (see Screenshot)
![bildschirmfoto 2018-02-02 um 18 28 42](https://user-images.githubusercontent.com/1416731/35754810-2657d244-0865-11e8-95a5-13b7ca1bc338.jpg)

- [ ] The link in the sharing option is: https://hfg-madek-prod.ruby.zhdk.ch/entries/a79c81b2-155f-44de-9b05-c8a9ad3d9b0f . But it should be: https://madek.hfg-karlsruhe.de/entries/UUID (see screenshot)
![bildschirmfoto 2018-02-01 um 22 18 23](https://user-images.githubusercontent.com/1416731/35754829-35ca5c2e-0865-11e8-994c-0d9c7a9730ba.jpg)

**Comment by nadjaweisskopf** [comment]
Zencoder has already been installed.

**Comment by nadjaweisskopf** [comment]
@eins78 Could we give Michal this ticket or rather not because its HfG?

**Comment by eins78** [comment]
@nadjaweisskopf I think its best I do it, has to with deploy config and the new gateway. I already had to do something similar for embedding.

**Comment by eins78** [comment]
As it turns out, we need to fix the embed API as well. In both cases we should be using `external_base_url`.

- [ ] fix `absolute_url` in oembed controller

**Comment by SusanneSchumacher** [comment]
Hello! Concerning the issue of ISO-Ländercode:
- Thomas integrated ISO-Codes on the staging-Instanz of HfG, which is very good. But unfortunately he created a new vocabulary, which was not the idea.
- The Country Codes should be available on the existing Meta-Key "ISO-Ländercode". Its ID is: https://medienarchiv.zhdk.ch/admin/meta_keys/media_content:portrayed_object_country_code
- Please delete the newly defined metakey: https://madek.hfg-karlsruhe.de/admin/meta_keys/geo:country_code
- Please delete the newly defined vocabulary geo: https://madek.hfg-karlsruhe.de/admin/vocabularies/geo
- In the User-Interface the coutry codes should be displayed like at ZHdK-Instance (with names of Countries). (See Screenshots).
![bildschirmfoto 2018-02-13 um 18 14 54](https://user-images.githubusercontent.com/1416731/36163852-f2fbb2e2-10ea-11e8-9628-d915db154f7f.jpg)
![bildschirmfoto 2018-02-13 um 18 15 17](https://user-images.githubusercontent.com/1416731/36163854-f32b2ec8-10ea-11e8-92f9-20017d9df7f6.jpg)

**Comment by nadjaweisskopf** [comment]
@eins78 will adjust the key words

@SusanneSchumacher as soon as Max has adjusted the key words you can move the meta key with the admin interface

@SusanneSchumacher created a ticket next iteration for last point.

**Comment by eins78** [comment]
@SusanneSchumacher HfG Madek now has Country-Keyword like in our instance. Please check, and if OK move the MetaKey to where it should be (the "Imported" Vocab can then be deleted, but its non-public anyhow)
https://madek.hfg-karlsruhe.de/admin/meta_keys/imported:iso_country_code

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher Will you accept this ticket or should I ask Tashi complete the ticket?

**Comment by SusanneSchumacher** [comment]
@nadjaweisskopf Was ist mit dem dritten Punkt des Tickets? Ist der auch schon gemacht?

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher created a ticket next iteration for last point. #60
