### ISSUE TITLE
Countdown / Hinweis auf Logout

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#464]
### Ausgangslage

Das Login im Medienarchiv ist neuerdings Session-gebunden. Es läuft nach einer fixen Zeit ab.

### Problem
Da die Formular-Daten nicht automatisch gespeichert werden, kann es gut und gerne vorkommen, dass die Login-Zeit genau dann abläuft, wenn ein User mitten in der Formularbefüllung ist. Alle eingegebenen und nicht gespeicherten Daten werden gelöscht. Frust ist hoch!

### Lösungsvorschlag
Ein Time-out Banner anzeigen (Standard Hinweis-Banner), z.B.
- orange: eine halbe Stunde vor Logout: Sie werden in 30 min augeloggt. Bitte speichern Sie Ihre Eingaben und __melden Sie sich neu an__ (Link zu Login).
- rot: 10min vor logout mit Countdown: Sie werden in x Minuten ausgeloggt. Bitte __melden Sie sich neu an__ (Link zu Login).

Optional: Session-Zeit verlängert sich bei jeder Speicherung, wie z.B. bei Online Banking ?

**Comment by nimaai** [comment]
@phoettli auf in der admin-webapp ?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/2801968b37668d4089b248243e7a2181a48d3855

umgesetzt auch im admin-webapp. die nachricht erhält keinen link zum login, weil sich der user eh zuerst selber ausloggen muss.

**Comment by phoettli** [comment]
funktiert super !
<img width="484" alt="image" src="https://github.com/Madek/Madek/assets/42544602/5b6f0565-4344-4004-8858-79d2d7514303">
