### ISSUE TITLE
madek-Core Labels bearbeiten für Tab "Alle Daten"

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#465]
### Ausgangslage

Sowohl [Medieneinträge](https://medienarchiv.zhdk.ch/entries/3dde51fa-1e62-4646-b5d4-1137cdab7f7b/more_data) wie [Sets](https://medienarchiv.zhdk.ch/sets/38656a1c-b23a-4400-baa3-fc6d2e1a166f/more_data) haben einen Tab "Alle Metadaten" (browse mode) resp. "Alle Daten" (edit mode für Set und ME).
In diesem Tab werden Meta-Keys ausgegeben, wie sie in Vokabularen erfasst sind. Die Labels können nicht durch einen Context überschrieben werden.

### Problem
Das Madek-Core-Vokabular wurde an verschiedenen Stellen über Contexte zurecht gebogen, damit die Bezeichnungen für das Medienarchiv passen. Nun gibt es eine Diskrepanz zwischen den Bezeichnungen in den Alle-Daten-Tabs und denen in den weiteren Tabs, die über die Contexte überschrieben werden können.

### Lösungsansätze

a) ~~Labels für Madek-Core in den Language-Files anpassen~~. ==> dies ist nur für die Bezeichnung des Meta-Keys möglich. Description und Hint können so nicht angepasst werden

b) Label, Description und Hint in den Vokabular-Einstellungen bei Madek-Core [zum Bearbeiten freischalten](https://github.com/Madek/Madek/issues/465#issuecomment-1640226508).
<img width="2018" alt="image" src="https://github.com/Madek/Madek/assets/42544602/fba36835-42cc-4159-907a-86b661f2ec49">

**Comment by phoettli** [comment]
<img width="786" alt="image" src="https://github.com/Madek/Madek/assets/42544602/8de40d00-43d3-4165-ba92-0b19bde738d2">

**Comment by phoettli** [comment]
> bei den Core-Keys zurückhaltend vorgehen. was ist das minimum, das man braucht, um dem Ticket zu genügen? reichen Hints ?

Die grösste Verwirrung resultiert aus den unterschiedlichen Bezeichnungen der Labels. Description (inkl. Links) und Hints sind v.a. für die Verständlichkeit und Nutzerführung wichtig. Die Labels könnten auch in den Language Files angepasst werden. Die Labels werden aber auch z.B. in der API ausgegeben, dort greifen die Language Files aber wohl nicht, was wiederum zu Inkonsistenzen führt.

**Comment by phoettli** [comment]
@nimaai Sie super aus!
Meine Tests auf `Test` inkl. RDF-Export zeigten keine Auffälligkeiten, einzig API-Labels konnte ich nicht testen, wegen 4.0.0.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/b011501c1d8c9d9a529840c3b1091400836fdfc6
