### ISSUE TITLE
Tab "Alle Daten" im Edit Mode mit Gruppenberechtigung

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#466]
### Ausgangslage
Im Tab "Alle Daten" im edit mode für Sets und Medieneinträge werden alle Meta-Keys nach Vokabularen geordnet aufgelistet ausgegeben. Auch Felder, die z.B. nicht mehr verwendet werden sollen, werden aufgeführt. Da nach Vokabularen geordnet, fehlt bei gewissen Feldern auch der wichtige thematische Zusammenhang.

### Problem
Viele User – insbesondere Neuuser – sind mit dieser Darstellung überfordert. Die zusätzliche Auflistung der Felder, z.T. auch mit unterschiedlichen Bezeichnungen verwirren viele User.
Viele Power User nutzen aber genau diese Ansicht, weil sie dadurch alle Felder auf einer Seite sichtbar haben.

### Lösungsansätze
Den Tab "alle Daten" im Edit Mode an eine Gruppe binden, damit nur die Mitglieder dieser Gruppe diesen Tab sehen können.

Diese Funktion der Gruppenbindung wird bereits für Workflows und die Beta-Stapelverarbeitung eingesetzt:
<img width="770" alt="image" src="https://github.com/Madek/Madek/assets/42544602/dceb5254-a9bb-450a-a7f5-2268c083de43">
<img width="979" alt="image" src="https://github.com/Madek/Madek/assets/42544602/208f800c-4b6f-4ba6-9e05-e7085c9c09d5">

(Optional für später denkbar: unter meinArchiv einen Bereich _Einstellungen_ erstellen, wo diese Einstellung individuell vom User eingestellt werden kann.)

### Bedingungen

- Der Tab soll für alle User sichtbar sein, wenn keine Gruppe zugewiesen ist.
- Gruppenname (Vorschlag): System Advanced Edit Mode
Es sollte eine InstGruppe sein, diese kann ich nicht selber erstellen
- Die Gruppe sollte vor dem Enhancement-Deployment verfügbar sein, damit wir sie bereits vorgängig mit den Usern befüllen können.
- Der Tab "Alle Metadaten" im browse mode ist von der Einschränkung nicht betroffen und immer sichtbar.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/8c27ce2c77d135fd81c9ed14745f9310fddcd90f

**Comment by phoettli** [comment]
Gruppe in Settings einbinden
<img width="984" alt="image" src="https://github.com/Madek/Madek/assets/42544602/10d86f9c-8f48-4ea8-9dc4-ffc5d209e416">
