### ISSUE TITLE
Vorversion auf TEST

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#468]
auf `Test` liegt Version 4.0.0
<img width="430" alt="image" src="https://github.com/Madek/Madek/assets/42544602/7967c172-d546-4404-abfe-49ec025e8cf5">

aktuell ist aber 4.1.0 (`Staging` und `Prod`)
<img width="433" alt="image" src="https://github.com/Madek/Madek/assets/42544602/dd30c6a9-e4f8-40a5-9565-905b9168fe0c">

bitte angleichen.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/325872ddda82a9259700e51f2675e85a54de7b9e
