### ISSUE TITLE
Admin-Interface / Settings: Delete Teaser-Set

### ISSUE THREAD

**Issue by SusanneSchumacher** [Madek/madek#47]
After the redesign of the Explore page, there is no more teaser set. -> Delete the section teaser set from admin-interface / settings.

**Comment by michalpodlecki** [comment]
done with #55

**Comment by nadjaweisskopf** [comment]
@ltsotrug Tashi, ready to test

**Comment by ltsotrug** [comment]
@nadjaweisskopf @michalpodlecki thank you, it's deleted on https://test.madek.zhdk.ch
