### ISSUE TITLE
Lizenz flächendeckend

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#472]
Übersicht Madek-Repos [hier](https://github.com/orgs/Madek/repositories?q=madek&type=all&language=&sort=)

aktuell nur in 

- [x] [madek-webapp](https://github.com/Madek/madek-webapp)  GPL-3.0
- [x] [madek-api](https://github.com/Madek/madek-api) GPL-3.0
- [x] [madek-auth](https://github.com/Madek/madek-auth) GPL-3.0

https://github.com/Madek/madek-webapp/blob/c125b5075b0edd2c3d5458d553668f894339dee9/LICENSE

fehlt in

- [ ] [Madek/Madek](https://github.com/Madek/Madek) n/d
- [ ] [madek_admin-webapp](https://github.com/Madek/madek_admin-webapp) n/d
- [ ] [madek-exporter](https://github.com/Madek/madek-exporter) n/d
- [ ] [madek-datalayer](https://github.com/Madek/madek-datalayer) n/d
- [ ] [madek-deploy](https://github.com/Madek/madek-deploy) n/d ???
- [ ] [madek-documentation](https://github.com/Madek/madek-documentation) n/d ???
- [ ] [madek-media-service](https://github.com/Madek/madek-media-service) n/d ???
- [ ] ...

Wer soll dazu sorge tragen? Und die Readmes aktuell halten?

**Comment by SeduroDotCom** [comment]
Überprüft / Lizenzvergleich
1. ToUse _> https://raw.githubusercontent.com/Madek/madek-webapp/master/LICENSE
2. Lizenzen von folgenden Repos haben zu viel Text
   1. DIFF _> https://github.com/Madek/madek-auth/blob/master/LICENSE.txt#L621-L674
   2. DIFF _> https://github.com/Madek/madek-api/blob/master/LICENSE.txt#L621-L674

<br/><br/>

Korrektur Ticket:
```
aktuell nur in 

- [x] Webapp (madek-webapp)
- [x] API (madek-api)
- [x] Auth (madek-auth)

https://github.com/Madek/madek-webapp/blob/c125b5075b0edd2c3d5458d553668f894339dee9/LICENSE

fehlt in

- [ ] Madek/Madek
- [ ] admin-Webapp (madek_admin-webapp)
- [ ] Exporter (madek-exporter)
- [ ] Datalayer (madek-datalayer)

** Missing repos
- [ ] Madek/madek-deploy
- [ ] Madek/madek-documentation
**

Wer soll dazu sorge tragen? Und die Readmes aktuell halten?
```

<br/><br/>

Aktueller Stand / ToClarify
1. Bei **Madek/madek-auth** fehlen die GithubTags?
2. Lizenzen von **madek-api & madek-auth** haben zu viel Text (jeweils am Ende)
3. Lizenz auch ins **Madek/madek-documentation** hinzufügen?
4. **Madek/madek-webapp** fehlt das GitHubTag "madek"?

**Comment by DrTom** [comment]
OK, wir weitgehend GPL.

Bei ein paar eher unwichtigen Sachen MIT, könnte sein, dass das bei denen aus einem Projekt-Template kam. Wegen mir einfach lassen. 

*Bei den Hauptprojekten die Aktuelle GPL Version zufügen.* Ich meine es braucht dazu eben das File und besser auch noch ein (kurzer) Abschnitt im README. Das sind dann folgende Projekte

- [ ] Madek/Madek
- [ ] admin-Webapp (madek_admin-webapp)
- [ ] Exporter (madek-exporter)
- [ ] Datalayer (madek-datalayer)

Für Dokumentation wie Madek/madek-documentation macht die GPL kaum Sinn. Da müsste man ggf so etwas wie CC zufügen -> mit Philipp abklären 

Für Madek/madek-deploy könnte man auch die GPL zufügen. Die Flughöhe finde ich da aber so gering, dass das irgendwie albern ist.

**Comment by SeduroDotCom** [comment]
Merged changes
1. https://github.com/Madek/madek-api/commit/5127c8f9932f103952e505f2aed0c82c96a772cc
2. https://github.com/Madek/madek-auth/commit/68efff3812d3983ef20d0d2268691a25824ffc14
3. https://github.com/Madek/Madek/commit/06f96b7c98d6331778e20086ef2243c327058b81 (Madek/Madek)
4. https://github.com/Madek/madek_admin-webapp/commit/c5a7064a9f144c4e143cbe068f793f0a85ad5ed2
5. https://github.com/Madek/madek-exporter/commit/4acdf39ed4e25da4090b2346cac585dd136b6d86 
6. https://github.com/Madek/madek-datalayer/commit/a2c7245dec5d55f25eafc15486505df16d27901a
7. https://github.com/Madek/madek-webapp/commit/2bc98e7da7ba9f3616d14b32eddb916d4b8b47ea
