### ISSUE TITLE
Keyword-Merge zuverlässig umsetzen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#473]
### Ausgangslage

Keyword Merge sei gemäss Tom nur halbherzig umgesetzt
Gemäss Urs mit kleinem Aufwand sauber lösbar.
(siehe #412 )

> Was ist heute implentiert? Getestet anhand Keywords:
> 
> Wenn A nach B gemerget wird, wird das entsprechende ID-Tupel in die previous_keyword_ids Tabelle geschrieben
Dieser Eintrag bewirkt, dass ein Aufruf auf z.B. "/media_entries/(ID von A)" auf "/media_entries/(ID von B)" redirected wird
Wenn später B auf C gemerget wird, wird der Eintrag A -> B ersetzt durch B -> C.
M.E. sollten bei einer Kette von Merges alle historischen IDs erhalten bleiben. Wie folgt:

> Prüfen ob HIstory-Einträge bestehen, deren Target das Merge Victim ist. Deren Target-ID muss vom ID des Merge Victim auf das neue Merge Target geändert werden
Neuer History-Eintrag für den letzten Merge erstellen
Tabelleneinträge nach 1. Merge: A -> B
Tabelleneinträge nach 2. Merge: A -> C; B -> C
> 
> Zufallsbefund:
> 
> Wenn eine Ressource sowohl mit Merge Target wie auch Merge Victim verbunden ist, scheitert der Merge (da ein Doublette entsteht -> es müsste für diesen Fall die Verbindung zum Merge Victim gelöscht werden)

**Comment by phoettli** [comment]
Müssen diese Merges für alle Ewigkeit behalten werden (Datenberg) oder kann man die auch irgend einmal wieder löschen? z.B. nach 5 oder 10 Jahren ;)
Wäre es ggf. sinnvoll das Datum der Merges dazu in der DB festzuhalten?

**Comment by nimaai** [comment]
> Wenn eine Ressource sowohl mit Merge Target wie auch Merge Victim verbunden ist, scheitert der Merge (da ein Doublette entsteht -> es müsste für diesen Fall die Verbindung zum Merge Victim gelöscht werden)

@urs-van-binsbergen Kannst du bitte ein Beispiel mit A, B, C machen bitte?

**Comment by nimaai** [comment]
@phoettli @urs-van-binsbergen muss man da was von den bestehenden daten migrieren?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/709a0af9c149ce7b6e6b889cbc9112f49bb54a0b
