### ISSUE TITLE
Feldbereinigung Hilfe-URL

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#475]
### Ausgangslage
Für die [Hilfe-URL](https://github.com/Madek/Madek/issues/284) gibt es ggw. drei Felder:
- ein neutrales Feld
- je eines für DE und EN

### Problem
Nur die Felder für DE und EN haben eine Daseinsberechtigung.
<img width="548" alt="image" src="https://github.com/Madek/Madek/assets/42544602/dc6cd822-40a7-4aa2-877a-17537d379cc6">

### Lösung
- [x] Das neutrale Feld bitte entfernen.
- [x] Die Felder sollten nur abhängig von den Sprachversionen entstehen.

**Comment by phoettli** [comment]
> was meinst du mit “Die Felder sollten nur abhängig von den Sprachversionen entstehen.”

Ich gehe davon aus, dass man irgendwo eine zusätzliche Sprache einstellen kann. Nur dann sollen für diese Sprache die URL-Felder entstehen. 😇
Falls dem nicht so ist, einfach die Felder für DE und EN.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/e047b2e4374cf6e783214031f0b18cbcfc64074e
