### ISSUE TITLE
Verantwortlichkeit bei ME ersetzen korrigieren

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#476]
### Ausgangslage
Die Funktion "[Medieneintrag ersetzen](https://github.com/Madek/Madek/issues/269)" ermöglicht Metadaten und Zugriffsberechtigungen (und Zusammenhänge und sprechende URL) von einem Medieneintrag auf einen weiteren zu übertragen; eine Art neue Version erstellen.
<img width="329" alt="image" src="https://github.com/Madek/Madek/assets/42544602/50c5216f-6844-4ec8-a3a1-e940e104f7fd">

Damit ich einen Medieneintrage "ersetzen" kann, muss ich über Schreibrechte für die Metadaten verfügen.

### Problem
Die Verantwortlichkeit wird bei dieser Funktion ebenfalls übernommen, anstatt dass als Verantwortlichkeit der User eingetragen wird, der die Funktion aufruft.

Z.B. können so neue Medieneinträge angelegt werden unter der Verantwortlichkeit einer Person, die längst keinen Zugriff auf das System mehr hat etc.

Die verantwortliche Person ist die einzige Instanz, die den erstellten Medieneintrag löschen kann.

### Lösung
Als Verantwortliche Person muss die Person aufgeführt werden, die die Funktion ausführt.
<img width="674" alt="image" src="https://github.com/Madek/Madek/assets/42544602/80b1ddbf-ae14-491a-ad35-28727ddfdc6a">

**Comment by nimaai** [comment]
@phoettli was soll mit MEs die man jetzt nicht löschen kann passieren? irgendeine art migration...?

**Comment by nimaai** [comment]
> Z.B. können so neue Medieneinträge angelegt werden unter der Verantwortlichkeit einer Person, die längst keinen Zugriff auf das System mehr hat etc.

so "orphans" kann man meines erachtens nach sowieso nicht vermeiden, richtig @phoettli ? selbst ME wo ich verantwortlicher bin können orphans werden, wenn ich nicht mehr zugriff aufs system habe.

**Comment by phoettli** [comment]
Bestehende Einträge sind kein Problem @nimaai . Es geht nicht darum, Bereinigungen durch zuführen, sondern zu verhindern, dass neue Einträge erstellt werden in der Verantwortlichkeit von nicht mehr aktiven Usern.

**Comment by phoettli** [comment]
> @phoettli was soll mit MEs die man jetzt nicht löschen kann passieren? irgendeine art migration...?

so belassen wie sie sind. Die werden – falls nötig – punktuell neu organisiert oder – falls es mal einen entsprechenden Entscheid geben sollte, auf Zuruf entsprechend bereinigt.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/c020949eafc201dde1cc774ac4b63b41b62dda91
