### ISSUE TITLE
Content Downstaging steht wieder still

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#478]
seit dem 11.7. (Datum Release 4.1) geht das Content Downstaging wiederum nicht.
Letzter öffentlicher Eintrag auf `STAGING`: 10.7.: https://staging.madek.zhdk.ch/entries?list_conf%5Border%5D=created_at+DESC
Letzter öffentlicher Eintrag auf `PROD`: 22.8.: https://medienarchiv.zhdk.ch/entries?list_conf%5Border%5D=created_at+DESC

siehe auch: https://madek.slack.com/archives/C7ZRE6P9Q/p1688458459043459

Bitte nachhaltig flicken.
Danke !

**Comment by DrTom** [comment]
Das geht nun wieder. 

Grund war ein externes Problem (Debian Install) was den Deploy für die Container verhindert hat.  Von wegen "Nachhaltig flicken": da können wir nichts machen.
