### ISSUE TITLE
Madek configuration: browsing restrictions

### ISSUE THREAD

**Issue by SusanneSchumacher** [Madek/madek#48]
![bildschirmfoto 2018-02-02 um 18 14 49](https://user-images.githubusercontent.com/1416731/35766359-36ae228e-08d7-11e8-8070-90c6388abd2b.jpg)
We have the the new browsing options on the bottom of a media entry detail view and as a context based action (Stöbern nach ähnlichen Inhalten).
It works only of in the Admin-Interface explicitly excludes browsing for the metakey rights:certificate. Otherwise a 500-Error is given.
How can we make sure that a Madek instance can be set up by persons who does not know this? Remark in Admin-Intface? Documentation? Automatic exclusion of this metakey?

**Comment by eins78** [comment]
This is a simple bug, the feature doesnt work if no config is set but it should not.
I'd guess it slipped through because in our case we always had this settings.

Solution: make sure `/entries/$ID/browse` works when `settings.ignored_keyword_keys_for_browsing = NULL`.

**Comment by nadjaweisskopf** [comment]
@ltsotrug Tashi, ready to test

**Comment by ltsotrug** [comment]
@nadjaweisskopf as soon as the RC is ready, @eins78 will tell @ltsotrug what exactly has to be rechecked

**Comment by eins78** [comment]
@ltsotrug in short: this page does not crash anymore, nothing else to do https://staging.madek.hfg-karlsruhe.de/entries/e7d50707-8ba5-4da5-baa4-65733c6a749d/browse
