### ISSUE TITLE
Notifikationen: Subtask Datenstruktur

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#481]
Notifikationen sind im Issue #409 beschrieben.

### erster Schritt: Datenstruktur anlegen

Welche Informationen kommen woher?

- Encodings aus Zencoder-Meldungen
- Übertragung von Verantwortlichkeit: ev. aus Audit ?
- ...

**Comment by phoettli** [comment]
ggf.

- Hinzufügen zu Arbeitsgruppen

**Comment by phoettli** [comment]
@DrTom siehe https://github.com/Madek/Madek/issues/409#issuecomment-1816847762

**Comment by nimaai** [comment]
wip: https://github.com/Madek/madek-datalayer/tree/mk/notif-409

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/6d6d877d90c50daa2754280a1534d6142b95fea5
