### ISSUE TITLE
ID-Bezeichnung einheitlich in Admin UI

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#490]
in admin ui sind die attribute die in der DB mit `_id` enden uneinheitlich und verwirrend gerendert werden. vergleich `institutional_id` auf “Group” (_Institutional Id_) und “User” (_Institutional_).

Ziel: einheitlich

- _ID_, 
- _Institutional ID_

für alles was mit `_id` endet in der DB (und auch nur `id`).

**Comment by phoettli** [comment]
Bestehende Bezeichnungen lassen ergänzen um DB-Feldbezeichnung in Klammer (ggf. Monospace)

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/37c7981ab0207696849497969a401276a321a79c

**Comment by phoettli** [comment]
@nimaai sorry für Rumgemäckel: aber ginge die Schrift auch Schwarz oder Grau und ohne Hinterlegung anstatt rot ([siehe Beispiel oben](https://github.com/Madek/Madek/issues/490#issuecomment-1775115730))
Rot finde ich sinnvoll für Fehler oder Warnungen, für normale Bezeichnungen eher ungeeignet.
(Falls dies genereller Code-Style in Admin App ist, müsste man diesen überdenken und anpassen.)

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/b7b222ed02c29238b3f51bce5c5bb52dd6eb8b60
