### ISSUE TITLE
People-Merge: Klärung ob Bereinigung der Merge-History benötigt wird

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#492]
bei den Keywords wurde die Merge-History bereinigt: https://github.com/Madek/Madek/issues/473
brauchts diese Bereinigung auch bei den People-Einträgen ?

Und bei den institutionalGroups?
<img width="388" alt="image" src="https://github.com/Madek/Madek/assets/42544602/d6540032-a825-4ede-b636-2c438b9e5b6f">

**Comment by nimaai** [comment]
@phoettli gemäss https://madek.slack.com/archives/C7ZRE6P9Q/p1664553141115369 wurden alle `previous_xyz_id` Tabellen entsprechend bereinigt.

Soll die rekursive Funktionalität à la https://github.com/Madek/Madek/issues/412#issuecomment-1663855500 umgesetzt werden? Wenn ja, auch bei Groups?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/54716e876186feb2e92bcaf2e0fc6f0a21054e52
