### ISSUE TITLE
Details der Inst. ZHdK-Gruppen im Mein Archiv ergänzen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#499]
### Ausgangslage
ZHdK-Gruppen werden in mehrere Differenzierungen unterteilt z.B.

- `Gruppe.alle`
- `Gruppe.alle_angestellte`
- `Gruppe.dozierende`
- `Gruppe.mittelbau`
- `Gruppe.studierende`
- ...

### Problem
In der Gruppendarstellung im "Mein Archiv" werden die Gruppen ohne das Suffix ausgegeben. Es ist nicht direkt ersichtlich, welcher der verschiedenen Gruppen man angehört:
<img width="859" alt="image" src="https://github.com/Madek/Madek/assets/42544602/9eaecd30-dc73-47af-b9ea-4fcb61f3ddcf">
Die Mehrfachauflistung sieht wie ein Fehler aus und verbirgt die Tatsache, dass eine Gruppenzugehörigkeit zu mehreren Gruppen vorliegt.

### Lösung
Gruppen in "Mein Archiv" inkl. des Gruppen-Suffix `.alle`, `.dozierende`, `.mittelbau` etc. ausgeben

ggf. dito Admin App/User-Detail-Seite

**Comment by urs-van-binsbergen** [comment]
Das wird dann so: 
<img width="912" alt="image" src="https://github.com/Madek/Madek/assets/25439444/a3858162-49c3-463f-8794-6844ed024065">

Analog zu Mein Archiv > Gruppen. 

Schöner wäre sowas wie 
- Services, ITZ, Development & Integration (alle)
- Services, ITZ, Development & Integration (alle Angestellten)
- etc.

Aber das geben die Daten aus der Tabelle `groups` nicht her. Es gibt dort `name` (das ist die bisher angezeigte nichteindeutige human-friendly Bezeichnung), sowie `institutional_name` (das ist der technoide String in Klammern). Ich dachte erst, man könnte den `institutional_name` bei der Anzeige automatisch "humanisieren", das ist aber nicht sinnvoll.

**Comment by phoettli** [comment]
Ich nehme an, `name` kommt aus AD/Envento so geliefert. Da macht es nicht viel sinn, dies umzubiegen. Allenfalls könnten die eine andere "humanisierte" Version liefern. Das müsste aber dort geschehen.

**Comment by urs-van-binsbergen** [comment]
Genau, man muss das auf Ebene Schnittstelle bzw. LDAP/AD/Evento anschauen. 

Ich merge das aber mal so, OK? Dann ist es konsistent und sieht nicht nach Fehler aus.

**Comment by phoettli** [comment]
superperfekt ! Vielen Dank.

**Comment by urs-van-binsbergen** [comment]
OK, ist gemerget: https://github.com/Madek/Madek/commit/e4e17a5a16ed333d25bca418e04a0c41a137f2f8

Soll der Issue noch offenbleiben im Hinblick auf die Abklärung, ob man aus dem Directory noch "bessere" Namen rausbekommen könnte?
