### ISSUE TITLE
Person can not be clearly identified 

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#50]
Problem mentioned by HSLU and ZHdK

Same name can pop up twice or more times, 
For example: 
Markus Meier (User 1)
Markus Meier (User 2)

**Sections where these user names are shown**
- Edit meta-data - user
- Set permissions - adjust with email address - ask Mischa, if we are allowed to show the email address
- Show permissions
- Filter
- No adjustiment needed for list view 
- work group view page - list of users
- work group edit page - list of users

quickest solutions:
- Enhancement in Admin-interface. New fields for additional information where these few users can be differed.
- Admin can search for users with same names

Needs a bit more work:
- Show more information in a popup or similar solution (E-Mail, Picture, etc.)

Possible future solution (project): 
- Data could be imported from AGW or wikidata or GND (Deutsche Nationalbibliothek)

Check with Mischa Senn which information we are allowed to publish.

**Comment by nadjaweisskopf** [comment]
If we discuss a solution then invite Susanne and Tashi to refinement.

**Comment by nadjaweisskopf** [comment]
@nadja  ask Mischa, if we are allowed to show the email address

**Comment by nadjaweisskopf** [comment]
When adding a user then place the email address in the auto complete. Only in authorisation - show zhdk-email  - could also be the private address.
Use pseudonym, adjust in admin interface if double names exist. 
Discuss on 6.3.18 with Susanne

**Comment by eins78** [comment]
## People

new fields
- external_url
- comment (non-admin)

both on people page (public), editable in admin (also check for Keywords)

SQL-Assistant: find ambigously named People

## User
- mail addresse in autocomplete, if possible
- autocompletes should detect UUID-based URLs (if user pastes `…/people/$ID`)

**Comment by eins78** [comment]
remaining tasks for this ticket:

- [ ] db: fields for People: `external_url`, `comment`/`description`(?)
- [ ] admin: edit forms `people.*`, `keywords.external_url`
- [ ] webapp: new fields on People#show

**Comment by eins78** [comment]
done in https://github.com/Madek/madek/commit/f8face89cdef0d122ed4be5dd27f213aa69b6bb2

**Comment by eins78** [comment]
people page in webapp:
![screen shot 2018-03-07 at 16 14 35](https://user-images.githubusercontent.com/134942/37143918-d4f35fdc-22bc-11e8-8c42-e5d772e86f31.png)

**Comment by nadjaweisskopf** [comment]
@susanneschumacher ready to test - Tashi will merge same persons and correct spelling mistakes

**Comment by SusanneSchumacher** [comment]
Das funktioniert sehr gut! Vielen Dank!
- Ok: Editieren im Admin-Interfaceh
- Ok: Darstellung im User-Interface
- Ok: Analyse des SQL-Assitenten

Zwei Verbesserungswünsche:
- Im Admin-Interface: 
--Bei URI soll man mehrere URIs eingeben können. Für Personen gibt es häufig mehrere Quellen, die Normadaten zur Verfügung stellen. Am besten: Eine mehrzeiliges Eingabefeld, die URLs können dann mit einem Zeilen umbruch eingeben werden. Dies ist jetzt auch so im URL-Feld bei den Metadaten. Problem in der jetzigen Lösung ist: Wenn man zwei URLs eingibt, dann werden die zu einer "verschmolzen" (Siehe Screenshot).
-- Im Admin-Interface: Das Eingabefeld für die Description soll mehrzeilig sein.
- Im User-Interface: Der Text für die Description soll nicht über die ganze Bildschirmbreite laufen, sondern, wie sonst auch, früher umgebrochen werden.

![bildschirmfoto 2018-03-13 um 19 14 53](https://user-images.githubusercontent.com/1416731/37362044-8e0a80aa-26f4-11e8-8409-b52e2eb5a55e.jpg)

**Comment by nadjaweisskopf** [comment]
@eins78 Max, können wir die zwei Anforderungen gem. Susannes Kommentar oben ändern und noch mit diesem Madek-Release ausliefern?

**Comment by eins78** [comment]
1. Zeilenlänge angepasst, für kommendes Release
2. Mehrere URLs wäre eine mittelgrosse Anpassung in DB + UI, sinnvollerweise für alle bestehenden Felder auf einmal, sonst ist es inkonsistent. Neues Ticket: #74
