### ISSUE TITLE
Username bzw. E-Mail wie eingegeben an AGW übergeben

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#500]
AGW akzeptiert jetzt alle Eingaben.
Bitte beim Login bei Eingaben direkt an AGW übergeben.

**Comment by phoettli** [comment]
siehe: https://madek.slack.com/archives/C7ZRE6P9Q/p1706528343402579?thread_ts=1706521200.375509&cid=C7ZRE6P9Q

**Comment by urs-van-binsbergen** [comment]
de9c1fda1f1452fd3ba68e5e35b47b89f137e1ca
