### ISSUE TITLE
Upgrade API-V2 to next-jdbc and HoneySQL 2

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#502]
wo?

**Comment by SeduroDotCom** [comment]
DEV-Branch:
1. https://github.com/Madek/madek-api-v2/commit/9559056d547e5e116de831938c1153bc7a96ec58
2. Spec-Tests cleanup: https://github.com/Madek/madek-api-v2/commit/b80e5ce4a0bbf9332748512fb472358ac75fa29f
