### ISSUE TITLE
fehlendes Bild inkl. Preview

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#503]
da fehlt ein Bild:
~/entries/e0f8712f-5314-475c-930d-7a1e2d18c155
inkl. der Previews

wie kann das sein resp. entstehen ?
lässt sich das wieder herstellen?

seltsamerweise gibt Original-File-Export in der Web App ein Bild zurück
ebenfalls ~/files/6e7124d2-7f20-4933-a964-1fecdb0dbcb3

**Comment by urs-van-binsbergen** [comment]
Unser Rails Script Runner (execute-script_play.yml) funktioniert nicht mehr, es muss an das neue Setup mit `asdf` angepasst werden. Ich komme nicht weiter. Ein Fall für unsere Dev-Ops-Spezialisten.

**Comment by urs-van-binsbergen** [comment]
Ich habe die "kaputten" Previews bereits über die Admin-Webapp gelöscht (also die DB-Einträge, zu denen keine Bilddateien erzeugt wurden). D.h. es muss nur noch das obige Skript ⬆️⬆️⬆️ ausgeführt werden.

**Comment by nimaai** [comment]
@urs-van-binsbergen https://github.com/Madek/madek/commit/32b8daeb1f016c0fd3d1dae33fcfe2b4fb292c4b

**Comment by urs-van-binsbergen** [comment]
Wie diskutiert: Das Bild lässt sich mit ImageMagick 7 verarbeiten, aber offenbar nicht mit ImageMagick 6. 

Habe das Bild lokal eingefüttert und dann die Previews per SCP hochkopiert. Es fehlen die Dimensionen, aber das ist auch für alle Bilder vor 2023 der Fall. Es lohnt sich daher nicht das händisch zu flicken. Somit aus meiner Sicht Fall erledigt. 

Als separater Issue zu behandeln: "Update ImageMagick 7". Achtung, IM7 kommt NICHT automatisch mit Debian 12.

**Comment by urs-van-binsbergen** [comment]
Das Problem ist die Konfiguration. Das Bild überschreitet die maximale Breite von 16'000 Pixel.

```
# convert -list resource
Resource limits:
  Width: 16KP
  Height: 16KP
  ...
```
