### ISSUE TITLE
Sammelticket Admin App Enhancement

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#508]
Hier kann gesammelt werden, was in der Admin App für Verbesserungen notwendig sind.

Einheitliche Verweise der Listen auf
- ❓ Detailseite [Lupe mit +] (gid10) oder neues Symbol ?
- ❓ Web App-Vorschau [Auge] (gid16)
- [ ] Assozierte Listen auf den Detailansichten sollten auch diegleichen Symbol-Konventionen usw. befolgen.

### Media Entries List
- [x] Filtern nach Responsible User (UUID)
- [x] NEU Uploaded by (creator id)
- [x] Vorschau in Webapp

### Users List
- [ ] „Resources“ zeigt nur Anzahl Medieneinträge, besser wäre:
    - [x] getrennt: | Media Entries (unpublished MEs) | Collections |
    - [x] Summe aller Ressourcen (publ. & unpubl. MEs & Sets zusammengezählt)
    - [ ] Details auf der Detailseite: unpubl. ME, publ. ME, Collections, Created MEs
- [x] Anzahl Resourcen als Link direkt auf Filter Media Entries/Resp.User
- opt. NEU Anzahl Uploads
- opt. NEU Anzahl Uploads als Link direkt auf Filter Media Entries/Uploaded by
- [x] „Grant Admin Role“ orange hinterlegt (anstatt grün)
- [x] Filterzählung soll Anzahl Fundstellen zeigen (anstatt Gesamtanzahl)
- ❓ resp. User (anstatt Person)

### Media Files List
- √ ~~Filtern nach Uploader~~

### People List
- √ ~~Link auf Detailseite~~
- [x] Vorschau in Webapp mit anderm Icon
- [x] Filter nach UUID
- √ (~Zählung von Filterergebnissen~)

### Person (People) Detail
- ❓ NEU Feld für Admin-Kommentar

### Set List
- [x] Filter nach UUID
- [x] Filter nach Responsible User/Delegation (UUID)
- [x] Filter nach Uploaded by (creator id)
- [x] Vorschau in Webapp
  - /collection/ Segment Redirect nach /set/ (richtiges Segment-Ziel wenn man /admin/ entfernt) analog /media_entries/ => /entries/

### Set Detail
- Responsible User als (User-)Name
- Creator als (User-)Name

### Groups List
- √ (~Zählung von Filterergebnissen~)
- [x] Vorschau in Web App
- NEU: ev. Anzahl Gruppenmitglieder

### Groups (Detail)
- NEU Erstellungsdatum
- ev. NEU Erstellungs-User (ohne Abhängikeit beim Löschen)
- Zählung der Mitglieder (User) korrekt (nicht Anzahl Nennungen pro Seite !)

**Comment by nimaai** [comment]
> ❓ Detailseite [Lupe mit +] (gid10) oder neues Symbol ?
❓ Web App-Vorschau [Auge] (gid16)

@phoettli alternative schlage ich vor:
- `glyphicon-eye-open` für Detailseite in Admin
- `glyphicon-globe` für Web-App-Seite 

https://getbootstrap.com/docs/3.3/components/#glyphicons

**Comment by nimaai** [comment]
> getrennt: | Media Entries (unpublished MEs) | Collections |
@phoettli In Bezug auf "Media Entries" braucht es folgende Bedinungen: 
- entweder ist man bei den jeweiligen MEs der Responsible oder der Creator

**Comment by phoettli** [comment]
> > ❓ Detailseite [Lupe mit +] (gid10) oder neues Symbol ?
> > ❓ Web App-Vorschau [Auge] (gid16)
> 
> @phoettli alternative schlage ich vor:
> 
> * `glyphicon-eye-open` für Detailseite in Admin
> * `glyphicon-globe` für Web-App-Seite
> 
> https://getbootstrap.com/docs/3.3/components/#glyphicons

sehr guter Vorschlag @nimaai ! vielen Dank.
Im Madek-Font sind die beiden Icons allerdings auch enthalten. Bitte auf Konsistenz achten und bevorzugt nur einen Icon-Font verwenden.

**Comment by phoettli** [comment]
> > getrennt: | Media Entries (unpublished MEs) | Collections |
> > @phoettli In Bezug auf "Media Entries" braucht es folgende Bedinungen:
> 
> * entweder ist man bei den jeweiligen MEs der Responsible oder der Creator

Gute Frage @nimaai !
In Bezug auf ME ist im Alltag der Creator eigentlich nicht so relevant. Einzig beim Löschen wichtig, da vorhandene von einem User erstellte MEs das Löschen blockieren.

```
| Typ           | Responsible | Creator     |
| Medieneintrag | relevant    | interessant |
| Media File    | interessant | relevant    |
| Set           | relevant    | interessant |
```

### Use Cases

a) im Alltag interessiert mich: welcher User verantwortet welche Inhalte -- `Responsible User` vom ME, sprich publizierte und nicht publizierte MEs.
b) dito beim Set (ohne unpublizierte, weil es diese nicht gibt)
c) beim Löschen interessiert mich a) und b) und zusätzlich, welche MEs vom betreffenden User erstellt wurden. Letzteres würde ich aber eher beim `Media File` schauen. Allenfalls kommen da später auch noch zusätzliche Ressourcen dazu (Workflows etc.)

### Lösungsmöglichkeiten

Welche Anzeige ist jetzt die, die mit kleinstem Aufwand den grössten Nutzen hergibt?
a) `| Media Entries (unpublished MEs) | Collections |` (alle Werte bezogen auf `Responsible User` -- keine Created)
b) `| Total Resources (Entry: ME, Collection: Set) | Created MEs |` (ersteres für Responsible, letzteres für Created -- auf unpublizierte wird verzichtet)
c) `| Media Entries (created MEs) | Collections (created Sets) |` ( ohne Klammer die verantworteten, in Klammern die erstellten Ressourcen -- auf unpublizierte wird verzichtet)

Was denkst du? 
c) scheint mir die übersichtlichste Darstellung.

**Comment by phoettli** [comment]
Leider kann ich die Beschreibung oben nicht ändern, ohne alle deine Änderungen zu überschreiben @nimaai , deshalb hier zusammengefasst:

- [x] Vorschau generell
- [x] Media Entries List
- [x] Users List
- [x] People List
- People Detail => Neues Ticket [#514](https://github.com/Madek/Madek/issues/514)
- Sets List
  - [x] Filter nach UUID
  - [x]  Filter nach Responsible User/Delegation (UUID)
  - [x] Filter nach Uploaded by (creator id)
  - [ ] **Vorschau in Webapp** => `Routing Error` Segment sollte `/sets/` heissen (anstatt `collections`)
- Set Detail => [#260](https://github.com/Madek/Madek/issues/260)
- Groups List
  - [x] Vorschau in Web App
  - [ ] **NEUE Spalte: Anzahl Gruppenmitglieder**
- Groups Detail
  - NEU Erstellungsdatum => Neues Ticket [#515](https://github.com/Madek/Madek/issues/515)
  - NEU Erstellungs-User => Neues Ticket [#515](https://github.com/Madek/Madek/issues/515)
  - [ ] **Zählung der Mitglieder (User) korrektes Total** (nicht Anzahl Nennungen pro Seite !)

grossartige und sehr hilfreiche Erweiterung, vielen Dank !

**Comment by nimaai** [comment]
@phoettli 

im bezug auf:
>NEUE Spalte: Anzahl Gruppenmitglieder
ich entferne mal die spalte "search rank" um platz zu sparen. es scheint, nicht verwendet zu werden. 
frage:
soll man zwei zahlen anzeigen? anzahl user members und anzahl delegation members? 
oder eine zahl gesamt? oder eine zahl aber: direct members + members through delegations?

**Comment by nimaai** [comment]
@phoettli 

> NEU Erstellungs-User => Neues Ticket https://github.com/Madek/Madek/issues/515

und was in dem fall das eine gruppe durch einen sync erstellt wurde? evtl. `created_by_api_client_id` ?

**Comment by phoettli** [comment]
Zu Deinen Fragen:
> ich entferne mal die spalte "search rank" um platz zu sparen.

Gute Idee !
> soll man zwei zahlen anzeigen? anzahl user members und anzahl delegation members?

Kann man Delegations Gruppen zuweisen? Ich glaube nicht. In den Gruppen sind m.W. nur Einzeluser.
> und was in dem fall das eine gruppe durch einen sync erstellt wurde? evtl. created_by_api_client_id ?

sehr gute Idee !

Vielen Dank @nimaai

**Comment by nimaai** [comment]
> ich entferne mal die spalte "search rank" um platz zu sparen.

sorry, es wird doch verwendet und zwar im zusammenhang mit der select-box "Sort (and search) by". ich lasse es.

**Comment by phoettli** [comment]
Interessant. Ev. könnte man klären, wozu es den überhaupt braucht bzw. wie er zustande kommt #517

**Comment by nimaai** [comment]
@phoettli man sollte sich überlegen, ob man `groups.created_by_user_id` wirklich braucht, da die information auch den audits zu entnehmen ist. zudem gedenkt man `api_clients` zu entfernen und stattdessen mit user tokens zu arbeiten in der zukunft.

**Comment by phoettli** [comment]
@nimaai hab dir im [#515 geantwortet](https://github.com/Madek/Madek/issues/515#issuecomment-1869817058)

**Comment by nimaai** [comment]
korrekt @phoettli. done: https://github.com/Madek/madek/commit/430ba9463a873f2d9c9bcd51dab2e241c0ce6b21
