### ISSUE TITLE
Audio-Vorschau fehlt in Weitere Medieneinträge und Ähnliche-Inhalte

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#509]
In den Medieneinträgen fehlt bei den Weiteren Medieneinträgen und Ähnlichen Inhalten die Kennzeichnungn für Audio-Files:
<img width="552" alt="image" src="https://github.com/Madek/Madek/assets/42544602/54a9fd3e-57fc-4ea4-81be-b52fff6185b8">

Lösungsvorschlag
die Vorschau mit dem Audio-Symbol darstellen
<img width="500" alt="image" src="https://github.com/Madek/Madek/assets/42544602/0bef72e7-c2da-4b6c-85a6-fa13996ee589">

Zur Info: später dann die Vorschau in Wellen-Form im gleichen Format wie Videos (302x170px ?) darstellen

**Comment by urs-van-binsbergen** [comment]
f4867c25cb3de327bcfe857d1c6351d9e5cc8cb2
