### ISSUE TITLE
User-Tabelle um Klarnamen (Vorname, Name) ergänzen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#510]
Dem Usereintrag fehlt Vorname und Nachname. Namensangaben werden offenbar bisher aus People bezogen.

Usertabelle um Vorname/Nachname ergänzen.

Migration ?
Wie bekommen wir die fehlenden Angaben nachgeführt?
- aktive User über Insitutional-ID
- inaktive User: 
 - allenfalls aus E-Mail extrahieren? Wie umgehen mit Umlaut etc.?
 - aus People auslesen?

Vorbedingung für #260

**Comment by phoettli** [comment]
@DrTom alle User scheinen heute um 15:30h erneut aktualisiert worden zu sein, inkl. Updated Timestamp:
<img width="670" alt="image" src="https://github.com/Madek/Madek/assets/42544602/e9a8d93d-7497-4a4a-9cd1-53c6d35bd937">

**Comment by DrTom** [comment]
@phoettli wo und wann hast du das wieder nachgeschaut; lokal bei mir wird `updated_at` nicht erneuert?

**Comment by DrTom** [comment]
Komisch auf test sehe ich das auch; bei mir lokal nicht ???
