### ISSUE TITLE
Admin App: People Detail erweitern um Admin Comment

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#514]
Die Detaileinträge der Personen um ein Feld `Admin Comment` oder `Notes` erweitern:

<img width="600" alt="image" src="https://github.com/Madek/Madek/assets/42544602/cc034c03-0d5a-4f0f-8392-9652d9d4529a">

**Comment by phoettli** [comment]
@DrTom erstellt Datenbankfeld

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/c54a8bd8ca7b9ace20c16435418c72187f770aa8
