### ISSUE TITLE
Admin App: Groups Detail ergänzen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#515]
Die Detailseite von Groups ergänzen um folgende Felder
- Erstellungs Datum: `created at`
- Erstellungs User (falls vorhanden resp. Bot, falls automatisch (?)): `creator` (nur Information, keine Löschblockade)

...oder importieren von entsprechender "Person"?

<img width="402" alt="image" src="https://github.com/Madek/Madek/assets/42544602/9b9230dc-8145-4220-b350-e1aa413c6b9e">

**Comment by phoettli** [comment]
> @phoettli man sollte sich überlegen, ob man groups.created_by_user_id wirklich braucht, da die information auch den audits zu entnehmen ist. zudem gedenkt man api_clients zu entfernen und stattdessen mit user tokens zu arbeiten in der zukunft (dann hat sich das mit created_by_api_client_id erübrigt).

@nimaai das Feld ist sehr hilfreich für Support oder wenn man Gruppen entfernen möchte. Es gibt den Hinweis, von wem die Gruppe erstellt wurde. Auf die Audits haben wir im Support keinen direkten Zugriff (und es ist noch nicht definiert, wie lange zurück die verbleiben werden.).
Die API Clients werden wohl noch bleiben. Schlimmstenfalls falls nicht, würde auch der Token-User reichen.

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/trees/de46dc00e2dad6056cecb38fdeeac870cfb43e76

**Comment by phoettli** [comment]
das ist auf STAGING jetzt ein Zeitstempel drin, möglicherweise vom Contentdownstaging letzte Nacht. Ist das so gewollt?
<img width="749" alt="image" src="https://github.com/Madek/Madek/assets/42544602/7a7504f3-eb73-4464-ba66-79ca369e75f7">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/f0fde59f5f1e0a4e04ca63aad89454a4baa3942b
