### ISSUE TITLE
Vokabulare: People-Reiter hinter Login

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#519]
Der Reiter Personen in den Vokabularen darf nur für eingeloggte User zugänglich sein.

<img width="624" alt="image" src="https://github.com/Madek/Madek/assets/42544602/8b19adf1-9d09-4ec2-b330-9dbc40109b2f">

**Comment by urs-van-binsbergen** [comment]
67552f107bd0a9469e9509609f347e1c185646e0

**Comment by phoettli** [comment]
Das ist jetzt etwas schräg:
Eingeloggt sehe ich jetzt nur drei Reiter, der Personen-Reiter fehlt:
<img width="410" alt="image" src="https://github.com/Madek/Madek/assets/42544602/a6b5cd63-16a9-4355-9f3a-72369c6fb09b">

Sobald ich auf den Reiter "Inhalte" klicke, sehe ich plötzlich auch den Reiter "Personen"
<img width="492" alt="image" src="https://github.com/Madek/Madek/assets/42544602/99355a1e-2563-4079-bad7-c3a301effa13">

gehe ich zurück auf "Vokabular" verschwindet der Personen-Reiter wieder.

ausgeloggt ist alles korrekt!

**Comment by urs-van-binsbergen** [comment]
1c8ac8b5f1848ce9d44f4ccbf2d6f356e727c4b6
