### ISSUE TITLE
New filter in Admin section

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#52]
In Admin-Interface / User: Deactivated user is shown without recognition in Admin-Interfaace. It is not possible to select or identify deactivated users. 

Steps: 

- [x] filter needed to select deactivated users

- [x] deactivated users should be identifyable

follows ticket https://www.pivotaltracker.com/n/projects/1600743/stories/132982429

**Comment by eins78** [comment]
UI: ![screen shot 2018-03-12 at 16 03 37](https://user-images.githubusercontent.com/134942/37291466-fc9adad8-260e-11e8-95a2-ec0c52722700.png)
