### ISSUE TITLE
Filterliste: Personen-Listen auflösen und durchsuchbar machen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#520]
Die Filterlisten zu Personen (`Autor/in`, `Medienersteller/in`, `Mitwirkende` etc.) sind viel zu lang und unpraktisch.
Wie kann die Liste

- durchsuchbar
- öffentlich eingeschränkt

gemacht werden?

Beachten: `ZHdK > Bereich ZHdK`  (Gruppen-Listing) !

Mögliche Lösungen
- Suchfeld wie bei den Berechtigungen mit Treffereinschränkung für Public
- ...?

beachten:
- Performance !

**Comment by urs-van-binsbergen** [comment]
@nimaai Beispiel: 

Suche nach "mozart"
https://staging.madek.zhdk.ch/entries?list%5Bfilter%5D=%7B%22search%22%3A%22%22%7D&list%5Bshow_filter%5D=true

Dynamic Filters, Section "meta_data"
https://staging.madek.zhdk.ch/entries.json?list%5Bfilter%5D=%7B%22search%22%3A%22mozart%22%7D&list%5Bshow_filter%5D=true&list%5Baccordion%5D=%7B%7D&list%5Bpage%5D=1&list%5Bsparse_filter%5D=true&___sparse=%7B%22dynamic_filters%22%3A%7B%22section_group_meta_data%22%3A%7B%7D%7D%7D

**Comment by phoettli** [comment]
sieht gut aus auf `STAGING`
