### ISSUE TITLE
Mailservice implementieren

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#525]
für verschiedene Dienste wird ein Mailservice gebraucht:

- #409 Notifikationen (Übertragung Verantwortlichkeit, Abschluss Upload/Transcodierung...)
- Admin-Hinweis neuer User angelegt mit Personen-Dublette

in einem ersten Schritt den Mailservice implentieren, analog leihs.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/4afa3d9ee92de566030596bc781f838491319523
