### ISSUE TITLE
Freigabe-Darstellung in Berechtigungen ist verwirrend

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#526]
### Ausgangslage
In den Zugriffsberechtigungen wird die Sichtbarkeit von Inhalten eingestellt.

### Problem
Nicht gesetzte Zugriffsberechtigungen werden durch ein dunkelgraues Kreuz markiert.
Ungeübte User verwirrt dieses Kreuz häufig, weil es auch als "markierte Checkbox" gelesen werden kann, insbesondere wenn die vergleichende markierte Checkbox fehlt.

<img width="866" alt="image" src="https://github.com/Madek/Madek/assets/42544602/041de1fb-3e85-4a97-b2a0-3ee7f1f5b962">

### Lösungsansatz
für nicht gesetzte Zugriffsberechtigungen ein Icon wählen, das unmissverständlich ist. z.B.:
- leere Checkbox
- rotes X
- invertiertes X in Kreis
- rotes Ø
- ...

**Comment by phoettli** [comment]
zusammen mit #523

**Comment by urs-van-binsbergen** [comment]
39753c59660c99af140ac47741e9df54fdec0505
