### ISSUE TITLE
Keys schützen in DB für APIs

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#528]
analog [leihs #1664](https://github.com/leihs/leihs/issues/1664)

- [x] Code Anpassung
- [ ] ~Deployment anpassen~

**Comment by DrTom** [comment]
This is now possible i.e. implemented in code. 

After reviewing the whole process: we don't need to configure this in the near future (or maybe ever). Leaking the private key of the server is not sufficient to compromise sign-ins.
