### ISSUE TITLE
display of deactivated users in web app

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#53]
follows ticket https://www.pivotaltracker.com/n/projects/1600743/stories/132982429

**Comment by eins78** [comment]
needs list of all places in UI

- [ ] media resource - Responsible User

**Comment by nadjaweisskopf** [comment]
@ltsotrug 
Tashi, could you please check if there is any other place than the one mentioned by Max. Otherwise we would develop for this specific place.

**Comment by eins78** [comment]
Form with deactivated responsible user + permission for 1 deactivated user.

![screen shot 2018-03-08 at 14 44 17](https://user-images.githubusercontent.com/134942/37154119-4d83037c-22df-11e8-90d2-36e63fa53ca9.png)

**Comment by nadjaweisskopf** [comment]
@susanneschumacher @ltsotrug  ready to test

**Comment by eins78** [comment]
![screen shot 2018-03-13 at 10 20 58](https://user-images.githubusercontent.com/134942/37332976-6b998cb0-26a8-11e8-8ec7-4ac026dabdc5.png)

**Comment by SusanneSchumacher** [comment]
Dieses Ticket kann sehr gut von Tashi getestet werden.

@ltsotrug Noch ein Hinweis für die Bereinigungspraxis: Dieser Screenshot weisst darauf hin, dass Du beim Löschen von Usern unbedingt zuerst den User aus allen Zusammenhängen im System entfernen musst und ihn erst dann löschen solltest. Sonst entstehen solche Leichen.

**Comment by ltsotrug** [comment]
@SusanneSchumacher Danke für den Hinweis.

**Comment by ltsotrug** [comment]
@eins78 Bei einem erweiterten Test (Set übertragen und Zugriffsberechtigung entfernen, Schlagwörter erstellen und im Admin Bereich entfernen) ist mir aufgefallen, dass der Test User John Doe nicht mehr endgültig aus dem System "entfernt" respektive "destroyed" werden kann. Ist das richtig? 

![bildschirmfoto 2018-03-15 um 13 36 52](https://user-images.githubusercontent.com/29139407/37464896-06fa7aae-285a-11e8-8804-e9fec60695b5.png)

**Comment by eins78** [comment]
@ltsotrug In kurz: Ja. In lang:
User können nicht gelöscht werden, wenn noch "irgendwie Daten" dranhängen. Genau dafür gibt es ja inzwischen "Deaktivieren statt Löschen". Für die meisten User, die aktiv das Archiv benutzt ist auch gar nicht möglich alles Daten manuell zu entfernen, so dass der User richtig gelöscht werden könnte bzw ist das nicht gewünscht. Beispiel: Schlagworte, die der User erstellt hat sollen erhalten bleiben. In deinem Beispiel ist es die Information, dass der betr. User das Set erstellt hat (unabhängig von der Verantwortlichkeit)
