### ISSUE TITLE
ZHdK-Inhalte als anvertraute Inhalte

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#530]
### Ausgangslage
Unter "Mein Archiv" gibt es einen Menüpunkt "Mir anvertraute Medieneinträge". Darunter fallen Einträge, über die ich Zugang habe.

### Problem
Die Berechtigungsgruppe `AuthenticationGroup` ZHdK (quasi intern) speist dieser Bereich ebenfalls. Wie sinnvoll ist es jetzt aber, unter "Mir anvertraute Medieneinträge" sämtliche über die ZHdK-Gruppe zugänglichen Einträge aufzuführen?
- viele
- viele ohne persönlichen Bezug

siehe z.B. 
`012a44e3-ece3-4447-a943-3b9b26f8c82b`
<img width="782" alt="image" src="https://github.com/Madek/Madek/assets/42544602/c4974bff-fb9f-4c04-9989-bf64a7c0344b">

### Lösungsvorschlag
Ist es möglich, die Berechtigungsgruppe ZHdK von dieser Aufführung auszunehmen?

ev. nur Schreibberechtigungen aufführen?

**Comment by nimaai** [comment]
> ev. nur Schreibberechtigungen aufführen?
@phoettli das wäre die bessere lösung. es sollte aber im kontext vom gesamten dashboard nochmals angeschaut werden.

**Comment by phoettli** [comment]
- Systemgruppen werden ausgeschlossen
- In der Auflistung werden die Systemgruppen((Link zu Meinarchiv-Gruppen)) aufgeführt: Nicht berücksichtigte System-.Gruppen: angemeldete...., ZHdK..... (ggf. externe User)

**Comment by nimaai** [comment]
backend done: https://github.com/Madek/madek-webapp/tree/mk/gh-530

**Comment by urs-van-binsbergen** [comment]
82799d83100990826885600011c6df4f6c7c8e69
