### ISSUE TITLE
Exporter bricht ab bei Rollenabfrage

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#531]
Der Exporter scheint abzubrechen, wenn Rollen vorkommen.
Er exportiert von ca. 29 Sets (`b1c887a2-9ed6-42de-aef6-480aa1353242`) nur eines, und das ohne Medieneinträge.

Ein einzelnes Beispielset mit Rollen: `d84c6f6f-fb7a-471a-944f-b30e9cf3c41c`

<img width="912" alt="image" src="https://github.com/Madek/Madek/assets/42544602/f812a148-26c5-498f-840d-d1bd25218ffd">

**Comment by phoettli** [comment]
@DrTom Der Fehler sollte auch beim leeren Set auftreten.
Hier gibt es z.B. eines mit enthaltenen Medieneinträgen `ea247384-7702-473a-8478-56e7d36da0fe` 
Siehst du da Inhalt?

**Comment by DrTom** [comment]
Ja: aber ich bin nur für eines download berechtigt. Damit hat es keinen Fehler gegeben. 

Ich habe mich jetzt für alle selbst (auf Staging) berechtigt und er downloaded jetzt schon recht lange irgend etwas runter. Ist vermutlich etwas grösseres dabei. 

Selbst wenn ich damit das Problem finde taugt das nichts zur Fehlersuche. Ich bräuchte ein minimales Beispiel; ein Media-Entry mit kleinem Download bei dem ich das reproduzieren kann. Kannst du mit so etwas anlegen. Wenn das kaum Metadaten ausser dem Problemfall hätte wäre das um so Praktischer.

Mit dem Exporter ist es nun so: im dev Modus bekommen ich ihn nicht mehr zum laufen. D.h. ich muss für jeden Test den ich mache einen neuen Build anstossen. Schon deshalb sollte das so klein wie möglich sein

**Comment by DrTom** [comment]
Jetzt ist er fertig, alles runtergeladen aber kein Fehler aufgetreten.

**Comment by phoettli** [comment]
hmm, kannst du mal schauen, ob der Exporter die Rollen richtig auflöst?
in folgender Sequenz sollten auch die Namen stehen:
```
{
  "collection_id" : "ea247384-7702-473a-8478-56e7d36da0fe",
  "id" : "d925e704-1938-4333-9b45-c2a576c5caea",
  "meta_key_id" : "media_object:creative_participants_roles",
  "type" : "MetaDatum::Roles",
  "values" : [ {
    "id" : "d1bfd128-2dc1-49a5-b403-149467396a4a",
    "meta_datum_id" : "d925e704-1938-4333-9b45-c2a576c5caea",
    "person_id" : "936d5b34-3c65-42eb-a033-08b067b36f7d",
    "position" : 0,
    "role_id" : "d544b9cf-9a45-4d03-96d3-87f8cd49fd54"
  } ]
},
```

**Comment by DrTom** [comment]
Hm, kein Fehler aber es sieht genau so aus wie bei dir:
```
 {
  "collection_id" : "ea247384-7702-473a-8478-56e7d36da0fe",
  "id" : "d925e704-1938-4333-9b45-c2a576c5caea",
  "meta_key_id" : "media_object:creative_participants_roles",
  "type" : "MetaDatum::Roles",
  "values" : [ {
    "id" : "d1bfd128-2dc1-49a5-b403-149467396a4a",
    "meta_datum_id" : "d925e704-1938-4333-9b45-c2a576c5caea",
    "person_id" : "936d5b34-3c65-42eb-a033-08b067b36f7d",
    "position" : 0,
    "role_id" : "d544b9cf-9a45-4d03-96d3-87f8cd49fd54"
  }
  ```

**Comment by phoettli** [comment]
wenn ich ein neues Set erstelle, kann ich leider nicht sehen, ob der Fehler auftritt. In dem Set oben, hatte ich diesen beobachten können.

Ein weiteres Set` fda413ee-fb3f-4d67-9ae3-347c5e8ea096` (`STAGING`) habe ich mit Rollen befüllt...

**Comment by DrTom** [comment]
Auch damit kein Fehler; Inhalt scheint mir analog 

[meta-data.json](https://github.com/Madek/Madek/files/14575534/meta-data.json)

**Comment by DrTom** [comment]
Aha, er gibt im Prinzip schon das richtige aus, so sieht das im Schema aus:

```
madek=# \d meta_data_roles
                   Table "public.meta_data_roles"
    Column     |  Type   | Collation | Nullable |      Default
---------------+---------+-----------+----------+-------------------
 id            | uuid    |           | not null | gen_random_uuid()
 meta_datum_id | uuid    |           | not null |
 person_id     | uuid    |           | not null |
 role_id       | uuid    |           |          |
 position      | integer |           | not null | 0
```
Verstehe ich es richtig: er soll jetzt die `person_id` nehmen, das auflösen und davon den Inhalt in diese Struktur legen? 
Ich vermute wir haben schon etwas, das so ähnlich funktioniert?

**Comment by phoettli** [comment]
sehr cool, läuft !  👍
