### ISSUE TITLE
"Last sign in at" wird nicht aktualisiert

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#534]
bei externen Usern wird beim Login das Feld "Last sign it at" nicht aktualisiert:
<img width="675" alt="image" src="https://github.com/Madek/Madek/assets/42544602/11212040-bc0b-4eaf-85c5-0c658a145c4f">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/108d69498b8bd17456a475e4563caa9789cd3ba7

**Comment by phoettli** [comment]
vielen Dank!
