### ISSUE TITLE
Mailfunktion implementieren lassen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#541]
=> Betrieb

wie in leihs:
- SMTP Server konfigurieren
- Mailboxen einrichten (pro Instanz eine eigene Mailbox für alle zugänglich an gesharte Boxen)
-

beachte: #540

**Comment by phoettli** [comment]
ist eingerichtet

**Comment by nimaai** [comment]
wie heissen die email-adressen / mailboxes? ich finde sie nicht in zhdk outlook. @phoettli @DrTom

**Comment by nimaai** [comment]
tests ausstehend

**Comment by nimaai** [comment]
email-test auf test und staging erfolgreich.
