### ISSUE TITLE
Notifikationen: Daten sammeln lassen und auswerten

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#546]
Subtask von #409

1. wo kommen die Daten her für die Notifkationen? 
2. welche können verwendet werden?
3. wie werden Notifikationen getriggert (allenfalls), falls nicht nur Zusammenfassungen versendet

**Comment by nimaai** [comment]
@phoettli was ist genau der zweck von diesem task?

ich denke, man könnte es auch sein lassen. für jeden gewünschten notifikationen-typ kann man wie folgt vorgehen:
1. der trigger bestimmen (z.b. übertragung von rechten)
2. das template erfassen
3. implementation vom trigger

den rest übernimmt die ganze maschinerie: 
1. heraussuchen vom entsprechendem template
2. eintrag in die `notifications` tabelle
3. verschicken übers UI/email je nach einstellung vom user
4. markierung von der notifikation (ggfs. email) als "done"
5. ggfs. markierung von der notifikation als "acknowledged" falls über UI geliefert und von user als "gelesen" markiert
6. automatisches löschen von der notifikation und ggfs. email nach ablauf einer frist

**Comment by phoettli** [comment]
@nimaai das war euer Vorschlag. 
Von mir aus kannst du das Ticket schliessen, wenn erledigt bzw. wenn's das nicht braucht.
