### ISSUE TITLE
Notifikationen: Admin App erweitern für Templates und Anpassung DB

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#548]
Subtask von #409

Bearbeitungsbereich eintrichten für

- E-Mail-Templates DE & EN
  - Verantwortlichkeit übertragen
  - Uploads
.
  - ggf. Doppeltes Personen-Auftreten

**Comment by nimaai** [comment]
https://ci.zhdk.ch/cider-ci/trees/1ee6c7a668e4d7c9410c8596fffe1122b1d04a7b

**Comment by nimaai** [comment]
@phoettli wie / wo sollen die "Subject" Zeilen für die Emails verwaltet werden? Man kann vorerst hard-coden. Mache dafür bitte Vorschläge.

**Comment by phoettli** [comment]
geht das nicht auch hier rein?
~/admin/notification_templates/responsibility_transfer

**Comment by phoettli** [comment]
Templates nur Label und Description
nicht editierbar

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/ac55880074f8a2f4f2b89bc4a074f137d13369a6
