### ISSUE TITLE
Notifikationen: SMTP settings verwalten im Admin UI

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#550]

**Comment by nimaai** [comment]
@phoettli einfach wie alle anderen settings auf https://medienarchiv.zhdk.ch/admin/app_settings ?

**Comment by phoettli** [comment]
> @phoettli einfach wie alle anderen settings auf https://medienarchiv.zhdk.ch/admin/app_settings ?

gerne.
Könnte von mir aus aber auch in einem der Config-Files sein (Tom fragen?). Einfach, was einfacher geht und praktikabler ist.

**Comment by nimaai** [comment]
@phoettli Es ist besser (Rolle) und einfacher (Code / Rails) eine eigene Seite dafür zu machen mit eigenen Menüeintrag "Emails".

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/6d6d877d90c50daa2754280a1534d6142b95fea5
