### ISSUE TITLE
Notifikationen: Zuordnung in Delegations

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#551]
Subtask von #409

in Admin-App bei den Delegations:
- wer bekommt Notifikationen angezeigt/zugeschickt?
  - bei Delegations mit Usern
  - markieren von einzelnen Usern möglich (ev. sollen nicht alle zugespamt werden?)
  - bei Delegations ohne User => mehrere E-Mail-Adressen möglich ~oder besser: Userverknüpfung (ohne Verantwortlichkeit)~(geht nicht bei anonymen Adressen)

**Comment by phoettli** [comment]
Zuständigkeit für Delegations:

1. **einfachster Fall**: 1–4 User zuweisen, sie bekommen alle Notifikationen und können in der Webapp die individuellen Einstellungen verwalten
2. **kollaborativer Fall**: alle Mitglieder der Delegation bekommen Notifikation (dies ist insbesondere bei zugewiesenen Gruppen sinnvoll, damit nicht sämtliche Gruppenmitglieder nochmal aufgeführt werden müssen) und können in der Webapp die individuellen Einstellungen verwalten. Die Verantwortliche Zuständigkeit hat nur informativen Charakter.
3. **anonyme Delegation**: unpersönliche Email-Adresse überschreibt E-Mail von verantwortlicher Zuständigkeit für die Delegation. D.h.
   - es kann (oder muss) eine verantwortliche Zuständigkeit definiert werden
   - durch die Hinterlegung einer unpersönlichen E-Mailadresse wird der User von den Notifikationen verschont, stattdessen gehen die Notifikationen an die angegebene E-Mail
   - Problem: 
     - wo werden die Settings für die Notifikation gesetzt?
     - allenfalls: wo landen die Webapp-Notifkationen?


Mögliche Umsetzung

```
....
Admin Comment (admin_comment)                     blah
User(s) in charge (....)                          [ + Add a User ]
Notification to all Members                       true|false
Optional overwriting E-Mail-Address               notifikation-beim-user@werden-ueberschrieben.com
--------------------------------------------------------------------------------------------------
Users ( )                                         Groups ( )
....
```

**Comment by phoettli** [comment]
Use Cases

1. Mehrere Personen zusammen bearbeiten ein gemeinsames Projekt, sammeln Daten und reichern sie mit Metadaten an.
2. Mittelbau/ATP ist zuständig für die Medien von einem Studienbereich, es gibt mehrere Stellvertreter:innen für Ferien etc.
3. Delegation wird verwendet für "parkierte" Inhalte, sie werden nicht mehr aktiv bewirtschaftet und dürfen nicht gelöscht werden.

**Comment by nimaai** [comment]
todo:
- [ ] neue spalte in db `delegations.email`
- [ ] admin ui: neues feld "email"
- [ ] admin ui: auswahl bei der delegation an wen die notifikation-email geht: an `delegations.email` und/oder die einzelne supervisors

**Comment by phoettli** [comment]
@nimaai Use Cases ausformuliert, ausgehend von aktueller Umsetzung in Admin App mit Supervisors:

###   1a): n User arbeiten kollaborativ alle bekommen Notifikationen, eine ist Chef

```
....
Notification to all Members                       true
Optional overwriting E-Mail-Address               --
--------------------------------------------------------------------------------------------------
Users ( )                                         Groups ( )
Marie                                             --
Peter
Jakob
Hilda

Supervisors ()
Marie
```
Alle User bekommen Notifications (`Notification to all Members=true`)

###   1b): n User arbeiten kollaborativ alle bekommen Notifikationen, eine ist Chef, alle User sind in einer Gruppe zusammengefasst

```
....
Notification to all Members                       true
Optional overwriting E-Mail-Address               --
--------------------------------------------------------------------------------------------------
Users ( )                                         Groups ( )
--                                                Gruppe-MariePeterJakobHilda

Supervisors ()
Marie
```
Alle User bekommen Notifications (`Notification to all Members=true`)


###   2): ATP-Person Paula bearbeitet, sie hat zwei Stellvertreterinnen, die keine Notifikationen bekommen

```
....
Notification to all Members                       false
Optional overwriting E-Mail-Address               --
--------------------------------------------------------------------------------------------------
Users ( )                                         Groups ( )
Paula                                             --
Lisa (StV)
Anna (StV)

Supervisors ()
Paula
```
Notifications bekommt nur Paula: Webapp und Mail (`Notification to all Members=false`)


###   3): Delegation für parkierte Inhalte, E-Mails gehen an unpersönliche E-Mailadresse

```
....
Notification to all Members                       false
Optional overwriting E-Mail-Address               archiv@institution.com
--------------------------------------------------------------------------------------------------
Users ( )                                         Groups ( )
--                                                Archiv-der-Institution (Roger, Emil, Frieda, Ursula, Beat...)

Supervisors ()
Katharina
```
Notifications gehen in Webapp von Katharina und per Mail nur an unpersönliche E-Mail (`Notification to all Members=true`)


### zu klären:

- [ ] wie und wo können Mail-Settings für Use Case 3 eingestellt werden?

**Comment by nimaai** [comment]
@phoettli 1b) verstehe ich es richtig, dass alle mitglieder der gruppe auch benachrichtigt werden sollen?

**Comment by nimaai** [comment]
@phoettli ich habe es technische zusammengefasst, somit ich es in code-logik übersetzen kann:
```
+-----------------------------++--------------------------------------+
| Notification settings       || Entities to be notified              |
+=============================++=======================================
| All members | Email defined || Supervisors | Users | Groups | Email | 
+-------------+---------------++-------------+-------+--------+-------+
| true        | null          || yes         | yes   | yes    | no    |
| true        | not null      || yes         | yes   | yes    | yes   |
| false       | null          || yes         | no    | no     | no    |
| false       | not null      || yes         | no    | no     | yes   |
+-------------+---------------++-------------+-------+--------+-------+
```
Das heisst u.a.: 
* Alle Supervisors werden immer benachrichtigt.
* Sobald eine Email-Addresse hinterlegt ist, wird diese auch immer benachrichtigt.

richtig?

**Comment by phoettli** [comment]
@nimaai sehr cool, danke!

könnten die Mails auch differenziert sein?

```
+--------------------------------++-----------------------------------------------------------------------+
| Notification settings          || Entities to be notified                                               |
+================================++=======================================================================+
| All members | DG Email defined || Supervisors | Sv mail | Users | Ur mail | Groups | Gp mail | DG Email | 
+-------------+------------------++-------------+---------+-------+---------+--------+---------+----------+
| true        | no               || yes         | setting | yes   | setting | yes    | setting | no       | *)
| true        | yes              || yes         | no      | yes   | no      | yes    | no      | yes      |
| false       | no               || yes         | setting | no    | no      | no     | no      | no       |
| false       | yes              || yes         | no      | no    | no      | no     | no      | yes      |
+-------------+------------------++-------------+---------+-------+---------+--------+---------+----------+
*) Avoid multiple Emails for Supervisors, if Supervisor is also Group Member or listet as User
```

so wäre:
- Zeile 1: Fälle 1a & 1b
- Zeile 2: war bei mir nicht vorgesehen. vielen Dank für deine Ergänzung !
- Zeile 3: Fall 2
- Zeile 4: Fall 3

Könnte das so klappen?

**Comment by nimaai** [comment]
@phoettli was meinst du mit "differenziert"? was bedeuten die spalten: "Sv mail", "Ur mail", "Gp mail" mit je "setting/no"?

**Comment by phoettli** [comment]
@nimaai 
> @phoettli was meinst du mit "differenziert"? was bedeuten die spalten: "Sv mail", "Ur mail", "Gp mail" mit je "setting/no"?

DG Mail: Delegation Email Überschreibung
Sv Mail: Supervisor Email (gemäss Settings in Webapp): Notifikationen, die per Mail verteilt werden sofern gesetzt
Ur Mail: User Email (gemäss Settings in Webapp): Notifikationen, die per Mail verteilt werden sofern gesetzt
Gp Mail: Group Email, resp. Group Members (gemäss Settings in Webapp): Notifikationen, die per Mail verteilt werden sofern gesetzt

**Comment by nimaai** [comment]
@phoettli gemäss aktueller spezifikation werden die benachrichtigungen an die delegationsemail einzeln und augenblicklich verschickt (keine Option für daily/weekly). ist es ok so? das würde einiges vereinfachen... 🙏

**Comment by phoettli** [comment]
hmm, guter Punkt @nimaai !
Merke grad: das ist irgendwie nicht zuende gedacht. Einzelhinweise wären ansich schon cool, wenn da aber 250 Mails losgefeuert werden, ist das wohl nicht so angenehm.
Andererseits sind aber Zusammenfassungen mit unterschiedlicher Herkunft auch nicht ideal.
Dazu werden wir uns noch Gedanken machen müssen und eine Lösung finden.

Lass doch vorerst mal Einzelmails. Optimierung sobald Lösung bekannt...

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/01bed56a48025b9568361f56e42fbd7e1f3b8c87

**Comment by phoettli** [comment]
OK soweit ich testen kann auf `STAGING`, Mail geht aber noch nicht.
