### ISSUE TITLE
Notifikationen: Mechanismus für periodischen Emailversand

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#553]
@DrTom ich schlage zwei Cron-Jobs (mit entsprechenden Rake-Tasks) a la Leihs vor fürs "daily" und "weekly" Versand. D'accord?

To-Do:
- [x] nightly jobs
- [x] weekly jobs

**Comment by DrTom** [comment]
Ja, aber im Detail:  nicht cron sondern Systemd Oneshot Service  und Systemd Timer.

**Comment by nimaai** [comment]
@DrTom Mehr oder weniger copy-paste von [leihs_deploy](https://github.com/leihs/leihs_deploy/tree/master/roles/leihs-legacy-install/templates), oder?

**Comment by nimaai** [comment]
@phoettli wöchentlicher versand an welchem tag und welcher uhrzeit? den täglichen kann man in der nacht machen (wie in leihs).

**Comment by phoettli** [comment]
Leider hab ich keine Übersicht über sonstige Jobs. Was wäre sinnvoll?
- Samstagvormittag 11h
- Sonntagabend 22h ?
- Montagmorgen 0100h ? (mein Favorit)

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/9797cddf228712376d7c8d6e4b92ef0375a5f31a
