### ISSUE TITLE
Feature-Toggle für Workflows und Beta-Batch-Editor fehlt

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#554]
ev. seit Release [4.3.0 ](https://github.com/Madek/Madek/milestone/39)fehlen die Feature-Toggles für [Workflows](https://github.com/Madek/Madek/issues/230) und [Beta-Batch-Editor](https://github.com/Madek/Madek/issues/134)

**Comment by phoettli** [comment]
gemäss @nimaai nur User rausgeflogen.

**Comment by phoettli** [comment]
Veränderte Gruppen:
- Workflows `e12e1bc0-b29f-5e93-85d6-ff0aae9a9db0`
<img width="753" alt="image" src="https://github.com/Madek/Madek/assets/42544602/57222ed5-1316-45eb-a44e-54d549fa12c2">
seltsamerweise sind da zwei ehemalige User drin, die aktiven benötigten fehlen.

- Batch-Editor (Metadaten-Stapelverarbeitung) `8ffe3710-088c-5b31-ad23-573335c9017a`
<img width="739" alt="image" src="https://github.com/Madek/Madek/assets/42544602/d7eb381e-f32f-4584-aedb-782d2561f0f9">

**Comment by phoettli** [comment]
infolge neuem AGW durch Login aus den Gruppen geworfen:
https://madek.slack.com/archives/C7ZRE6P9Q/p1709740394749459?thread_ts=1709734059.491709&cid=C7ZRE6P9Q

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/8cd97b4a1dc1976dfaed78b22aa3513b89f2a92a

**Comment by phoettli** [comment]
Anmerkung: die Gruppen (interne Gruppen) können durch Mitglieder editiert/erweitert werden.
