### ISSUE TITLE
Notifikationen: `responsibility_transfer`

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#555]
Sammelticket für Notifikationen der Verantwortlichkeit
Teil von #409 

- [x] #556
- [x] Webapp-Anzeige
- [x] Delegationen
- [x] Email-Versand

**Comment by phoettli** [comment]
Funktionalität:

- Einzelübertragungen werden aufgeführt :)
- Wenn ich über die Stapelverarbeitung Verantwortlichkeiten übertrage, werden sie nicht aufgeführt :(

**Comment by nimaai** [comment]
batch edit gefixt: https://github.com/Madek/madek/commit/02017d808214be6b8c7f73967ab3e48ed87c95f3

**Comment by phoettli** [comment]
cool ! Stapelübertragung der Verantwortlichkeit klappt auf `Test`
<img width="770" alt="image" src="https://github.com/Madek/Madek/assets/42544602/7e51a91d-5c8d-4637-8644-25e453cea233">

Danke !
