### ISSUE TITLE
action: to add to set is in working group view disabled (concerns media entrys and sets)

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#56]
Bug was reported by Rolf Wolfensberger

![bug to add to set in working group view](https://user-images.githubusercontent.com/29139407/36662173-d1f02fe0-1add-11e8-9517-b18231f64a82.gif)

**Comment by phiku** [comment]
Hint: Without analysis, I guess it could have broken after the I18n Refactoring.

**Comment by phiku** [comment]
I will revert the I18n for "Batch Add To Set" and "Batch Remove From Set". The paths for these actions were passed wrongly. You would need to find every place where a Media Resources Box is used and make sure that the according presenters deliver the urls for theses actions if you want to add the language parameter server side.

**Comment by phiku** [comment]
@nadjaweisskopf Ready to test.

**Comment by nadjaweisskopf** [comment]
@ltsotrug Bereit zum testen auf https://test.madek.zhdk.ch.

**Comment by ltsotrug** [comment]
@nadjaweisskopf @phiku thank you, it works properly on https://test.madek.zhdk.ch
