### ISSUE TITLE
Delegation: Quellfile-Export geht nicht

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#565]
Als Mitglied einer Delegation, die die Verantwortlichkeit eines Medieneintrages innehat habe ich keine Berechtigung das Quellfile zu exportieren:
<img width="567" alt="image" src="https://github.com/Madek/Madek/assets/42544602/9cfb5c33-4efe-4a25-9295-d63db3daf43c">

Verantwortlichkeit sollte alle Rechte am Objekt besitzen, auch über eine Delegation.

**Comment by phoettli** [comment]
@urs-van-binsbergen hast du das schon auf `TEST` deployed? geht bei mir noch nicht.

**Comment by urs-van-binsbergen** [comment]
@phoettli In der Tat hat der Deploy nicht geklappt. Der erste Fix ist drauf (Verantw. übertragen / löschen), aber nicht der zweite. Ich habe den Deploy nochmals angestossen.

**Comment by urs-van-binsbergen** [comment]
PS: Deploy scheint kaputt zu sein, ich kläre das ab.
