### ISSUE TITLE
API: Sortierreihenfolge aus Web App berücksichtigen in Listen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#567]
### Ausgangslage
In der API werden Listen von Einträgen nach UUID ausgegeben. Die Sortierung wird benötigt, damit z.B. bei Paginierungen etc. keine Einträge doppelt ausgegeben werden.

### Problem
Die Web-App wird bei API-Anwendungen als Dateneingabe-Interface benutzt. Z.B. bei den Studienprojekten auf der Website. Benutzer versuchen die Listeneingaben in Reihenfolgen abzuspeichern, die in der API jedoch nicht berücksichtigt werden.
<img width="435" alt="image" src="https://github.com/Madek/Madek/assets/42544602/8cf7da75-53fc-4495-99d1-45f57568b82d">

### Lösungsvorschlag
Bei Listenfeldern (`Person`, `Keywords`), in der API die Sortierreihenfolge mitgeben.
z.B. /api/meta-data-roles/75f7b7b3-3009-43f9-9044-b5978a954cc1
<img width="432" alt="image" src="https://github.com/Madek/Madek/assets/42544602/568e1524-4c50-4480-869d-38ebc17c1348">

Brauchts da eine Auflistung der Metadaten-Felder? 
(Ich würde generisch bei allen Feldern die Sortierung ausgeben, auch wenn nicht explizit sortiert werden kann. Vielleicht folgt das ja noch. Und der API-Consumer kann dann selber entscheiden, ob und wie Sortierung übernommen werden soll.)

**Comment by DrTom** [comment]
In https://github.com/Madek/madek-api/commit/5540670c4ef24186bc0d1d167003904f2b0648ed
werden 4 Resourcen nun gemäss dem `position` Feld sortiert.  Für diese war das jetzt einfach anzupassen: es gab bisher keine Sortierung (hätte allerdings so sein sollen) und damit bricht auch nichts wenn wir diese nun einführen. 

Sind das die Fälle, die gemeint sind? Fehlen noch welche, etwa listen, die sich in einer Resources selbst befinden?

**Comment by phoettli** [comment]
Sortierung wird benötigt für:
- `zhdk_bereich:institutional_affiliation` 
- `madek_core:authors`


aber eigentlich ganz generell für:
- `"type" : "MetaDatum::Keywords",`
  - `copyright:license`
  - `madek_core:keywords`
  - ...
- `"type" : "MetaDatum::People"`
  - `madek_core:authors`
  - `zhdk_bereich:institutional_affiliation`
  - `media_object:creator`
  - ...

**Comment by DrTom** [comment]
Ich hab eine neue Version https://github.com/Madek/madek-api/commit/b48a23e1bbaa1a9d44f235ed04087540923b3b91 auf https://tom.madek.rubydev.zhdk.ch/ aufgespielt. 

Wie am commit zu sehen ist habe ich aber nicht viel Gefunden: 
1. Rollen sind nun auch sortiert (in `/meta-datum`) 
2. Keywords sollten hier schon seit dem Vorigen commit sortiert sein; das geht in https://github.com/Madek/madek-api/blob/b48a23e1bbaa1a9d44f235ed04087540923b3b91/src/madek/api/resources/meta_data/meta_datum.clj#L72 zurück auf eben diese Resource
3. bei People sehe ich nicht wo die Ordnung her kommen sollte; das geht via `meta_data_people` auf `people`; in keiner der  beiden Tabelle gibt eine `position`

**Comment by phoettli** [comment]
aktuelles Problem:

Die Bereiche können auf der ZHdK-Website nicht wie in der Web-App sortiert ausgegeben werden:

[20240312_ZHdK-Bereiche-API.pdf](https://github.com/user-attachments/files/17277886/20240312_ZHdK-Bereiche-API.pdf)

**Comment by DrTom** [comment]
Erledigt soweit wie möglich; Personen insbesondere nicht, da die Webapp dort auch noch keine Sortierung kennt: neues Ticket.

**Comment by phoettli** [comment]
Neue Tickets: #682 und #683
