### ISSUE TITLE
Verantwortlichkeit übertragen aus Delegation geht nicht in Stapelverarbeitung

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#571]
wenn ich Teil einer Delegation bin
kann ich die Verantwortlichkeit von Medieneinträgen und Sets in der Stapelverarbeitung nicht mehr übertragen z.B. an mich oder andere:
<img width="802" alt="image" src="https://github.com/Madek/Madek/assets/42544602/e482fded-8251-405e-be96-1fb5cdf15647">

Als Teil der Delegation sollten mir diese Rechte zustehen.
Die einzelne Übertragung der Verantwortlichkeit in einer Delegation funktioniert.

**Comment by phoettli** [comment]
wenn gefixt an nimaii übergeben (#555)

**Comment by urs-van-binsbergen** [comment]
@phoettli gemäss Code ist in der Stapelverarbeitung auch das Löschen von Ressourcen nicht möglich, für welche man via Delegation verantwortlich ist. Das passe ich dann auch gleich an, korrekt?

**Comment by phoettli** [comment]
sehr gerne @urs-van-binsbergen , vielen Dank!
scheint beides vergessen gegangen zu sein.

**Comment by urs-van-binsbergen** [comment]
Reopen: habe festgestellt, das der Fix nur für direkt zugeordnete Delegationen funktioniert, aber nicht via Gruppe.
