### ISSUE TITLE
Zuständigkeit definieren für Delegations

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#573]
Delegations haben keine (organisatorische) Zuständigkeit, sie wird gegenwärtig im Admin-Kommentar aufgeführt.

Lösung:
Die Delegations um Zuständigkeit ergänzen.

Aus meiner Sicht müsste die Zuständigkeit

- zwingend sein (Pflichtfeld)
- entsprechende User vor Löschen geschützt werden
- für mehrere User möglich sein

siehe auch Hinweise für [Notifikationen in Delegations](https://github.com/Madek/Madek/issues/551#issuecomment-2004345072)

**Comment by nimaai** [comment]
müssen die zuständigen personen zwingend auch mitglieder der delegation sein @phoettli ?

**Comment by phoettli** [comment]
@nimaai nein, es sollten auch Nichmitglieder möglich sein. Insbesondere bei leeren Delegations.

**Comment by nimaai** [comment]
@phoettli wie will man mit bestehenden delegationen vorgehen? wollt ihr sie manuell bearbeiten und einen (oder mehrere) zuständigen eintragen? dann würde ich den constraint (dass jede delegation mindestens einen zuständigen haben muss) später aufschalten. sonst müsste man eine entsprechende migration definieren, durch welche man die zuständigen eintragen würde.

**Comment by phoettli** [comment]
@nimaai gerne Schritt für Schritt: 1. Zuständige manuell eintragen, 2. wenn wir sie alle erfasst haben, Constraint ergänzen.

**Comment by nimaai** [comment]
umgesetzt: https://github.com/Madek/madek/commit/16dad2d87a1f58f02bfced0b5b0030482de47cb9

man kann mit 1. beginnen sobald auf prod deployed @phoettli

**Comment by phoettli** [comment]
Schritt 2 erfolgt in #592

**Comment by phoettli** [comment]
@nimaai Die Unterscheidung zwischen technischen und administrativen Usern ist nicht direkt ersichtlich. Könnten die verschiedenen Funktionen der Userzuordnung besser/transparenter sichtbar gemacht werden? (User mit Aufgaben (technisch) vs. administrative User (Zuständigkeit))

<img width="1120" alt="image" src="https://github.com/Madek/Madek/assets/42544602/dfa66845-0c9f-416b-8a93-9be97cf9c5af">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/51a255e1d5e69a7c83e9c50e4b0469c901eadfe6

**Comment by phoettli** [comment]
@nimaai super! vielen Dank!
