### ISSUE TITLE
zweistufige Löschung der ME/Metadaten/Files & Sets

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#576]
Einträge werden ggw. definitiv gelöscht. Neu sollen sie eine gewisse Zeit lang wiederherstellbar sein.

### Welche Einträge:
- Medieneinträge
   - Original-File
   - ev. enthaltene Previews (möglicherweise nicht nötig, weil wiederherstellbar)
   - Zugriffsrechte
   - UUID
   - ggf. speaking URL
   - Zusammenhänge
   - ... ? 
- Sets
   - Zugriffsrechte
   - UUID
   - ggf. speaking URL
   - Zusammenhänge 
- ...

### Ablauf:
    1. Löschvorgang in Webapp => Eintrag markieren mit deaktiviert Flag,
        - in Webapp: nicht mehr sichtbar/aufrufbar
        - in API: ME bzw. Set, File und Previews: Hinweis auf Gelöscht: `410` ?
    3. Admin kann wiederherstellen
    4. definitiv entfernen (nach 180 Tagen)

Files ev. erst im Media-Service zu lösen. In Metadaten eher schwierig und sehr aufwändig.

=> viel Aufwand

zu klären:
- verschiedene Abhängigkeiten z.B.
   - sprechende URL
   - Keywords
   - Links (früherer Eintrag)
   - People
   - User

mögliches Vorgehen
- erster Vorstoss in Datenbank abklären
- Alternativvorschlag: alle relevanten Inhalte versionieren
==> Timebox

**Comment by nimaai** [comment]
to-do:
- [ ] funktionalität: https://github.com/Madek/madek/commit/369c672db70e7a38857eee72c3d53cc72cfc3615
- [ ] aufräum-job

**Comment by phoettli** [comment]
@nimaai Funktionalität ist cool !
aus meiner Sicht müssten zwei Punkte noch ergänzt werden:
- Visuelle Kennzeichnung des gelöschten ME im Frontend (z.B. roter Error-Balken (This ... ist deleted, not visible to User))
- Aussagekräftiger Hinweis, wenn man User löschen möchte und wegen Abhängigkeit nicht möglich.

API muss ich noch Checken.

**Comment by phoettli** [comment]
<img width="1072" alt="image" src="https://github.com/Madek/Madek/assets/42544602/824e9533-2e43-4a5e-982b-c62622465c53">
Text z.B.

DE: Dieser Medieneintrag wurde gelöscht, für Benutzer nicht mehr sichtbar
EN: This media entry has been deleted and is no longer visible to users.

DE: Dieses Set wurde gelöscht, für Benutzer nicht mehr sichtbar
EN: This Set has been deleted and is no longer visible to users.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/1dc36980b09a5593c4682a2fb7a88d47814876c9

**Comment by phoettli** [comment]
Löschen über Stapelverarbeitung geht nicht über Soft Delete, sowohl Set wie Medieneintrag. Solche Elemente werden direkt vollständig gelöscht.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/7c757f1919ebdc4e81ff152af95c6dfb75ce31df
