### ISSUE TITLE
Zweitstufige Löschung (Minimal-Variante)

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#577]
#576

### Problem
Quellfiles werden bei Löschung direkt entfernt.

### Anforderung
Quellfiles sollen nicht direkt gelöscht werden können, da sonst potentieller Datenverlust droht

### Lösungsmöglichkeiten

die Files bleiben n Tage nach Löschung verfügbar, ebenfalls Medieneintrag in Rumpf-Version, ggf. Metadaten als JSON verfügbar, im Schadenfall Metadaten und Berechtigungen in Audit verfügbar.

(JSON könnte ggf. auch als Metadaten-Export verwendet werden)

### Umsetzung => zu prüfen
Z.B. bei Löschung

1. File-Eintrag mit gelöscht Flag versehen
2. Metadaten z.B. als JSON-Sidecar ablegen
3. wie kann UUID von Medieneintrag wiederherstellbar bleiben ?
4. nach n Tagen File und markierten File-Eintrag über Cron o.ä. entfernen
5. Braucht es spezielle Sicherheitsabfragen, damit nicht versehentlich falsche Files entfernt werden?

**Comment by nimaai** [comment]
muss nochmals im gesamtkontext von https://github.com/Madek/Madek/issues/576 mehr refined werden (@drtom u. co.)

**Comment by phoettli** [comment]
versuchen vollständige Lösung #576 umzusetzen.

**Comment by phoettli** [comment]
#576 wurde umgesetzt
