### ISSUE TITLE
Make support-email-adress configurable, and show in error messages

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#58]
Write "..., dann kontaktieren SIe bitte den Support ihrer Institution mit einer Beschreibung ..." --> ohne E-Mail-Adresse. 

<img width="665" alt="bildschirmfoto 2018-02-26 um 15 22 47" src="https://user-images.githubusercontent.com/3356016/36675328-ed43abf2-1b08-11e8-846b-12a8720eaf0b.png">

**Comment by nadjaweisskopf** [comment]
Evtl. ein Admin-Feld zur Verfügung stellen, um die Support-ID zu hinterlegen.

**Comment by phoettli** [comment]
Vorschlag: Config file? z.B. auch für 
- Workflow Default-Felder
- Superadmin ?
- weitere Lokale Settings (Zencoder Settings usw.)

**Comment by eins78** [comment]
> Vorschlag: Config file? z.B. auch für

Jep, das gibt es genau wie beschrieben :) https://github.com/Madek/madek-deploy/blob/24438ff1eae58053ce868e68b687324fea9802b0/inventories/zhdk/group_vars/zhdk.yml

Wenn sich die support-email in der praxis so selten ändert, und auch sonst nix dafür spricht es in die DB zu tun, kann das auch da rein. Aufwand ist fast gleich in beiden Fällen, aber eh gering.
