### ISSUE TITLE
upgrade ruby to 3.2

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#584]
- [x] admin-webapp (https://github.com/Madek/madek/commit/332b4a31fdc9b76eb9ebbc877dba0d68ed5d49d6)
- [x] webapp

**Comment by nimaai** [comment]
@urs-van-binsbergen bitte analog zu leihs

**Comment by urs-van-binsbergen** [comment]
30b5e0371f1c462fccfcf953abfd9956e8d1b83b
