### ISSUE TITLE
Server-Fehler auf Keyword-Seite

### ISSUE THREAD

**Issue by ltsotrug** [Madek/Madek#585]
https://medienarchiv.zhdk.ch/explore/keywords

Die Fehlermeldung tritt in allen Browsern auf.

![fehler-explore-keywords](https://github.com/Madek/Madek/assets/29139407/a9111d7f-b45a-4a5e-a2d7-732f8fbb2df2)

**Comment by urs-van-binsbergen** [comment]
Das ist kaputt seit https://github.com/Madek/Madek/issues/443
Leider keine Spec für dieses Feature, daher nicht erkannt. 
Fix inkl. Spec wird demnächst auf `master` gemerget

**Comment by urs-van-binsbergen** [comment]
5a0781957fb51c4c358ab3ecfbc6b1013798d8e8
