### ISSUE TITLE
Constraint für Zuständigkeit der Delegation einrichten

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#592]
die Zuständigkeit für Delegation wurde hier eingerichtet: #573 

nach dem manuellen Nachführen der Zuständigkeiten durch Support

die Bedingung auf Zuständigkeit (Constraint) scharfschalten.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/9d0607fb72d20e1c6b6c67a2f135bda0418ced36
