### ISSUE TITLE
Session cookie is missing the 'secure' flag

### ISSUE THREAD

**Issue by eins78** [Madek/Madek#593]
The session cookie set by Madek auth should set the 'secure' flag.

## steps to reproduce

```
❯ curl -sfI https://medienarchiv.zhdk.ch | grep -i set-cookie
```

actual:
```
set-cookie: _madek_session=xxx…xxx; path=/; HttpOnly; SameSite=Lax
```

expected:

```
set-cookie: _madek_session=xxx…xxx; path=/; secure; HttpOnly; SameSite=Lax

```

**Comment by eins78** [comment]
See here: https://github.com/Madek/madek-auth/blob/e77cc41093f84291157068a58cb35c0a30448383/cljc-src/madek/auth/http/session.clj#L80

**Comment by DrTom** [comment]
It seems possible to alter some cookies via https://httpd.apache.org/docs/2.4/mod/mod_headers.html

**Comment by DrTom** [comment]
Works via Proxy:

```
set-cookie: madek-session=REPLACED;HttpOnly;Path=/;Secure
```

**Comment by eins78** [comment]
for future reference, the actual apache config is:

```
Header edit Set-Cookie "(.*)" "$1;Secure"
```
