### ISSUE TITLE
Spracheinstellung für Emailversand beim User speichern

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#598]
Für den Emailversand muss vom User die Spracheinstellung der Emails gewählt werden können.

**Comment by urs-van-binsbergen** [comment]
Wenn fertig: @urs-van-binsbergen informieren, um den Settings-Dialog mit der Sprachwahl zu ergänzen.

**Comment by nimaai** [comment]
backend done: 
https://github.com/Madek/madek/commit/41e351d5a1a504f2d4352c09dc87727b58450121

**Comment by urs-van-binsbergen** [comment]
c92c2d57e5b30db15da2f5801d8c2146cfe51807
