### ISSUE TITLE
unflätige Bots sperren

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#600]
gewisse Bots belasten das System etwas arg.
Sperren.

**Comment by phoettli** [comment]
https://madek.slack.com/archives/C7ZRE6P9Q/p1714487675529809?thread_ts=1714486071.046719&cid=C7ZRE6P9Q

**Comment by phoettli** [comment]
funktioniert. Mit Erfolg !

**Comment by DrTom** [comment]
Uff:

> ** muss noch ins Deploy **

**Comment by DrTom** [comment]
https://github.com/Madek/madek/commit/f034598235f24be1b18f0c25328055ee2b993afa
