### ISSUE TITLE
Feature-Bilder auf Startseite schneller laden

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#603]
Die Feature-Bilder auf der Startseite brauchen relativ lange, bis sie geladen sind.
Die Zufallsberechnung verbraucht viel Zeit.
<img width="326" alt="image" src="https://github.com/Madek/Madek/assets/42544602/e062a368-8ac5-494d-926a-f3433db28575">

Kann die Zufallsberechnung vereinfacht werden?
z.B. Zufallsbild aus Einträgen 
- der letzten 14 Tage oder 
- 50 neusten Einträge berechnen

Ausserdem wäre Link zum zugehörigen Medieneintrag toll #441

Beachte: für eine statische Startseite müsste ggf. ein Pool an Feature-Bildern erzeugt werden (#604)

**Comment by urs-van-binsbergen** [comment]
Wir müssen das nochmals anschauen, weil auf TEST zeigt sich, dass die Performance dafür bei eingeloggten Usern umso schlechter ist :/

**Comment by urs-van-binsbergen** [comment]
8244f58f3ab927d5a4c114bdb7edd7fd70a1a842

OK, Performance auch für eingeloggte User jetzt gut.

**Comment by phoettli** [comment]
cool @urs-van-binsbergen 
bei mir sind jetzt allerdings häufig Bilder der ersten und zweiten Kategorie identisch.
