### ISSUE TITLE
Notifikationen für Delegations in Webapp

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#614]
Subtask von #409

Notifikationen von Delegations sollen in der Webapp dargestellt werden.

Mehrere Optionen sind denkbar siehe unten:

- [Option 1](#issuecomment-2163629971): Alle Notifikationen zur Verantwortlichkeit wild durcheinander mit Möglichkeit zum filtern
- [Option 2](#issuecomment-2163631143): Notifikationen nach persönlich/Delegation/en gruppiert (würde dann auch für _Wetterbericht_ gelten)
- [x] [Option 3](#issuecomment-2163645246): jeweils nur die ersten 20 Einträge anzeigen mit Erweiterungsmöglichkeit
- [Option 4](#issuecomment-2163710007): wild durcheinander, Filter gilt für ganze Seite Notifikationen inkl. _Wetterbericht_

mein persönlicher Favorit: Option 3 oder Option 4

**Comment by phoettli** [comment]
### Option 2

<img width="1147" alt="image" src="https://github.com/Madek/Madek/assets/42544602/bef03be2-74d1-4d60-a160-d1bfaa13748b">

**Comment by phoettli** [comment]
### Option 3: Erweiterungsmöglichkeit

<img width="1147" alt="image" src="https://github.com/Madek/Madek/assets/42544602/c8dee7ba-ddd9-4b4a-bc80-3996c1d7334e">

**Comment by phoettli** [comment]
### Option 4 Möglichkeit die ganze Seite Notifikation zu filtern

<img width="1158" alt="image" src="https://github.com/Madek/Madek/assets/42544602/912dd104-05bb-43e6-b2c2-19efe735bda9">

**Comment by urs-van-binsbergen** [comment]
Ich würde im ersten Schritt die einfachste Variante wählen (einfach auch für die User): Option 2.

**Comment by phoettli** [comment]
@urs-van-binsbergen da bräuchte es m.M.n. aber noch ein Inhaltsverzeichnis mit Sprungmarken, wenn z.B. 75 Inhalte übertragen wurden. Nicht zuletzt auch um zu erkennen, welche Notfikationen es überhaupt gibt z.B. Wetterbericht für Delegation A und später abgeschlossene Encodings für mich persönlich irgendwo weit unten.

Wie sieht es mit der Ladezeit aus, bei z.b 200 Einträgen (Stapelübertragung) ?

**Comment by urs-van-binsbergen** [comment]
Ladezeit ist bei 200 Records sicher noch kein Problem. 

Länge der Seite: Wir haben ja auch noch die automatische Einklappung bei mehr als 3 Records pro Tag. Aber Sprungmarken machen wohl Sinn. Oder eine Einklappung pro Typ analog zu Datum.

**Comment by phoettli** [comment]
@urs-van-binsbergen Wie wäre?
- 20 Einträge direkt anzuzeigen
- den Link aus Option 3 "Alle Anzeigen ->" als Ausklappung zu verwenden
- ein Maximum von 200 Einträgen ausgeklappt auszugeben mit Option "Mehr Inhalte werden geladen" wie in Aktivität, damit die Seite nicht bricht, falls es zu viele Einträge gibt?

**Comment by phoettli** [comment]
@urs-van-binsbergen 

<img width="1145" alt="image" src="https://github.com/Madek/Madek/assets/42544602/6cc92aec-5578-4feb-b312-51ca43e28385">


Anmerkung:
- Ausklappung über Titel mit Dreieck funktioniert nicht, wenn ein Teil der Einträge bereits angezeigt wird. Ich würde trotzdem über Link "Alle anzeigen" gehen, einfach ohne Rechtspfeil.

Alles klar?

**Comment by urs-van-binsbergen** [comment]
f6c5dd137c23e7d98fc1ac99090c99651ddec0c9

**Comment by phoettli** [comment]
Delegations werden nicht Aufgelöst bei Übertragung aus Delegation: #637
