### ISSUE TITLE
Notifications: Email Templates for Delegations

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#615]
Subtask von #409

Die Email-Templates müssen für die Delegations erweitert werden.

siehe ggf. #614 
bzw. tbd.

**Comment by phoettli** [comment]
@nimaai Vorschlag für E-Mail-Templates:

### für alle Notifikationen

_Subject_
`[SITE_TITLES-Notifikation] Notifikationen vom DATUM UHRZEIT`

_Mailtext_
```
Guten Tag
Notifikationen von SITE_TITLES
```

### für Verantwortlichkeit
```
übertragene Verantwortlichkeiten, die Sie betreffen:

Verantwortlichkeit an Sie übertragen (7)
* 25.05.2024 - Verantwortlichkeit für Medieneintrag [Hansdampf](https://link.zum/medieneintrag/) wurde von Dampf Hans an Sie übertragen
* 26.05.2024
    * 10:51 – Verantwortlichkeit für Medieneintrag [2xx](https://link.zum/medieneintrag/) wurde von Mark Bein an Sie übertragen.
    * 10:53 – Verantwortlichkeit für Medieneintrag [3xx](https://link.zum/medieneintrag/) wurde von Mark Bein an Sie übertragen.
* 29.05.2024
    * 18:11 – Verantwortlichkeit für Set [Hochschulkommunikation](https://link.zum/set/) wurde von Kurt C. Hose an Sie übertragen
    * 18:12 – Verantwortlichkeit für Medieneintrag [der Sommer kommt](https://link.zum/medieneintrag/) wurde von Kurt C. Hose an Sie übertragen
    * 18:13 – Verantwortlichkeit für Medieneintrag [kommt er wirklich?](https://link.zum/medieneintrag/) wurde von Kurt C. Hose an Sie übertragen
* 31.05.2024 – Verantwortlichkeit für Set [Mimimi](https://link.zum/set/) wurde von g_Alles-zu-mir an Sie übertragen


Verantwortlichkeit übertragen an Verantwortungs-Gruppe g_Alles-zu-mir (2)
* 29.05.2024 – Verantwortlichkeit für Set [Mimimi](https://link.zum/set/) wurde von d_wir-wollen-nix an g_Alles-zu-mir übertragen
* 31.05.2024 – Verantwortlichkeit für Set [Momomo](https://link.zum/set/) wurde von Momo Omo an g_Alles-zu-mir übertragen


Verantwortlichkeit übertragen an Verantwortungs-Gruppe d_wir-wollen-nix (4)
* 27.05.2024
    * 16:35 – Verantwortlichkeit für Set [Mauerblümchen](https://link.zum/set/) wurde von A. Hörnchen an d_wir-wollen-nix übertragen
    * 18:12 – Verantwortlichkeit für Medieneintrag [Einzweidreivier](https://link.zum/medieneintrag/) wurde von B. Hörnchen an d_wir-wollen-nix übertragen
    * 18:13 – Verantwortlichkeit für Medieneintrag [Blau ist der Himmel, der Himmel ist schön](https://link.zum/medieneintrag/) wurde von C. Hörnchen an d_wir-wollen-nix übertragen
* 28.05.2024 – Verantwortlichkeit für Set [Mimimi](https://link.zum/set/) wurde von Hans Gwüsst an d_wir-wollen-nix übertragen
```


### Footer für alle Notifikationen
```
Diese E-Mail bekommen Sie [entsprechend Ihrer Einstellungen](https://DOMAIN/my/settings) im SITE_TITLES. 
Die von Ihnen gewählte Häufigkeit für E-Mail-Notifikationen: HÄUFIGKEIT
Änderungen Ihrer Einstellungen können Sie selbständig vornehmen.

Haben Sie Fragen an den Support? Kontaktieren Sie [MADEK_SUPPORT_EMAIL](mailto:MADEK_SUPPORT_EMAIL).
[PROVENANCE_NOTICES](https://DOMAIN)
```

**Comment by nimaai** [comment]
Subject:
`[SITE_TITLES-Notifikation] Notifikationen vom DATUM UHRZEIT`

@phoettli was ist mit `DATUM UHRZEIT` gemeint?

**Comment by nimaai** [comment]
@phoettli wir brauchen auch templates für die augenblicklichen einzelnen emails.

**Comment by phoettli** [comment]
@nimaai
>  was ist mit DATUM UHRZEIT gemeint?

z.B.: 25.7.2024 11:19

**Comment by nimaai** [comment]
@phoettli ist das die uhrzeit vom verschicken der email selbst oder was für eine?

**Comment by nimaai** [comment]
```
Verantwortlichkeit an Sie übertragen (7)
* 25.05.2024 - Verantwortlichkeit für Medieneintrag "Hansdampf" wurde von Dampf Hans an Sie übertragen https://link.zum/medieneintrag/
* 26.05.2024
    * 10:51 – Verantwortlichkeit für Medieneintrag "2xx" wurde von Mark Bein an Sie übertragen https://link.zum/medieneintrag/
    * 10:53 – Verantwortlichkeit für Medieneintrag "3xx" wurde von Mark Bein an Sie übertragen https://link.zum/medieneintrag/
```

@phoettli warum kann mein am 25.05. auf die genau uhrzeit verzichten und am 26.05. nicht? warum spielt sie am mehreren notifikation pro tag eine rolle?

**Comment by phoettli** [comment]
> 25.05. auf die genaue uhrzeit verzichten und am 26.05.

das ist eine Gute Frage @nimaai 
Als Sortierungselement finde ich die Uhrzeit eine gelungene Information. Wenns an einem Tag nur eine Notifikation gibt, braucht sie ja nicht sortiert zu werden. Ist übrigens analog der Darstellung in der [Webapp](https://github.com/Madek/Madek/issues/614#issuecomment-2185273499).

**Comment by phoettli** [comment]
> wir brauchen auch templates für die augenblicklichen einzelnen emails.

kannst du mir auflisten, welche Templates du alles brauchst? In Kleinportionen wird es sonst etwas unübersichtlich :/

**Comment by nimaai** [comment]
@phoettli 

```
+-----------------+---------------+-----------------------------------+
|                 |  User's email | Delegation's email (unpersőnlich) |
+-----------------+---------------+-----------------------------------+
| Einzeln         |               |                                   |
| Zusammenfassung |  vorhanden    | n.a.                              |
+-----------------+---------------+-----------------------------------+
```

In der Kombination "Zusammenfassung" + "Delegation's email (unpersőnlich)" werden gemäss vorherigen Absprache und Implementierung **nur** einzelne Emails verschickt.

**Comment by nimaai** [comment]
```
Haben Sie Fragen an den Support? Kontaktieren Sie mailto:MADEK_SUPPORT_EMAIL.
PROVENANCE_NOTICES https://DOMAIN
```
@phoettli von wo kommen `MADEK_SUPPORT_EMAIL` und `PROVENANCE_NOTICES` ?

**Comment by phoettli** [comment]
a) `/admin` > System > Storage > Deploy-Config > `madek_support_email`

b) `/admin/app_settings` > General > `provenance_notices`

**Comment by phoettli** [comment]
uups, da gab es glaub ein Missverständnis @nimaai :
> In der Kombination "Zusammenfassung" + "Delegation's email (unpersőnlich)" werden gemäss vorherigen Absprache und Implementierung nur einzelne Emails verschickt.

Das würde bei einem Stapel von 500 Übertragungen 500 Mails auslösen? :/
Aus meiner Sicht sollte die Zusammenfassung hier `täglich` lauten.

**Comment by phoettli** [comment]
deine Rückfragen haben mich nochmal zum Überdenken gebracht @nimaai 
Sinnvollerweise sind die Notifikations-Subjects für jeden Typ eindeutig und auch entsprechend individuell, d.h. Encodings verschicken eigene Mails, Verantwortlichkeit-Übertragung verschickt eigene Mails etc.
Das würde für die Subject der Verantworltichkeits-Übertragung dann wie folgt aussehen:

Subjects für die verschiedenen Mails:

#### Verantwortlichkeit persönlich, sofort
_Subject_
 `[SITE_TITLES-Notifikation] Verantwortlichkeits-Übertragung vom DATUM UHRZEIT`

#### Verantwortlichkeit persönlich, täglich
_Subject_
` [SITE_TITLES-Notifikation] tägliche Zusammenfassung der Verantwortlichkeits-Übertragungen vom DATUM UHRZEIT`

#### Verantwortlichkeit persönlich, wöchentlich

_Subject_
`[SITE_TITLES-Notifikation] wöchentliche Zusammenfassung der Verantwortlichkeits-Übertragungen vom DATUM UHRZEIT`


#### Verantwortlichkeits-Gruppen (unpersönlich), täglich
_Subject_
` [SITE_TITLES-Notifikation] tägliche Zusammenfassung von Verantwortlichkeits-Übertragungen an Verantwortlichkeits-Gruppen vom DATUM UHRZEIT`


Die ensprechenden Subjects für Encoding-Hinweise erstelle ich dir [in separatem Ticket](https://github.com/Madek/Madek/issues/654#issuecomment-2258995592). Dann könnte man ev. Variablen verwenden...

**Comment by nimaai** [comment]
@phoettli kein missverständnis, da du es selber bestätigt hast
> Lass doch vorerst mal Einzelmails.

https://github.com/Madek/Madek/issues/551#issuecomment-2186369821

aber wir können es, wie damals von dir schon erwartet, jetzt noch anpassen. 

also: `täglich` auf die delegationsemail ohne möglichkeit im UI umzustellen, richtig?

**Comment by phoettli** [comment]
da sieht man mal, wie Weitsicht das Hirn lüftet @nimaai ;) Danke für den Hinweis!

ich glaub, umstellen auf `täglich` wäre super, wenn das geht. Und sinnvoll.

**Comment by nimaai** [comment]
@phoettli was repräsentiert genau "DATUM UHRZEIT" im Betreff von täglichen/wöchentlichen Emails?`

und ich brauche noch ein Body-Template für **Verantwortlichkeit persönlich, sofort**.

**Comment by nimaai** [comment]
@phoettli betreffend: **Verantwortlichkeits-Gruppen (unpersönlich), täglich**

`[SITE_TITLES-Notifikation] tägliche Zusammenfassung von Verantwortlichkeits-Übertragungen an Verantwortlichkeits-Gruppen vom DATUM UHRZEIT`

Ich interpretiere es als bekäme jede Delegation die Zusammenfassung der Übertragungen an sämtlichen anderen Delegationen an ihre Notifikation-Email-Adresse zugeschickt. Das macht mit unserem aktuellen Datenmodell kein Sinn. Falls das aber so gewünscht ist, dann würde ich die `notifications_email` bei den Delegationen entfernen und eine globale Email-Einstellung einführen, die dann für alle Delegationen gilt (eine Inbox für alle Delegationen sozusagen).

**Comment by phoettli** [comment]
hoi @nimaai 
> Ich interpretiere es als bekäme jede Delegation die Zusammenfassung der Übertragungen an sämtlichen anderen Delegationen an ihre Notifikation-Email-Adresse zugeschickt.

Hier sollten Verantwortlichkeitsübertragungen nur für eine Verantwortungsgruppe zusammengefasst werden.
Ich bin jedoch davon ausgegangen, dass Mails per User aufbereitet werden. Was passiert also in dem speziellen Fall, wenn ein User in mehreren Verantwortlichkeitsgruppen (Delegations) ist, dafür Mail-Notifikationen bekommt und zufälligerweise mehrere Übertragungen in mehreren Delegations stattgefunden haben? Müssten dann (und natürlich nur dann) nicht alle Übertragungen nach Delegations zusammengefasst in einer Mail verschickt werden?

**Comment by phoettli** [comment]
@nimaai 
> Wenn es sich dabei um Zeitpunkt vom Versenden handelt, dann sieht der User wann sie in seine/ihre Mailbox reingekommen ist.

Da geb ich dir grundsätzlich recht.  Filtern, suchen oder ordnen lässt sich leichter, wenns im Subject steht bzw. das Subject sich unterscheidet, als wenn immer die selben Subjects mit unterschiedlichen Inhalten versehen sind. Mit Datum finde ich also übersichtlicher. Kannst du aber machen wie für dich geht.

**Comment by phoettli** [comment]
> und ich brauche noch ein Body-Template für Verantwortlichkeit persönlich, sofort.

oh Mist, können wir diese Einstellung unterbinden bei den Verantwortlichkeiten? Das wird sonst im schlimmsten Fall zur Spamschleuder (Stapelverarbeitung von z.B. 255 Einträgen).
Oder falls nicht geht, ein Delay von einer Stunde? Das wäre dann aber blöd bei den abgeschlossenen Encodings, dort sollten die Mails sofort verschickt werden... Hast du eine Idee @nimaai ?

**Comment by nimaai** [comment]
>persönliche Mail
Ich bin jedoch davon ausgegangen, dass Mails per User aufbereitet werden. Was passiert also in dem speziellen Fall, wenn ein User in mehreren Verantwortlichkeitsgruppen (Delegations) ist, dafür Mail-Notifikationen bekommt und zufälligerweise mehrere Übertragungen in mehreren Delegations stattgefunden haben? Müssten dann (und natürlich nur dann) nicht alle Übertragungen nach Delegations zusammengefasst in einer Mail verschickt werden?

das ist so

**Comment by nimaai** [comment]
>oh Mist, können wir diese Einstellung unterbinden bei den Verantwortlichkeiten? Das wird sonst im schlimmsten Fall zur Spamschleuder (Stapelverarbeitung von z.B. 255 Einträgen).
Oder falls nicht geht, ein Delay von einer Stunde? Das wäre dann aber blöd bei den abgeschlossenen Encodings, dort sollten die Mails sofort verschickt werden... Hast du eine Idee @nimaai ?

ich habe es gerade mit @urs-van-binsbergen besprochen. lösung: die mail-einstellung von "sofort" bei diesem notification-case verunmöglichen.

**Comment by phoettli** [comment]
> die mail-einstellung von "sofort" bei diesem notification-case verunmöglichen.

ausgezeichnet @nimaai , vielen Dank !

**Comment by nimaai** [comment]
@phoettli wie soll man mit langen emails umgehen? z.b. der fall, dass an einem tag 250 übertragungen (über batch usw.) stattgefunden haben.

**Comment by phoettli** [comment]
was schlägst du vor @nimaai ?
Gibt es eine Begrenzung?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/a23315bf9ba4f8820926aeda18e5d3c1b1cd2096

**Comment by nimaai** [comment]
@phoettli in SMTP protokoll gibt es keine limit definition. alles hängt von jeweiligem client und server ab.

**Comment by nimaai** [comment]
@phoettli von welcher dimension an notifikationen-menge gehst du aus in worst-case-szenario? gesammelt pro woche.

**Comment by nimaai** [comment]
mehr zu diesem thema in https://github.com/Madek/Madek/issues/668
