### ISSUE TITLE
Verwirrende Angaben zu deaktiviertem User in Admin App

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#617]
Die Angaben zu gelöschtem User sind verwirrend.
Die Admin App zeigt z.B. bei User `6fa20365-591f-418d-aba4-6e0b66267683`
- in der Listenansicht korrekt `Deactivated`
- in der Detailansicht
<img width="678" alt="image" src="https://github.com/Madek/Madek/assets/42544602/23b41f5c-59d8-4cad-acd3-885aaeb83b37">

- im Edit-Modus allerdings
<img width="318" alt="image" src="https://github.com/Madek/Madek/assets/42544602/9252f4b6-420f-444b-9cf5-67af030ad49e">
 

m.M.n. sollte das aktiv gesetzte Datum angezeigt werden, wenn eines gesetzt ist.

**Comment by nimaai** [comment]
https://github.com/Madek/Madek/issues/617
