### ISSUE TITLE
Aussagekräftiger Hinweis bei Lösch-Fehler infolge Softdelete

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#622]
der Soft-Delete #576  sperrt Inhalte vor der Darstellung.

Wenn man abhängige Inhalte wie z.B. User löschen möchte, für die nach ME oder Sets im Softdelete bestehen, fehlt ein aussagekräfitiger Fehlerhinweis.
Man sieht dann zwar keine abhängigen MEs oder Sets, muss dann aber die Löschmarkierten Inhalte suchen gehen.

<img width="330" alt="image" src="https://github.com/Madek/Madek/assets/42544602/3c5364c2-08c0-483b-80fb-060d89bbb53d">
<img width="877" alt="image" src="https://github.com/Madek/Madek/assets/42544602/ad2a5f3b-f459-45ca-b415-1aa219a2cb78">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/325cbee0094cf3dedd743dbb8d66a82dd8bef7e5
