### ISSUE TITLE
Server BasicAuth and new API don't work together

### ISSUE THREAD

**Issue by DrTom** [Madek/Madek#629]
Reproduce:

1. the server is configured to be using BasicAuth
2. the user enters via the main route and provides BasicAuth parameters via the Browser
3. the user visits /api-v2/api-docs/index.html : the api service will then respond with 401; it tries to use BasicAuth information which is not correct; 

Now the user is stuck in an loop and can not access the new API. 

After responding with 401 the browser does not remove basic auth. There seems to be something wrong with response here.

**Comment by DrTom** [comment]
This problem could also be resolved by other means than fixing it with https://github.com/Madek/Madek/issues/630

**Comment by SeduroDotCom** [comment]
@DrTom Current state

FYI: basicAuth has been removed from api-v2 _> https://github.com/Madek/Madek/issues/630

Test & Staging
- Madek is protected by rproxy basicAuth
- No rproxy/basicAuth protection for api-v2-endpoints
      - https://test.madek.zhdk.ch/api-v2/api-docs/index.html
      - https://test.madek.zhdk.ch/api-v2/auth-info
      - https://test.madek.zhdk.ch/api-v2/app-settings

Production
   - all /api-v2/* are not accessible
   - Displayed: **Madek API-V2 Disabled**
