### ISSUE TITLE
adjustable set cover : user should be able to scale and to position the set cover

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#63]
often reported by new user

<img width="158" alt="20180227 set cover" src="https://user-images.githubusercontent.com/29139407/36736551-35d992b6-1bd9-11e8-9a27-2f6da5e53f21.png">

**Comment by eins78** [comment]
steps:
- [ ] remove set-cover styles and handle images like for entry
- [ ] deploy to test
- [ ] feedback via @ltsotrug

**Comment by eins78** [comment]
@ltsotrug  as we've discussed, there is now a version on staging that handles images for set-cover like for entries (no scaling). please check if this would be an enhancement to the status quo.
(I say: It is not perfect in all cases, but neither is the current version. We can swap one kind of ugliness against another. But this version is easier to handle for users that want to make a specific cover image and have it look good – just make it square)
Data is still synced nightly, so you can create test data on prod and look at it the next day.
It will be on this server until we do the next Release Candidate, we'll stay in touch about that.
@susanneschumacher, you might want to have a look as well.
https://staging.madek.zhdk.ch/sets

**Comment by ltsotrug** [comment]
Thank you @eins78. Rolf and I prefer the new user friendly no-scale-version.

**Comment by eins78** [comment]
will be in next release
