### ISSUE TITLE
Remove BasicAuth in api-v2

### ISSUE THREAD

**Issue by DrTom** [Madek/Madek#630]
Using basic auth in the reverse proxy server and using basic-auth in one of the services can easily cause issues. 

As the new api-v2 is not officially released yet we can remove basic-auth and avoid these Problems.

**Comment by SeduroDotCom** [comment]
@DrTom To be more precise, you want to keep rProxy-BasicAuth and remove Api-Endpoint-BasicAuth right?

**Comment by SeduroDotCom** [comment]
https://github.com/Madek/madek-api-v2/pull/16
