### ISSUE TITLE
Fehlerseite für Soft Delete Inhalte anpassen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#633]
Die Fehlerseite für Soft Delete-Inhalte (#576 )

<img width="793" alt="image" src="https://github.com/Madek/Madek/assets/42544602/6019bf0b-4a0c-4e11-99cd-1667970fec59">

sollte 404 sein.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/efd154c41632adae1aa14477d7c9319920f17e16
