### ISSUE TITLE
Delegation in Notifikation lesbar identifizieren

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#637]
Delegation wird in den Notifikationen nicht verständlich ausgegeben:

<img width="857" alt="image" src="https://github.com/Madek/Madek/assets/42544602/99675e09-1ee7-4d40-bd29-6569bb6e1b7a">

Bitte Bezeichnung auflösen

**Comment by urs-van-binsbergen** [comment]
Ups... worked on my machine 🤔 Ich schaue das an, danke für die Meldung.

**Comment by urs-van-binsbergen** [comment]
Ach so, das ist gar kein Frontend-Thema, sondern entsteht an der Quelle.
