### ISSUE TITLE
Mapping of keys to other meta keys

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#64]
The Meta data schema should contain the defined mapping of the key to other meta keys.

**Comment by nadjaweisskopf** [comment]
Please ask Max for advice.

**Comment by eins78** [comment]
table: `io_mappings`
api output: 

```json
// meta key
{
  "id": "madek_core:subtitle",
  ...
  "mappings": [
    {
      "id": "default",
      "keys": [
        "XMP-photoshop:Headline"
      ]
    },
    {
      "id": "tms",
      "keys": [
        "objtitles.title titletypID=6"
      ]
    }
  ]
}
```

**Comment by michalpodlecki** [comment]
done: https://github.com/Madek/madek/pull/101

**Comment by nadjaweisskopf** [comment]
testing: if the additional code is attached to the exporter-file

**Comment by eins78** [comment]
@ltsotrug I was tried out something else with the exporter, so i had a quick look and can confirm that the IO-Mappings are exported as expected.

![screen shot 2018-06-21 at 12 27 56](https://user-images.githubusercontent.com/134942/41713877-c8cf488a-754e-11e8-877a-c4be11a9fa06.png)

**Comment by ltsotrug** [comment]
@eins78 thank you

**Comment by ltsotrug** [comment]
@nadjaweisskopf test was successfull
