### ISSUE TITLE
falsche Support-Email in Config

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#643]
die Kontakt-E-Mailadresse im Config, resp. in den Fehlermeldungen ist falsch: `madek_support_email`

<img width="709" alt="image" src="https://github.com/user-attachments/assets/5f5a99cb-7299-4ccd-be97-90b233e147fb">

diese Adresse existiert nicht!

korrekt ist:
https://wiki.zhdk.ch/medienarchiv/doku.php?id=start#support_per_e-mail

**Comment by SeduroDotCom** [comment]
FYI:
- https://github.com/search?q=org%3AMadek%20support.madek%40zhdk.ch&type=code

**Comment by SeduroDotCom** [comment]
Successfully tetsted
- https://test.madek.zhdk.ch/meta_meta_data?type=MediaEntry
- ![Image](https://github.com/user-attachments/assets/d0c9eeed-18cf-4b48-813a-b41a005bd373)
