### ISSUE TITLE
Delegation: Verantwortlichkeit deklarieren bei Übertragung

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#647]
Bei der Übertragung der Verantwortlichkeit aus einer Delegation wird nicht angezeigt, in welcher Delegation die Verantwortlichkeit aktuell liegt:

<img width="804" alt="image" src="https://github.com/Madek/Madek/assets/42544602/f5db28c5-90b0-474e-a1e5-ae5fb43e3c75">

Es können auch gleichzeitig Einträge aus unterschiedlichen DGs übertragen werden.

Ein Hinweis wäre sinnvoll
z.B. mit folgender Angabe:
```
Sie ändern die aktuelle Verantwortungs-Gruppe [Delegation-Name] zu
[Auswahlfeld]
```

bzw.
```
Es sind Medieneinträge|Sets mit mehreren unterschiedlichen Verantwortungs-Gruppen ausgewählt! [Delegation-Name], [Delegation-Name], ...
[Auswahlfeld]
```

Allerdings wäre noch besser, wenn die Auswahl mit mehreren Delegations gar nicht gehen würde!

**Comment by urs-van-binsbergen** [comment]
@phoettli 

Frage: sollte es nicht möglich sein, der vorher verantwortlichen Delegation Berechtigungen zu vergeben, analog zu Usern? 

> Allerdings wäre noch besser, wenn die Auswahl mit mehreren Delegations gar nicht gehen würde!

Es fällt mir gerade schwer, einen Flow zu definieren, der dies sicherstellt. 

Ich habe angeschaut, wie das Problem bei verschiedenen Usern gehandelt wird (nur im Admin-Modus möglich). Es steht "Sie, (Name des ersten Responsible) behalten folgende Berechtigungen..." Die anderen Responsibles werden nicht erwähnt... Die Verarbeitung ist aber korrekt (d.h. es werden nicht etwa fälschlich die Rechte nur dem erwähnten User zugewiesen).

**Comment by urs-van-binsbergen** [comment]
Noch ein Nebenbefund: Wenn die Verantwortlichkeit zu einem User geht, werden dessen Berechtigungen entfernt (falls vorhanden). Nicht jedoch wenn die Verantwortlichkeit zu einer Delegation geht. Das müsste ws. einheitlich sein?

**Comment by phoettli** [comment]
> Ich habe angeschaut, wie das Problem bei verschiedenen Usern gehandelt wird (nur im Admin-Modus möglich). Es steht "Sie, (Name des ersten Responsible) behalten folgende Berechtigungen..." Die anderen Responsibles werden nicht erwähnt... Die Verarbeitung ist aber korrekt (d.h. es werden nicht etwa fälschlich die Rechte nur dem erwähnten User zugewiesen).

@urs-van-binsbergen Wie geht das? Bei Einzeluser kann doch immer nur einer die Verantwortlichkeit haben oder?

**Comment by urs-van-binsbergen** [comment]
> Wie geht das? Bei Einzeluser kann doch immer nur einer die Verantwortlichkeit haben oder?

Bei Verantwortung übertragen von mehreren Ressourcen gleichzeitig, können mehrere User vorkommen, welche aktuell die Verantwortung haben. Dies wie gesagt nur im Admin Modus möglich, wo man auch die Verantwortung übertragen von Ressourcen, für die man aktuell nicht selber verantwortlich ist.

**Comment by phoettli** [comment]
> Bei Verantwortung übertragen von mehreren Ressourcen gleichzeitig, können mehrere User vorkommen, welche aktuell die Verantwortung haben. Dies wie gesagt nur im Admin Modus möglich,

@urs-van-binsbergen ok, danke für den Hinweis! Ist ja eigentlich logisch als Admin :)

ok, dann nehm ich das zurück:
~~Allerdings wäre noch besser, wenn die Auswahl mit mehreren Delegations gar nicht gehen würde!~~

Aber ein Hinweis auf die verschiedenen Delegations wäre toll. Was wäre eine gute Möglichkeit?
- gelb markiert analog Stapeländerung bei den Metadaten
- Checkboxen mit [–] wie bei den Stapeländerung der Berechtigungen
- ganz eine andere Anzeige?

**Comment by urs-van-binsbergen** [comment]
@phoettli Ist deployed auf meinen persönlichen Madek-Server, zum UI-Review

Fälle: 
- Einzelaktion: 
  - Von mir
  - von jemand anders (Admin-Modus!)
  - von einer Delegation
- Mehrfachaktion/Batch: 
  - 1..n welche alle mir gehörten
  - 2..n mit verschiedenen Benutzern und/oder Delegationen

Nebenthemen: 
- ich habe versuchshalber ermöglicht, dass auch Delegationen die Berechtigungen behalten können. Falls nicht erwünscht, entferne ich das einfach wieder
- Wie erwähnt gibt es eine Inkonsistenz: Wenn der neu verantw. User vorher direkt zugeordnete Berechtigungen hatte, werden diese automatisch entfernt. Bei einer Delegation ist das nicht der Fall. Das habe ich so belassen, aber sollte man das ändern? 
- Auch etwas seltsam: Wenn in der Mehrfachauswahl/Batch Sets und ME vorhanden sind, wird die Verantwortungsübertragung nur auf die ME angewendet. Habe ich ebenfalls so belassen.

**Comment by phoettli** [comment]
Vielen Dank @urs-van-binsbergen  !
> Einzelaktion:
Von mir
von jemand anders (Admin-Modus!)
von einer Delegation
Mehrfachaktion/Batch:
1..n welche alle mir gehörten
2..n mit verschiedenen Benutzern und/oder Delegationen

✅

> ich habe versuchshalber ermöglicht, dass auch Delegationen die Berechtigungen behalten können. 

✅ Die Funktion finde ich gut. Kannst du bei den Delegations allenfalls die Checkboxen deaktiviert lassen? Die Verschiebung auf Einzeluser braucht man bei DGs wohl meist nicht.

> Wie erwähnt gibt es eine Inkonsistenz: Wenn der neu verantw. User vorher direkt zugeordnete Berechtigungen hatte, werden diese automatisch entfernt. Bei einer Delegation ist das nicht der Fall.

✅ Falls möglich, wäre dieses Verhalten wohl auch bei Delegations sinnvoll.

> Auch etwas seltsam: Wenn in der Mehrfachauswahl/Batch Sets und ME vorhanden sind, wird die Verantwortungsübertragung nur auf die ME angewendet. Habe ich ebenfalls so belassen.

⁉️ Das kann ich nicht nachvollziehen. Wenn sowohl Sets wie auch MEs ausgewählt sind, müssten doch unterschiedliche Funktionen im Menü erscheinen z.B.
<img width="846" alt="image" src="https://github.com/user-attachments/assets/5a34884c-2b29-4da4-aa63-861c7a0a6a6f">
Da fehlen aber in der Tat die Sets in der Mehrfachbearbeitung. Muss man das noch nachflicken analog #571 ?

**Comment by urs-van-binsbergen** [comment]
167cc2bf46d10aef1fc1c6fb707c0ce25821f672
