### ISSUE TITLE
Users can not be cleary identified

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#65]
User --> will create a new ticket for this feature

- [x] User-Autocomplete should show email address (like extended label for groups)
- [x] User-Autocomplete should detect UUID or UUID-based URLs (if user pastes …/people/$ID)
- [x] User-Autocomplete should detect exact match by email adress
- [x] People-Autocomplete should detect UUID or UUID-based URLs (if user pastes …/people/$ID)
- [x] specs

**Comment by eins78** [comment]
shows email:
![screen shot 2018-03-08 at 13 50 14](https://user-images.githubusercontent.com/134942/37152685-7f153f5e-22da-11e8-9a5d-fb4e73e66dff.png)

---

if email is entered and there is an exact match, show only this user (e.g. dont show users that have this email as a pseudonym or something)
![screen shot 2018-03-08 at 14 09 38](https://user-images.githubusercontent.com/134942/37152742-a661f606-22da-11e8-8cf2-88c313248b17.png)

---

same with UUIDs (most useful for admins), or URLs that end with a UUID (for searching People when I already have found their "page")
![screen shot 2018-03-08 at 14 10 14](https://user-images.githubusercontent.com/134942/37152787-ce0883aa-22da-11e8-959c-5bf736c44107.png)

---
![screen shot 2018-03-08 at 14 14 27](https://user-images.githubusercontent.com/134942/37152861-07f52bd6-22db-11e8-9d0f-2acb83ee85d0.png)

**Comment by nadjaweisskopf** [comment]
@susanneschumacher ready to test

**Comment by nadjaweisskopf** [comment]
@SusanneSchumacher Mischa will correct the conditions this week. have you already tested this ticket?
