### ISSUE TITLE
Delegations: Verantwortlichkeit übertragen für Sets geht nicht im Stapel

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#650]
wie in #571 für Medieneinträge geht die Übertragung der Verantwortlichkeit im Stapel auch nicht für Sets:
<img width="846" alt="image" src="https://github.com/user-attachments/assets/1d243abd-c37a-4d8f-8771-12f814898ad0">

**Comment by urs-van-binsbergen** [comment]
Das Problem betrifft neben "Verantwortlichkeit von Sets übertragen" auch "Berechtigungen für Sets editieren". 
Es tritt nicht in allen Ansichten auf, z.B. nicht unter "Sets in gemeinsamer Verantwortung"
Bei #571 handelte es sich um ein anderes Problem, das erst im Dialog beim Speichern auftrat.

**Comment by urs-van-binsbergen** [comment]
Neue Erkenntnisse: Das Problem tritt generell in gemischten Listen (ME + Sets) auf. Diese basieren auf dem View `vw_media_resources`, das ist ein UNION JOIN von `media_entries` und `collections`. Bei diesem View fehlt die Spalte `responsible_delegation_id`!

Allerdings müsste in gemischten Ansichten das Problem eigentlich auch mit Medieneinträgen auftreten. Bei diesen wird aber aus anderen Gründen ein Patch angewendet, der sie von einer `media_resource` in einen "echte" `media_entry` konvertiert. 

Die Lösung ist also einfach: Spalte `vw_media_resource.responsible_delegation_id` ergänzen.
