### ISSUE TITLE
Supervisor in Delegation geht nicht wenn bereits User

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#653]
Supervisor kann in Delegation nicht definiert werden, wenn bereits als User hinterlegt. (#573 )
Punkt 2 hieraus geht dann nicht: https://github.com/Madek/Madek/issues/551#issuecomment-2004345072

Hat denn ein Supervisor gleiche Delegations-Rechte wie ein User?
Dann ginge Punkt 3 hieraus ebenfalls nicht: https://github.com/Madek/Madek/issues/551#issuecomment-2004345072

Supervisor sollte nur administrativ vergeben sein (ohne Berechtigungen) und Notifikationen bekommen,
aber möglich sein als User UND als Supervisor.

**Comment by nimaai** [comment]
> Hat denn ein Supervisor gleiche Delegations-Rechte wie ein User?

nein

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/bee2b2eda8d53f7b58460cd001d8925f2df2d3e0
