### ISSUE TITLE
User--Person: neue Personen--User-Beziehung

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#657]
Subtask von #581 

Die Personen--User-Beziehung wird von einer direkten Beziehung zu einer Beziehung via Inst.-ID (z.B. Evento-ID) geändert:
- [ ] Beim Anlegen eines Users wird eine Person angelegt
- [ ] Beim Löschen eines Users wird die Person belassen
- [ ] Wird ein User erneut angelegt, der bereits einmal bestanden hatte (z.B. BA-Studi zu späterem MA-Studi) und damals eine Person erstellt wurde, wird wiederum diese Person zugewiesen und nicht eine neue Person angelegt.
- [ ] Personen, die ehemaligen User zugeordnet waren, sind in Admin-App als solche erkennbar (Inst-ID).
- [ ] Personen haben im Edit-Modus erweiterte zusätzliche Angaben, um die Eindeutigkeit z.B. bei Autorschaft zu gewährleisten (via Inst-ID).

Wie werden Personen ehemaliger oder noch nicht erstellter User mit Inst-ID versehen?

**Comment by urs-van-binsbergen** [comment]
@phoe Erste Version 04.11.2024 (auf UVB.madek....). Anpassungen:
- DB-Migration für ZHdK, welche die IID von den Benutzern auf die verbundene Person überträgt
- Neue DB-Constraint stellt sicher, dass Benutzer mit Institutional-ID mit der entsprechenden Person sind ("entsprechend" meint "gleiche Institution und Institutional ID") 
- Admin: 
  - Detailansichten gemäss https://github.com/Madek/Madek/wiki/Ueberarbeitung-User-Personen#konzepte überarbeitet. Das ist natürlich als Vorschlag zu verstehen. Wichtigste Änderungen:
    - Zusammengehörige Felder direkt untereinander (z.B. institution und institutional_id). Eher technische Felder zuunterst (z.B. searchable)
    - Link und Angaben zu Person in Detailansicht eines Benutzers
    - In Liste und Detailansicht Person ersichtlich, wenn mehrere Benutzer auf die Person verweisen + mehr Angaben
  - Neu lässt sich das Institutional-ID einer Person zu ändern (aber nur, wenn sie nicht mit einem entsprechenden Benutzer verbunden ist)
- Webapp: IID (Institution + Institutional ID) wird im Personen-Auswahlfeld angezeigt
- Auth: Bei Login eines bisher unbekannten Users wird wie früher eine allfällig bestehende Person anhand des IID verbunden. Bemerkung: Der Name der Person aus dem Auth-System wird bei Update bewusst nicht übernommen (TBD).

**Comment by phoe** [comment]
@urs-van-binsbergen You probably didn't want to ping me. Did you mean @phoettli?

**Comment by urs-van-binsbergen** [comment]
@phoe Yes exactly, thanks and sorry 😇

**Comment by urs-van-binsbergen** [comment]
c2e45f97c99dd030ed4e9c0fb0fa043baec83879
