### ISSUE TITLE
provisorische Zusatzinfos für Personen im Edit Mode

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#658]
Subtask von #581 

Personen müssen bei der Auswahl eindeutig identifiziert werden können (Autorschaft etc.).
Mit dem automatischen User-Sync werden aktive Personen verfügbar. Externe Personen sollen durch Zusatzinfos identifiziert werden (siehe #581 )

Bis zum User-Sync sollen bereits jetzt mögliche Informationen für die Redaktions-User bei der Personen-Auswahl verfügbar sein.
z.B.
- [ ] Inst-ID
- [ ] Externe Informationen

<img width="831" alt="image" src="https://github.com/Madek/Madek/assets/42544602/c2939dcd-2082-4ac8-890c-33ef82f7f7fa">

**Comment by urs-van-binsbergen** [comment]
Ich gehe mal von _einem_ Feld aus. Wie würde das im Admin konkret aussehen. Z.B. so?

<img width="918" alt="image" src="https://github.com/user-attachments/assets/6c9fa71f-5690-429d-8428-829c25947815">

Frage betreffend interner Personen: wie verfahren wir mit diesem Feld, wenn der neue Sync produktiv geht? Wird es inklusive seiner Daten wieder gelöscht?  

Frage betreffend externer Personen: da bringt der neue Sync keine Änderung, d.h. man muss das separat betrachten. Eigentlich reicht dort _ein_ Textfeld nicht, wenn man den Wireframe oben betrachtet.

**Comment by phoettli** [comment]
gute und berechtigte Frage @urs-van-binsbergen !
Für mich passt das Feld so super. Nach der Migration könnte man das löschen, sofern nur interne Info.

Die Fragen sind aus meiner Sicht dann
- wo werden externe Zusatzinfos definiert? (kann warten)
- Wann werden InstID in die Person eingefügt?
- Wie wird unterschieden zwischen interner und externer Zusatzinfo?
- Wann werden welche Felder wieder gelöscht?

Dies ist aber alles sehr vom Vorgehen abhängig. Oder was denkst du?
Sollen wir das am Workshop definieren? Oder mal zwischendurch?

**Comment by urs-van-binsbergen** [comment]
Ich würde sagen am Workshop.

**Comment by phoettli** [comment]
> - wo werden externe Zusatzinfos definiert? (kann warten)
> - Wann werden InstID in die Person eingefügt?
> - Wie wird unterschieden zwischen interner und externer Zusatzinfo?
> - Wann werden welche Felder wieder gelöscht?
> Dies ist aber alles sehr vom Vorgehen abhängig. Oder was denkst du?

Externe Infos in separatem Feld => neues Ticket.
InstID kommt in späterem Task bei der Umbiegung der Relation User--Person.

**Comment by urs-van-binsbergen** [comment]
69690b45dd70a126fc6c1111e0bbb5dbf3c17cf3
