### ISSUE TITLE
SQL-Assistant: find ambigously named People

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#66]
- [x] needed: new query/queriesfor "SQL console" (defined [here](https://github.com/Madek/madek_admin-webapp/blob/master/config/sql_snippets.yml))

- [x] prio 1: find People with exactly same names
- [x] prio 2: find People with same names when *displayed* (stringify logic [here](https://github.com/Madek/madek-datalayer/blob/master/app/models/person.rb#L22-L31)))
- [x] prio 3: same like 1 and 2 but also find "close matches", to catch typos and other variations. Only if postgres natively supports something clever like https://en.wikipedia.org/wiki/Levenshtein_distance)

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/34d8e3c51d0fc59bf88380221fa1442549137ea3

**Comment by eins78** [comment]
merged in https://github.com/Madek/madek/commit/f8485017a8908fc6dfacd4b246494c68172e1d76

**Comment by nadjaweisskopf** [comment]
@ltsotrug ready to test (if needed)
