### ISSUE TITLE
madek: restrict delivery of media-files for soft-deleted media resources

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#662]
to-do:
- [x] **webapp**: rendern/ausliefern von resourcen nicht zulassen
- [x] **admin-webapp**: zulassen, aber kennzeichnen (siehe kommentar weiter unten)

**Comment by nimaai** [comment]
antwort von @phoettli :

>Für Files wäre eine Kennzeichnung optimal, allenfalles default ausgefiltert (später?). Zugang in Admin App sollte aber möglich sein.
Meta Darums meinst du zugehörige zu gelöschten Medieneinträgen? Belassen wies ist.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/e3cf704d34b552334659959d0a07f2792c4f262a

**Comment by phoettli** [comment]
Wenn ich das richtig verstehe sind jetzt die Files von `Drafts` ebenfalls mit `Deleted` gekennzeichnet. Das ist aus meiner sicht etwas unglücklich. 
<img width="446" alt="image" src="https://github.com/user-attachments/assets/e3f0ce43-98d3-4464-9ec6-8bed0e97de72">


Müssen die `Drafts` denn wirklich auf `Deleted` gesetzt sein? Falls die eine Markierung benötigen, gäbe es allenfalls einen anderen Status wie _not published_ o.ä.?

**Comment by nimaai** [comment]
Ja, das ist zur Zeit suboptimal. Ich schlage vor es ausschliesslich durch den Status auf dem Medieneintrag (wo es tatsächlich auch gehört) zu lösen. Erstmal in der Liste der Media-Files selbst:
<img width="1399" alt="Screenshot 2024-10-04 at 13 52 06" src="https://github.com/user-attachments/assets/2573ee6c-745a-4faa-8c85-f3b22090627e">
Die Spalte "Deleted" entfällt, da sie so auf den Media-Files eigentlich gar nicht so gibt. Dafür wird korrekterweise neben dem Eintragtitel das Label angezeigt.

Zum Zweiten auf der Detailansicht selbst:
<img width="1415" alt="Screenshot 2024-10-04 at 13 52 20" src="https://github.com/user-attachments/assets/5b7a4bd4-e7b9-4fb9-a9dd-7768188dbdb8">
Da gibt es neulich den Link zum Eintrag selbst und dort wird es ausgezeichnet.

Der Status "Unpublished" spielt in diesem Zusammenhang keine Rolle und wird auch nachwievor nirgends auf den Media-Files Seiten angezeigt.

**Comment by phoettli** [comment]
hmm, die Funktion, dass die Files nicht mehr zugänglich sind fand ich schon gut. Sollte auch für die API so sein. Einzig bei den Drafts passt diese Funktion nicht:
- fehlende Previews
- falscher Tag Deleted.

Die Drafts von der Funktion `Deleted` ausnehmen geht nicht?

**Comment by phoettli** [comment]
Dein Vorschlag könnte schon auch funktionieren. Es müsste aber sichergestellt sein, dass auf Files mit Deleted ME kein Zugriff möglich ist, auch nicht in der API, weil dort der Bezug nicht direkt sichtbar ist.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/4121f1b8978f2e36bf18273f8bde969947fd9d9a

**Comment by phoettli** [comment]
@nimaai auf `staging` gibt es seltsamerweise zwei Files, die in der Übersicht `Deleted` angezeigt werden, nicht aber in der File-Detailseite und auch nicht als Medieneintrag.

<img width="1161" alt="image" src="https://github.com/user-attachments/assets/a7f52518-b89c-42b3-ae83-03f034253ea3">

Auf `prod` sind sie nicht als gelöscht markiert!

Die weiteren Stichproben haben korrekt funktioniert.

**Comment by phoettli** [comment]
ausserdem:
Wenn ein Medieneintrag gelöscht wird, wird korrekt `Deleted` in der Admin App beim Entry, File und in der File-Übersicht angezeigt.

Wird hingegen der Medieneintrag wiederhergestellt bleibt ebenfalls der Hinweis `Deleted:Yes `in der File-Übersicht bestehen. (Beim Entry und in der File-Detailanzeige wird der Hinweis korrekt entfernt).

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/5421d7c595c25b6ab8caf50b02c321b8bbfb9ee6
