### ISSUE TITLE
notifications: limit the size of body in the emails 

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#668]
in SMTP protokoll gibt es keine limit definition. alles hängt von jeweiligem client und server ab.

**Comment by nimaai** [comment]
@phoettli von welcher dimension an notifikationen-menge gehst du aus in worst-case-szenario? gesammelt pro woche.

**Comment by nimaai** [comment]
@phoettli allenfalls könnte man die anzahl notifikationen pro sektion (persönlich/delegation) mit einem sinnvollen wert beschränken. zusätzlich einen hinweis anzeigen: "sie finden alle ihre notifikationen unter ..."

**Comment by phoettli** [comment]
@nimaai so 1000 – 2000 könnte es vielleicht schon mal geben, aber wohl auch eher selten. Darüber ist wohl eher unwahrscheinlich und eher bei grösseren Migrationen der Fall, die wir ggf. im Backend abfangen könnten (Mail- und Zuständigkeits-Settings)

**Comment by phoettli** [comment]
blöd ist, in [Zeile 4](https://github.com/Madek/Madek/issues/551#issuecomment-2167878464) bekommt lokal keiner Notifications angezeigt, nur per Mail an unpersönliche E-Mail. Oder nicht @nimaai ?

**Comment by nimaai** [comment]
supervisors werden immer in UI benachrichtigt. jede delegation hat zwingend mindestens 1 supervisor. ich nehme an, dass die unpersönliche email vor allem gerade von den supervisors gelesen wird. oder wie ist das?

**Comment by phoettli** [comment]
> supervisors werden immer in UI benachrichtigt...., dass die unpersönliche email vor allem gerade von den supervisors gelesen wird.

Die übrigen, die die Mail bekommen, haben dann aber eben keinen Zugriff auf die Notifikationen des Supervisors.
Die Idee an der unpersönlichen Mail ist ja schon, dass diese Info an viele verbreitet werden kann.

**Comment by phoettli** [comment]
...`Teil 1, Teil 2, Teil n` meinst du? Finde ich eine gute Idee!

**Comment by nimaai** [comment]
@phoettli OK. wie viele notifikationen pro email?

**Comment by phoettli** [comment]
was ist eine gute Länge?

- [ ] 600 ?
- [ ] 800 ?
- [ ] 1200 ?

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/57bc913830dde7f5f1cb02d8341932163e4329ff
