### ISSUE TITLE
Code aufräumen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#672]
- [x] FIXME
- [x] TODO

- Identifizieren
- direkt fixen wo möglich
- allenfalls diskutieren
- ggf. neue Tickets

**Comment by nimaai** [comment]
admin-webapp & datalayer done: https://github.com/Madek/madek/commit/c10434d300154c38e40670287e91c97ed34e2fec
follow-up: https://github.com/Madek/Madek/issues/677

**Comment by nimaai** [comment]
webapp backend done: https://github.com/Madek/madek/commit/9b663aca97547886418dabaa019751f9647309f2
webapp backend follow-up: https://github.com/Madek/Madek/issues/678

**Comment by nimaai** [comment]
webapp frontend follow-up: https://github.com/Madek/Madek/issues/679
