### ISSUE TITLE
File-Zugang für Encodierung an Encodier-Job binden

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#673]
- [x] access-Code bei Aufruf von Zencoder-Job generieren
- [x] access-Code deaktivieren bei
  - [x] Abschluss des Zencoder-Jobs
  - [x] Failure
  - [x] spätestens nach 48h
- [x] Encodier-Zugang beschränken auf Video- und Audio-Files
- [x] alte Codes entfernen bzw. alte Codes ungültig machen für abgeschlossene, fehlgeschlagene Jobs oder älter als 48 Stunden
- [x] überprüfen, dass ohne Codes kein Zugang möglich

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/4696e3adf501854fe6fd6ee432bde7f846740962
