### ISSUE TITLE
Auth-Kollision in der Staging-API ?

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#674]
die Authorisation der Staging-API fragt bei der ersten Gelegenheit nach Authentisierung:

https://github.com/user-attachments/assets/6057a27d-a616-4e57-89b0-6b079cbca405

Auf Prod kommt das Login-Fenster nicht.

**Comment by DrTom** [comment]
Ich bin gerade selbst darüber gestolpert. Es gibt tatsächlich eine Kollision und es sieht so aus, als wären (wieder einmal) unabsichtlich beide BasicAuths auf dem `/api` Pfad aktiv. 

Eigentlich ist das (unter anderem) per Konfiguration für /api abgeschalten, der Regex Ausdruck ist auch korrekt sich folgend überprüfen lässt: 

https://regex101.com/r/S3Ai5p/1

Leider funktioniert es aber in unserer Konfiguration aus bisher nicht erklärlichen Gründen nicht.

**Comment by DrTom** [comment]
Uff, das scheint noch komplizierter zu sein. Google Chrome scheint sich den BasicAuth, den man eventuell einmal eingegeben hat länger zu merken. Das war hier das Problem. 

Die Eingabe von `chrome://restart` in der Google-Chrome URL schafft Abhilfe.

**Comment by phoettli** [comment]
ich habs bisher vorallem mit Safari beobachtet ;)
