### ISSUE TITLE
datalayer: work on codeactions

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#677]
to-dos:
1. `meta_data.created_by_id NOT NULL` constraint in DB
2. more robust previews creation: https://github.com/Madek/madek-datalayer/blob/master/app/models/media_file.rb#L78-L79

**Comment by nimaai** [comment]
@phoettli mit dir zu besprechen

**Comment by phoettli** [comment]
1. Not enforced, Bitte kontrollieren, ob aktuell befüllt wird bzw. woher die leeren Felder stammen.
2. hat sich erledigt. Kommentar löschen

**Comment by nimaai** [comment]
@phoettli 

1. alle medieneinträge die nach 18.10.2016 erstellt worden sind haben `meta_data.created_by_id` abgefüllt. das datum korreliert mit dem v3.0.0 release. ich denke es wurde mit dieser version eingeführt.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/8f89db64f234fd1b3315bbe50bae487d51e5a0d3
