### ISSUE TITLE
webapp: work on codetags (backend)

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#678]
- [x] `app/policies/vocabulary_policy.rb:41:    show? # TODO: policy???`
- [x] `app/presenters/presenters/shared/media_resource/media_resource_relations.rb:36:          # TODO: exclusion of self from siblings should be done`
- [x] `app/presenters/presenters/shared/media_resource/media_resources.rb:170:          # FIXME: fails non-deterministally, workaround by retrying…`
- [x] `app/controllers/modules/media_entries/upload.rb:61:            flash[:warning] = 'The collection does not exist!' # TODO: i18n!`
- [x] `lib/madek/user_precaching.rb:10:    # TODO: improve and make it less brittle`

**Comment by nimaai** [comment]
first tasks done: https://github.com/Madek/madek/commit/8cb29f6a5e879a0e1a75c19830e4833068e66795

**Comment by nimaai** [comment]
`lib/madek/user_precaching.rb:10:    # TODO: improve and make it less brittle` 

@drtom any need to do something here in your opinion?

**Comment by DrTom** [comment]
Zum precaching: das funktioniert nur auf Java; am Besten entfernen und vergessen

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/061485254276e7572f0f35c721dade20613a697d
