### ISSUE TITLE
APIv1 bei Keywords und People das DB-Feld Position ausgeben

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#683]
Bei Keywords und Personen wird neu ein Feld `position` definiert und befüllt. In der APIv1 dieses Feld bei der Ausgabe berücksichtigen.

Und in APIv2 nachziehen.

Siehe #682 

---------
### Ausgangslage
Stellenweise wird die Webapp als Interface für API-Erfassung verwendet. User gehen dann davon aus, dass "Darstellung" wie z.B. Sortierreihenfolge von Personen, Inst. Gruppen, Keywords etc. in dieser Art übernommen werden in der externen Systemausgabe, wie z.B. die Website.

### Problem
Die Sortierreihenfolge von Personen, Keywords etc. wird in der API nicht abgebildet. Die API verwendet eine generische Sortierreihenfolge für die Ausgabe. 

### Lösungsvorschlag
Rollen haben bereits einen Positionsmarker, der ausgegeben wird. Beim Bezug der Daten über die API kann gewählt werden, ob die Sortierung 
- von der API, 
- die Sortierung aus der Webapp übernommen oder
- eine eigene Sortierung vorgenommen werden soll.

### Geltungsbereich
Die Erweiterung gilt sowohl für Medieneinträge, wie auch Sets.

### Vorgehen
in #682 wurde nun die Position in der Webapp für Personen, Keywords etc. identifiziert.
Nun müssen diese Werte in der API noch ausgegeben werden.

#### bereits umgesetzt
- Medieneintrag mit Rollen ~/entries/c7773f7f-4d16-4a31-b180-cb6870c4f93b
- Metadaten in der API `~/api/meta-data/8b26ea60-c701-4de9-94bd-378227daa53b`
  - Rollen-Detail in der API **inkl. Positionmarker** `~/api/meta-data-roles/e4e99edd-7e0b-40d9-965d-180685640eea`
  => `"position": 0,`

#### zu ergänzen
- Medieneintrag mit Keywords, Personen, Inst. Gruppen, Lizenzen etc. `~/entries/afc48ac0-7786-41a3-a798-b9ef1532c487`
- Metadaten in der API
  - Beispiel Personen `~/api/meta-data/9b1fc4f1-e181-4b32-b4cc-397f7936b1d5`
    - Personen-Detail `~/api/people/071f61be-644f-45a6-9c5c-3120451718fb`  => Position ergänzen
  - Beispiel ZHdK-Bereich `~/api/meta-data/e50aae52-5f4b-4399-a308-d2e9053eaa90`
    - Bereich-Detail `~/api/people/c915d0d5-68fa-4d64-83f5-3cd367f0ccb3`  => Position ergänzen
  - Beispiel Keywords `~/api/meta-data/16a3d4ac-0ef3-4c9a-ba0f-54ce6fd7551b`
    - Keyword-Detail `~/api/keywords/dc76ff3b-8cce-479c-a602-8b01116576fa` => Position ergänzen

**Comment by urs-van-binsbergen** [comment]
Personen: `order by meta_data_people.position, people.last_name, people.first_name, people.id`
Keywords: leider etwas komplizierter, da abhängig von den Settings im `meta_key`: https://github.com/Madek/madek-datalayer/commit/be1a49bbf3d0c4a2025e0b9c356699885a977ac2#diff-4bb61fa4cfee1e676e760b274e4b4e7b391f036368c67aec81d2cf8cb40750caR12-R18

**Comment by DrTom** [comment]
Das funktioniert leider nicht so. Bei Personen ist Sortierungsfeld ist nicht in der Resource selbst sonder auf der Verbindungstabelle zwischen Person und Metadatum. 

Eine Person hat nur eine Sortierung im Bezug auf ein bestimmtes MetaDatum! 

Bei Keywords ist es noch komplexer: dort gibt das Feld `position` aber es gibt noch einmal eines wiederum auf der Verbindungstabelle.  

Wo man die `position` aus der Verbindungstabelle zufügen könnte ist in der Auflistung. Z.B. `/api/meta-data/9b1fc4f1-e181-4b32-b4cc-397f7936b1d5` gibt es ein key `value` und dann ein liste die letztlich zu den Personen führt:

```
{
  "id": "9b1fc4f1-e181-4b32-b4cc-397f7936b1d5",
  "media_entry_id": "afc48ac0-7786-41a3-a798-b9ef1532c487",
  "meta_key_id": "madek_core:authors",
  "type": "MetaDatum::People",
  "value": [
    {"id": "f8850a34-3c9a-496c-aeba-cb3d752b0a3c"},
    {"id": "071f61be-644f-45a6-9c5c-3120451718fb"},
    {"id": "a28dfa3b-9954-492e-849f-86c8011f6ada"},
    {"id": "9f7fd1f7-f10c-41b7-9600-c488023c2906"}
  ]
}
```

In dieser Liste steht im Moment nur die `id` aber dort könnt man nun die `position` zufügen.

**Comment by phoettli** [comment]
Super so @DrTom !

**Comment by DrTom** [comment]
Also, noch mal im Detail: 


 `/api/meta-data/9b1fc4f1-e181-4b32-b4cc-397f7936b1d5`: 
```
  "type": "MetaDatum::People",
  "value": [
    {
      "id": "f8850a34-3c9a-496c-aeba-cb3d752b0a3c",
      "position": 0
    },
    {
      "id": "071f61be-644f-45a6-9c5c-3120451718fb",
      "position": 0
    },
    {
      "id": "a28dfa3b-9954-492e-849f-86c8011f6ada",
      "position": 0
    },
    {
      "id": "9f7fd1f7-f10c-41b7-9600-c488023c2906",
      "position": 0
    }
  ]
```

und  `/api/meta-data/16a3d4ac-0ef3-4c9a-ba0f-54ce6fd7551b`: 
```
  "type": "MetaDatum::Keywords",
  "value": [
    {
      "id": "6803ad37-61b3-4a9c-9d6d-ed1a3778601e",
      "position": 10273
    },
    {
      "id": "dc76ff3b-8cce-479c-a602-8b01116576fa",
      "position": 757
    },
    {
      "id": "11484663-1430-4ec3-8d32-954f0b91e5b1",
      "position": 4987
    },
    {
      "id": "62f684a9-15b3-4eff-80c8-af250fcb5744",
      "position": 5548
    },
    {
      "id": "eccc6eff-2ccc-4b21-9497-c11b126d26db",
      "position": 13533
    }
  ]
  ```
  
  Ist OK. Ich könnte jetzt noch gemäss dieser Positionen die Liste sortieren, das entspricht dann wohl der Webapp. Auf der anderen Seite verändert das vielleicht unnötig die API was auch Nebeneffekte haben könnte. 
  
 So oder so: kann ich das (mit oder ohne die zusätzliche Sortierung) mergen und schliessen?

**Comment by phoettli** [comment]
@drtom die Ausgabe sieht super aus. Aber entsprechen die Werte von `position` jetzt der Sortierreihenfolge in der Webapp?
Viermal `0` bei den Personen scheint mir seltsam. Und die gigantisch hohen Werte bei den Keywords ebenfalls.
Kannst du das mit @urs-van-binsbergen checken?

Sortierung würde ich belassen wie allgemein in der API vorgesehen. Die Reihenfolge wie in der Webapp vorgenommen, kann ja jeder selber wählen anhand `position`.

**Comment by urs-van-binsbergen** [comment]
Die neuen Felder `meta_data_keywords.position` bzw. `meta_data_people.position` haben für die bestehenden Daten überall 0. Insofern überraschen die 0 beim Personenbeispiel nicht. 

So wie es aussieht, wird aber bei den Keywords ein Fallback auf `keyboards.position` gemacht, daher die hohen Zahlen.

Die Sortierlogik ist ja leider etwas komplex, siehe mein Kommentar oben. Entweder man überlässt es dem Client, damit umzugehen, dann würde ich die nackten Daten liefern, also kein Fallback. 

Oder man liefert die Daten in der korrekten Reihenfolge. Dann müssten wir `position` gar nicht unbedingt exponieren. Das wäre mein Favorit.

**Comment by DrTom** [comment]
> So wie es aussieht, wird aber bei den Keywords ein Fallback auf keyboards.position gemacht, daher die hohen Zahlen.

Ja aber unabsichtlich; mit HoneySQL 1 hat das nicht so funktioniert wie erwartet. Das ist jetzt repariert.
