### ISSUE TITLE
notifikationen: periodischer versand geht nicht

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#687]
auf test.madek.zhdk.ch:

```
Oct 10 13:10:45 zhdk-madek-test madek-produce-daily-emails-cron[1176645]: [WARN , 2024-10-10T13:10:45+00:00] Error while producing summary email: no implicit conversion of Symbol into Integer
```

**Comment by nimaai** [comment]
https://github.com/Madek/madek-datalayer/blob/master/app/lib/email_templates/transfer_responsibility.rb#L191

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/d38d195ed6cebaae9b4f8e9ff0fc8ef528942bc7

**Comment by phoettli** [comment]
Versandzeitpunkt `test` und `staging`: `15h + n(random) UTC` (nicht an Sommerzeit angepasst!)
