### ISSUE TITLE
Testing Notification-Mail Responisibility Transfer

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#689]
- [X] daily mails auf `test` funktionieren !
- [x] weekly Mails auf `test` sind noch nicht angekommen
- [x] Plattform identifikation fehlt: `Notifikationen von SITE_TITLES`:
<img width="239" alt="image" src="https://github.com/user-attachments/assets/9be5f71f-4704-48e2-9188-d20d44bb0abe">

.

- [x] Host bei den URLs fehlt, damit klickbare Links entstehen: [https://link.zum/medieneintrag/](https://link.zum/medieneintrag/) bzw. [https://link.zum/set/](https://link.zum/set/):
<img width="413" alt="image" src="https://github.com/user-attachments/assets/cd281c0c-96d3-46fe-b841-9710fa297396">

.

- [x] Absender-Adresse sieht etwas seltsam aus resp. entspricht dem technischen statt logischen Namen:
<img width="259" alt="image" src="https://github.com/user-attachments/assets/0568a20e-14a5-438d-a4b2-ed665368e938">

.

- [x] im Footer fehlt die Herkunftsbezeichnung als Absender `PROVENANCE_NOTICES https://DOMAIN`:
<img width="208" alt="image" src="https://github.com/user-attachments/assets/28f26335-922a-4aa9-998c-803aae7c790f">

.

Falls einfach möglich:
Fallback auf Deutsch der Global Settings bei fehlenden Englischen Einträgen: 
- `site_titles`
- `provenance_notices`

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/a1dec6d8d1db86e49e4cf43238c1645ed8579364

> Absender-Adresse sieht etwas seltsam aus resp. entspricht dem technischen statt logischen Namen

ich vermute, dass ist eine konfigurationssache vom server/mailer/inbox usw. tom oder roman fragen

**Comment by phoettli** [comment]
absender Adresse in Setttings kionfigurieren: `default_from_address`

**Comment by nimaai** [comment]
bei leihs:
```

Domain Name (domain)        | ausleihe.zhdk.ch
--------------------------- | -------------------
From (default_from_address) | noreply@zhdk.ch

```

**Comment by phoettli** [comment]
die punkte oben sind super @nimaai ! Zwei Fragen:
1) kannst du die Absenderadresse (`noreply@SERVERNAME`) der jeweiligen Testinstanzen im Deploy/Config eintragen, damit diese Einstellung auf den entsprechenden Server direkt stimmt und nicht immer händisch nachgetragen werden muss?
2) im Test-Email-Konto liegen aktuell zwei unzustellbare Mails von `Test`, gestern versendet (28.10.), stammen aber vom Mittwoch (23.10.). Die scheinen irgendwo hängengeblieben zu sein. Muss man dem nachgehen, damit wir von solchen Mails allenfalls nicht geflutet werden?

**Comment by nimaai** [comment]
@phoettli 

1. Meiner Meinung nach lohnt sich der zusätzliche Konfigurationsaufwand und -komplexität nicht. Auch wenn später auf PROD diese Werte korrekt konfiguriert werden (und somit der Teil nach `noreply@` nicht direkt mit eigentlichem Hostname auto-vervollständigt wird sondern der Wert von PROD selber genommen wird, wie z.b. `noreply@zhdk.ch`) macht der Wert für alle Instanzen Sinn (weil `zhdk.ch`). Zudem werden die Emails sowieso auf die entsprechenden Inboxes verteilt anhand dessen automatisch klar ist woher die Emails stammen.  
2. Wir machen z.Z. keine nächtlichen Dumps auf TEST und somit ist es schwierig für mich herauszufinden, ob und was für ein Fehler auf der Applikationsseite hätte stattfinden können. Ich und Tom nehmen aber an, dass wahrscheinlich keiner. Der SMTP-Server hat die Email entgegen genommen. Aus irgendwelchem Grund hat's bei ihm nicht geklappt. Nach einer gewissen Zeit probiert er nochmals und irgendwann gibt er auf. Deshalb die Verzögerung um ein Paar Tage. Das kann immer mal passieren. Ich würde vorschlagen vorerst nichts machen und weiter testen und beobachten. Falls es nochmals auftauchen sollte, dann muss man vermutlich beim EnOp nach mehr Infos fragen.

**Comment by phoettli** [comment]
@nimaai 
2. ist ok.
1. wir haben nur eine und die selbe Inbox für `test` &` test-blank`, könnte dann möglicherweise für Verwirrung sorgen. Wäre für mich und die Tests etwas komfortabler gewesen. Aber den Server kann man auch im Quelltext der Mail erkennen. Also ebenfalls ok.

Danke !
