### ISSUE TITLE
2 Medieneinträge ohne Vorschau

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#690]
folgende Medieneinträge (Dokument/PDF) haben kein Vorschau-Bild:
- eb8e685e-3095-405b-ab9b-7d85107f0925
- e51b620f-3869-411c-8fb3-efb9f33c72f4
<img width="332" alt="image" src="https://github.com/user-attachments/assets/ab76f76b-8956-4c15-a451-e86ab6a83459">

Quelle exportiert und auf `test-blank` importiert generiert Vorschaubild problemlos:
<img width="333" alt="image" src="https://github.com/user-attachments/assets/0540dd5b-fe40-4bf4-abb9-20b4a0b7b843">

Bitte Vorschaubild erneut erstellen.

**Comment by urs-van-binsbergen** [comment]
feecc3025e87a50e9d64e51c1af8338b90e2fba6
