### ISSUE TITLE
Filename über IO Mappings einfüllen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#696]
Über IO Mappings können diverse Metadaten direkt in Meta-Felder übernommen werden.
<img width="192" alt="image" src="https://github.com/user-attachments/assets/23df8def-4cd0-4853-b503-176b6d1ba4d4">

.
z.B. kann ein XMP-Titel in das Titelfeld geschrieben werden:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/907e723f-56c0-4fc0-a784-8a8973557057">

.
Leider ist der Filename zur Zeit des Imports im IO Mappings nicht mehr identifizierbar.
Filname in IO-Mapping verfügbar machen.

**Comment by urs-van-binsbergen** [comment]
@phoe Soll `XMP-dc:Title` weiterhin berücksichtigt werden? So dass `Filename` nur dann zum Zug kommt, wenn der andere Wert leer ist (was bekanntlich bei der Mehrheit der Files der Fall ist)?

**Comment by phoe** [comment]
@urs-van-binsbergen I'm probably not the person you want to ping. Did you mean @phoettli?

**Comment by urs-van-binsbergen** [comment]
@phoe Sorry and it's already the second time 🙈 I owe you a beer!

**Comment by phoettli** [comment]
wäre toll
1. Filename
2. Titel in Meta-Tag wenn vorhanden – also überschreiben von Filename

**Comment by urs-van-binsbergen** [comment]
ee688ac35c54a994df6ad5e11175b43bda3b95fe
