### ISSUE TITLE
Admin App: User zeigt keine Delegation-Mitgliedschaft über Gruppen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#697]
Die User-Anzeige in der Admin App zeigt keine Delegation-Mitgliedschaften, die über Gruppen erfolgen:
<img width="692" alt="image" src="https://github.com/user-attachments/assets/22d9d7c4-4b51-42dc-9a1e-a6f7e34bffe4">

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/668b8d6b9f0b8daa56d50bb5167012da4f7c8778
