### ISSUE TITLE
General check on translations

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#70]
- where do we need enhancements or translations, which parts have already been translated, do we have bugs?

**Comment by eins78** [comment]
task-tree:

- translation of APP
  - UI uses keys for strings, translated in [CSV/table](https://github.com/Madek/madek-webapp/blob/master/config/locale/translations.csv)
  - languages
    - [ ] german (default language)
    - [ ] english: pending corrections #71
  - per-Instance translations: not currently supported (as its part of the precompiled frontend)
    - [ ] decide if/how we want to support this OR make all relevant words configurable in settings (example: "noun for this archive" -> "Medienarchiv" or "FOO-Katalog")

- translation of CONTENT
  - translatable by admin
    - [ ] MetaKeys DB/UI
        - needs (fixed) translations for `madek_core` Vocab (which admin can't change)
    - [ ] ContextKeys DB/UI
    - [ ] batch translate UI

**Comment by nadjaweisskopf** [comment]
@ltsotrug @susanneschumacher Should we have a refinement on the topic "translations"? Max has listed all points he could think of regarding this topic. Now we need to define which development steps are needed.

**Comment by nadjaweisskopf** [comment]
Prio 2: - Startseite und Explore-Seite: Übersetzungen der Titel wie ZHdK-Katalog, Bereich ZHdK
! - Inhalte, die User eingeben werden nicht übersetzt !
Prio 3: - Admin-Texte rausfinden, die nicht übersetzt sind und definieren, welche übersetzt werden sollen
Prio 1: - Bugs beheben - separate Tickets 
- https://github.com/Madek/madek/issues/132 
- https://github.com/Madek/madek/issues/135 
- https://github.com/Madek/madek/issues/123 (Sprache bei Export nicht mitgeben (auch nicht bei API nicht)
- https://github.com/Madek/madek/issues/99

**Comment by eins78** [comment]
update: @michalpodlecki is working on the last 2 remaining translations of Entities (Vocabs/Contexts).
We will do some general cleanup after that, for all the Entities that are translated so far (see last task above)

**Comment by phoettli** [comment]
wie/wo finde ich die Übersetzungsmöglichkeit der Texte aus den Settings ("settings relating to languages")? Plattform-Name, Intro-Text, about-Page...

**Comment by eins78** [comment]
@phoettli Gibt es (noch) nicht – können wir hier mit aufnehmen. Allerdings unter "translatable by admin", "settings relating to languages" meinte die Einstellungen zur Sprache selbst, also welche default ist.
Im aktuellen RC ist nur der Punkt "DB cleanup: remove the old label (etc) fields. => #170" enthalten (hier gerade abgehakt), was keine Funktion ändern sollte (nur in der Datenbank wurde aufgeräumt)

**Comment by phoettli** [comment]
schlecht, eigentlich sollte Mehrsprachigkeit bis Mai abgeschlossen sein :(.
Und die Settings-Texte gehören da schon auch rein (war Teil vom Auftrag vom Januar). Lass uns das am Montag besprechen, wie wir das Thema Mehrsprachigkeit schnell und vollständig abschliessen können.

**Comment by eins78** [comment]
@phoettli OK, schauen wir am Montag drauf. Schade, dass es so nicht in der Liste stand, dann wäre das früher aufgefallen, dass es fehlt. Diese Felder sind aber vergleichsweise simpel (nicht an so vielen Stellen benutzt wie z.B. die MetaKeys); und für die About Page müsste man es ja eh nachziehen weil die neu ist. 

Bis dahin: alle diese Einstellungen sollten auf einer Seite sein: https://staging.madek.zhdk.ch/admin/app_settings
Schaue mal drauf und überprüfe ob alles dabei ist. 
Einzige Feld, das etwas komplizierter ist: Die Sitemap/Links im Footer, das sind strukturierte Daten und nicht nur ien einfacher Text.

**Comment by phoettli** [comment]
subi !

**Comment by eins78** [comment]
fast alles fertig, teilweise noch kleine bugs die in extra tickets kommen.

**Comment by eins78** [comment]
done according to PO
