### ISSUE TITLE
fehlende ausgewiesene Inhalte zu Person

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#703]
folgende Person hat in Admin App ausgewiesene Inhalte:

- `47f50749-3a1a-4bf7-b51e-0b6ed96e46a6`
- _2 times in 2 entries and 0 collections_

Aufruf der Personen-Seite ergibt allerdings 47 Inhalte (admin 48). Woher rührt der Unterschied?
<img width="635" alt="image" src="https://github.com/user-attachments/assets/dd56e4a7-f1ac-4fce-88a6-bdd3053f1b2f">

Nach mergen mit der Person `c217bdc1-0011-4fb9-906a-371c5020b93a` (Personen-Duplikat), bleiben seltsamerweise nur noch zwei Medieneinträge übrig. Wo sind die anderen hin verschwunden ?
<img width="566" alt="image" src="https://github.com/user-attachments/assets/76b9b699-f2c8-4285-89a2-7f64dafbe674">

**Comment by urs-van-binsbergen** [comment]
Vermutung: die 2 verbliebenen sind die, welche in Admin angezeigt werden.

**Comment by nimaai** [comment]
@phoettli 

Problem 1: wenn man auch dir Rollen in die entsprechende Query reinnimmt, dann schlägt es ziemlich auf die Performanz. Wäre es OK diese Information von "Usage" nur auf der Detailansicht der Person anzuzeigen und auf der Listenansicht darauf verzichten?

**Comment by phoettli** [comment]
@nimaai die Zählung von der Listenansicht auf die Detailseite der Person verschieben.

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/99f03899400cda49fdaafc513f5b6b8dda171b3d
