### ISSUE TITLE
Permissions: Creator ID fehlt

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#707]
In den Permissions fehlt die creator_id
<img width="2336" alt="image" src="https://github.com/user-attachments/assets/fff76148-6701-45c3-acd6-9c769bd38c98">

da die Audits ggf. zeitlich beschränkt gespeichert sind, wäre eine Befüllung sinnvoll.

- collection_api_client_permissions
- collection_group_permissions
- collection_user_permissions
- media_entry_api_client_permissions
- media_entry_group_permissions
- media_entry_user_permissions

**Comment by nimaai** [comment]
@phoettli i schlage eine lösung mit audits vor. diese tabellen sollten wir sowieso auditen; ich aktiviere es. danach ist diese spalte und use case überflüssig. ich kann im sql admin interface eine entsprechende query bereit stellen mit hilfe denen man nachvollziehen kann, wer hat die permissions erstellt und/oder bearbeitet. Ok?

**Comment by phoettli** [comment]
Audit ist zeitlich begrenzt.
Letzte Änderung der Permissions nicht. Daher ist der Eintrag in dieser Tabelle schon auch sinnvoll.

Sind die Änderungen noch nicht in Audits? Falls so, brauchts dafür ein separates Ticket?

**Comment by nimaai** [comment]
ah ok. nein sind noch nicht geaudited. vielleicht ein separates ticket dafür. dort kann man auch zusätzlichen tabellen sammeln die man auditen soll.

**Comment by nimaai** [comment]
@phoettli und was ist mit:
* vocabulary_api_client_permissions
* vocabulary_group_permissions
* vocabulary_user_permissions

braucht es dort auch? bislang haben wir nicht einmal `updator_id` auf diesen tabellen...

**Comment by nimaai** [comment]
https://github.com/Madek/madek/commit/ae51793d1725e74a6e7f716c2ce177b9ef347ba1
