### ISSUE TITLE
Requirement from User (ZHdK Website/ Studienprojekte)

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#73]
![bildschirmfoto 2018-03-15 um 09 33 16](https://user-images.githubusercontent.com/29139407/37452135-f8ed6b5e-2833-11e8-8d48-af118ecd1950.png)

**Comment by ltsotrug** [comment]
steps:
- [ ] @nadjaweisskopf evaluates the ticket with @eins78 
- [ ] @eins78 feedback to @ltsotrug

**Comment by nadjaweisskopf** [comment]
datierung is a text field and can not be sorted. We either migrate to a date field or we introduce a new field. We propose that the zhdk-website sorts according to the date entered and DDK always enters the same/according format.

**Comment by nadjaweisskopf** [comment]
@ltsotrug I sent the following mail to Yvonne: 

*******
Liebe Yvonne

Hier eine kurze Aufführung des Problems und der möglichen Lösung: 

Das Datierungsfeld im Medienarchiv ist leider ein Textfeld. Aus diesem Grund ist eine Sortierung im Medienarchiv oder auf der ZHdK-Webseite schwierig. Der Vorschlag unserer Entwicklung sieht folgendermassen aus: 

Wenn die Erfassung des Datumsfelds für die Studierendenprojekte immer gleich daherkommt, also z.B. DD.MM.YYYY - DD.MM.YYYY, dann könnte Snowflake anhand dieses Textformats eine Sortierung vornehmen. 

Die Anpassung im Medienarchiv würde länger dauern. 

Könntest Du bitte Martin fragen, ob er diese Umsetzung abklären kann?
Er kann mich gerne kontaktieren, falls er Fragen hat. 

Danke vielmals und liebe Grüsse
Nadja
********

**Comment by nadjaweisskopf** [comment]
@ltsotrug I haven't heard anything until now from Yvonne to my mail she forwarded to snowflake. What we are additionally enhancing at the moment is that the default value of the fields "Datierung" and "Erstellungsdatum" are date-pickers instead of text fields. This might already help. 

I will close this ticket for now and reopen it as soon as I have a msg. from Yvonne.

**Comment by eins78** [comment]
@ltsotrug @nadjaweisskopf I like the idea to make the default input the Date-Picker. It cant be configured by the admin so we would have to do it for all date fields, but I think its beneficial to "nudge" users into using "real" dates. 
We just need to make sure to only use that default if the field is currently empty, as soon as it has a value the UI can not know what the original format was and we have to leave it as "Freitext" or risk data curruption!

**Comment by nadjaweisskopf** [comment]
we will introduce the date picker as default value - seperate ticket: https://github.com/Madek/madek/issues/86

Snowflake will not adjust the sorting of the student projects until next year 2019.
