### ISSUE TITLE
Optimise oembed how media is integrated in other systems such as Moodle

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#75]
- [x] restyle

---

 - [x] Add madek as provider to oembed plugin https://oembed.com
  - waiting for merging: https://github.com/iamcal/oembed/pull/290

--- 

- [x] There is a big space on the right and underneath the medium - don't show these empty spaces - see example https://demo.moodle.ch/zhdk/mod/page/view.php?id=110
- [x] Films are not shown correct in Moodle (correct iframe) example: https://demo.moodle.ch/zhdk/mod/page/view.php?id=110

With nanoo film it works well

- [ ] Support preview of PDFs of Medienarchiv in oembed plugin. At the moment we get an error "not supported". - really needed!? then create a new ticket.

**Comment by nadjaweisskopf** [comment]
Grund: bestehendes madek-frontend nicht responsive
embed und player rausziehen, ohne alte styles implementieren
madek verwendet dann den eigenen player
normalerweise 16x9
stylingprobleme wären nicht mehr so schlimm wenn filehandling abgeschlossen ist.

**Comment by eins78** [comment]
@nadjaweisskopf regarding "add to providers on oembed.com": I have prepared this and will apply as soon as we roll out the new version. In the meantime, this can also be configured in Moodle as a "Local Provider" (see [docs](https://moodle.org/plugins/filter_oembed).
Example config here: https://github.com/Madek/madek-webapp/blob/40f54244038f21bec6faed16ddd9612296402bf0/lib/madek/constants/webapp.rb#L35-L39

**Comment by nadjaweisskopf** [comment]
Test: snowflake can attach demo.madek.zhdk.ch
config still to be done if wished: don't show title in external program like paul / show media even if not global.

**Comment by nadjaweisskopf** [comment]
@nadjaweisskopf Renato fragen, ob Ticket geschlossen werden kann
