### ISSUE TITLE
Exporter problem or user handling problem?

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/Madek#76]
Issue from Rolf:

Ich habe es im Netzwerk jetzt nochmals mit allen Laufwerken als Zielort versucht:
das exportierte Set - https://medienarchiv.zhdk.ch/sets/c23f9850-6c9e-45bf-b59b-21fcb3591c31 mit 2 ME: Video und PDF
 
C: geht nicht weil der Profilspeicherplatz zu klein ist.
 
Ein Export auf H: (rwolfens) und S: (Rektorat_MIZ) dauert sehr lange (über 90 Minuten).
 
Resultat:
Das Originalvideo (.mov) und die Metadaten zum Set und den ME’s sind vollständig da, das Originalvideo ist abspielbar.
 
Die beiden Preview-Videos (mp4, webm) sind zwar da, es erscheint jedoch die Fehlermeldung zum Pfad (jpg ‘Preview_Video’ angehängt).
Die Standbilder, die von Zencoder generiert werden (zusätzliche ID zur UUID im Präfix) melden ebenfalls ein Pfadproblem (jpg Preview_Standbild angehängt).
 
Die Standbilder, die früher vom Medienarchiv generiert wurden, sind hingegen in Ordnung.
 
(muss die Exporter App auf dem gleichen Laufwerk liegen wie der Zielordner?)
 
Ich hoffe, die Erläuterungen sind verständlich.

**I exported the data via Expoter to my user-folder and had no problems.**

**Comment by nadjaweisskopf** [comment]
@nadja: Check with Atdhe

**Comment by nadjaweisskopf** [comment]
I have created a ticket in OTRS: ZHDK#2018061110000658
Adthe should get in touch with Rolf.

**Comment by nadjaweisskopf** [comment]
According to Adthe the problem is the long filename. Explorer can dael with a max. string length of 255. As soon as they shorten the filename, the video works.

**Comment by gurmir** [comment]
I have speaked with our Sys-Admins. The Mainproblem is, that Microsoft not allowed more then 260 Characters in there own Explorer. When we need an other Explorer like Total Commander or Double Commander or any other Alternativ Explorer it is now problem to open it. 

Our Sys-Admins still waiting that microsoft solve the problem with the Windows Explorer App.

**Comment by nadjaweisskopf** [comment]
@gurmir Sind wir hier schon weiter oder ist die Situation unverändert?
