### ISSUE TITLE
Exporter: Correct Umlaute in exported text / titles / names

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#77]
Msg. from Judith: 
Umlaute und Buchstaben wie é werden falsch dargestellt:
 
![image001](https://user-images.githubusercontent.com/3356016/37907650-03601548-3106-11e8-9f2d-cc46b3bd482d.png)
 
Ich nehme an, es braucht einfach diesen Unicode.

Ich habe noch mit einer weiteren Datei getestet und gesehen, dass im HTML-File die Umlaute korrekt sind. Das json-File wird vielleicht ja von den Maschinen dann schon korrekt interepretiert.

**Comment by nadjaweisskopf** [comment]
Judith needs to edit json files in textwrangler... user behaviour.

**Comment by eins78** [comment]
Editor auf window, statt textmate: https://code.visualstudio.com

**Comment by nadjaweisskopf** [comment]
@nadja talk to Judith and accept ticket
