### ISSUE TITLE
Error when searching for string "webvideo 'experiment' FS18"

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#80]
![bildschirmfoto 2018-04-04 um 15 16 27](https://user-images.githubusercontent.com/3356016/38309784-2dff5a72-381b-11e8-946a-b0bc61cf058b.png)

**Comment by phiku** [comment]
@nadjaweisskopf Bitte genauere Schritte zum reproduzieren.

**Comment by gurmir** [comment]
@phiku 
Steps:
1. Go to media archive
2. insert to search engine "webvideo 'experiment' FS18" and klick Enter
3. Message pops up

**Comment by phiku** [comment]
@nadjaweisskopf @gurmir Hotfix wird morgen 5. April auf Prod deployed.
