### ISSUE TITLE
Comparison Gitbook - Wiki

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#81]
Check if all information from Wiki-instructions are in gitbook

Communicate to users the URLs, which have changed

**Comment by nadjaweisskopf** [comment]
@ltsotrug  It seems like more than 90% is done. Is it ok, if we switch to gitbook? Then the missing or buggy text can be delivered and corrected later.

**Comment by ltsotrug** [comment]
@nadjaweisskopf ok, I agree.

**Comment by nadjaweisskopf** [comment]
@ltsotrug Please set gitbook as support site in Admin section
