### ISSUE TITLE
Concerns Forschungsdatenbank Outputdata: Links are not directing to Media Archive and other Websites

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#82]
- User Sarah Marinucci (IPF) asks why the https protocol looses the colon in the browser (Firefox, Chrome, Safari)

**Comment by ltsotrug** [comment]
![bildschirmfoto 2018-04-10 um 11 17 28](https://user-images.githubusercontent.com/29139407/38547962-cae4cf2c-3cb0-11e8-8ee7-8a60a0123bce.png)

**Comment by eins78** [comment]
@ltsotrug I dont see any probem concerning Madek software, please reopen with a description of the problem if still relevant.
