### ISSUE TITLE
User can not embed a video from our mediarchive on his website.

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#85]
He uses different tools, node.js, p5.js and other low-level tools eg. also pure HTML.
So no TYPO3, Wordpress, php-based or similar.

Please consider the foregoing mails on OTRS: ZHDK#2018051410000743

**Comment by nadjaweisskopf** [comment]
@ltsotrug @phoettli Könntet ihr bitte mit dem User prüfen, ob er das Video nun auf seiner Website abspielen kann? Wir hatten im Mai aufgrund diesem und einem weiteren embed-Ticket den Video-Player angepasst. 

Tashi hat damals geteset, von Snowflake und der HSK habe ich damals ein OK erhalten. Max hat Wordpress getestet. 

![bildschirmfoto 2018-10-08 um 15 46 19](https://user-images.githubusercontent.com/3356016/46612706-a0f39280-cb11-11e8-9716-b4c27640c1b6.png)

**Comment by ltsotrug** [comment]
@nadjaweisskopf mein letzter Stand war, dass der User einen sehr spezifischen Case hat, weil er seine Website mit versch. Tools, node.js p5.js und weiteren low-level tools, z.T. auch reines HTML betreibt. 

Nach Absprache mit @eins78 habe ich dem User (28.05.18) folgendes geschrieben und dachte das Ticket wäre somit erledigt: 

(...) Dein Anwendungsfall wurde auf der folgenden Test-Seite durchgespielt:
https://zhdk.kiste.li/madek-test-embeds/bootstrap.html

Für den eigenen Eintrag muss die iframe-src, _**seitens User**_, angepasst werden.
Dies gilt auch in Bezug auf das Styling.

Die Entwickler können bei diesem spezifischen Anwendungsfall leider keinen
Support leisten.



Weiter Infos zum OTRS Ticket unter: https://service.itz.zhdk.ch/otrs/index.pl?Action=AgentTicketZoom;TicketID=225223

**Comment by nadjaweisskopf** [comment]
@ltsotrug Hallo Tashi, ok, dann schliesse ich das Ticket. Könntest Du dies bitte das nächste Mal ins Ticket schreiben und das Ticket schliessen? Merci.
