### ISSUE TITLE
Default of Date should be "am" / "Date of creation"

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#86]
When editing a media entry, the default value of the field "datierung" should be "date of creation" / "am" instead of "Freie Eingabe". 

Sort Order of the values: 
1. "Am" as default value - if a value has not already been entered
2. "von/bis"
3. "Freie Eingabe""

**Comment by nadjaweisskopf** [comment]
test: https://test-blank.madek.zhdk.ch

**Comment by nadjaweisskopf** [comment]
- [ ] Provide language translation - G / E according to switcher

**Comment by phiku** [comment]
- When using date picker, show date in input field using the locale from the settings which is determined as default locale in the admin.
- Texts for months and weeks.

**Comment by nadjaweisskopf** [comment]
nw: 15.1. besprochen und für nächste Iteration einplanen

**Comment by phoettli** [comment]
ok auf `staging`
