### ISSUE TITLE
batch process has an action button too much

### ISSUE THREAD

**Issue by ltsotrug** [Madek/madek#87]
actionbutton  **remove from set**  has no function (and doesn’t work)
because there is already the actionbutton  **remove selected one from batch processing**

![bildschirmfoto 2018-05-17 um 11 19 17](https://user-images.githubusercontent.com/29139407/40170668-4c3523e4-59c9-11e8-833c-8ce6620b0da3.png)

**Comment by nadjaweisskopf** [comment]
@ltsotrug Wrong interpretation according to Susanne. The function on the top "aus Set entfernen" opens a further dialog where you get the possibility to chose the sets, where the media entry should be removed. Could you please retest this ticket?

**Comment by ltsotrug** [comment]
I retested it. But the action gets stuck in preloading (different browser and with 2-12 media entrys).
![bildschirmfoto 2018-06-18 um 16 42 24](https://user-images.githubusercontent.com/29139407/41543247-e016f158-7316-11e8-8e76-b916feeb0ccd.png)

**Comment by nadjaweisskopf** [comment]
Prod and staging, problem exists in both environments

**Comment by nadjaweisskopf** [comment]
Delete upper line from action dialog.

**Comment by nadjaweisskopf** [comment]
@ltsotrug could you please test this ticket? Thanks

**Comment by ltsotrug** [comment]
@nadjaweisskopf I tested it on test.madek.zhdk.ch - it's good. But on staging there is still the old version.
