### ISSUE TITLE
Install HSLU Zencoder Key

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#88]
According to mail from Michi from 18.05.18 to @DrTom and me.

**Comment by DrTom** [comment]
In master und zhdk/staging

https://ci.zhdk.ch/cider-ci/trees/9bca1f448697d5f9535d09cce4aa13b9d5e01c3f
https://ci.zhdk.ch/cider-ci/trees/a07a42c0153a13aaee8c1d14091575ec5a11adb7
