### ISSUE TITLE
Analyse: More than 36 entities should be selectable for any batch process

### ISSUE THREAD

**Issue by nadjaweisskopf** [Madek/madek#92]
**Analyse and check further solutions.**
A general solution for the functions of the batch processing (see printscreen) needs to be found. It shall be possible to process more than 36 media entries at once. Analyse if there is another solution than pulling all UUIDs together - in this solution the browser has a max string amount. 
When using the page "Stapelverarbeitung", more than 4000 media entries can be processed at once. 

![bildschirmfoto 2018-05-28 um 09 35 03](https://user-images.githubusercontent.com/3356016/40603072-1ec49c2e-625b-11e8-94ef-1b278108c7c9.png)

********************
Infos from Refinement:

Stapelverarbeitung:
Mehrere 1000 können in der Stapelverarbeitung geändert werden (erfolgreich getestet)

Einzelauswahl: 
Mögliche Lösung für editieren der Metadaten: Ähnliche Lösung wie bei leihs - Metadaten werden vorbestimmt und anschliessen werden diese Felder auf einzelne Einträge auf Listenelemente angewendet. 

Für die URL-Lösung mit max. 36 Einträgen muss eine neue Lsg. gesucht werden.

**Comment by phiku** [comment]
Notizen:
- Posts anstatt Gets => Problem, grosse Selektionen sind nicht gut, da sie bei Refresh verloren gehen. Wieso wird das benötigt? Sobald man einzelne selektiert, wäre ein „Pinsel“ besser. 

- Unvollständige kann man nicht in die Stapelverarbeitung tun. Deshalb mu

- Entwürfe kann man nicht in Set tun, deshalb kann man bei Upload kein Set kreieren. 

- Problem: Wenn ich 150 habe, dann lade ich die hoch, kann sie nicht in ein Set oder Stapelverarbeitung tun, muss alle iterativ jeweils 36 auswählen, die Pflichtfelder ausfüllen. Dann erscheinen sie bei Medieneinträgen. Dort könnte ich

**Comment by nadjaweisskopf** [comment]
Treffen 11. Juli 2018 - Claudia, Philipp, Max, Thomas, Susanne
- Claudia prüft in welchen Fällen die User mehr als 36 Metadaten editieren, Berechtigungen zuteilen, etc. / Wann wird die Stapelverarbeitung verwendet. 
- Philipp verfeinert den Prototypen
- Max erklärt, dass die technische Lösung des aktuellen Prototypen sicher auch für Berechtigungen funktionieren wird.
