### ISSUE TITLE
 In the batch editing a User wants to copy values from one media entry to one or more other media entries

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#94]
(Kopiert von Pivotal) #132981243
Wie in V2 beim Importieren solle es möglich sein, in der Stapelverarbeitung die Werte eines Metadatenfeldes in das selbe Feld bei den anderen Medieneinträgen zu übertragen, die in dem Stapel enthalten sind.

Neben jedem Metadatenfeld sollen folgenden Funktionen verfügbar sein:
 
Wert nur in freie Felder eintragen
Wert überschreibt alle Felder
(bitte nochmals bei v2 checken)
Löschen in allen Feldern (Gibt es schon)

Die Werte dieses Medieneintrags in freie Felder bei den anderen Medieneinträgen eintragen.
Die Werte dieses Medieneintrags überschreiben alle Felder der anderen Medieneinträge.
Alle Werte in diesem Feld in den ausgewählten Medieneinträgen löschen. (Gibt es schon)

***********************************************************************
(Copied from Pivotal) #132981243
Like the import function in V2 it shout be possible in the batch processing that data from the Meta-tag field in the same field can be transmitted from the same batch. 

Each Metadatafields should have the following functions:
- Insert Data only in the free fields
- Override all field (please check it in V2)
- Delete in all fields (Already exists)

- Transmitting the data in all free fields who's all selected media-items.
- Override all fields who in the batch process with this tags
- Delete all fields by the selected media-items.(Already exists)

![pivotal](https://user-images.githubusercontent.com/37148448/40602250-3a8e9796-6258-11e8-9283-8721e2633799.png)

**Comment by phoettli** [comment]
zu komplizierte Anforderung
