### ISSUE TITLE
Improve the filter of API-Clients

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#95]
In the Filter function the user wants to filter API-Clients. The Filters should be removed from the "Visibility" part and added as seperate filter.

- [x] delete the API-filter from "Sichtbarkeit"
- [x] add a new group called "Sichtbarkeit für API-Clients"
- [x] add a search field to search for an API-Client - when klicking in the search field list all API-Clients

![bildschirmfoto 2018-03-12 um 16 20 39](https://user-images.githubusercontent.com/37148448/40492401-b04bf2ca-5f70-11e8-99f8-38a79a5e4074.jpg)

Pivotal: #148278853

**Comment by phoettli** [comment]
OK auf `staging`
