### ISSUE TITLE
Searching: Optimize Search Engine

### ISSUE THREAD

**Issue by gurmir** [Madek/madek#98]
A User wants to search in the Media Archive for media where the title contains "mazdamazda". The user enters the string "mazda". Items containing "mazda" should appear. But the search result is empty.

To Reproduce:
1. Go to Media Archive
2. Upload a media entry with the title "mazdamazda" 
2. Type the string "mazda" in the serach field and press enter 
3. Media entry containing the title "mazdamazda" does not appear

Please optimize the search engine to make parts of titles searchable. 
Details in the Print screen

![search engine](https://user-images.githubusercontent.com/37148448/40660587-ba9762d4-6351-11e8-9d4e-38d7b2708f16.png)

**Comment by gurmir** [comment]
For technical questions please ask max

**Comment by nadjaweisskopf** [comment]
Please include aut. test

**Comment by nadjaweisskopf** [comment]
@gurmir @nadja please test

**Comment by gurmir** [comment]
Test in Chrome was successfull.

**Comment by ltsotrug** [comment]
@nadjaweisskopf Test in Safari, Friefox, Chrome was successfull
