### ISSUE TITLE
Shibboleth login does not pass through `lang` parameter

### ISSUE THREAD

**Issue by eins78** [Madek/madek#99]
steps:

I am logged out
I switch the language English (a non-default language)
I log in using Shibboleth / Switch AAI
FAIL: The language is default language again
EXPECTED: The language is English as previously.

Solution: Add `lang` param with current value to `return_to`(?) param of the Shibboleth login, *if possible*.
Ask @DrTom for Shib questions.

Note: it does work as expected for the "ZHdK AGW" login, as the complete current URL including all parameters is always passed through `return_to`

**Comment by nadjaweisskopf** [comment]
@michalpodlecki check documentation and try to find parameter. If you have any questions, please ask @DrTom

**Comment by nadjaweisskopf** [comment]
@phoettli HSLU informieren, sobald bereit zum Testen.

**Comment by eins78** [comment]
It works and is (controller-) tested. We already give a target url to Switch AAI, it was just a matter of dynamically adding the language parameter.
Needed config changes, which only affected HSLU instance.
@DrTom FYI ☝️ 

Because it only works on prod and staging instances, it can only be tested/demo'd again when a RC for the next released is deployed there. Otherwise needs manual deploy or see GIF below:

![switch-aai-lang-param mov](https://user-images.githubusercontent.com/134942/55726921-2bf60c80-5a11-11e9-973d-6c9b96af5bce.gif)

**Comment by eins78** [comment]
@phoettli auf deren staging: https://i-portfoliodb.hslu.ch/

**Comment by phoettli** [comment]
HSLU schreibt
`Habe es gemäss deinen Schritten getestet. Die Einstellung bleibt englisch.`
